### ISSUE TITLE
In the previous aer simulator we had a job.qobj

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-aer#10]
### What is the expected behaviour?
In the previous simulator, we had a job.qobj. I know @ajavadia wanted this for the IBMQ. I am not sure we need this for simulators but I'm putting it here as I think we need to either add job.qobj here or remove job.qobj from basic. I don't mind which way we go but i would like the two simulators to have the same methods with aer having more not less.

**Comment by chriseclectic** [comment]
Maybe the `qobj` method should be added as an abstract method to the `BaseJob` qiskit-terra class if we want to force all Job classes to implement it
