### ISSUE TITLE
New errors about invalid instructions for the MPS simulator

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#1004]
When a circuit contains the `ry` gate (this happens also with many other gates, probably all the `r` ones), like the following circuit:
```
import qiskit
sim = qiskit.Aer.get_backend('qasm_simulator')

qc = qiskit.QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
qc.ry(4, 0)

res = qiskit.execute(qc, sim,
                     backend_options={'method': 'matrix_product_state'}).result()

from pprint import pprint
pprint(vars(res))
```
This is the output with Qiskit version 0.23.0:
```
{<some irrelevant data that I deleted>,
 'results': [ExperimentResult(shots=0, success=False, meas_level=MeasLevel.CLASSIFIED, data=ExperimentResultData(), status=ERROR: Circuit contains invalid instructions {"optypes": {gate}, "gates": {cx, ry, h}} for "matrix_product_state" method, seed_simulator=0, time_taken=0.0)],
 'status': 'ERROR:  [Experiment 0] Circuit contains invalid instructions '
           '{"optypes": {gate}, "gates": {cx, ry, h}} for '
           '"matrix_product_state" method',
 'success': False}
```
whereas with Version 0.22.0 I get:
```
{...,
 'results': [<qiskit.result.models.ExperimentResult object at 0x7fdbc2558668>],
 'status': 'COMPLETED',
 'success': True}
```

Questions/comments:
1. Is it true that the MPS simulator does not support gates like `ry` and `rz`? This is not what I remember.
2. If `ry` is invalid, then the error message should not include `h` and `cx`; users are surprised to hear that `cx` apparently is invalid for the MPS simulator...
3. How comes it is not working now, if it used to work until recently?
4. Looks like more tests are required, since I expect coverage to be large enough to capture such a scenario.

**Comment by chriseclectic** [comment]
1. ry and rz etc are not supported by MPS simulator
2. It should only be returning "ry" as the unsupported gate. I located the bug for why the incorrect list of unsupported gates is being returned. The c++ function `std::set_difference` which is used to check for differences between two sets of gates doesn't work as intended with unordered sets.
3. Rotation gates like ry were only added as a basis gate to the other simulators last release (see the release notes which highlights this). Previously these were always unrolled to other basis gates (u1, u2, u3).

**Comment by yaelbh** [comment]
#1005 is taking care of (2). I'll open separate issues for the other items.
