### ISSUE TITLE
Installing qiskit-aer-gpu causes Python core dump upon `import qiskit`

### ISSUE THREAD

**Issue by iamlucaswolf** [Qiskit/qiskit-aer#1023]
# Informations

- **Qiskit Aer version**: 0.7.0
- **Python version**: 3.8.6 (via Pyenv)
- **Operating system**: Ubuntu 18.04
- **CUDA version**:  10.2 (driver 440.100)
- **GPU**: NVIDIA GeForece GTX 1070

### What is the current behavior?
When I `import qiskit` on a fresh virtualenv after installing the meta-package (`poetry add qiskit`), everything works fine:

```python
>>> import qiskit
>>> from qiskit import Aer
# -> No warnings or error messages
>>> qiskit.__qiskit_version__
{'qiskit-terra': '0.16.0',
 'qiskit-aer': '0.7.0',
 'qiskit-ignis': '0.5.0',
 'qiskit-ibmq-provider': '0.11.0',
 'qiskit-aqua': '0.8.0',
 'qiskit': '0.23.0'}
```

However, after installing GPU support (`poetry add qiskit-aer-gpu`): 

```
>>> import qiskit
Illegal instruction (core dumped)
```

I use [Poetry](https://python-poetry.org) to manage dependencies and also have [Pennylane](https://pennylane.ai/) (including the Qiskit plugin) installed in the same virtualenv. Other than that, I am not aware of anything that might interfere with Qiskit. GPU/CUDA information is attached at the top.

### Steps to reproduce the problem
N/A

### What is the expected behavior?
N/A

### Suggested solutions
N/A

**Comment by mtreinish** [comment]
Which CPU are you running on? There is a limitation with the `qiskit-aer-gpu` package where it requires a CPU that has avx2 support. On the `qiskit-aer` package it does runtime detection and only uses avx2 if the CPU supports it, but with the `qiskit-aer-gpu` package the way that runtime detection is built doesn't work with nvcc.

**Comment by iamlucaswolf** [comment]
Thanks for the fast response!

That seems to be it. I'm running on an (ancient) AMD FX-6300. If this is an instruction set issue, is there any hope for a workaround (e.g. compiling from source)?

**Comment by mtreinish** [comment]
You can try building it from source, I personally don't have experience doing this on a system without avx2, but I think everything should have ifdefs to block avx2 compilation if its not available. Looking at the cmake files though you'll probably need to edit the flags when CUDA is set as the thrust method: https://github.com/Qiskit/qiskit-aer/blob/721fcb4dbdeda625392f66b479b9868f45b756e2/CMakeLists.txt#L226-L269 to not set the avx2 flag.

@vvilpas do you have any suggestions on this?

**Comment by vvilpas** [comment]
Hi, a PR is open trying to solve this exact issue #859. We are still solving some details but it should work. You can try it. Let us know how it goes.

**Comment by iamlucaswolf** [comment]
Hi, I might try that over the next few days (or just give in to the inevitability of a hardware upgrade). Anyway, I'm closing this for now.

Thanks so much for your help, I'll keep you posted!

**Comment by intelligi123** [comment]
Hi, Were you able to solve this issue? I am not getting this but kernelimagenotfound against my NVIDIA GPU having cuda 12.1 and GPU Geforce GTX 980ti
