### ISSUE TITLE
Snapshot of Unitary Simulator does not return a subset

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-aer#1030]
### Informations

- **Qiskit Aer version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

Unitary simulator does not return a matrix of a part of qubits.

### Steps to reproduce the problem

```
from qiskit import QuantumCircuit, assemble, Aer
from qiskit.providers.aer.extensions import Snapshot

qc = QuantumCircuit(3)
qc.u(0.1, 0.2, 0.3, 0)
qc.u(1.1, 1.2, 1.3, 1)
qc.u(2.1, 2.2, 2.3, 2)
qc.append(Snapshot("final",  "unitary", 2), [0, 1])

unitary = Aer.get_backend('unitary_simulator').run(assemble(qc), backend_options={'simd_enable': False}).result().data(0)['snapshots']['unitary']['final'][0]
unitary.shape == (2 **2, 2**2) # must be True
```

### What is the expected behavior?

Because `Snapshot` specifies two qubits, simulator should return a 4x4 matrix.

### Suggested solutions

Change [here](https://github.com/Qiskit/qiskit-aer/blob/0e5f01c8aa9e96b48a5c756733d8c103eac4251f/src/simulators/unitary/unitary_state.hpp#L476-L477) to generate a matrix of `op.qubits`.

**Comment by chriseclectic** [comment]
Unitary snapshots are like statevector snapshots and must be on the full width of the circuit. They don't support subsets since there is no way in general to marginalize the full unitary without converting it to a Choi (like converting Statevector to density matrix and partial tracing)
