### ISSUE TITLE
python setup.py build Error

### ISSUE THREAD

**Issue by quantumhamiltonian** [Qiskit/qiskit-aer#105]
### Informations

- **Qiskit Aer version**:
- **Python version 3.6.4**:
- **Operating system RHEL 6.4**:

### What is the current behavior?
I want to compile the cpp_simulator.
Now, I want to execute:
python setup.py build
and get the error:
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /opt/xsite/cte/tools/python/3.6.4/lib/libpython3.6m.a(getcopyright.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

### Steps to reproduce the problem
I have build cmake, OpenBlas and Boost. After that, I have tried to execute:
python setup.py build

**Comment by yaelbh** [comment]
Try to follow exactly the instructions in https://github.com/Qiskit/qiskit-aer/blob/master/.github/CONTRIBUTING.md

**Comment by atilag** [comment]
@quantumhamiltonian Im closing this, if you are still having problems after reading the guide, feel free to repone the issue.
Thanks!
