### ISSUE TITLE
Failed import on python version 3.9.0

### ISSUE THREAD

**Issue by paniash** [Qiskit/qiskit-aer#1067]
### Informations

- **Qiskit Aer version**: 0.7.1
- **Python version**: 3.9.0
- **Operating system**: Artix Linux

### What is the current behavior?
When importing qiskit in the python REPL, I get the following error message:

```python
>>> from qiskit import Aer
/home/ashish/.local/lib/python3.9/site-packages/qiskit/__init__.py:62: RuntimeWarning: Could not import the Aer provider from the qiskit-aer package. Install qiskit-aer or check your installation.
  warnings.warn('Could not import the Aer provider from the qiskit-aer '
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Aer' from 'qiskit' (/home/ashish/.local/lib/python3.9/site-packages/qiskit/__init__.py)
```

However, doing a quick `pip list | grep qiskit` yields:

```
qiskit               0.23.1
qiskit-aer           0.7.1
qiskit-aqua          0.8.1
qiskit-ibmq-provider 0.11.1
qiskit-ignis         0.5.1
qiskit-terra         0.16.1
```

which means that `qiskit-aer` is installed, contrary to the error message.

### What is the expected behavior?
Importing Aer from qiskit must not yield error messages.

### Suggested solutions
One way is to downgrade to python 3.8.6 but I don't see why version 3.9.0 might have this issue.

**Comment by iyanmv** [comment]
I have same problem in Arch Linux. What do you get when you try
``` python
from qiskit.providers.aer import Aer
```

In my case I get this error

```
ImportError: /usr/lib/python3.9/site-packages/qiskit/providers/aer/backends/controller_wrappers.cpython-39-x86_64-linux-gnu.so: undefined symbol: slamch_
```

Anyways, in the requirements for the moment they do not support python 3.9 officially, so probably there is some issue that they will fix for the next release. If I find out a solution I will let you know.

**Comment by paniash** [comment]
@iyanmv Yes, there was an update about 3 days back which rolled out python 3.9 to Arch linux (Artix is based on Arch).



>  What do you get when you try
> 
> ```python
> from qiskit.providers.aer import Aer
> ```
> 
> In my case I get this error
> 
> ```
> ImportError: /usr/lib/python3.9/site-packages/qiskit/providers/aer/backends/controller_wrappers.cpython-39-x86_64-linux-gnu.so: undefined symbol: slamch_
> ```

I get the same error as well.

**Comment by paniash** [comment]
@iyanmv There's a hacky solution for now. In the AUR, there's a package for version 3.8 with the name `python38`. I created a virtual environment using `virtualenv` available in the official repos as `python-virtualenv` and specified the version of python to be used. Installed qiskit and it works as expected. However, this only works with the virtual environment. 

You can create as I did, using

```shell
virtualenv -p python3.8 envname
```

**Comment by mtreinish** [comment]
There is no release of qiskit-aer with python 3.9 support yet (I'm working on a PR now to add it to ci, update pkg metadata, etc). But in the meantime since there are no precompiled binaries locally unless there are unforeseen issues there shouldn't be any blocker from building it from source locally with python3.9. The error `undefined symbol: slamch_` normally means that you don't have a lapack library that aer works with locally. Normally I use openblas with lapack support enabled. (on archlinux https://aur.archlinux.org/packages/openblas-lapack/ )
