### ISSUE TITLE
How to disable conan?

### ISSUE THREAD

**Issue by iyanmv** [Qiskit/qiskit-aer#1069]
In [CONTRIBUTING.md](https://github.com/Qiskit/qiskit-aer/blob/master/CONTRIBUTING.md) it is mentioned the following

> Note: Conan use can be disabled with the flag or environment variable DISABLE_CONAN=ON . This is useful for building from source offline, or to reuse the installed package dependencies.

However, if I do

```python
DISABLE_CONAN="ON" python setup.py build
```
Conan is still used. What is the right way to disable conan?

**Comment by mtreinish** [comment]
Which version are you trying to build?`DISABLE_CONAN` only works from master currently. It was added in #999 and hasn't been included in a release yet.

**Comment by iyanmv** [comment]
Ah, okay okay! I didn't notice that, I was trying the latest release.

**Comment by vvilpas** [comment]
Closing this then. @iyanmv let us know if you find other problems.
