### ISSUE TITLE
QasmSimulator.from_backend() fails with "has no attribute 'from_backend'"

### ISSUE THREAD

**Issue by jwoehr** [Qiskit/qiskit-aer#1073]
### Informations

- **Qiskit Aer version**: 0.6.1 `master cd397be test gates on all basis states (#1057)`
- **Python version**: 3.8.5
- **Operating system**: Linux varian 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux NAME="Ubuntu" VERSION="20.04.1 LTS (Focal Fossa)"

### What is the current behavior?

`QasmSimulator.from_backend()` is not found.

### Steps to reproduce the problem
```
(qiskit_dev_venv5) jax@varian:~/work/QISKit$ python
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from qiskit import IBMQ
>>> provider=IBMQ.load_account()
/home/jax/work/QISKit/qiskit_dev_venv5/lib/python3.8/site-packages/qiskit/providers/ibmq/ibmqfactory.py:192: UserWarning: Timestamps in IBMQ backend properties, jobs, and job results are all now in local time instead of UTC.
  warnings.warn('Timestamps in IBMQ backend properties, jobs, and job results '
>>> b = provider.get_backend('ibmqx2')
>>> from qiskit.providers.aer import QasmSimulator
>>> q = QasmSimulator.from_backend(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'QasmSimulator' has no attribute 'from_backend'
>>> type(QasmSimulator)
<class 'abc.ABCMeta'>
```

### What is the expected behavior?

The method should work.

**Comment by vvilpas** [comment]
Hi @jwoehr . I have tested this with the latest release and with master as well and everything works. If I downgrade to version `0.6.1` it fails as you mention. Can you update your version and try again?

**Comment by chriseclectic** [comment]
As @vvilpas this functionality was added in the 0.7 release so you need to upgrade your qiskit-aer install
