### ISSUE TITLE
c_if does not work for large size classical registers

### ISSUE THREAD

**Issue by avartak** [Qiskit/qiskit-aer#1077]
### Informations

- **Qiskit Aer version**: 0.7.1
- **Qiskit Terra version**: 0.16.1
- **Qiskit version**: 0.23.1
- **Python version**: 3.8.5
- **Operating system**: macOs Big Sur 11.0.1

### What is the current behavior?
As far as I understand, a `c_if` should work on a classical register of arbitrary size. However, a test I performed seems to indicate that 
- `c_if` works if the register size is less than 64 bits
- It causes a crash for a register size of exactly 64 bits
- It fails for register size larger than 64 bits

I also noticed that if I run the QASM simulator using BasicAer, `c_if` works as it should in all the three cases mentioned above.

### Steps to reproduce the problem

Here is the test code that I ran

```
from qiskit import *

def get_circuit(n):
    creg = ClassicalRegister(n)
    dreg = ClassicalRegister(1)
    
    qreg = QuantumRegister(1)
    mreg = QuantumRegister(1)
    
    circ = QuantumCircuit(qreg, mreg, creg, dreg)
    
    for i in range(n):
        circ.measure(qreg[0], creg[i])
    
    circ.x(mreg[0]).c_if(creg, 0)
    circ.measure(mreg[0], dreg[0])
    
    return circ


sim_basic_aer = BasicAer.get_backend('qasm_simulator')
sim_aer = Aer.get_backend('qasm_simulator')

circ72 = get_circuit(72)
circ48 = get_circuit(48)

print("72 clbits (Aer)       : ", execute(circ72, sim_aer).result().get_counts())
print("72 clbits (Basic Aer) : ", execute(circ72, sim_basic_aer).result().get_counts())
print("")
print("48 clbits (Aer)       : ", execute(circ48, sim_aer).result().get_counts())
print("48 clbits (Basic Aer) : ", execute(circ48, sim_basic_aer).result().get_counts())
```

### What is the expected behavior?

Here is the result I get after running the above code

```
72 clbits (Aer)       :  {'0 000000000000000000000000000000000000000000000000000000000000000000000000': 1024}
72 clbits (Basic Aer) :  {'1 000000000000000000000000000000000000000000000000000000000000000000000000': 1024}

48 clbits (Aer)       :  {'1 000000000000000000000000000000000000000000000000': 1024}
48 clbits (Basic Aer) :  {'1 000000000000000000000000000000000000000000000000': 1024}
```

When I have a classical register with 72 bits, the leftmost bit is set to 0, while it should be 1. 

### Suggested solutions

Given that the code fails at 64-bits (crashes at n=64, fails for n>64), I would naively think that the code is not handling big integers (bigger than the system word size) well.

**Comment by b63** [comment]
Hello, the problem seems to be a combination of a typo in [`hex2bin`](https://github.com/Qiskit/qiskit-aer/blob/4a82bab1d5329730bf5ebecfcaf1d24441d95ae9/src/framework/utils.hpp#L1018) and leading zeros in the masked register value when comparing it the target conditional value in [`apply_bfunc`](https://github.com/Qiskit/qiskit-aer/blob/4a82bab1d5329730bf5ebecfcaf1d24441d95ae9/src/framework/creg.hpp#L188).

I will submit a WIP PR. Please let me know if I should add/change anything.
Thanks

**Comment by chriseclectic** [comment]
Thanks for the PR @b63. Most of the team has been on vacation over christmas / new years, but we will try and review it soon
