### ISSUE TITLE
Qiskit -aer still not installing despite checking issues #546, 547, 549, 806, and 987

### ISSUE THREAD

**Issue by PandaComputes** [Qiskit/qiskit-aer#1096]
### Informations
- **Qiskit Aer version**: 0.23.2
- **Python version**: 3.8 64-bit
- **Operating system**: Windows 10

### What is the current behavior?
qiskit - aer not installing

### Steps to reproduce the problem
Apologies if this is not specific enough as I'm new.  At the anaconda3 prompt and using an environment, I just set up, 
pip install qiskit 
It does most of the installation until it gets to 
Building wheels for collected packages: qiskit-aer, qisket-terra
 Building wheel for qiskit-aer (setup.py) ... error

### What is the expected behavior?
That the wheel is built for qisket-aer

### Suggested solutions
At first, I could not get a build for either qisket-aer or qiskit-terra.  I followed the instructions to upgrade setuptools to setuptools-51.1.2 and also install Microsoft Build Tools for Visual Studio 2019, ensuring the latest versions of MSVCv142-vS 2019 C++ x64/x86 build tools and Windows 10 SDK are checked.  That helped with installing qiskit-terra but not qisket-aer.

For qisket-aer I tried solutions proposed in #987, #806, #549, #546, and #547 with no luck  so far.
It looks like a compiler error, CMake unable to find a build program corresponding to "Ninja" and so I tried one suggestion
'pip install ninja-build'
And the error was 'Could not find a version that satisfies the requirement ninja-build' and 'No matching distribution found for ninja-build'
There was another suggestion
'pip install -r requirements-dev.txt'
However, I assume this is a file someone built as it couldn't find it, same with another suggestion in #547 
'install -U 'git+https://github.com/chriseclectic/qiskit-aer.git@fix-pulse-build'
In #546 it was suggested that a change might be made to setup.py to avoid and force installing all deps at pip installation time but did this get fixed in the CMakeLists as discussed where the pip call was removed from setup.py?  
Also, there is a suggestion in the error that Python 3.9 requires Microsoft Visual Studio 2017 (see above I installed the 2019 version as suggested which did fix the installation of qiskit -terra).   
Someone also indicated they got it to work going back to Python 3.7, but I'm hoping not to do that.  
Appreciate any help to get qiskit -aer installed!

**Comment by PandaComputes** [comment]
Solved it which was to downgrade to Python 3.8.3
conda install python=3.8.3
pip install qiskit
My understanding is this is because the base environment for Python is version 3.8.3 while any new environment you activate is version 3.9 which is not compatible with qiskit 
https://quantumcomputing.stackexchange.com/questions/9826/installing-qiskit-with-pip-install-qiskit-gives-error-command-errored-out-wi

**Comment by vvilpas** [comment]
Hi @PandaComputes! No support for python 3.9 yet, but is on the way.
