### ISSUE TITLE
Avoid calling State::qreg() from outside

### ISSUE THREAD

**Issue by doichanj** [Qiskit/qiskit-aer#1104]
### What is the expected behavior?

For the future release using chunk based state management, calling `qreg()`  from outside of State class causes problem.
Because there will be multiple qregs for multi-chunk implementation.

For example, in unitary_controller.hpp
`  state.save_data_single(result, "unitary", state.qreg().move_to_matrix());`
can not return whole matrix if the matrix is distributed on chunks. 

So, it will be implemented as 
`  state.save_data_single(result, "unitary", state.move_to_matrix());`
then state can collect whole matrix inside state classes.

#1025 is the implementation.

**Comment by doichanj** [comment]
#1025 is related to this

**Comment by vvilpas** [comment]
Closing as #1025 is already merged.
