### ISSUE TITLE
Qasm simulator says it can do 30Q but raises Error

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#1114]
### Informations

- **Qiskit Aer version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
I am trying to do a noise simulation on a 30Q circuit.  The simulator config `sim.configuration().num_qubits` says it can handle 30Q, but when doing so I get:

QiskitError: 'ERROR:  [Experiment 0] QasmSimulator: Insufficient memory for 30-qubit circuit using "statevector" method.

The raw data storage at 30Q is 16Gb of memory, and I have 32 (well effectively reported as 31 since on linux).  

### What is the expected behavior?
An user would expect the number of qubits in the config to be the true value.

**Comment by hhorii** [comment]
Total memory is calculated differently for `MAX_QUBITS_STATEVECTOR` in python and for default `max_memory_mb` in C++.  
- `MAX_QUBITS_STATEVECTOR`: calculated with all the `SYSTEM_MEMORY_GB` (`psutil.virtual_memory()`)
- default `max_memory_mb`:  **half** of the system memory (`sysconf(_SC_PAGE_SIZE)` and `sysconf(_SC_PHYS_PAGES)`).

https://qiskit.org/documentation/stubs/qiskit.providers.aer.QasmSimulator.html
> max_memory_mb (int): Sets the maximum size of memory to store a state vector. If a state vector needs more, an error is thrown. In general, a state vector of n-qubits uses 2^n complex values (16 Bytes). If set to 0, the maximum will be automatically set to half the system memory size (Default: 0).

By setting `max_memory_mb` as `16384` or more, 31 qubit will be available.

> @chriseclectic should we allow Aer to use all the memory by default?

**Comment by nonhermitian** [comment]
Yes, my point is there should not be a difference. I would also expect to be able to run a 30Q sim on a system with 32gb of installed memory.
