### ISSUE TITLE
Error: ImportError: cannot import name 'Aer' from 'qiskit' with Ananconda Linux 

### ISSUE THREAD

**Issue by claudefalbriard** [Qiskit/qiskit-aer#112]
### Informations

- **Qiskit Aer version**: from Git https://github.com/Qiskit/qiskit-aer.git
- **Python version**: 3.7 from Anaconda, Development Environment
- **Operating system**: Ubuntu Linux 17.10

### What is the current behavior?
Runtime error at statement: from qiskit import Aer
ImportError: cannot import name 'Aer' from 'qiskit' (/home/claude/anaconda3/envs/QiskitDevenv/lib/python3.7/site-packages/qiskit/__init__.py)

### Steps to reproduce the problem
My install sequence:  
conda create -y -n QiskitDevenv python=3
source activate QiskitDevenv

download zip https://github.com/Qiskit/qiskit-aqua.git
cd /home/claude/Downloads/qiskit-aqua/qiskit-aqua-master
pip install -r requirements.txt
pip install -r requirements-dev.txt

pip install git+https://github.com/Qiskit/qiskit.git
pip install git+https://github.com/Qiskit/qiskit-aer.git
pip install git+https://github.com/Qiskit/qiskit-terra.git
pip install git+https://github.com/Qiskit/qiskit-aqua.git
pip install git+https://github.com/Qiskit/qiskit-chemistry.git
conda install -n QiskitDevenv -c anaconda anaconda-navigator
conda install  -n QiskitDevenv nbconvert
~/anaconda-navigator 
launch Jupyter, execute notebook with chemistry pilot sample 

pip list 
..
qiskit                0.8.0      
qiskit-aer            0.1.1      
qiskit-aqua           0.4.2      
qiskit-chemistry      0.4.3      
qiskit-ignis          0.1.0      
qiskit-terra          0.8.0   
..
### What is the expected behavior?
Successful import of class Aer from the installed qiskit package.

**Comment by chriseclectic** [comment]
@claudefalbriard You need to follow the [build instructions](https://github.com/Qiskit/qiskit-aer/blob/master/.github/CONTRIBUTING.md#building) for building and install Aer from source if you are installing from the git repo. Otherwise use `pip install qiskit-aer` to install pre-built wheels.

**Comment by claudefalbriard** [comment]
Thanks @chriseclectic . Got a working installation using the basic pip installation process. I've corrected it with the pip uninstall & install procedure. Important was to add the packages in the following sequence: 
pip uninstall qiskit-chemistry 
pip uninstall qiskit-aqua
pip uninstall qiskit-terra
pip uninstall qiskit-aer
pip uninstall qiskit
pip install qiskit      # (also installs aer and terra)
pip install qiskit-aqua
pip install qiskit-chemistry 

In the sample, there also was a slight change in the module names of aqua components, needed to be adjusted at the chemistry sample (qiskit.aqua.components now are qiskit_aqua.components).

**Comment by chriseclectic** [comment]
Glad you got it working!

**Comment by ltmamela** [comment]
Hi please help me with this error below:

ImportError: cannot import name 'Aer' from 'qiskit' with Microsoft Visual studio
