### ISSUE TITLE
Revisit usage of move_all_qubits_to_sorted_ordering

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#1122]
`move_all_qubits_to_sorted_ordering` is a function in the MPS simulator, which may cause up to `n^2` swap operations to take place. It is called by `sample_measure_using_probabilities` and `apply_measure`. It seems that, in both cases, the calling functions can be rewritten, in a way that allows to remove the call to `move_all_qubits_to_sorted_ordering` and save the swap operations.

**Comment by merav-aharoni** [comment]
Note that when doing this enhancement, you need to pay attention to the ordering of measuring the qubits in `measure_all`. In this case, the order of measuring must always be from a measured qubit to a physical neighbor. Best to use `qubit_ordering_` and not rely on default ordering.
