### ISSUE TITLE
pip install qiskit-aer puts providers into qiskit meta-package

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#113]
### Informations

- **Qiskit Aer version**: 0.1.1
- **Python version**: 3.7
- **Operating system**: OSX

Qiskit Terra: master

### What is the current behavior?
`pip install qiskit-aer` is putting the `Aer` provider into the `qiskit` meta package and not into the terra providers module:

```
/miniconda3/lib/python3.7/site-packages/qiskit/providers/aer/*
```
So terra cannot find it:
```
ImportError: cannot import name 'Aer' from 'qiskit' (/miniconda3/lib/python3.7/site-packages/qiskit_terra-0.8.0-py3.7-macosx-10.7-x86_64.egg/qiskit/__init__.py)
```

**Comment by atilag** [comment]
Have this changed recently on Terra?
Where should `Aer` goes now?

**Comment by nonhermitian** [comment]
It should still go into terra providers. But it seems that it goes into meta package on my machine.

**Comment by ronyaad** [comment]
How do you fix this? I'm new to programming.

**Comment by atilag** [comment]
On all my envs, I don't have that Terra path in `site-packages`. @nonhermitian how did you install Terra? Seems like coming from an `egg` package (which is the old format of setuptools). We haven't tested packages installed via `egg` with packages installed via `wheel`, the latter is considered the standard way of packaging.

**Comment by chriseclectic** [comment]
Is this a bug with aer install, or with the qiskit meta-package install?

**Comment by nonhermitian** [comment]
I did setup.py install from terra sourse

**Comment by nonhermitian** [comment]
If you install everything from source with no meta-package, then Aer does the right thing.  Will close.
