### ISSUE TITLE
Access to the MPS that comes out of the QasmSimulator(method='matrix_product_state')

### ISSUE THREAD

**Issue by henrik-dreyer** [Qiskit/qiskit-aer#1156]
It would be very useful for my application, if I had access to the matrix product state at the end of the quantum evolution, i.e.,

```
from qiskit import QuantumCircuit
from qiskit import execute
from qiskit.providers.aer import QasmSimulator

circ = QuantumCircuit(2, 2)
circ.h(0)
circ.cx(0, 1)

simulator = QasmSimulator(method='matrix_product_state')

result = execute(circ, simulator).result()

#this would be nice:
final_mps = result.MPS.matrices
```

**Comment by merav-aharoni** [comment]
I assume you mean you would like to print out the internal structure of the MPS. If so, we are actually working on this at the moment, so you will have it soon.

**Comment by chriseclectic** [comment]
Support for saving the MPS state was added in #1159
