### ISSUE TITLE
'from_backend' method is replacing the 'local' config. property with the real backend 'local' property

### ISSUE THREAD

**Issue by manoelmarques** [Qiskit/qiskit-aer#1177]
### Informations

- **Qiskit Aer version**: 0.8.0
- **Python version**: 3.7.9
- **Operating system**: Ubuntu/MacOS

### What is the current behavior?

When someone uses from_backend to 'mimic' a real backend, the 'local' configuration property is set to False which causes problems In qiskit.utils.QuantumInstance. As described on issue Qiskit/qiskit-aqua#1551 

### Steps to reproduce the problem:

```
from qiskit.providers.aer import QasmSimulator
from qiskit import IBMQ

IBMQ.load_account()
provider = IBMQ.providers()[0]
backend = provider.get_backend('ibmq_santiago')
print(backend.configuration().to_dict()['local']) # it is False
print(QasmSimulator().configuration().to_dict()['local'])  # it is True
print(QasmSimulator.from_backend(backend).configuration().to_dict()['local']) # Becomes False
```

### What is the expected behavior?

The 'local' property should remain unchanged since the backend is still local.

### Suggested solutions

Keep 'local' configuration property unchanged, set to 'True'

**Comment by woodsp-ibm** [comment]
@chriseclectic Any comment on this as this is causing Aqua to treat a local simulator, and the way we interact with it, as if it were a remote one based on this local flag.

**Comment by chriseclectic** [comment]
I don't really understand why you would need to do anything special depending on local vs remote for simulators, simulator vs not simulator should probably be enough, but either way it's a simple enough fix.

**Comment by woodsp-ibm** [comment]
Thanks Chris. To answer why we also have remote simulators. Anything remote had that configurable wait time; hence the test. At that point in code it does not care whether its a simulator or real device, all it cared about was the extra config that I guess is around how long we wait for remote, that does not apply when local.
