### ISSUE TITLE
MPS segfaults with noise model and measurement

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-aer#1184]
### Informations

- **Qiskit Aer version**: 0.7.6
- **Python version**: 3.8
- **Operating system**: MacOs

### Steps to reproduce the problem
```python
from qiskit import execute
from qiskit.test.mock import FakeManhattan
from qiskit.providers.aer import QasmSimulator
from qiskit.circuit.library import GraphState
from numpy import zeros 


n_qubits = 12
A = zeros((n_qubits, n_qubits))
rows = [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11]
cols = [1, 5, 0, 2, 1, 3, 2, 4, 3, 6, 0, 7, 4, 11, 5, 8, 7, 9, 8, 10, 9, 11, 6, 10]
A[rows, cols] = 1

qc = GraphState(A)

qc.measure_all()

simulator = QasmSimulator.from_backend(FakeManhattan(), method='matrix_product_state')

execute(qc, simulator, shots=1024, optimization_level=0, seed_simulator=0, seed_transpiler=0)
```
```
lda must be >= MAX(M,1): lda=0 M=0.ldc must be >= MAX(M,1): ldc=0 M=0. BLAS error: Parameter number 9 passed to cblas_zgemm had an invalid value
Segmentation fault: 11
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 5 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Notice that does not segfaults if the `measure_all` is commented out.

**Comment by yaelbh** [comment]
Looks related to #991

**Comment by merav-aharoni** [comment]
@1ucian0, I made a fix for issue #991  (the bug you found with MPS on QFT) in PR #1188 . I would like to check if the fix is relevant for this bug as well. However, I am unable to run this example on master (only on stable). Can you update the test case to run on master?

**Comment by 1ucian0** [comment]
Could it be that is already solved in master?

**Comment by chriseclectic** [comment]
@1ucian0 This should be fixed by #1188 which was just merged into master. You can reopen if you find more bugs

**Comment by merav-aharoni** [comment]
I think there is another bug here, I am investigating at the moment. Let's keep it open until I understand more.

**Comment by chriseclectic** [comment]
I think we can finally close this one now
