### ISSUE TITLE
Incorrect results when using cache_blocking statevector simulator

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#1193]
### Informations

- **Qiskit Aer version**: 0.7
- **Python version**: 3.7
- **Operating system**: MacOS

### What is the current behavior?

Running the test teleport circuit on the statevector simulator with cache blocking enabled gives the wrong result.

### Steps to reproduce the problem

```python
import qiskit
from qiskit.providers.aer import QasmSimulator
from qiskit.visualization import plot_histogram

def teleport_circuit():
    """Testing a circuit originated in the teleportation algorithm"""

    # Classic 3-qubit teleportation
    qr = QuantumRegister(3)
    c0 = ClassicalRegister(1)
    c1 = ClassicalRegister(1)
    c2 = ClassicalRegister(1)
    # Compiles to creg order [c2, c1, c0]
    circuit = QuantumCircuit(qr, c0, c1, c2)

    # Teleport the |0> state from qr[0] to qr[2]
    circuit.h(qr[1])
    circuit.cx(qr[1], qr[2])
    circuit.barrier(qr)
    circuit.cx(qr[0], qr[1])
    circuit.h(qr[0])
    circuit.measure(qr[0], c0[0])
    circuit.measure(qr[1], c1[0])
    circuit.z(qr[2]).c_if(c0, 1)
    circuit.x(qr[2]).c_if(c1, 1)
    circuit.measure(qr[2], c2[0])
    
    return circuit

method = 'statevector'
sim1 = QasmSimulator(method=method)
sim2 = QasmSimulator(method=method, blocking_qubits=2)

qc = teleport_circuit()
a = qiskit.execute(qc, sim1).result().get_counts(0)
b = qiskit.execute(qc, sim2).result().get_counts(0)

plot_histogram([a, b])
```

Returns

![Screen Shot 2021-03-24 at 3 48 15 PM](https://user-images.githubusercontent.com/2235104/112374362-61f13180-8cb8-11eb-8747-de8683b71e67.png)

### What is the expected behavior?

The returned counts should be equal (up to sampling fluctuations)

### Suggested solutions

I'm not sure, this might only be an issue with circuits containing conditional instructions. The above example returns the correct result on the density matrix simulator with cache blocking enabled.

**Comment by doichanj** [comment]
I found a bug in cache blocking transpiler in handling measure operation. And I think I have fixed this bug to get proper cache blocked circuit. But I think I also have to test chunk state implementation. I need one more day.

**Comment by doichanj** [comment]
I opened PR #1197 to fix this issue.
