### ISSUE TITLE
running multiple quantum device in parallel

### ISSUE THREAD

**Issue by sassan72** [Qiskit/qiskit-aer#1195]
Is it possible with qiskit to define multiple quantum devices and run their circuits in parallel.  For example, considering some different devices 
dev0 = device("qiskit.aer", qubits=2)
dev1 = device("qiskit.aer", qubits=4)
dev2 = device("qiskit.aer", qubits=4)
and so on. 
for each of these devices, i have a quantum circuit. I am going to model multiple machine learning models based on the defined quantum circuits, like classical ensemble learning models. Finally, run all these quantum machine learning models in parallel to calculate their prediction.

**Comment by chriseclectic** [comment]
I think this is outside the scope of Aer. I suspect you would need to use some multiprocessing library to run jobs on multiple qiskit backends in parallel if these need to be independent and trained in some ML model.

If you just want to split execution of multiple circuits in parallel on an Aer simulator you could also try using the job splitting and custom executor functionality being added in the qiskit aer 0.9 release.
