### ISSUE TITLE
qisikit-aer-0.1.1 can't be found by pip

### ISSUE THREAD

**Issue by jwoehr** [Qiskit/qiskit-aer#120]
### Informations

- **Qiskit Aer version**: 0.1.1
- **Python version**: 3.6.8
- **Operating system**: IBM i

### What is the current behavior?
```
$ pip install qiskit-aer==0.1.1
Collecting qiskit-aer==0.1.1
  Could not find a version that satisfies the requirement qiskit-aer==0.1.1 (from versions: 0.1.0)
No matching distribution found for qiskit-aer==0.1.1
```
### Steps to reproduce the problem

```
pip install qiskit
```
### What is the expected behavior?
Installation of qiskit 0.8.0 should install qiskit-aer 0.1.1.

### Suggested solutions
Find out what got broken at PyPi.

**Comment by jwoehr** [comment]
Other users have reported this in qiskit.slack.com on other platforms.

**Comment by atilag** [comment]
Currently, we only support 64 bits on Linux / MacOS / Windows 10. So we only provide precompiled packages for these platforms. 
For the next release, we are going to support pip building in platforms where there's no a precompiled package (wheel package), but we cannot guarantee that everything will work.
There's a [CONTRIBUTING](https://github.com/Qiskit/qiskit-aer/blob/master/.github/CONTRIBUTING.md#pre-requisites) guide with detailed instructions on how to build from soure code.
