### ISSUE TITLE
Improve benchmarking framework

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#121]
We need to have this framework in place for the 0.2 release. 

### Additional features

* [ ] Add benchmarks for measure / reset
* [ ] Add benchmarks for structured circuits (eg from aqua algorithms).

### Bugs to fix

* [x] Result figures include large chunks of qobj text
* [x] Build doesn't work on some systems since it hardcodes building with g++-7

**Comment by atilag** [comment]
I have filed a new Feature Request in ASV repo (https://github.com/airspeed-velocity/asv/issues/803) that would be very useful for us. In the meantime, we will have to force benchmarkings to a specific platform/configuration.

**Comment by yehuda-naveh** [comment]
Not sure, how is this related to the new benchmark library in Qiskit - https://github.com/Qiskit/qiskit/tree/master/test/benchmarks

is it a separate thing/lib in aer? Additional benchmarks in the same lib? Try to add the features tested to existing benchmarks in the lib?

**Comment by atilag** [comment]
We are using the same python library for running the benchmarks, but we are measuring totally different things though. I've removed from the benchmarks the initial creation of the circuits and the compilation times. We only measure pure running time.
