### ISSUE TITLE
AerSimulator(method="statevector") with different performance from StatevectorSimulator

### ISSUE THREAD

**Issue by duarte-jfs** [Qiskit/qiskit-aer#1210]
### Informations

- **Qiskit Aer version**:0.8.0
- **Python version**:3.8.5
- **Operating system**:Windows 10 64-bit

### What is the current behavior?

The AerSimulator(method="statevector") takes exponentially more time to accomplish the same task when compared to StatevectorSimulator() and QasmSimulator(method="statevector").

![data](https://user-images.githubusercontent.com/60704674/113520628-3f9ac600-958c-11eb-9b15-2b1800115990.png)

### Steps to reproduce the problem

```python
from qiskit import *
from qiskit.providers import aer
from qiskit.quantum_info import random_statevector, Statevector, random_unitary
import numpy as np
from matplotlib import pyplot as plt
import time 

qasm=aer.QasmSimulator(method="statevector")
state=aer.StatevectorSimulator()
aer_sim=aer.AerSimulator(method="statevector")

def get_circuit(N, seed=3):
    state=random_statevector(2**N, seed=seed)
    unitary=random_unitary(2**N,seed=seed)

    qc=QuantumCircuit(N)
    qc.initialize(state,[i for i in range(N)])
    qc.append(unitary,[i for i in range(N)])
    return qc

qubits_range=[i for i in range(1,12+1)]

data_time_state=np.zeros(len(qubits_range))
data_time_qasm=np.zeros(len(qubits_range))
data_time_aer=np.zeros(len(qubits_range))
start1=time.time()
for i in range(len(qubits_range)):
    if i==0:
        print("num_qubits: {}/{}".format(qubits_range[i],qubits_range[-1]))
        start_main=time.time()
    else:
        print("num_qubits: {}/{} | time: {:.3f}".format(qubits_range[i],qubits_range[-1], time.time()-start_main))
        start_main=time.time()

    N=qubits_range[i]
    qc=get_circuit(N)
    
    start=time.time()
    data=execute(qc,backend=state)
    end=time.time()
    data_time_state[i]=end-start
        
    start=time.time()
    data=execute(qc,backend=qasm)
    end=time.time()
    data_time_qasm[i]=end-start
    
    start=time.time()
    data=execute(qc,backend=aer_sim)
    end=time.time()
    data_time_aer[i]=end-start
    
    
fig=plt.figure()
ax=fig.add_subplot(111)

ax.plot(qubits_range,data_time_qasm, label="qasm", marker="o")
ax.plot(qubits_range,data_time_state, label="state", marker="o")
ax.plot(qubits_range,data_time_aer, label="aer", marker="o")

ax.legend(loc="upper left")
# ax.set_yscale("log")
ax.set_xlabel("Number of qubits")
ax.set_ylabel("Ellapsed time ")

fig.savefig("data.png")
plt.close()
```

### What is the expected behavior?

I was expecting that all of them to have the same performance.

**Comment by chriseclectic** [comment]
Execute runs asynchronously so you can't benchmark it the way you have here. If you block until each simulation is finished by changing the line to `execute(qc, sim).result()`. You get the actual run time of each simulator:

![issue1210](https://user-images.githubusercontent.com/2235104/113733022-15e6b980-96c8-11eb-821d-3df9c99c43e2.png)

Here Aer and Qasm are the same as expected, but it does look like there is a bug with the qasm/aer simulators running all 1024 shots even though there is no measurement (while statevector always runs 1). Manually setting shots=1 everything looks as expected:

![issue1210_shots1](https://user-images.githubusercontent.com/2235104/113733011-12ebc900-96c8-11eb-8b46-df89b0469d3a.png)

**Comment by chriseclectic** [comment]
I double checked the code and the shots / sampling isn't technically a bug. Because the circuit contains initialize it disables sampling since a general initialize instruction requires a reset which doesn't allow sampling. If you changed it to `set_statevector` then sampling is enabled by default.
