### ISSUE TITLE
Partial result is no longer schema compliant

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-aer#1214]
### Informations

- **Qiskit Aer version**: 0.8.0
- **Python version**:
- **Operating system**:

### What is the current behavior?
Prior to 0.8.0, if some (but not all) of the circuits in a job fails, the resulting JSON is still schema compliant and can be loaded using `Result.from_dict()`. More specifically, result data for the failed circuit was `"data": {}`. 

In 0.8.0, this is now `"data:" null` and also `"metadata": null`, which cannot be used in `Result.from_dict()`. 

This applies to the standalone simulator (e.g. `ibmq_qasm_simulator`). 

### Steps to reproduce the problem

Prepare a qobj with 1 good and 1 bad circuit:
```
qc_new = transpile(ReferenceCircuits.bell())
qobj = assemble([qc_new]*2)
qobj.experiments[1].instructions[1].name = 'bad_instruction'
```
Run the qobj using standalone: `qasm_simulator qobj.json`.

### What is the expected behavior?

Partial result should still be schema compliant and can be loaded using `Result.from_dict()`.

**Comment by chriseclectic** [comment]
This looks like a bug with JSON serialization function when data/metadata classes are empty. I think the initial JSON structures just needs to be initialized explicitly as an object, not the library default (which I guess is null).
