### ISSUE TITLE
About the 24 qubits constraints for state vector or QASM simulator

### ISSUE THREAD

**Issue by SchordingersDogCat** [Qiskit/qiskit-aer#1228]
*BUG TEMPLATE* 

### Informations

- **Qiskit AER version**:latest version
- **Operating system**:Ubuntu 18.04

### What is the current behavior?

FAILURE: Can not get job id, Resubmit the qobj to get job id. Terra job error: 'Number of qubits 30 is greater than maximum (24) for "statevector_simulator".' 

###  Questions?

I am wondering why Qiskit sets such constraints on simulation. The memory of my computer is 64GB and can support the simulation of 32 qubits. 

However, when I execute my program using 30 qubits, I encounter the above problem.

**Comment by chriseclectic** [comment]
It sounds like you aren't using `Aer` but possible `BasicAer` or `IBMQ` provider? If you switch to using Aer you should be able to run 30 qubits.

See the  following tutorial: https://qiskit.org/documentation/tutorials/simulators/1_aer_provider.html

**Comment by SchordingersDogCat** [comment]
Hi,

I am very curious why Qiskit-Aer limits the number of qubits in simulation.

I checked that Aer does support 30 qubits. However, whatif I have more available mem, doesn't Aer support it?

Regards,
Vincent
