### ISSUE TITLE
Undeclared variable in state_chunk.hpp when compiling with AER_MPI

### ISSUE THREAD

**Issue by otbrown** [Qiskit/qiskit-aer#1234]
### Informations

- **Qiskit Aer version**: 0.9.0 (master branch)
- **Python version**: Python 3.8.5
- **Operating system**: HPE Cray Linux Environment (based on SLES 15)

### What is the current behavior?
Unable to compile with MPI support, due to an undeclared identifier compilation error. Error thrown in [state_chunk.hpp](https://github.com/Qiskit/qiskit-aer/blob/master/src/simulators/state_chunk.hpp).
`qiskit-aer/src/simulators/state_chunk.hpp:1263:7: error: use of undeclared identifier 'nLarge'`

### Steps to reproduce the problem
Compile from source with `AER_MPI` enabled.
`python ./setup.py bdist_wheel -- -DAER_MPI=True`

### What is the expected behavior?
Compile successfully with no errors.

### Suggested solutions
Add `uint_t nLarge;` somewhere between line 1256 and 1261 in state_chunk.hpp. qiskir-aer compiles successfully for me with this fix.

**Comment by chriseclectic** [comment]
@doichanj can you check this

**Comment by danbev** [comment]
@chriseclectic Sorry about this, this was my fault. I've opened #1241 with a suggestion to fix this.

**Comment by doichanj** [comment]
`nLarge` in `apply_chunk_x` function is not used so we can remove this variable (sorry I copied codes from `apply_chunk_swap` function and forgot removing this variable)

**Comment by otbrown** [comment]
Thanks for the prompt fix :)
