### ISSUE TITLE
AerProvider documentation incomplete 

### ISSUE THREAD

**Issue by Durd3nT** [Qiskit/qiskit-aer#1237]
The description of the arguments of the class methods `AerProvider.backend()` and `AerProvider.get_backends()` is imcomplete [here](https://qiskit.org/documentation/stubs/qiskit.providers.aer.AerProvider.html?highlight=aer%20get_backend#qiskit.providers.aer.AerProvider.get_backend).

**Comment by adam4nj** [comment]
which parts seems to be incomplete? i think it is well defined

**Comment by Durd3nT** [comment]
There's no documentation for the argument `filters` in `AerProvider.backends`. Or should the documentation currently used for `**kwarg` be the one for `filters` instead?

**Comment by adam4nj** [comment]
As `backends` returns a list of backends, filters can be applied,
```backends(name=None, filters=None, **kwargs)```.

In `get_backend`, it returns a **specific** backend by "specific filtering", so there isn't the need for a `filters` argument.

I think the parameter section of `backend`can be updated with `filters`
argument in the docs.

You could take a look at the source code for any further clarifications.

**Comment by hhorii** [comment]
Let me close this issue. If this issue still remains, please open a new issue.
