### ISSUE TITLE
qiskit.exceptions.QiskitError: 'Data for experiment "circuit15" could not be found.'

### ISSUE THREAD

**Issue by sudoyang** [Qiskit/qiskit-aer#1240]
### Informations

- **qiskit-aer': '0.7.5'**:
- **Python 3.7.9 (default, Nov  4 2020, 21:30:07) **:
- **Ubuntu 20.04**:

### What is the current behavior?

I try to run a simulation of 32 qubits but the qiskit report the error above. The same simulation can be run with 8 qubits,  and nothing else is changed. 

### Steps to reproduce the problem

I can provide the program if needed, actually it is the option pricing program (quantum_unary_option_pricing)

### What is the expected behavior?

32 qubit should be as same as 8 qubit behavior

### Suggested solutions

I do not know yet. I do not even know how to debug with this error message. Any suggestion is welcomed. Thanks!

**Comment by lhonrush** [comment]
Hello, I also encountered this kind of problem, when I reproduced the quantum neural network paper.
"QiskitError: 'Data for experiment "circuit-3" could not be found.'"
Do you have some workarounds?
And I want to look your code, okay?I'm also more interested in option pricing.

**Comment by sudoyang** [comment]
@lhonrush Hey,

I just describe my case, which maybe applies to your case as well.

It is due to the  simulation scale is way too big to be handled by Qiskit. So it throws the error.

In my case, debug process goes into Qiskit source code (qasm_controller.hpp) and eventually, I got 

"status=ERROR:
QasmSimulator:Insufficient memory for 33-qubit circuit using "statevector method. You could try using the "marix_product_state" or "extended_stabilizer" method instead."

In file qasm_controller.hpp, it checks available memory. If it fails, the corresponding circuit-x can not generate and python reports error like yours.

So the core reason for this is due to simulation scale is too big and insufficient memory.
