### ISSUE TITLE
CI: "Docs and Tutorial / tutorials (3.7)" fails on PRs

### ISSUE THREAD

**Issue by drewrisinger** [Qiskit/qiskit-aer#1251]
### Informations

- **Qiskit Aer version**: ``main`` branch
- **Python version**: 3.7
- **Operating system**: CI: ubuntu-20.04

### What is the current behavior?

On PR #1250, the "Docs and Tutorial / tutorials (3.7) (pull_request)" job is failing with the following error. It's unrelated to the contents of that PR.
```
2021-05-10T22:28:50.6161663Z sphinx-tabs 2.1.0 has requirement sphinx<4,>=2, but you have sphinx 4.0.1.
```

### Suggested solutions

I guess the constraints for sphinx or sphinx-tabs will need to be tightened to prevent incompatible versions being installed.
This should be temporary, b/c ``sphinx-tabs`` has already been updated with support, and this pin could be removed on the next release. https://github.com/executablebooks/sphinx-tabs/pull/110

**Comment by mtreinish** [comment]
Oh actually I was mistaken the issue is we're unnecessarily installing sphinx again in the tutorial job and that's ignoring the constraint from the already installed sphinx-tabs and causing pip check to fail at the end. That's even easier to fix.
