### ISSUE TITLE
qubits with only delays should not be simulated (in ideal)

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-aer#1299]
The output of the Qiskit transpiler when a circuit is scheduled is a circuit with a bunch of delay instructions. So when compiling to a large device the circuit will contain delays on idle qubits. 

Ideal aer simulator should treat those delays as no-op, and simulate a much smaller circuit.

e.g. qubits 0, 5, 6 should not be simulated in the circuit below.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/8622381/127585042-71e83cc7-0501-46c4-aede-e031ef04b387.png">

**Comment by chriseclectic** [comment]
Fixed in 0.9.0
