### ISSUE TITLE
Add circuit -> schedule conversion in Pulse Simulator

### ISSUE THREAD

**Issue by DanPuzzuoli** [Qiskit/qiskit-aer#1309]
### What is the expected behavior?

Allow circuits to be passed to the pulse simulator - internally we will need to add a line detecting circuits and calling:
```
sched = schedule(qc, backend)
```
along with changing the signature of the `run` function and adding a kwarg for `schedule` options.

Here is a self-contained example from @taalexander that can be used for testing:
```
import qiskit
from qiskit import pulse, transpile, schedule

backend_sim = qiskit.providers.aer.PulseSimulator()

backend = provider.get_backend("ibmq_armonk")

sim = qiskit.providers.aer.PulseSimulator.from_backend(backend)

qc = QuantumCircuit(1, 1)
qc.x(0)
qc.measure(0, 0)

with pulse.build(backend, name='x') as x_q0:
    pulse.play(pulse.Gaussian(duration=128, amp=0.1, sigma=16), pulse.drive_channel(0)) 

qc.add_calibration('x', (0,), x_q0)

sched = schedule(transpile(qc, backend), backend)
    
# Run simulation
results = sim.run(sched)
```

I.e. we should be able to call `sim.run(qc)` at the end without the schedule conversion.

**Comment by mtreinish** [comment]
Part of this was already done with: https://github.com/Qiskit/qiskit-aer/commit/ecb08195f9792a60902bd81e545930ed0e033234 but I don't know if calibrations work (I didn't test it). I assume it works fine since under the covers it just schedules the circuit but this just should be tested.

**Comment by jakelishman** [comment]
I think adding a kwarg for schedule options might not be right - in the proposal, there's already a way to manually control the scheduling, and that's to call `schedule(qc, backend, **kwargs)` yourself.  Adding more unrelated kwargs to `sim.run` possibly just makes the interface more complicated than having the manual call.

Would you still have `transpile` be needed to be called outside `sim.run`?   Presumably yes, since otherwise you'd be duplicating the transpilation pass?

**Comment by DanPuzzuoli** [comment]
I made this issue due to a bug pointed out by @Matt-Stypulkoski , however he has said that it turns out this isn't actually what the problem is :D (consistent with @mtreinish 's comment). Maybe we can keep this issue open for discussion while it gets tracked down, and then close and open another once it's sorted out.

**Comment by taalexander** [comment]
Can we close as @mtreinish's PR handles this and the execution issues are a result of https://github.com/Qiskit/qiskit-terra/issues/6898

**Comment by DanPuzzuoli** [comment]
Yep makes sense.
