### ISSUE TITLE
Add additional test coverage for optimized gates

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#132]
### What is the expected behavior?

Add additional test coverage for optimized gates in qubitvector class.

- [ ] mcx gate (currently only cx, ccx are tested using this)
- [ ] mcy gate
- [ ] mcz gate
- [ ] mcu1 gate
- [ ] mcu2 gate
- [ ] mcu3 gate
- [ ] mcswap
- [ ] apply_matrix for N-qubit gates (using unitary instruction)
- [ ] apply_diagonal_matrix for N-qubit gates (using unitary instruction)

**Comment by jparr721** [comment]
Hi @chriseclectic, 

I am heavily interested in helping out here. I don't necessarily have a heavy background in the subject but I am eager to learn. How might the ideal form of this expanded test coverage look? Is there any literature I can leverage to get up to speed more quickly?

Thanks

**Comment by chriseclectic** [comment]
Hi @jparr721 that would be great! If you're interested in helping out on this I just made some issues that might be a better place to start for the controlled-swap (#274) and controlled-u3 gates (#274), since these are both supported by Terra compiler to unroll into basis gates.

After that you could try these gates, but since there isn't a specific gate object in Terra yet you would have to define your own to build the tests, and you couldn't test the unrolling.

In general we should define class objects for these multi-controlled gates, but you could do a quick version for testing by directly using the gate objects (note that this will be defining them for a fixed number of qubits though). Ie something like

```python
from qiskit import QuantumCircuit, execute
from qiskit.circuit import Gate
from qiskit.providers.aer import QasmSimulator

# Make a 3-qubit controlled X gate
cccx = Gate("mcx", 4, [])   # 4-qubit gate

# Add to a quantum circuit where control bits are all set to 1
circ = QuantumCircuit(4, 4)
circ.x(0)
circ.x(1)
circ.x(2)
circ.append(cccx, [0, 1, 2, 3])
for j in range(4):
    circ.measure(j, j)

# Use custom basis gates because mcx isn't in QasmSimulator basis_gates yet
basis_gates = ['mcx', 'x']

# Get counts (should all be "1111")
result = execute(circ, QasmSimulator(), basis_gates=basis_gates).result()
result.get_counts(0)
```

**Comment by abhik-99** [comment]
Hey @chriseclectic, are the test added? I'd like to help out in any way I can.

**Comment by clarebirch** [comment]
Hi @chriseclectic! Is this issue still open? If so, I'd like to help out.

**Comment by yaelbh** [comment]
Multi-controlled gates: #1076 adds tests to all mc gates that are supported by Terra (some of them are not supported by Terra - see #1070). #1076 excludes deprecated `mcu1`.
