### ISSUE TITLE
Changing expval label causes circuit execution to fail

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#1332]
### Informations

- **Qiskit Aer version**: 0.8.2
- **Python version**:
- **Operating system**: Ubuntu 20.04

### What is the current behavior?
```python

N = 12
qc = QuantumCircuit(N)

qc.x(range(0, N))
qc.h(range(0, N))

for kk in range(N//2,0,-1):
    qc.ch(kk, kk-1)
for kk in range(N//2, N-1):
    qc.ch(kk, kk+1)
qc.measure_all()
qc.save_expectation_value(Pauli('Z'*12), range(12), label='counts')
```
raises:

```
~/miniconda3/envs/qiskit/lib/python3.9/site-packages/qiskit/providers/aer/backends/backend_utils.py in cpp_execute(controller, qobj)
     40     qobj.config.library_dir = LIBRARY_DIR
     41 
---> 42     return controller(qobj)
     43 
     44 

TypeError: 'float' object is not iterable
```

when using the aer or qasm simulators.  However, if I remove the `label` kwarg then the code executes without error.

### Steps to reproduce the problem
Run the above.

### What is the expected behavior?
It works.

**Comment by nonhermitian** [comment]
It looks like maybe using `counts` is just a no-no as it works with other labels.

**Comment by jakelishman** [comment]
Yeah as it stands, `counts` will conflict with the default outputs (think `Result.get_counts`) in Aer and BasicAer.  I expect you might get some weird behaviour if you use `"statevector"` or `"unitary"` as well, especially if you later try to retrieve the statevector or unitary.

It does perhaps raise the question of whether we should be namespacing parts of `Result`, to alleviate some of this sort of thing?

**Comment by chriseclectic** [comment]
"counts" is reserved for measurement counts. If you try and use it for something else you will end up passing some other raw data structure to initialize the qiskit `Counts` object which is going to error.

**Comment by hhorii** [comment]
I think that discussion was concluded that this is not an issue. Please reopen this if this is still a problem.
