### ISSUE TITLE
Expectation value using exval instruction does not match that of counts data for noisy simulations.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#1334]
### Informations

- **Qiskit Aer version**: 0.8.2
- **Python version**:
- **Operating system**:

### What is the current behavior?
Executing the below circuit using the mock Guadalupe backend gives different results for the exp val returned by the instruction and doing so directly from counts.
```python

N = 12
qc = QuantumCircuit(N)

qc.x(range(0, N))
qc.h(range(0, N))

for kk in range(N//2,0,-1):
    qc.ch(kk, kk-1)
for kk in range(N//2, N-1):
    qc.ch(kk, kk+1)

qc.measure_all()
qc.save_expectation_value(Pauli('Z'*12), range(12), label='after_meas_expval')
```
The instruction says the expval is `0.10888671875` where as doing the same calculation from the counts (using the Ignis `expectation_value` function) gives `0.060302734375`.

### What is the expected behavior?
I would expect these to be the same if I am interpreting the usage correctly.

**Comment by chriseclectic** [comment]
If you measure qubits, then compute an expectation value you are computing the expectation value of the collapsed state. You need to put the save instruction before measurement.

**Comment by nonhermitian** [comment]
Ahh so I cannot use this as a way to do exp vals from an ensemble of shots data.  Ok got it.
