### ISSUE TITLE
Why this Qiskit Aer noise circuit solved result like this

### ISSUE THREAD

**Issue by NicolasYL** [Qiskit/qiskit-aer#1336]
*BUG TEMPLATE* 

### Informations

- **Qiskit AER version**:
- **Operating system**:

### What is the current behavior?

**The code :**

![image](https://user-images.githubusercontent.com/47812418/131822980-bdd6bfdd-c7bb-4829-8994-f3a90571cc29.png)

**And I add print,the result is**

![image](https://user-images.githubusercontent.com/47812418/131822683-dc98a816-a84b-4b4e-990f-782c11ab8852.png)

**The output is :**
** {'0011': 5002, '0111': 4998}**

### What is the expected behavior?

**I guess the right answer is {0001:10000} ,Because the circuit is full of X and CX gate and noise gate error probability is 1.0**

So why it has two results? waiting for your reply,thanks a lot

---

**Comment by chriseclectic** [comment]
You should draw the transpiled circuit to see how the controlled gate is decomposed into basis gates for the simulator
