### ISSUE TITLE
Snapshot raises an error with statevector simulator

### ISSUE THREAD

**Issue by maddy-tod** [Qiskit/qiskit-aer#134]
### Informations

- **Qiskit Aer version**: 0.1.1
- **Python version**: 3.6
- **Operating system**: McOS

### What is the current behavior?
Using the snapshot instruction on the statevector simulator causes an error.

### Steps to reproduce the problem
```
from qiskit import *
import qiskit.extensions.simulator
q = QuantumRegister(1)
c = ClassicalRegister(1)
qc = QuantumCircuit(q,c)

qc.h(q[0])
qc.snapshot('1')
qc.s(q[0])

backend = Aer.get_backend('statevector_simulator')
result = execute(qc, backend=backend).result()
```
This raises the error
`'ERROR: Circuit contains invalid instructions ( invalid snapshot instructions: {MISSING})'`

**Comment by chriseclectic** [comment]
Hi @maddy-tod I think this might is fixed on the master branch. Running your above code snippet I get for `result.data(0)`:

```python
{'counts': {'0x0': 1},
 'statevector': [[0.7071067811865476, 0.0], [0.0, 0.7071067811865475]],
 'snapshots': {'statevector': {'1': [[[0.7071067811865476, 0.0],
     [0.7071067811865475, 0.0]]]}}}
```

**Comment by maddy-tod** [comment]
Hi @chriseclectic thanks for looking into this! Running against master fixed this issue
