### ISSUE TITLE
Statevector simulator gives incorrect result for ghz

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#135]
### Informations

- **Qiskit Aer version**: 0.1.1
- **Python version**:
- **Operating system**: osx

### What is the current behavior?
```python

qr = QuantumRegister(5,'qr')
cr = ClassicalRegister(5, 'cr')
ghz = QuantumCircuit(qr, cr)

ghz.h(qr[0])
ghz.cx(qr[0],qr[1])
ghz.cx(qr[1],qr[2])
ghz.cx(qr[2],qr[3])
ghz.cx(qr[3],qr[4])
ghz.barrier(qr)
ghz.measure(qr,cr)
ghz.draw()
```

```python
sim_backend = Aer.get_backend('statevector_simulator')
sim_result = execute(ghz, sim_backend).result()
sim_result.get_statevector(0)

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j])
```

### What is the expected behavior?
```python

sim_backend = BasicAer.get_backend('statevector_simulator')
sim_result = execute(ghz, sim_backend).result()
sim_result.get_statevector(0)

array([0.70710678+0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
       0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
       0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
       0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
       0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
       0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
       0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j,
       0.        +0.j, 0.        +0.j, 0.        +0.j, 0.70710678+0.j])
```

**Comment by chriseclectic** [comment]
This looks like the correct behaviour: You have a measurement so the statevector returned is after measurement collapse. You need to remove measure from your circuit if you want the entangled state returned.

**Comment by nonhermitian** [comment]
Actually, I still have issue with this answer.  You are correct that it is doing a measurement, but it is doing only a single measurement.  The original input has `shots=1024`, but the output shots is equal to one.  So you are returning only a single possible realization.  Indeed, the max shots allowed by the state vector simulator is equal to one.  Allowing measurements in a statevector simulator, and thus the possibility for multiple statevectors at output, seems in contradiction to the limit of a single shot.

**Comment by chriseclectic** [comment]
Yep the statevector and unitary simulator only allow a single shot, and will ignore shots command in qobj. The alternative would be that they raise an error if you do shots>1, but that might be a little overbearing since default is 1024.

You're right that Aer and BasicAer should produce the same output though. It looks like this is a bug in BasicAer due to measure sampling: for circuits like the one you have above the BasicAer simulator is getting the optimize flag that it can do measurement sampling, so its returning the final state as the state before sampling, but really this optimization should be disabled for the case of `shots=1`. I'll put a PR into terra to fix this.

**Comment by nonhermitian** [comment]
I understand for the unitary case, but the statecrctor simulator allowing measurements, but only doing a single shot is not consistent. It does not follow the other backends where probablistic output is sampled shots times.

**Comment by chriseclectic** [comment]
I don't think it's inconsistent, its just kind of useless. The idea is the statevector simulator is exactly a single-shot pass of the qasm simulator. This was decided after many long discussions so if for some reason someone *wanted* to  this they can, but generally if you want statevectors for multiple shots you should be using a snapshot on the qasm simulator.

**Comment by nonhermitian** [comment]
Exactly, so what is the point of performing measurements in the statevector simulator in the first place?  You just told me the correct way to do it is via qasm simulator.

**Comment by nonhermitian** [comment]
Regardless, will close.
