### ISSUE TITLE
Documentation error for `optimize_noise_threshold`

### ISSUE THREAD

**Issue by we-taper** [Qiskit/qiskit-aer#1359]
I wonder if `optimize_noise_threshold` applies for noisy circuit simulation, or just:

```
    * ``optimize_noise_threshold`` (int): Sets the qubit threshold for
      applying circuit optimization passes on ideal circuits.
      Passes include gate fusion and truncation of unused qubits
      (Default: 12).
```
as shown here:

https://github.com/Qiskit/qiskit-aer/blob/ea2ad477d9fe796c14a1b8c7a1d40d636ec30d4c/qiskit/providers/aer/backends/aer_simulator.py#L211

and here:

https://github.com/Qiskit/qiskit-aer/blob/ea2ad477d9fe796c14a1b8c7a1d40d636ec30d4c/qiskit/providers/aer/backends/qasm_simulator.py#L174

**Comment by jakelishman** [comment]
Just to check: you're asking whether it should say something like

> Sets the qubits threshold for application circuit optimization passes on _**noisy**_ circuits.  Passes include ...

I think, since this documentation is currently just a copy of the point above it for the `optimize_ideal_threshold` option?

**Comment by jakelishman** [comment]
@chriseclectic: this (and `optimize_ideal_threshold`) now appear to be dummy options with no effect - the most recent reference I could find to them being accessed was removed in #698.

**Comment by chriseclectic** [comment]
@jakelishman Yeah I think this is no longer used anywhere since refactoring circuit truncation to be done during circuit loading, and fusion has its own option value, so it should be removed from the backend options. `optimize_ideal_threadhold` is probably also unused now too.
