### ISSUE TITLE
qiskit-aer-gpu returns 'device': 'CPU' with pip install pkg or build from src

### ISSUE THREAD

**Issue by jasonlarkin** [Qiskit/qiskit-aer#1381]
### Informations

- **Qiskit Aer version**:

qiskit-aer-gpu     0.9.1
qiskit-terra       0.18.3

- **Python version**:

python --version
Python 3.7.11

- **CUDA version**:

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Sep_13_19:13:29_PDT_2021
Cuda compilation tools, release 11.5, V11.5.50
Build cuda_11.5.r11.5/compiler.30411180_0

nvidia-smi
Mon Nov  1 11:36:51 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:3B:00.0 Off |                    0 |
| N/A   27C    P0    35W / 250W |      0MiB / 16160MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

- **Operating system**:

cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"

### What is the current behavior?

I am running the demo qiskit-aer-gpu example from:
https://qiskit.org/documentation/tutorials/simulators/1_aer_provider.html
but in result.result() shows:

'device': 'CPU'

I have installed qiskit-aer-gpu via pip install and also built from src via:
https://github.com/Qiskit/qiskit-aer/blob/master/CONTRIBUTING.md#building-with-gpu-support

each with the same result.result()

### Steps to reproduce the problem

pip install qiskit-aer-gpu and https://github.com/Qiskit/qiskit-aer/blob/master/CONTRIBUTING.md#building-with-gpu-support

### What is the expected behavior?

That 'device': 'GPU' (and probably more diagnostics to confirm that it actually is running on GPU, including a performance benchmark).

### Suggested solutions

Not quite sure, have tried both methods of installation, also have tried both methods of install on a separate instance (ubuntu 20.04 and CUDA 10.1) with same result.result.  

### qiskit_gpu_test.py

```python

from qiskit import *

qc = QuantumCircuit(2, 2)
qc.h(0)
qc.cx(0, 1)

from qiskit.providers.aer import AerError

try:
    simulator_gpu = Aer.get_backend('aer_simulator')
    simulator_gpu.set_options(device='GPU')
except AerError as e:
    print(e)

result=execute(qc,backend=simulator_gpu)
print(result.result())

```

**Comment by chriseclectic** [comment]
Can you check the simulation method in your returned results? What should be happening is because your input circuit is Clifford and you didn't select a specific simulation method, the simulator will automatically select to run this circuit using the stabilizer method.

The stabilizer method does not have a GPU version so will always run on CPU. If you want to run a statevector simulation on a GPU you should also specify `method="statevector"` in the options, and then you should correctly see `"device": "GPU"` in the returned result metadata.
