### ISSUE TITLE
Non Unitary gate in simulator

### ISSUE THREAD

**Issue by akhil21** [Qiskit/qiskit-aer#1383]
### What is the expected behavior?
Is it possible to add a non-unitary gate by giving it's density matrix in a single qubit 'qasm-simulator'?
Certainly, I can't use `circuit.unitary()` for that. Is there any other way?

**Comment by chriseclectic** [comment]
I don't really understand what it is you are asking. A density matrix is a state, not a gate. Circuits can already accept non-unitary instructions in the form of Kraus or QuantumError instructions and be run on the simulator to simulate non-unitary noise or dynamics. Have you gone through the [simulator tutorials](https://qiskit.org/documentation/tutorials.html#classical-simulators) in particular the [building noise models one](https://qiskit.org/documentation/tutorials/simulators/3_building_noise_models.html)?

**Comment by akhil21** [comment]
@chriseclectic  The term **density matrix** might be misleading. I meant is it possible to apply a non-unitary gate by mentioning its matrix. For example, if I want to apply a Projection gate (projection on |0> ), can I provide [[1,0],[0,0]] matrix as the gate in the simulator?

**Comment by sassan72** [comment]
yes. You can. (PauliZ + Identity(2) )/2= [[1,0],[0,0]]
