### ISSUE TITLE
run code

### ISSUE THREAD

**Issue by Guogggg** [Qiskit/qiskit-aer#1389]
### Informations

- **Qiskit Aer version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
When I run in the fusion gate code in CostBasedFusion: : aggregate_operations function, debugging breakpoints shows the wrong values. Is there multithreaded control here?

### Steps to reproduce the problem
run more than15 bit

**Comment by jakelishman** [comment]
Please can you provide more information, such as a code sample, what the incorrect values are and what they should be?

**Comment by chriseclectic** [comment]
Closing inactive, feel free to reopen if you can provide more details
