### ISSUE TITLE
time_taken is overwritten

### ISSUE THREAD

**Issue by doichanj** [Qiskit/qiskit-aer#1398]
### Informations

- **Qiskit Aer version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
`time_taken` tags are written twice in the metadata.

https://github.com/Qiskit/qiskit-aer/blob/fb4cfa205f6b6860f69980a91a8dbe85e7d0dd22/src/controllers/aer_controller.hpp#L866-L868

and

https://github.com/Qiskit/qiskit-aer/blob/fb4cfa205f6b6860f69980a91a8dbe85e7d0dd22/src/controllers/aer_controller.hpp#L997-L999

so prior one overwrites `time_taken` 

### Suggested solutions

I think one of them should be renamed.

**Comment by chriseclectic** [comment]
Fixed in 1408
