### ISSUE TITLE
AER GPU execution fails with cuda-11.3

### ISSUE THREAD

**Issue by jackaraz** [Qiskit/qiskit-aer#1416]
### Informations
- qiskit  v0.34.0
- qiskit-aer v0.10.1
- qiskit-aer-gpu v0.10.1
- **Python version**: 3.8.11
- **Operating system**: CentOS Linux 7
- CUDA 11.3
- NVIDIA Tesla P100 PCIe 12GB

### What is the current behavior?
Qiskit AER simulator does not recognize the GPU and fails execution by saying that GPU is not supported on the system.

### Steps to reproduce the problem
```python
from qiskit import *

qc = QuantumCircuit(2, 2)
qc.h(0)
qc.cx(0, 1)

from qiskit.providers.aer import AerError

try:
    simulator_gpu = Aer.get_backend('aer_simulator')
    simulator_gpu.set_options(device='GPU')
except AerError as err:
    print(err)

result=execute(qc,backend=simulator_gpu)
print(result.result())
```
Output:
```
Simulation failed and returned the following error message:
ERROR: Failed to load qobj: Simulation device "GPU" is not supported on this system
Result(backend_name='aer_simulator_gpu', backend_version='0.10.1', qobj_id='', job_id='281eed6e-adbe-44ae-a1bc-e26e35ead147', success=False, results=[], date=2021-12-26T17:24:55.378961, status=ERROR: Failed to load qobj: Simulation device "GPU" is not supported on this system, metadata={}, time_taken=0.0009694099426269531)
```

### What is the expected behavior?
When I change the device to CPU I get the following;
```
Result(backend_name='aer_simulator', backend_version='0.10.1', qobj_id='4b7a25bf-bb70-4fc6-bc01-24d684425bc0', job_id='d6d68f3e-b085-4568-9772-7d7c4d9114f8', success=True, results=[ExperimentResult(shots=1024, success=True, meas_level=2, data=ExperimentResultData(), header=QobjExperimentHeader(clbit_labels=[['c', 0], ['c', 1]], creg_sizes=[['c', 2]], global_phase=0.0, memory_slots=2, metadata=None, n_qubits=2, name='circuit-146', qreg_sizes=[['q', 2]], qubit_labels=[['q', 0], ['q', 1]]), status=DONE, seed_simulator=3439217257, metadata={'parallel_state_update': 64, 'batched_shots_optimization': False, 'measure_sampling': False, 'device': 'CPU', 'num_qubits': 0, 'parallel_shots': 1, 'remapped_qubits': False, 'method': 'stabilizer', 'active_input_qubits': [], 'num_clbits': 2, 'input_qubit_map': []}, time_taken=3.5662000000000005e-05)], date=2021-12-26T17:36:14.007266, status=COMPLETED, status=QobjHeader(backend_name='aer_simulator', backend_version='0.10.1'), metadata={'time_taken': 0.000548059, 'time_taken_execute': 0.000118098, 'parallel_experiments': 1, 'omp_enabled': True, 'max_gpu_memory_mb': 0, 'num_mpi_processes': 1, 'time_taken_load_qobj': 0.000390756, 'max_memory_mb': 96035, 'mpi_rank': 0}, time_taken=0.0010790824890136719)
```

I'm not sure what is going wrong in this particular scenario since it's a very simple example I was expecting it to work. Are there any further steps to compile AER backend with CUDA libraries that I'm missing?

Thanks
Jack

**Comment by mtreinish** [comment]
Do you have both qiskit-aer and qiskit-aer-gpu installed in the same python environment? If so that might be your issue. The 2 packages are mutually exclusive and will conflict with each other if both are installed. Unfortunately python packaging doesn't give a mechanism to properly expose this automatically for pip so the burden is placed on users to install only one or the other. Do you get this issue if you only install `qiskit-aer-gpu` in your environment?

**Comment by hhorii** [comment]
I close this because no response for mostly one month. I hope @mtreinish 's comments cam be help.

**Comment by sirgeorgesawcon** [comment]
Reopening this issue, since I'm facing the same problem. I do have `cuquantum` and `qiskit-aer-gpu` installed, and I'm using the latest `qiskit 1.0` version. I'm running this code:

```python
from qiskit import *
from qiskit.primitives import BackendSampler
from qiskit_aer import Aer
qc = QuantumCircuit(2, 2)
qc.h(0)
qc.cx(0, 1)
qc.measure_all()
from qiskit_aer import AerError

try:
    simulator_gpu = Aer.get_backend('aer_simulator')
    simulator_gpu.set_options(device='GPU')
except AerError as err:
    print(err)


sampler = BackendSampler(simulator_gpu)
job = sampler.run(qc)
print(job.result().get_counts())
```

and it gives me the error 

```RuntimeError: Simulation device "GPU" is not supported on this system```

If I only install `qiskit-aer-gpu` and run the above code, I get the error that:


```ModuleNotFoundError: No module named 'qiskit_aer'```

So I had to install both `qiskit-aer` and `qiskit-aer-gpu`. 

But I'm not able to run the circuit.

**Comment by sanketsharma** [comment]
I am facing the same issue as above.

**Comment by LukeTheWalker** [comment]
Same issue here
