### ISSUE TITLE
Qiskit Aer Simulator Calling Error

### ISSUE THREAD

**Issue by alihakimtaskiran** [Qiskit/qiskit-aer#1417]
### Informations

- **Qiskit Aer version**:0.10.1
- **Python version**:3.8
- **Operating system**:Ubuntu 18.04
- **Architecture**: aarch64

### What is the current behavior?
I can't use `Aer Simulator`
 Trying to execute quantum circuit with Aer simulator with 
```
>>> import qiskit
>>> be=qiskit.Aer.backend("statevector_simulator")
``` 
 I am always getting following error:
```
Traceback (most recent call last):
  File "/home/ali/.local/lib/python3.8/site-packages/qiskit/__init__.py", line 88, in __getattr__
    from qiskit.providers import aer
  File "/home/ali/.local/lib/python3.8/site-packages/qiskit/providers/aer/__init__.py", line 65, in <module>
    from .aerprovider import AerProvider
  File "/home/ali/.local/lib/python3.8/site-packages/qiskit/providers/aer/aerprovider.py", line 19, in <module>
    from .backends.aer_simulator import AerSimulator
  File "/home/ali/.local/lib/python3.8/site-packages/qiskit/providers/aer/backends/__init__.py", line 17, in <module>
    from .aer_simulator import AerSimulator
  File "/home/ali/.local/lib/python3.8/site-packages/qiskit/providers/aer/backends/aer_simulator.py", line 29, in <module>
    from .controller_wrappers import aer_controller_execute
ImportError: /home/ali/.local/lib/python3.8/site-packages/qiskit/providers/aer/backends/../../../../qiskit_aer.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ali/.local/lib/python3.8/site-packages/qiskit/__init__.py", line 92, in __getattr__
    raise MissingOptionalLibraryError(
qiskit.exceptions.MissingOptionalLibraryError: "The 'qiskit-aer' library is required to use 'Aer provider'. You can install it with 'pip install qiskit-aer'."

```

### Steps to reproduce the problem
Due to the excpetion, I tried to install `qiskit-aer` from  [whl file](https://files.pythonhosted.org/packages/9d/b8/13830a3bc96ff2da54cc100e75d9842879c70c3c22cfb1dc58620ffdbd89/qiskit_aer-0.10.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl). Then I installed it with `python3.8 -m pip install qiskit_aer-0.10.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl` 

Whenever calling Aer backends,with `be=qiskit.Aer.backend("statevector_simulator")` , it returns error.

### What is the expected behavior?
I want to access Aer simulators

**Comment by alihakimtaskiran** [comment]
It got solved by adding `LD_PRELOAD` parameter. To do so, write in terminal `export LD_PRELOAD="~/.local/lib/python3.8/site-packages/qiskit_aer.libs/libgomp-d22c30c5.so.1.0.0 "`

**Comment by Myefan** [comment]
> It got solved by adding `LD_PRELOAD` parameter. To do so, write in terminal `export LD_PRELOAD="~/.local/lib/python3.8/site-packages/qiskit_aer.libs/libgomp-d22c30c5.so.1.0.0 "`

I ran into the same problem when I run https://github.com/Zhaoyilunnn/qdao.git. Following the README.md, I run
