### ISSUE TITLE
pip install fails on Windows with Python 3.10

### ISSUE THREAD

**Issue by fh-igd-mueller-roemer** [Qiskit/qiskit-aer#1426]
### Informations

- **Qiskit Aer version**: 0.10.2
- **Python version**: Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
- **Operating system**: Windows 10 Enterprise 21H2 (19044.1466)

### What is the current behavior?

pip install of `qiskit-aer` fails to build wheel with a compile error

```
C:\Users\xxxxxxxx\AppData\Local\Temp\pip-install-jjhrczf8\qiskit-aer_6d10377e38b245f1b64f0b51506ba143\src\simulators\statevector\qv_avx2.cpp : fatal error C1083: Cannot open compiler generated file: '': Invalid argument
```

### Steps to reproduce the problem

```powershell
pip install git+https://github.com/qiskit-community/qiskit-textbook.git#subdirectory=qiskit-textbook-src
# OR
pip install qiskit
```

### What is the expected behavior?

`qiskit`/`qiskit-aer` is installed sucessfully

### Suggested solutions

N/A

**Comment by jakelishman** [comment]
Neither Terra nor Aer are currently supported on Python 3.10 quite yet, sorry - we'll have wheels out for them in their next releases, but we were waiting on our dependencies for this cycle.  You should be able to have everything working fine if you use Python 3.9.

Our tracking issue on Terra is Qiskit/qiskit-terra#7102.

**Comment by fh-igd-mueller-roemer** [comment]
Thanks for the info. Guess I won't get around installing another copy of Python after all
