### ISSUE TITLE
AerJob should have circuits method

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-aer#1431]
### What is the expected behavior?

`AerJob` should have a `circuits` method that returns the circuits for the job. Besides being useful, it should exist because `IBMQJob` has it and the interfaces should match whenever possible.

**Comment by jakelishman** [comment]
Copied from #1432:

> While we should make things easy as possible for users, Aer still ought to be provider-independent; it's not specifically a simulator of IBM Q jobs, it's a simulator for all backends.  `AerJob` and `IBMQJob` already do derive from the same class - `qiskit.providers.job.JobV1`, which defines the spec.  `IBMQJob.circuits` goes beyond that, and it might not be appropriate in all situations - you can pass a `Schedule` to the Aer simulators too, which likely doesn't a circuit associated with it.

**Comment by hhorii** [comment]
I close this issue. I hope further discussion will be in [qiskit-terra](https://github.com/Qiskit/qiskit-terra) if`qiskit.providers.job.JobV1` should have `circuits`.
