### ISSUE TITLE
 AerJob should be consistent with IBMQJob

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-aer#1432]
### What is the expected behavior?

A common workflow is to use an Aer simulator backend while developing, and then switch to a hardware backend when ready to run on the hardware. To support this workflow, the AerJob and IBMQJob should be consistent with each other where appropriate. Maybe they should inherit from the same class.

Examples of inconsistency:
- #1431 
- `result.date` is a string in Aer but datetime in IBMQ

**Comment by jakelishman** [comment]
While we should make things easy as possible for users, Aer still ought to be provider-independent; it's not specifically a simulator of IBM Q jobs, it's a simulator for all backends.  `AerJob` and `IBMQJob` already do derive from the same class - `qiskit.providers.job.JobV1`, which defines the spec.  `IBMQJob.circuits` goes beyond that, and it might not be appropriate in all situations - you can pass a `Schedule` to the Aer simulators too, which likely doesn't a circuit associated with it.  Aer returning a datetime for its date would be better, but with it currently being implemented as a string, it's a little tricky to change the return type without breaking the public API.

**Comment by hhorii** [comment]
I close this issue. I hope further discussion will be in [qiskit-terra](https://github.com/Qiskit/qiskit-terra) if common result interface of `qiskit.providers.job.JobV1` is required.
