### ISSUE TITLE
build from source failed on windows

### ISSUE THREAD

**Issue by MichaelCache** [Qiskit/qiskit-aer#1433]
### Informations

- **Qiskit Aer version**: on branch stable/0.10
- **Python version**: 3.9.7
- **Operating system**: window 11 and 10

### What is the current behavior?
created a virtual environment by conda with python3.9.7 installed
build qiskit-aer from source with cmake options like:
`cmake -DSKBUILD=TRUE -DCMAKE_BUILD_TYPE=Debug`
It's wired that controller_wrappers.pyd and test_python_to_cpp.pyd can be produced but pulse_utils can not for it require python39_d.lib.
I checked CMakeLists.txt twice, did not figure out any difference among these targets.

Besides, import controller_wrappers from python will return DLL load failed 
### Steps to reproduce the problem
1. compile error
work in conda virtual env, and all depends pacakge installed by pip(include pybind11)
```
cd build
cmake -DSKBUILD=TRUE -DCMAKE_BUILD_TYPE=Debug ..
cmake --build .
```
Will cause
`LINK : fatal error LNK1104: cannot open file “python39_d.lib” [xxxxxx\qiskit-aer\build\src\open_pulse\pulse_utils.vcxproj]`

2. import error
post-build, go to lib directory where controller_wrappers lies, start python of same virtual env
`import controller_wrappers`
will cause
`ImportError: DLL load failed while importing controller_wrappers: The specified module could not be found.`
But import test_python_to_cpp work properly
### What is the expected behavior?
1. for complie error
pulse_utils.pyd can be compiled
2. for import error
import controller_wrappers module will work like qiskit-terra dose

### Suggested solutions
1. I traced cmake with option --trace-expand and checked pulse_utils.vcxproj, can't find where “python39_d.lib” come from
2. I disassembled controller_wrappers.pyd by using IDA Freeware,  find function symbol `PyInit_controller_wrappers_0` and `pybind11_init_controller_wrappers`. I thought it is the import entrance.

**Comment by MichaelCache** [comment]
By the way, build under linux all is OK

**Comment by jakelishman** [comment]
Aer is a Python package with a C++ backing, so we usually wrap the build with scikit-build; there are a few extra cmake options we set in `setup.py` if running on Windows.  Does the build succeed with `pip install -e .` here?

**Comment by MichaelCache** [comment]
> Aer is a Python package with a C++ backing, so we usually wrap the build with scikit-build; there are a few extra cmake options we set in `setup.py` if running on Windows. Does the build succeed with `pip install -e .` here?

I tried using `python setup.py build` and find out the answer:
1. for import error:
controller_wrappers.pyd depends on `libopenblas.dll`, which should be placed at dynamic library search path.
In Windows, controller_wrappers linked with openblas of Aer, under `src/third-party/win32` or `win64`
In Linux, I used openblas lib in standard system lib path
Solution: add the lib path to system enviroment PATH or just copy dll to pyd directory

2. for compile error:
I enabled `CMAKE_VERBOSE_MAKEFILE` to see what compiler and linker command done.
But disappointed, no clue found. 
I guess may source code of pulse_utils include python header and under `CMAKE_BUILD_TYPE=Debug`, it must link python debug version lib.
I will keep tracing the error

**Comment by jakelishman** [comment]
We vendor OpenBLAS with Aer; the CMake build should unpack the libraries and link them in without you needing to modify your path.  Please make sure you have installed all the compiler dependencies, which are in the instructions in the [Getting Started guide](https://qiskit.org/documentation/getting_started.html).  It is unusual to need to call `setup.py build` manually.  Generally you would use `bdist_wheel` if using `setup.py` directly at all, but even that is not recommended - it is preferred to use `pip install -e .` for an in-place build and install, or `pip install build; python -m build --wheel .` to build only.

**Comment by jakelishman** [comment]
Looking further, in your original post, you are attempting to do the CMake build manually, and then you are then going into the Aer source, and attempting to import only a subcomponent of Aer.  This is _highly_ unlikely to work out-of-the-box; you should use the full `scikit-build` procedure by following the installation instructions linked before, and then you need to import the complete Aer package with `import qiskit.providers.aer` in Python, not attempt to navigate part way into the tree and import a submodule as if it were a top-level package.

**Comment by jakelishman** [comment]
I'll close this for now, because I think the problems were likely to do with some missing steps in the installation.  Feel free to re-open this, or open a new issue if you find other problems with the build.
