### ISSUE TITLE
Simulation fails when circuit contains metadata

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-aer#1435]
### Informations

- **Qiskit Aer version**: 0.10.2
- **Python version**: 3.8
- **Operating system**: Arch Linux

### What is the current behavior?
Simulation fails when circuit contains metadata.

### Steps to reproduce the problem
Input:
```python
from qiskit import Aer, QuantumCircuit

backend = Aer.get_backend("statevector_simulator")
circuit = QuantumCircuit(1, metadata = {1: object})
backend.run(circuit)
```
Output:
```
Simulation failed and returned the following error message:
ERROR: Failed to load qobj: to_json not implemented for this type of object: <class 'type'>
```
Input:
```python
from qiskit import Aer, QuantumCircuit

backend = Aer.get_backend("statevector_simulator")
circuit = QuantumCircuit(1, metadata = {object: 1})
backend.run(circuit)
```
Output:
```
Simulation failed and returned the following error message:
ERROR: Failed to load qobj: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

### What is the expected behavior?
Simulation should succeed. The metadata should be handled according to https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.html#qiskit.circuit.QuantumCircuit, which says
> metadata (dict) – Arbitrary key value metadata to associate with the circuit. This gets stored as free-form data in a dict in the metadata attribute. It will not be directly used in the circuit.

### Suggested solutions
None (yet).

**Comment by chriseclectic** [comment]
@hhorii For this one it might be better to not attempt to serialize the header information at all, and instead store it on the python side and add it back to the results after execution.
