### ISSUE TITLE
API docs for noise models

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#1451]
As far as I see, the API docs (starting from https://qiskit.org/documentation/apidoc/aer_noise.html) don't contain documentation about depolarizing and flip errors/

**Comment by chriseclectic** [comment]
I don't follow what specifically you think is missing?

The API docs you linked list all the the noise generating classes and functions like `depolarizing_error`, `pauli_errors` etc. If you are talking about noise models from backend, that is described in the documentation for that method:
https://qiskit.org/documentation/stubs/qiskit.providers.aer.noise.NoiseModel.from_backend.html#qiskit.providers.aer.noise.NoiseModel.from_backend

**Comment by yaelbh** [comment]
I don't know. I didn't see the depolarizing before but I see it now. Must be my mistake. Closing.
