### ISSUE TITLE
idle qubits are not optimized away

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-aer#147]
### Informations

- **Qiskit Aer version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
The simulation of noise becomes extremely slow for a 20-qubit circuit, even though only 3 qubits are active.

Edit: the 3 qubit one is equally slow. That's probably a separate bug.

### What is the expected behavior?
Aer should be more efficient in simulating sparse circuits. With some recent changes, Terra now embeds a small circuit on the full device and returns a circuit the size of that device. So this is a real example I got trying to simulate the behavior of a small circuit on Tokyo.

### Steps to reproduce the problem
```python
qasm = """OPENQASM 2.0;
include "qelib1.inc";
qreg q[20];
creg c[3];
u3(1.10207363987740,3.38905574496354,-2.33347511214731) q[0];
u3(0.208506566967889,0.259713258155296,-2.12932391686369) q[1];
u3(0.199241978886621,-2.74203199956075,2.25788452327037) q[5];
cx q[0],q[5];
cx q[5],q[0];
cx q[0],q[5];
cx q[1],q[0];
u1(3.27262754774519) q[0];
u3(-0.811363284435596,0.0,0.0) q[1];
cx q[0],q[1];
u3(1.48572479330530,0.0,0.0) q[1];
cx q[1],q[0];
u3(2.51699832056813,-2.73058127778721,1.58262917334812) q[0];
cx q[0],q[5];
u3(0.989024262401792,4.42691825885413,-4.57369861647542) q[1];
cx q[5],q[0];
cx q[0],q[5];
cx q[1],q[0];
u1(2.46289370014954) q[0];
u3(-1.66213330644361,0.0,0.0) q[1];
cx q[0],q[1];
u3(3.09782206744186,0.0,0.0) q[1];
cx q[1],q[0];
u3(2.23147548122233,-0.350255348380724,0.602491869202778) q[0];
cx q[0],q[5];
u3(0.270435327116765,0.933056308516186,0.128753386588826) q[1];
cx q[5],q[0];
cx q[0],q[5];
cx q[0],q[1];
u3(-1.61740988418189,0.0,0.0) q[0];
u1(0.762771715778533) q[1];
cx q[1],q[0];
u3(3.07583422211664,0.0,0.0) q[0];
cx q[0],q[1];
u3(1.70456258257962,-0.252456527824428,-2.36180183089211) q[0];
u3(0.538560668214003,0.930143172545291,1.93761476960866) q[1];
barrier q[1],q[0],q[5];
measure q[0] -> c[0];
measure q[5] -> c[1];
measure q[1] -> c[2];
"""

circ = QuantumCircuit.from_qasm_str(qasm)
circ.draw(output='mpl', style={'fold': 100})

d = {0: 0, 1: 1, 5: 2}
small_q = QuantumRegister(3)
small_circ = QuantumCircuit(small_q, circ.cregs[0])
for gate, qargs, cargs in circ:
    new_qargs = list(map(lambda x: (small_q, d[x[1]]), qargs))
    small_circ.append(gate, new_qargs, cargs)
small_circ.draw(output='mpl', style={'fold': 100})

from qiskit import IBMQ, execute
from qiskit.providers.aer.noise.device import basic_device_noise_model

IBMQ.load_accounts()
devicename = 'ibmq_poughkeepsie'
device = IBMQ.get_backend(name=devicename)

qasm_sim = Aer.get_backend('qasm_simulator')
```

```python
%%time

# 20 q noisy simulation, only 3 q active -- time: 65 s
noisy_counts = execute(small_circ, qasm_sim, shots=100,
                       noise_model=basic_device_noise_model(device.properties()),
                       coupling_map=device.configuration().coupling_map,
                       basis_gates=device.configuration().basis_gates).result().get_counts()
```

```python
%%time

# same circuit, remove idle wires -- time: 65 s
noisy_counts = execute(small_circ, qasm_sim, shots=100,
                       noise_model=basic_device_noise_model(device.properties()),
                       coupling_map=device.configuration().coupling_map,
                       basis_gates=device.configuration().basis_gates).result().get_counts()
```

```python
%%time 

# no noise -- time: 0.3 s
noisy_counts = execute(circ, qasm_sim, shots=100,
                       coupling_map=device.configuration().coupling_map,
                       basis_gates=device.configuration().basis_gates).result().get_counts()
```

**Comment by chriseclectic** [comment]
This isn't a bug, but rather a limitation of the statevector simulation method. It's also the main reason for why we will be adding a density matrix simulator in the future for small numbers of qubits: you only need a single shot with measure sampling for noisy simulations. With statevector based methods (without branching) you are limited by `ideal_time * constant factor * shots / parallel_shot_threads` where the factor depends on how many additional noise instructions are inserted into the circuit for each shot, and the type (kraus noise is around 2-3 times as expensive as unitary noise for example). This constant factor could be able to be improved in a couple of ways:

* improving efficiency of applying kraus matrices
* adding circuit optimization pass that fuse sampled noise instructions and gates to reduce total operations

And for the original issue of unused qubits having an optimization pass that

* remap circuit to smaller qubit circuit if some qubits are unused by instructions

I think we should open separate issues to track each of these for after the current release is done.

A more long term optimization that would be a much larger undertaking is implementing caching and branching for each stochastic operation.
