### ISSUE TITLE
GPU multi-chunk measure fails when qubits are out of chunk

### ISSUE THREAD

**Issue by doichanj** [Qiskit/qiskit-aer#1483]
### Informations

- **Qiskit Aer version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
measure operation returns incorrect value when using multi-chunk parallelization (cache blocking) and index qubit is out of chunk qubits.

### Steps to reproduce the problem
This issue can be reproduced by using some noise model into a circuit and using cache blocking in statevector simulator.

### Suggested solutions
norm() and trace() returns batched sum for all chunks so the measured value is always [1, 0].
Disable batched sum so that each chunk returns local sum correctly.

**Comment by hhorii** [comment]
fixed with #1480.
