### ISSUE TITLE
aer_simulator_density_matrix doesn't work with cswap gates 

### ISSUE THREAD

**Issue by hykavitha** [Qiskit/qiskit-aer#1486]
### Environment

- **qiskit-terra**: 	0.19.2 
- **qiskit-aer**: 	0.10.3
- **qiskit-ignis**: 	0.7.0
- **qiskit-ibmq-provider**: 	0.18.3
- **qiskit**: 	0.34.2
- **qiskit-machine-learning**: 	0.3.0
- **System information**
- **Python version**: 	3.10.0
- **Python compiler**: 	Clang 12.0.0
- **Python build**: 	default, Nov 10 2021 11:24:47
- **OS**: 	Darwin
- **CPUs**: 	4
- **Memory (Gb)**: 	16.0
- **Wed Mar 16 18:45:34 2022 IST**
![Uploading Screenshot 2022-03-16 at 10.22.22 PM.png…]()

### What is happening?

when a quantum circuit has cswap gates, then using aer_simulator_density_matrix backend the code breaks with a qiskit error 

QiskitError: 'ERROR:  [Experiment 0] Circuit circuit-16 contains invalid instructions {"gates": {cswap}} for "density_matrix" method. ,  ERROR: Circuit circuit-16 contains invalid instructions {"gates": {cswap}} for "density_matrix" method.' 

### How can we reproduce the issue?

Please run this code with necessary imports
```python
shots = 10000

qc_qsp = QuantumCircuit(5)
qc_qsp.h(0)
qc_qsp.barrier()
qc_qsp.h(1)
qc_qsp.cx(1,2)
qc_qsp.barrier()
qc_qsp.cx(3,4)

qc_qsp.cswap(0,1,3)
qc_qsp.cswap(0,2,4)
qc_qsp.barrier()
qc_qsp.x(0)
qc_qsp.barrier()
qc_qsp.measure_all()

qc_qsp.draw()

sim_density = Aer.get_backend('aer_simulator_density_matrix')

job_density = sim_density.run(qc_qsp, shots=shots)
counts_density = job_density.result().get_counts(0)
plot_histogram(counts_density, color='midnightblue', title='Counts for aer_simulator_statevector')
```
### What should happen?

It should execute & return the experiment count example like this when I run in statevector simulator
<img width="743" alt="Screenshot 2022-03-16 at 10 25 53 PM" src="https://user-images.githubusercontent.com/13769864/158645099-71f23697-5f53-4efa-bc4f-fa0f77e142dd.png">
s

**Comment by mtreinish** [comment]
Not every simulation method supports all gates, they each have different basis gates they support. You can just call `transpile()` to have qiskit compile the circuit for the specified aer backend with the simulation method set. So in your code example above calling: `transpile(qc_qsp, sim_density)` prior to the `sim_density.run()` line will do this. That will compile the input circuit to something that can be run with the density matrix simulation method.

**Comment by hykavitha** [comment]
Thank you @mtreinish 
thats correct and hence closing this issue
