### ISSUE TITLE
Wrong units in qiskit.providers.aer.noise.device.thermal_relaxation_values documentation

### ISSUE THREAD

**Issue by renatomello** [Qiskit/qiskit-aer#1487]
[Documentation](https://qiskit.org/documentation/stubs/qiskit.providers.aer.noise.device.thermal_relaxation_values.html) says `T1` and `T2` are returned in microseconds. However, the function actually return `T1` and `T2` in nanoseconds

**Comment by y4izus** [comment]
To help fixing this bug, this is the [line that should be modified](https://github.com/Qiskit/qiskit-aer/blob/main/qiskit/providers/aer/noise/device/parameters.py#L152)
