### ISSUE TITLE
Remove documentation that MPS is restricted to up to 100 qubits

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#1493]
Somewhere in our documentation and tutorials (https://quantum-computing.ibm.com/services/docs/services/manage/simulator, maybe additional places), we estimate the number of qubits the different methods can take. This leads to a repeating question in the slack channels, as to why the MPS simulator is said to be restricted to 100 qubits, when it's sometimes able to do more. So we have to rephrase the docs.

Here's an example: https://quantumcomputing.stackexchange.com/questions/25631/why-am-i-able-to-simulate-such-high-qubit-numbers-on-my-laptop?noredirect=1#comment33446_25631 (note that this page possibly exposes some issue with the density-matrix simulator).

**Comment by mtreinish** [comment]
That isn't the qiskit-aer documentation it's the IBM service documentation. The IBM service uses qiskit-aer for its hosted simulator offerings, but the documentation for it is completely independent. There isn't any change we can make to the repo around documentation that would change that. I'm going to close this issue as it's not something we can fix in aer itself. But please feel free to reopen it if I'm missing something or there is more to discuss.

**Comment by yaelbh** [comment]
@mtreinish Do you know in which repo I should open this issue?

**Comment by HuangJunye** [comment]
@yaelbh I DM you the internal repo.
