### ISSUE TITLE
NoiseModel.from_dict() fails with numpy error

### ISSUE THREAD

**Issue by RSGuptaUS** [Qiskit/qiskit-aer#1505]
### Information

- **Qiskit Aer version**: {'qiskit-terra': '0.20.0', 'qiskit-aer': '0.10.4', 'qiskit-ignis': '0.7.0', 'qiskit-ibmq-provider': '0.19.0', 'qiskit-aqua': None, 'qiskit': '0.36.0', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}
- **Python version**: 3.9.7
- **Operating system**: Mac OS 12.2.1

### What is the current behavior?
The following code fails:
```
import qiskit as qk
import numpy as np
print("qiskit version:", qk.version.__qiskit_version__)
print("numpy version:", np.version.full_version)
from qiskit import IBMQ
from qiskit.providers.aer.noise.noise_model import NoiseModel
IBMQ.load_account()
provider=IBMQ.get_provider(hub=HUB, group=GROUP project=PROJECT)
backend = provider.get_backend(BACKEND)
d = NoiseModel.from_backend(backend).to_dict()
NoiseModel.from_dict(d)
```

Fails with:

```
/opt/anaconda3/envs/amebam3_1/lib/python3.9/site-packages/qiskit/quantum_info/operators/predicates.py in is_unitary_matrix(mat, rtol, atol)
    157     mat = np.array(mat)
    158     # Compute A^dagger.A and see if it is identity matrix
--> 159     mat = np.conj(mat.T).dot(mat)
    160     return is_identity_matrix(mat, ignore_phase=False, rtol=rtol, atol=atol)
    161 
AttributeError: 'numpy.complex128' object has no attribute 'dot'
```
Instantiating a noise model from dict (`NoiseModel.from_dict(d)`) also fails with qiskit aer version 0.10.2. However, it works for:

`{'qiskit-terra': '0.20.0', 'qiskit-aer': '0.9.1', 'qiskit-ignis': None, 'qiskit-ibmq-provider': '0.18.3', 'qiskit-aqua': None, 'qiskit': None, 'qiskit-nature': '0.3.0', 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}`

### Steps to reproduce the problem
Unknown

### What is the expected behavior?
Instantiating a noise model from dict (`NoiseModel.from_dict(d)`)  should return a valid `NoiseModel` obj.

### Suggested solutions
There were some bug fixes to NoiseModel methods in qiskit aer 0.10.2 that might have created this bug

**Comment by hhorii** [comment]
The reason is that `pauli` gate can not be deserialized  from a dict (ex: `{'name': 'pauli', 'params': ['II'], 'qubits': [0, 1]}`)  in [`QuantumError._to_circuit()`](https://github.com/Qiskit/qiskit-aer/blob/a21260c5030c4bf01256e911e715e4bf9d176254/qiskit/providers/aer/noise/errors/quantum_error.py#L281-L304). However, this deserialization is deprecated.
