### ISSUE TITLE
Add refresh and datetime arguments to NoiseModel.from_backend()

### ISSUE THREAD

**Issue by renatomello** [Qiskit/qiskit-aer#1507]
I suggest these two modifications to the NoiseModel class:

```python
    @classmethod
    def from_backend(cls, backend,
                     gate_error=True,
                     readout_error=True,
                     thermal_relaxation=True,
                     temperature=0,
                     gate_lengths=None,
                     gate_length_units='ns',
                     standard_gates=None,
                     warnings=True,
                     refresh: bool = False,
                     datetime: Optional[python_datetime] = None):
```
and
```python
    if backend_interface_version <= 1:
        properties = backend.properties(refresh = refresh, datetime = datetime)
```

This would allow a user to query different noise parameters using timestamps, which can improve analysis of local simulations of noise models.
I've done these modifications in my local install and they work fine, but I couldn't figure out how to PR them here

**Comment by HuangJunye** [comment]
Related issue in Terra: https://github.com/Qiskit/qiskit-terra/issues/7834

**Comment by renatomello** [comment]
> backend.properties() cannot take arguments.

But [here](https://qiskit.org/documentation/stubs/qiskit.providers.ibmq.IBMQBackend.properties.html#qiskit.providers.ibmq.IBMQBackend.properties) says it does take `refresh` and `datetime`. I have code running locally using these arguments on `backend.properties()`

**Comment by mtreinish** [comment]
The backend interface is vendor agnostic and provides an general interface for any hardware or simulator to interface with qiskit's compiler and provides a abstract interface that authors of applications can leverage to reliably and uniformly execute circuits on a variety of hardware. The `BackendV1` class defines this interface here: https://qiskit.org/documentation/stubs/qiskit.providers.BackendV1.properties.html#qiskit.providers.BackendV1.properties and as you can see it doesn't take any arguments. (you can also see a guide on how to write a provider here: https://qiskit.org/documentation/apidoc/providers.html#writing-a-new-provider but it is using a newer version of the interface which doesn't even have a `properties()` method). The `qiskit-ibmq-provider`'s backend class documentation you linked to is one implementation of this abstract interface and in that implementation they add the extra keyword arguments for `refresh` and `datetime` to the `properties()` method. But that is a custom feature for only the ibmq provider and not something that can be used generally as only backends from the ibmq provider will support it. qiskit-aer's `NoiseModel.from_backend()` constructor is designed to work with any backend object from any provider and we can't have it only work with IBM's backends. So if you wanted to build a noise model from a different provider (for example: https://github.com/qiskit-community/qiskit-honeywell-provider, https://github.com/Qiskit-Partners/qiskit-aqt-provider,  https://github.com/Qiskit-Partners/qiskit-ionq, or terra's fake backend provider) these kwargs aren't valid and would raise an exception if they're passed to the `properties()` method.

**Comment by renatomello** [comment]
I see now, thank you for the explanation

**Comment by hhorii** [comment]
This is not an issue of Aer. We hope a provider supports to set a specific datetime for `backend.properties()`.
