### ISSUE TITLE
All hyperlinks on the readme are hardcoded to point the now defunct Master branch

### ISSUE THREAD

**Issue by GenericUser127** [Qiskit/qiskit-aer#1509]
Since Main is now the default branch, this is obviously wrong and it ends up with users un knowingly following old documentation.

Example:

```
**Note**: This package is only available on x86_64 Linux. For other platforms
that have CUDA support you will have to build from source. You can refer to
the [contributing guide](https://github.com/Qiskit/qiskit-aer/blob/master/CONTRIBUTING.md#building-with-gpu-support)
for instructions on doing this.
```

My suggestion would be to use relative links:

```
[contributing guide](CONTRIBUTING.md#building-with-gpu-support)
```

**Comment by garrison** [comment]
Relative links will be best for the files in the root directory, but there are two mentions in a release not an one mention in a header file that should remain absolute links, with `main` instead of `master`.

**Comment by padraignix** [comment]
I ended up getting impacted by this while building locally. Happy to take it on and pay it forward.
