### ISSUE TITLE
AerSimulator.run() with parameter_binds returns identical results for each circuit instance in some cases

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit-aer#1511]
### Informations

- **Qiskit Aer version**: 0.10.4
- **Python version**: 3.8.12
- **Operating system**: MacOS

### What is the current behavior?
Running multiple instances of a noisy circuit results in the same counts dictionary for each instance of the circuit. They should be simulated as independent runs of a circuit so should not have identical outcomes.

This bug happens if `backend.run()` is called with the `parameter_binds` argument, where `backend` is a noisy `AerSimulator`.
It does not happen if the circuit instances are instead bound in advance and submitted to `backend.run()` without the `parameter_binds` argument.
The bug is also avoided if `seed_simulator` is passed to `run` along with `parameter_binds`. For the moment this is a temporary workaround to get the speed benefit of using `parameter_binds` while avoiding the bug.

### Steps to reproduce the problem
```
from qiskit.providers.aer import AerSimulator, noise
from qiskit import QuantumCircuit, __qiskit_version__
from qiskit.circuit import Parameter

noise_model = noise.NoiseModel()
noise_model.add_quantum_error(noise.depolarizing_error(0.01, 1), ['x'], [0])
noise_model.add_quantum_error(noise.depolarizing_error(0.01, 1), ['x'], [1])
        
backend = AerSimulator(noise_model=noise_model)

theta = Parameter('theta')
qc = QuantumCircuit(2)
qc.rz(theta,0) # dummy parameter, has no effect
qc.x([0,1])
qc.measure_all()
display(qc.draw(output='mpl'))

import numpy as np
all_counts_bound = backend.run([qc.assign_parameters([0]) for _ in range(5)]).result().get_counts()
all_counts_noseed = backend.run(qc,parameter_binds=[{theta:np.zeros(5)}]).result().get_counts()
all_counts_seeded = backend.run(qc,parameter_binds=[{theta:np.zeros(5)}],seed_simulator=0).result().get_counts()
print('unique outcomes submitting bound circuits (not all same --> GOOD)')
[print(c) for c in all_counts_bound]
print('\nunique outcomes submitting parameter_binds without seed_simulator (all same --> BAD):')
[print(c) for c in all_counts_noseed]
print('\nunique outcomes submitting parameter_binds with seed_simulator (not all same --> GOOD):')
[print(c) for c in all_counts_seeded];
```

Output:
<img width="687" alt="image" src="https://user-images.githubusercontent.com/60495383/164310093-5f702008-94ca-4b5b-9b55-360d7650133d.png">

### What is the expected behavior?
The counts from each circuit instance should be independent of those from each other circuit instance. Otherwise this causes serious and hard-to-notice problems for users running simulations.

**Comment by hhorii** [comment]
Thank you for your reports. I fixed this issue with #1512.
