### ISSUE TITLE
NoiseModel.add_basis_gates() appears not to add custom gates

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit-aer#1514]
### Informations

- **Qiskit Aer version**: 0.10.4
- **Python version**: 3.8.12
- **Operating system**: MacOS

### What is the current behavior?
![image](https://user-images.githubusercontent.com/60495383/165656671-648b8244-73a5-45fa-8308-31ba7ecc0b20.png)

### What is the expected behavior?
I expected `add_basis_gates()` would append that string to the basis gates of the noise model.
It seems to me this may be a bug. The source code for `add_basis_gates()` has a warning message (view by passing `warnings=True`) saying that it's adding a non-standard gate to the noise model basis, even though nothing happens. Sorry if it's actually the expected behavior and I'm just using it wrong.

(While I'm here -- bigger picture I'm trying to define a custom error, and add it to a circuit as its own gate (`quantum_channel`), and run that in a simulator. I'm now starting to think this doesn't require any noise model at all actually, because the Aer backend itself already supports a `quantum_channel`, but while tinkering found the above behavior that seems like a bug).

**Comment by hhorii** [comment]
Aer does not handle the predefined gates which are listed in [backend_utils.py](https://github.com/Qiskit/qiskit-aer/blob/d37415f29d9800f894b308adb07fbdbd1d9fd0c4/qiskit/providers/aer/backends/backend_utils.py#L52-L96). Therefore, `add_basis_gates('my_gate')` does not add any basis gates (warning will appear if `warnings=True` is specified).
I guess that [this document](https://qiskit.org/documentation/tutorials/simulators/4_custom_gate_noise.html) may help your work.
