### ISSUE TITLE
Problem when building the Qiskit Aer Python extension with MPI support

### ISSUE THREAD

**Issue by dotslaser** [Qiskit/qiskit-aer#1520]
Python version: 3.8.10
Operating System: Ubuntu 20.04.4 LTS

Building with (as seen [here](https://github.com/Qiskit/qiskit-aer/blob/main/CONTRIBUTING.md#building-with-mpi-support)):
**python ./setup.py bdist_wheel -- -DAER_MPI=True**

As far as I can see it just builds with the default configuration (AER_MPI=False). It doesn't use the CMake flags when building.
Any help would be appreciated :)

**Comment by jakelishman** [comment]
I think you need two lots of `--` to pass CMAKE options through `scikit-build` - do you get the same results if you do
```bash
python ./setup.py bdist_wheel -- -- -DAER_MPI=True
```
?

**Comment by dotslaser** [comment]
That does not seem to work, but thanks anyway!

**Comment by jakelishman** [comment]
Hmm, I'm very not sure - on my machine (macOS 11.something, python 3.9), I can see that the exact command you gave does trigger the MPI search correctly.  If I run `python setup.py bdist_wheel`, there's a section of the normal output that looks like:
```text
-- Conan: Loading conanbuildinfo.cmake
-- Conan: Adjusting output directories
-- Conan: Using cmake targets configuration
-- Library spdlog found /Users/jake/.conan/data/spdlog/1.5.0/_/_/package/00fe5aae379977aed80467b93af85a921a1b4a29/lib/libspdlog.a
-- Library gomp found /Users/jake/.conan/data/llvm-openmp/12.0.1/_/_/package/e46341e9b52d3e4c66657dc8fb13ab6cdd5831c6/lib/libgomp.dylib
-- Library iomp5 found /Users/jake/.conan/data/llvm-openmp/12.0.1/_/_/package/e46341e9b52d3e4c66657dc8fb13ab6cdd5831c6/lib/libiomp5.dylib
-- Library omp found /Users/jake/.conan/data/llvm-openmp/12.0.1/_/_/package/e46341e9b52d3e4c66657dc8fb13ab6cdd5831c6/lib/libomp.dylib
-- Library muparserx found /Users/jake/.conan/data/muparserx/4.0.8/_/_/package/6a83d7f783e7ee89a83cf2fe72b5f5f67538e2a6/lib/libmuparserx.a
-- Library fmt found /Users/jake/.conan/data/fmt/6.2.1/_/_/package/6a83d7f783e7ee89a83cf2fe72b5f5f67538e2a6/lib/libfmt.a
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: /Users/jake/code/qiskit/aer/_skbuild/macosx-10.16-x86_64-3.9/cmake-build
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Looking for Apple BLAS & Lapack library...
-- BLAS library found: /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Accelerate.framework
-- Performing Test flag_supported
-- Performing Test flag_supported - Success
-- No Thrust supported backend
-- No Thrust support enabled
-- Found PythonLibs: /Users/jake/.miniconda3/envs/qiskit/lib/libpython3.9.dylib (found version "3.9.7")
-- /Users/jake/.miniconda3/envs/qiskit/include/python3.9
```
(that's not all the output, I just picked out the surrounding lines)

and if I run `python setup.py bdist_wheel -- -DAER_MPI=True`, I can see that the MPI search happens before the last two lines I've copied:
```text
-- Found MPI_C: /usr/local/Cellar/open-mpi/4.1.2/lib/libmpi.dylib (found version "3.1")
-- Found MPI_CXX: /usr/local/Cellar/open-mpi/4.1.2/lib/libmpi.dylib (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Found PythonLibs: /Users/jake/.miniconda3/envs/qiskit/lib/libpython3.9.dylib (found version "3.9.7")
-- /Users/jake/.miniconda3/envs/qiskit/include/python3.9
```

If your search isn't occurring at all, I'm really not sure what might be going on here.  As a temporary workaround if you really want MPI support, you could modify `CMakeLists.txt` by making the `if(AER_MPI)` block on line 304 happen unconditionally.

**Comment by IgnacioRiveraGonzalez** [comment]
I tried again and you're right, MPI support is activated. I found a problem with my circuit and  that's why I couldn't distribute it with MPI. I find the 'blocking_qubits' option confusing. Could you briefly explain what it does and how it relates to the total number of qubits? Thanks a lot!!

**Comment by dotslaser** [comment]
I tried again and you're right, MPI support is activated. I found a problem with my circuit and that's why I couldn't distribute it with MPI. I find the 'blocking_qubits' option confusing. Could you briefly explain what it does and how it relates to the total number of qubits? Thanks a lot!!

**Comment by jakelishman** [comment]
I won't be able to give you a good answer, but I'll tag @doichanj and @hhorii, one of whom should be able to help.

**Comment by doichanj** [comment]
`blocking_qubits` option should be set if you use multiple processes with MPI. 
If the circuit has n-qubits and parallelizing with 2^m processes, `blocking_qubits` should be set to less than `n-m`.
However `blocking_qubits=n-m` requires 2*16*2^(n-m) bytes on each process to store distributed states and copy of states received from other process, So it is recommended to set around 20 to `blocking_qubits` if n is large (more than 30)

**Comment by dotslaser** [comment]
Thank you!! Now I understand it better.
