### ISSUE TITLE
Parallel.rst using deprecated method to apply gates

### ISSUE THREAD

**Issue by JMuff22** [Qiskit/qiskit-aer#1532]
Currently in `docs/apidocs/parallel.rst` the U gates are applied as `circ.u1(pi/2,2)` and `circ2.u1(pi/2,2)` which flags a warning that this method is deprecated as of 0.16.0. 

The fix should be using the circuit library (https://qiskit.org/documentation/apidoc/circuit_library.html) and 

```
from qiskit.circuit.library import U1Gate
...
gate = U1Gate(pi/2)
...
circ.append(gate, [2])
...
circ2.append(gate,[2])
```

**Comment by jakelishman** [comment]
Thanks, it's good to get rid of these deprecations.

`U1Gate` as a whole is actually not something we want to be using - the preferred form would actually be to use the general `u`, which is
```
circ.u(0, 0, 5, 2)
```

**Comment by upsideon** [comment]
@jakelishman The deprecation message suggests using the [PhaseGate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.PhaseGate.html#qiskit.circuit.library.PhaseGate) via [QuantumCircuit.p](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.p.html?highlight=p) as it is equivalent to the [U1Gate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.U1Gate.html?highlight=u1gate#qiskit.circuit.library.U1Gate). Is there a particular reason to use a `UGate` over `PhaseGate` when making changes to these examples?
