### ISSUE TITLE
Aer-0.1.1 installation from source

### ISSUE THREAD

**Issue by fvarchon** [Qiskit/qiskit-aer#155]
### Informations

- **Qiskit Aer version**: 0.1.1
- **Python version**: 3.7.3
- **Operating system**: Windows 10

### What is the current behavior?
Problem during installation from source:
pip install -r requirements-dev.txt     |     OK
python ./setup.py install    | FAIL

-- Build files have been written to: C:/Users/XXX/qiskit-aer-master/qiskit-aer-master/_cmake_test_compile/build
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying "Ninja" generator - success
--------------------------------------------------------------------------------

CMake Error at CMakeLists.txt:13 (project):
  Running

   'C:/Users/XXX/AppData/Local/Temp/pip-build-env-fx2syg7k/overlay/Scripts/ninja.exe' '--version'

  failed with:

   The system cannot find the file specified

### Steps to reproduce the problem

try to install aer from source

### Suggested solutions

WORKAROUND FOUND have to add 2 lines CMakeLists.txt

set(CMAKE_C_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe")
set(CMAKE_CXX_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe")

**Comment by atilag** [comment]
We need to improve building documentation for our Windows users, I'm closing this issue and creating a new one that will address the lack of documentation.
