### ISSUE TITLE
delete snapshot instructions

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-aer#1554]
### What is the expected behavior?

#1270 was released in [0.9.0](https://github.com/Qiskit/qiskit-aer/releases/tag/0.9.0) (Sept, 2021).
- https://github.com/Qiskit/qiskit-aer/pull/1270

**Comment by 1ucian0** [comment]
0.11 was released. Bumping this one to 0.12

**Comment by jakelishman** [comment]
Released in Aer 0.11 via #1591.
