### ISSUE TITLE
Aer.get_backend("aer_simulator", statevector_parallel_threshold=1) ignores the keyword arguments

### ISSUE THREAD

**Issue by rht** [Qiskit/qiskit-aer#1568]
### Informations

- **Qiskit Aer version**: 0.10.4 but also applies to latest main
- **Python version**: 3.10.5
- **Operating system**: Linux

### What is the current behavior?

The `statevector_parallel_threshold=1` is ignored.

### Steps to reproduce the problem
Initialize with `Aer.get_backend("aer_simulator", statevector_parallel_threshold=1)` and run a simulation. I didn't observe any matrix ops parallelization.

### Suggested solutions

I think this is the cause. In https://github.com/Qiskit/qiskit-aer/blob/8ca389a53314cf0f5d921277006ebf1795a51697/qiskit/providers/aer/aerprovider.py#L64-L77, the `kwargs` is not passed to the `backend_cls(**opts)`. This should be a quick fix.

**Comment by hhorii** [comment]
I created to a PR #1572 to discuss configurations of AerSimulator can be conditions of filtering and decided not.

Your requirement will be satisfied with `Aer.get_backend("aer_simulator").set_options(statevector_parallel_threshold=1)`, I believe.

**Comment by rht** [comment]
I see, thank you!

I find it confusing that the catch-all `kwargs` is being used specifically for filtering (in https://github.com/Qiskit/qiskit-terra/blob/3f9edfc83e6effdacbcce063361878d96b5ed1d5/qiskit/providers/providerutils.py#L47). If it were a keyword argument like `filter_criteria={"key": "value", ...}`, I would have encountered "unexpected keyword argument" when I passed in the `statevector_parallel_threshold=1`, and would be redirected to use `set_options` instead.

**Comment by rht** [comment]
To put more context on me being confused: when I searched on the internet on how to set backend option, this was one of the relevant results: https://qiskit.org/documentation/stubs/qiskit.providers.aer.AerSimulator.html.

Quoting the docstring:
> These may be set using the appropriate kwargs during initialization. They can also be set of updated using the [set_options()](https://qiskit.org/documentation/stubs/qiskit.providers.aer.AerSimulator.set_options.html#qiskit.providers.aer.AerSimulator.set_options) method.

The `AerSimulator` has this `kwargs`, and since I saw this before I read the docstring of `AccountProvider.get_backend
`, I assumed that the `kwargs` of `AccountProvider.get_backend` also has the same functionality.
