### ISSUE TITLE
extended_stabilizer_disable_measurement_opt does not work proprely

### ISSUE THREAD

**Issue by padraic-padraic** [Qiskit/qiskit-aer#157]
### Informations

- **Qiskit Aer version**: master
- **Python version**: 3.7.2
- **Operating system**: macOS

### What is the current behavior?
Enabling the measurement optimization for the `extended_stabilizer` method doesn't change the execution time.

### Steps to reproduce the problem
```python
qr = QuantumRegister(40)
cr = ClassicalRegister(40)
circ = QuantumCircuit(qr, cr)
circ.h(qr)
qubit_indices = [i for i in range(40)]
for i in range(10):
    control, target, t = random.sample(qubit_indices, 3)
    circ.cx(qr[control], qr[target])
    circ.t(qr[t])
circ.measure(qr, cr)
qobj = compile(circ, QasmSimulator(), shots=50)

unoptimized_job = QasmSimulator().run(qobj)
unoptimized_time = unoptimized_job.result().time_taken
optimized_job = QasmSimaultor().run(qobj, backend_options={
    'extended_stabilizer_disable_measurement_opt': True
})
optimized_time = optimized_job.result().time_taken
```

### What is the expected behavior?

`optimized_time` should be significantly smaller than the unoptimized time. However, currently, both options perform roughly the same.

### Suggested solutions

The bug seems to be introduced in line 290 of the `src/simulators/qasm/qasm_controller.hpp`

```C++
JSON::get_value(extended_stabilizer_disable_measurement_opt_, "disable_measurement_opt", config);
```

and indeed, passing `disable_measurement_opt` in `backend_options` gives the expected behaviour. So either this line or the documentation needs to be updated to make the option name consistent.

**Comment by chriseclectic** [comment]
Good catch @padraic-padraic. One question: is this measurement opt here different or equivalent to the sampling measurement opt used by the other simulation methods? If it's equivalent we should just have a single option `"disable_measure_sampling"` that can be set to `True` to disable sampling on all the qasm simulator methods.

**Comment by padraic-padraic** [comment]
It does function the same way i.e. it forces each shot to be resampled, and thus reruns the monte carlo method.

However, as I think came up in #98, disabling this option is required to get good results if simulating circuits that have some 0 probability amplitudes, so it's probably best that the optimizaiton is disabled by default for `extended_stabilizer`. This makes it slightly different from the other methods, where the optimization can be pretty sensibly turned on by default.

**Comment by chriseclectic** [comment]
Lets just have one option for now then `"extended_stabilizer_measure_sampling"` with default of `False` so that to enable you have to do `backend_options={"extended_stabilizer_measure_sampling": True}`.
