### ISSUE TITLE
qiskit namespace conflicts with Qiskit Terra in Jupyter environment

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-aer#1580]
### Informations

- **Qiskit Aer version**: 0.10.4
- **Python version**: 3.9.7
- **Operating system**: RHEL 8.6

### What is the current behavior?
qiskit namespace conflicts with Qiskit Terra in Jupyter environment

### Steps to reproduce the problem
1. Create a fresh virtual environment
```
pipenv shell
pip install --upgrade pip setuptools wheel
```
2. Install Qiskit Aer
```
pip install qiskit-aer
```
3. Install Qiskit Terra in editable mode
```
cd qiskit-terra
pip install -e .
```
4. Open a Jupyter notebook in this environment
```
pip install ipykernel
python -m ipykernel install --user --name tmp
```
5. In the Jupyter notebook, importing `qiskit` doesn't work. For example,
```python
import qiskit
print(qiskit)
```
```
<module 'qiskit' (namespace)>
```
```python
from qiskit import QuantumCircuit
```
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 from qiskit import QuantumCircuit

ImportError: cannot import name 'QuantumCircuit' from 'qiskit' (unknown location)
```

### What is the expected behavior?
Qiskit should work in the Jupyter notebook. It does work in a shell though.

### Suggested solutions
I don't know if this is related but I noticed that installing Qiskit Aer adds files to the virtual environment root where it seems they shouldn't be. For example, before installing Aer the virtual environment root has these contents:
```
bin
lib
lib64
pyvenv.cfg
```
After installing Aer, the contents are like this:
```
bin
cmake
CMakeLists.txt
contrib
lib
lib64
MANIFEST.in
pyproject.toml
pyvenv.cfg
qiskit
README.md
share
src
```
Most of the extra files seem to be from the Qiskit Aer repository.

**Comment by mtreinish** [comment]
This is a broader bug in python packaging around namespace packages see https://github.com/Qiskit/qiskit/issues/559. Namespace packaging in python is very error prone and I've been working for a long time on trying to fix this by removing namespace packaging from qiskit, and hopefully once #1526 merges we'll finally be done with using namespace packages for good.

The workaround in the meantime is try not to mix editable mode and standard installs of packages in the shared namespace, but if you must install terra first in editable mode and then try installing aer from pypi second.

As for the stray contents in the venv that's already reported in #1457 and is an upstream bug in scikit-build around the `MANIFEST.in` file.

**Comment by kevinsung** [comment]
Thanks @mtreinish . I tried installing both `qiskit-terra` and `qiskit-ibmq-provider` in editable mode, but installing the latter still causes the issue.

**Comment by kevinsung** [comment]
Setting the environment variable
```
SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
```
works around the issue. Thanks @jakelishman !

**Comment by kevinsung** [comment]
I'll close this issue since there is another one already tracking the namespace issue.
