### ISSUE TITLE
Incorrect result from Sampler when passing shots=None

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-aer#1584]
### Informations

- **Qiskit Aer version**: 788e2c31c8d2fc1787d142bad01cd8c8a296e7f5
- **Python version**: 3.9.13
- **Operating system**: Arch Linux

### What is the current behavior?
See title.

### Steps to reproduce the problem
```python
from qiskit import QuantumCircuit
from qiskit.primitives import Sampler as TerraSampler
from qiskit.providers.aer.primitives import Sampler as AerSampler

bell = QuantumCircuit(2)
bell.h(0)
bell.cx(0, 1)
bell.measure_all()

result = TerraSampler().run([bell], shots=None).result()
print("Terra result:")
print(result.quasi_dists)
print()

result = AerSampler().run([bell], shots=None).result()
print("Aer result:")
print(result.quasi_dists)
```
```
Terra result:
[{0: 0.4999999999999999, 1: 0.0, 2: 0.0, 3: 0.4999999999999999}]

Aer result:
[{3: 1.0}]
```

### What is the expected behavior?
The results should be correct (ideal probabilities in the absence of shot noise). In the above reproduction, the Sampler from Terra returns the correct result.

**Comment by ikkoham** [comment]
This is a documentation error. Are's Sampler does not support `shots=None` because Aer Sampler supports mid circuit measurements unlike Terra's reference implementation.

**Comment by ikkoham** [comment]
Anyway I'll fix it.

**Comment by kevinsung** [comment]
@ikkoham Simulating circuits without mid-circuit measurements is an extremely common use case. I think Aer's Sampler should behave the same as the reference implementation in this case. It can raise an error if `shots=None` and the circuit has mid-circuit measurements.

**Comment by ikkoham** [comment]
@kevinsung Yes, we can support such cases if we can make them error. I understand that some users need it as an enhancement request, so I will support it. #1588
