### ISSUE TITLE
QasmSimulator with density_matrix method returns "malloc: Incorrect checksum for freed object" error

### ISSUE THREAD

**Issue by v-r0** [Qiskit/qiskit-aer#1614]
### Informations

- **Qiskit Aer version**: 0.10.3
- **Python version**: 3.9.11
- **Operating system**: macOS 12.6

### What is the current behavior?

> python(2389,0x700007f38000) malloc: tiny_free_list_remove_ptr: Internal invariant broken (prev ptr of next): ptr=0x7fd0da7804d0, next_prev=0x8007fd0e27804d0
> python(2389,0x700008f3e000) malloc: Incorrect checksum for freed object 0x7fd0ca7bea08: probably modified after being freed.
> Corrupt value: 0x0
> python(2389,0x70000a747000) malloc: Incorrect checksum for freed object 0x7fd09b03cc48: probably modified after being freed.
> Corrupt value: 0x0
> python(2389,0x700007735000) malloc: Incorrect checksum for freed object 0x7fd0aa8082e8: probably modified after being freed.
> Corrupt value: 0x0
> python(2389,0x700009741000) malloc: Incorrect checksum for freed object 0x7fd07a705170: probably modified after being freed.
> Corrupt value: 0x0
> python(2389,0x700007f38000) malloc: *** set a breakpoint in malloc_error_break to debug
> python(2389,0x70000a747000) malloc: *** set a breakpoint in malloc_error_break to debug
> python(2389,0x700008f3e000) malloc: *** set a breakpoint in malloc_error_break to debug
> python(2389,0x700009741000) malloc: *** set a breakpoint in malloc_error_break to debug

### Steps to reproduce the problem

Run the following code

```
from qiskit.providers.aer import QasmSimulator
from qiskit import QuantumCircuit, execute

qc1 = QuantumCircuit(2,2)
qc1.h(0)
qc1.h(1)
qc1.measure(0,0)
qc1.save_density_matrix(label="dm1")

print(qc1.draw())

backend = QasmSimulator(method='density_matrix', precision='single')
result = execute(qc1, backend=backend)
```

### What is the expected behavior?

No memory allocation errors

### Suggested solutions

Removing 
`qc1.measure(0,0)`
avoids the runtime error. However, we don't get the desired density matrix after the measurement.

**Comment by hhorii** [comment]
Thank you for your reporting. I was not able to reproduce your situation with the latest version (0.11.0) on MacOS 12.6.
Do you observe this error in the latest code?

**Comment by v-r0** [comment]
@hhorii the code did run to completion on my side with 'qiskit': '0.38.0' and 'qiskit-aer': '0.11.0'

**Comment by hhorii** [comment]
@v-r0 Thanks. Please let reopen this issue (or create a new issue) if this problem is happened again.
