### ISSUE TITLE
Noise model from ibm calibration data instead of backend

### ISSUE THREAD

**Issue by YZ1999** [Qiskit/qiskit-aer#1615]
In the page of all ibm systems
https://quantum-computing.ibm.com/services/resources?tab=systems
calibration data is provided for quantum machines with larger number of qubits. However, with the NoiseModel.from_backend(backend) method, since I cannot access those quantum machines, creating a noise model of their calibration data cannot be done in a straight forward way.

### What is the expected behavior?

The user can use the calibration csv file downloaded from https://quantum-computing.ibm.com/services/resources?tab=systems to generate a noise model easily.

**Comment by itoko** [comment]
It's difficult for Qiskit to support the load of the csv files that is specific to IBM backends, I think.

I'm not sure IBM could accept the request (it may be unlikely), but why not ask IBM to make Backend objects available for all backends visible in the table view? (You could use the Slack channel #ibm-quantum-systems in qiskit.slack.com for that.) If it's accepted, that would be the most straightforward way to resolve this issue.

Even if it's not the case, you could do what you want to do using `FackBackend`s. `FackBackend` objects are created from JSON files (see e.g. https://github.com/Qiskit/qiskit-terra/tree/main/qiskit/providers/fake_provider/backends/manila). If you write some code to replace the values in `props_backendname.json` with those in a CSV file, you can create `NoiseModel` from the tweaked `FackBackend` object.
