### ISSUE TITLE
Can not build simulator from backend v2

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#1617]
### Informations

- **Qiskit Aer version**: 0.11
- **Python version**:
- **Operating system**:

### What is the current behavior?

This fails:

```python

sim = AerSimulator.from_backend(fake_provider.FakeAuckland())
```

`AerError: 'AerSimulator.from_backend does not currently support V2 Backends.'`

### What is the expected behavior?
I would expect to be able to build noise models for backend versions supported in Terra

**Comment by LucaZilli** [comment]
I have the same problem when I try to import qiskit_aer.noise.

`import qiskit_aer.noise`

> ImportError: cannot import name 'BackendV2' from 'qiskit.providers.backend'
