### ISSUE TITLE
Qiskit Aer still uses execute

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#1632]
E.g. https://qiskit.org/documentation/apidoc/aer_noise.html

**Comment by SrinathRamachandran** [comment]
I am interested in working on this issue, can you please assign this to me. Thanks!

**Comment by HuangJunye** [comment]
Great! @SrinathRamachandran is my mentor. Can you also assign me to this issue? @hhorii

**Comment by hhorii** [comment]
@SrinathRamachandran @HuangJunye I'm very sorry that my response is lazy.

Aer documentation is now here: https://qiskit.org/ecosystem/aer/apidocs/aer_noise.html. It still uses `execute()` :-).

**Comment by davidlearn** [comment]
I can work on this during the Unitary Fund Hackathon.

**Comment by davidlearn** [comment]
Has PR #1830 tested  the code in IBM Quantum Lab with the latest qiskit aer?

**Comment by dakk** [comment]
> Has PR #1830 tested the code in IBM Quantum Lab with the latest qiskit aer?

Yes. 
I made a small modification right now to the noise model example: now it uses fake_providers like the official tutorial (https://qiskit.org/documentation/tutorials/simulators/2_device_noise_simulation.html)

**Comment by davidlearn** [comment]
The real device ibm_vigo is retired now. Maybe you can use a certain fake device model related to a current running hardware device if possible.
________________________________

**Comment by dakk** [comment]
Good morning @hhorii , I have to be assigned to this issue  in order to receive the bounty; thank you
