### ISSUE TITLE
Aer documentation says IBMQ not IBM Quantum

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#1633]
Lots of places, eg.

https://qiskit.org/documentation/stubs/qiskit_aer.AerSimulator.html#qiskit_aer.AerSimulator

**Comment by 1ucian0** [comment]
Hi @AnsahMohammad  
   Do you mind comment on this issue so I can assign it to you?

**Comment by AnsahMohammad** [comment]
:) changed IBMQ to IBM Quantum 👍

**Comment by natestemen** [comment]
@1ucian0 are you sure this issue should be included in unitaryHACK. It looks like it was closed in January.

**Comment by 1ucian0** [comment]
you are right. This one is not UnitaryHACK. My bad.
