### ISSUE TITLE
Can't load an initial state in Aer simulator

### ISSUE THREAD

**Issue by mvcerezo** [Qiskit/qiskit-aer#166]
### Informations

- **Qiskit Aer version**: 0.7.1 (I got it from qiskit.__version__)
- **Python version**: 3.7.3 
- **Operating system**: Windows 10

### What is the current behavior?

I can't seem to load initial states in Aer. It always defaults to all qubits in the zero state

### Steps to reproduce the problem
`backend = Aer.get_backend('statevector_simulator')
qr = QuantumRegister(2)
circ = QuantumCircuit(qr)
circ.iden(qr)
config = {'initial_state': np.array([0, 0, 1, 1j])}
result = execute(circ, backend, shots=1, config=config).result()
print(result.get_statevector(circ))
circ.draw(output='mpl')`

### What is the expected behavior?
I would expect the result to be 
[0.+0.j 0.+0.j 0.+0.j 1.+0.j]

Whereas I'm getting [1.+0.j 0.+0.j 0.+0.j 0.+0.j]

### Suggested solutions
I have copied the previous example from [this post](https://github.com/Qiskit/qiskit-terra/issues/1424) but I can't get it to work now.

**Comment by chriseclectic** [comment]
@mvcerezo It looks like you are using an invalid config from an old pre-Aer version of qiskit.

You need to follow the this tutorial: https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/aer/aer_provider.ipynb

In the master branch (and version 0.2 when it is released soon) you should use the `intialize` circuit instruction directly to set an initial state (see here #82)

**Comment by mvcerezo** [comment]
@chriseclectic Thank you very much!
