### ISSUE TITLE
Can not load libcustatevec.so.1 correctly in Colab

### ISSUE THREAD

**Issue by Tim-Li** [Qiskit/qiskit-aer#1667]
I want to install "qiskit-aer" with GPU and cuStateVec support. I follow the previous issues on this repository to install. And I think I successfully installed the qiskit-aer. But I can not import qiskit-aer correctly. 

```
import qiskit
qiskit.__qiskit_version__
```
{'qiskit-terra': '0.22.2', 'qiskit-aer': None, 'qiskit-ignis': None, 'qiskit-ibmq-provider': '0.19.2', 'qiskit': '0.39.2', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}

How can I solve this problem?

 [Here](https://colab.research.google.com/github/Tim-Li/DLFBP-TXM/blob/main/TWCC_TEST.ipynb) is the link for colab. It shows more detail.

**Comment by hhorii** [comment]
What is your error log?

I guess you can not install qiskit-aer that you built because `!pip install -U dist/*` finished with following message:
> qiskit-aer is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
[ ]

**Comment by Tim-Li** [comment]
I execute the code:
`!pip uninstall qiskit-aer
 !pip install -U dist/* --force-reinstall
 `
when I run 
`
from qiskit.providers.aer import *
`
It shows：No module named 'qiskit.providers.aer'

And then I restart the colab, run again
`
from qiskit.providers.aer import *
`
It shows  "libcustatevec.so.1: cannot open shared object file: No such file or directory"

**Comment by hhorii** [comment]
> It shows "libcustatevec.so.1: cannot open shared object file: No such file or directory"

I think the above message is shown when the library is not in the `LD_LIBRARY_PATH`.  I guess colab does not apply your `LD_LIBRARY_PATH` configuration (`os.environ['LD_LIBRARY_PATH']=f"/usr/local/cuquantum/lib:{os.environ['LD_LIBRARY_PATH']}"`).

Please try just copy libraries to `/usr/lib64-nvidia/`, which is already included `LD_LIBRARY_PATH` in Colab with GPU.

```
!cp -r //usr/local/cuquantum/lib/* /usr/lib64-nvidia/
```

I do not think this is a good solution but I confirmed that it works in Colab.

**Comment by hhorii** [comment]
@derwind told me that ` -DCUSTATEVEC_STATIC=True` can resolve this issue. 

```
!python ./setup.py bdist_wheel -- -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CUDA_HOST_COMPILER=g++ -DAER_THRUST_BACKEND=CUDA -DCUSTATEVEC_ROOT=/usr/local/cuquantum -DCUSTATEVEC_STATIC=True
```

I confirmed it works: https://colab.research.google.com/drive/119Yx217cQoBazS56exLk5VSb9KyVuouk#scrollTo=E6EGA6TzI0gb
