### ISSUE TITLE
Develop own `assemble` to directly generate `Circuit` struct from `QuantumCircuit`

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-aer#1683]
### What is the expected behavior?

Currently Qiskit-Aer uses `QObj` as the common representation of simulation targets.
However, as #1660 mentioned, recent `QObj` does not support latest features of `QuantumCircuit`.
Also, converting `QObj` is an apparent overhead because it is converted into `Circuit` struct of C++ in pybind.
By providing own `assemble()` to convert `QuantumCircuit` to `Circuit` struct of C++, we will get performance and flexibility for its specification.
This new feature will also resolve an issue of #1652.

**Comment by adekusar-drl** [comment]
@hhorii are there any plans when this enhancement can be implemented?

**Comment by hhorii** [comment]
@adekusar-drl this will be a new feature in 0.12.0, which will be released in middle of this February.

**Comment by hhorii** [comment]
#1717 was merged.
