### ISSUE TITLE
Pass user specified directories to the build system

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#17]
### Informations

- **Qiskit AER version**: 0.1
- **Operating system**: OSX

### What is the current behavior?
The make system does not find the OpenBLAS libraries in their default location in OSX.  Instead, the Apple Accelerate libs are always used.

### What is the expected behavior?
The installer should find the OpenBLAS libs if they are installed in the default dirs.

**Comment by atilag** [comment]
There's a way to specify the BLAS implementation you want to use for building in [CMake](https://github.com/Qiskit/qiskit-aer/blob/master/CMakeLists.txt#L171). Apple Accelerate is our first candidate, so if CMake finds it, it just uses it.
This is not configurable at the moment. 
Seems to be a good candidate for a `Good First Issue`

**Comment by atilag** [comment]
Adding `HINTS` parameter to the find_package() and takeing it's value from a env variable seems the way to go here: 
```cmake
find_package(BLAS HINTS "$ENV{MY_ENV_VARIABLE}" REQUIRED)
```

**Comment by a07r** [comment]
@atilag  

I'm looking to get started, Not sure what "build system" tag is for! (there isn't a description to it in the labels)

Can I start here with this issue? (It's an old issue, has anything changed since you last made the comment!)

**Comment by atilag** [comment]
We have introduced a way to do this with BLAS so I'm closing this issue.
