### ISSUE TITLE
Installing from source cannot find module 'controller_wrappers'

### ISSUE THREAD

**Issue by Patataman** [Qiskit/qiskit-aer#1704]
I am trying to install Qiskit Aer from source but I get an error about a file that does not exists (or at least I am unable to find it).

### Informations

- **Qiskit Aer version**: main and 0.11.2
- **Python version**: 3.11 (but also tested with 3.10)
- **Operating system**: Ubuntu Jammy (22.04) under WSL

### What is the current behavior?

 ```
(venv) patataman@DESKTOP-A6AMFI6:~/dev/qiskit-aer$ python
Python 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import qiskit_aer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/patataman/dev/qiskit-aer/qiskit_aer/__init__.py", line 69, in <module>
    from qiskit_aer.aerprovider import AerProvider
  File "/home/patataman/dev/qiskit-aer/qiskit_aer/aerprovider.py", line 19, in <module>
    from .backends.aer_simulator import AerSimulator
  File "/home/patataman/dev/qiskit-aer/qiskit_aer/backends/__init__.py", line 17, in <module>
    from .aer_simulator import AerSimulator
  File "/home/patataman/dev/qiskit-aer/qiskit_aer/backends/aer_simulator.py", line 30, in <module>
    from .controller_wrappers import aer_controller_execute
ModuleNotFoundError: No module named 'qiskit_aer.backends.controller_wrappers'
```

### Steps to reproduce the problem

```
git clone https://github.com/Qiskit/qiskit-aer.git
cd qiskit-aer
git checkout stable/0.11
python3 -m virtualenv venv
source venv/bin/activate
pip install -e .
python -c "import qiskit_aer"
```

### What is the expected behavior?

No error

### Suggested solutions

It is very similar to this problem https://github.com/Qiskit/qiskit-aer/issues/1687, so might be related. However to this person the solution was just downgrade the version of Python 3.11.

I was trying with Python 3.10 an after seeing this I tried also with Python 3.11 (both cases got the same problem). 

This is my requirements

```
dill==0.3.6
mpmath==1.2.1
numpy==1.24.1
pbr==5.11.1
ply==3.11
psutil==5.9.4
python-dateutil==2.8.2
-e git+https://github.com/Qiskit/qiskit-aer.git@6b0e9996e907b48a3788b15ac2010aa8e1f32ff7#egg=qiskit_aer
qiskit-terra==0.22.4
retworkx==0.12.1
rustworkx==0.12.1
scipy==1.10.0
six==1.16.0
stevedore==4.1.1
symengine==0.9.2
sympy==1.11.1
```

**Comment by Patataman** [comment]
Notice that it only happens when trying to import Qiskit Aer when being in the project root folder.
Also saw that it is the same problem you are having with the CI (https://github.com/Qiskit/qiskit-aer/issues/1695), so I don't know if closing the issue...

**Comment by hhorii** [comment]
can you use `pip install .` instead of `pip install -e .`? Sometime editable mode is not good for a project with pybind.

also, if you in `qiskit-aer/` (top of this repository), to avoid to refer `qiskit_aer` package from the current directory, rename `qiskit_aer/` directory as `qiskit_aer.bak`.

In summary, I recommend you to do as follwos:

```
git clone https://github.com/Qiskit/qiskit-aer.git
cd qiskit-aer
git checkout stable/0.11
python3 -m virtualenv venv
source venv/bin/activate
pip install .
mv qiskit_aer qiskit_aer.bak
python -c "import qiskit_aer"
```

**Comment by Patataman** [comment]
Yes, renaming the qiskit_aer folder fix the problem.
