### ISSUE TITLE
Aer simulator does not have `break_loop`

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit-aer#1706]
### Informations

- **Qiskit Aer version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

```python
from qiskit_aer import Aer
Aer.get_backend("aer_simulator").configuration().basis_gates 
```
does not contain `break_loop`, so the following fails:

```python
om qiskit import QuantumCircuit, transpile
qc = QuantumCircuit(2, 1)

with qc.for_loop(range(5)):
    qc.measure(0, 0)
    qc.break_loop().c_if(0, True)

from qiskit_aer import Aer
backend = Aer.get_backend("aer_simulator")

transpile(qc, backend)
```

**Comment by jakelishman** [comment]
In theory I think the `AerSimulator` methods that support the other parts of dynamic circuits should also support `break` and `continue` internally, so this should just be a case of adding `break_loop` and `continue_loop` in the relevant lists of supported instructions.
