### ISSUE TITLE
How to use noise model in VQE calculation?

### ISSUE THREAD

**Issue by kitgood** [Qiskit/qiskit-aer#1718]
1. We can use Estimator() backend with noise free in VQE calculation, but how to assign a noise model by backends (such as ibmq_vigo) in VQE.
2. Can an Aer simulator (such as aer_simulator_stabilizer, aer_simulator_statevector) be used in VQE or VQEUCCFactory?

Thanks.

**Comment by woodsp-ibm** [comment]
Try these tutorials which I think show what you are looking for

https://qiskit.org/documentation/tutorials/algorithms/03_vqe_simulation_with_noise.html#Performance-with-noise

https://qiskit.org/documentation/tutorials/simulators/2_device_noise_simulation.html

For the Aer Estimator it sets the method internally. It can be set with parameters such as shots and approximation which change its behavior

https://qiskit.org/documentation/stubs/qiskit_aer.primitives.Estimator.html#qiskit_aer.primitives.Estimator

>shots (None or int) – The number of shots. If None and approximation is True, it calculates the exact expectation values. Otherwise, it calculates expectation values with sampling.

**Comment by hhorii** [comment]
Let me close this issue because no response in two months. Feel free to reopen this or open new issue if a problem remains.
