### ISSUE TITLE
error building qiskit-aer from source

### ISSUE THREAD

**Issue by vijaysunny** [Qiskit/qiskit-aer#1755]
### Informations

- **Qiskit AER version**:
- **Operating system**:fedora

### What is the current behavior?
CMake Error at cmake/conan.cmake:402 (message):
        Conan install failed='No such file or directory'
      Call Stack (most recent call first):
        cmake/conan.cmake:497 (conan_cmake_install)
        cmake/conan_utils.cmake:71 (conan_cmake_run)
        cmake/dependency_utils.cmake:20 (setup_conan)
        CMakeLists.txt:144 (setup_dependencies)
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-build-env-ps5pv3h9/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 634, in setup
          env = cmkr.configure(
        File "/tmp/pip-build-env-ps5pv3h9/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 332, in configure
          raise SKBuildError(
      
      An error occurred while configuring with CMake.

### What is the expected behavior?
qiskit-aer succcessfully build from source

### Suggested solutions

---

### What is the expected behavior?

---

**Comment by hhorii** [comment]
This issue is not from Aer. It is from Conan. What conan version are you using? Can you try again after removing `~/.conan/`?

**Comment by vijaysunny** [comment]
conan version is 1.59.0 
even i tried uninstall and reinstalling conan still it gives error

  -- Conan executing: /tmp/pip-build-env-8qxd3qbb/overlay/bin/conan install . -s build_type=Release -s compiler=gcc -s compiler.version=8 -s compiler.libcxx=libstdc++11 -e=CONAN_CMAKE_PROGRAM=/tmp/pip-build-env-p0ta0f3l/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake -g=cmake --build=missing
      CMake Error at cmake/conan.cmake:402 (message):
        Conan install failed='No such file or directory'
      Call Stack (most recent call first):
        cmake/conan.cmake:497 (conan_cmake_install)
        cmake/conan_utils.cmake:71 (conan_cmake_run)
        cmake/dependency_utils.cmake:20 (setup_conan)
        CMakeLists.txt:144 (setup_dependencies)
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/tmp/pip-build-env-p0ta0f3l/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 634, in setup
          env = cmkr.configure(
        File "/tmp/pip-build-env-p0ta0f3l/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 332, in configure
          raise SKBuildError(
      
      An error occurred while configuring with CMake.
        Command:
          /tmp/pip-build-env-p0ta0f3l/overlay/lib/python3.10/site-packages/cmake/data/bin/cmake /home/vijaysn/qiskit-aer -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/home/vijaysn/qiskit-aer/_skbuild/linux-x86_64-3.10/cmake-install -DPYTHON_VERSION_STRING:STRING=3.10.10 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-p0ta0f3l/overlay/lib/python3.10/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/vijaysn/anaconda3/envs/QiskitDevEnv/bin/python -DPYTHON_INCLUDE_DIR:PATH=/home/vijaysn/anaconda3/envs/QiskitDevEnv/include/python3.10 -DPYTHON_LIBRARY:PATH=/home/vijaysn/anaconda3/envs/QiskitDevEnv/lib/libpython3.10.so -DPython_EXECUTABLE:PATH=/home/vijaysn/anaconda3/envs/QiskitDevEnv/bin/python -DPython_ROOT_DIR:PATH=/home/vijaysn/anaconda3/envs/QiskitDevEnv -DPython_INCLUDE_DIR:PATH=/home/vijaysn/anaconda3/envs/QiskitDevEnv/include/python3.10 -DPython_FIND_REGISTRY:STRING=NEVER -DPython_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-p0ta0f3l/overlay/lib/python3.10/site-packages/numpy/core/include -DPython3_EXECUTABLE:PATH=/home/vijaysn/anaconda3/envs/QiskitDevEnv/bin/python -DPython3_ROOT_DIR:PATH=/home/vijaysn/anaconda3/envs/QiskitDevEnv -DPython3_INCLUDE_DIR:PATH=/home/vijaysn/anaconda3/envs/QiskitDevEnv/include/python3.10 -DPython3_FIND_REGISTRY:STRING=NEVER -DPython3_NumPy_INCLUDE_DIRS:PATH=/tmp/pip-build-env-p0ta0f3l/overlay/lib/python3.10/site-packages/numpy/core/include -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-p0ta0f3l/overlay/lib/python3.10/site-packages/ninja/data/bin/ninja -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          /home/vijaysn/qiskit-aer
        Working directory:
          /home/vijaysn/qiskit-aer/_skbuild/linux-x86_64-3.10/cmake-build
      Please see CMake's output for more information.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for qiskit-aer
Failed to build qiskit-aer
ERROR: Could not build wheels for qiskit-aer, which is required to install pyproject.toml-based projects

**Comment by hhorii** [comment]
I guess this is an issue of your conan configurations. Is there a directory `~/.conan`? If it exists, are there following packages in `~/.conan/data/`?

- nlohmann_json/3.1.1
- spdlog/1.9.2
- muparserx/4.0.8

If they do not exist, maybe installing them manually with `conan` command can be help to identify the root cause.

**Comment by hhorii** [comment]
Let me close this issue since no response in three weeks. Please create a new issue if you encounter the same issue.

**Comment by AlbertJP** [comment]
FWIW: I had this issue as well and were able to fix it by removing the _skbuild directory and running again.
