### ISSUE TITLE
Inconsistency in parameter input formats

### ISSUE THREAD

**Issue by plutoniumm** [Qiskit/qiskit-aer#1765]
### Informations

- **Qiskit Aer version**: 0.12.0
- **Python version**: 3.11.0
- **Operating system**: macOS 13.0 Ventura arm64 (Apple Silicon)

If below information happens to be insufficient, the notebook is [here](https://github.com/plutoniumm/plasma/blob/272ea0443f20bf4b191944ab255620245d42ddfb/notebooks/QCNN.ipynb)

### What is the current behavior?
Errors out under multiple scenarios

### Steps to reproduce the problem
My circuit is
```py
def SU2(prefix):
    return EfficientSU2(2, su2_gates=['ry'], entanglement='linear', reps=1, parameter_prefix=prefix)

executor = ThreadPoolExecutor(max_workers=8)
# backend = AerSimulator().from_backend("automatic")
backend = QasmSimulator(method="matrix_product_state")
backend.set_options(
    executor=executor, max_job_size=1,
    max_parallel_threads=8,max_parallel_experiments=0,
    max_parallel_shots=0
)

def QConvCircuit():
    qubits = 4
    params = [Q.Parameter(f"rx_{i}") for i in range(0,qubits)];
    all_q = [i for i in range(qubits)];

    qc = Q.QuantumCircuit(qubits, 1);

    qc.h(all_q);
    for i in all_q: qc.rx(params[i], i)
    for i in all_q: qc.cx(i, (i+1)%4)

    qc.barrier()
    qc.compose(SU2('a'), qubits=[0,1], inplace=True)
    qc.compose(SU2('b'), qubits=[2,3], inplace=True)
    qc.crx(Q.Parameter('mp_11'), 0,1)
    qc.crx(Q.Parameter('mp_12'), 2,3)
    qc.barrier()

    qc.compose(SU2('c'), qubits=[1,3], inplace=True)
    qc.crx(Q.Parameter('mp_21'), 1,3)
    qc.barrier()

    qc.measure(3,0)

    qc = qiskit.compiler.transpile(qc, optimization_level=3, backend=backend)
    return qc

demo = QConvCircuit()
input_names = [i for i in demo.parameters if i.name[0] == "r"]
weight_names = [i for i in demo.parameters if i.name[0] != "r"]

demo.draw('mpl')
```
![image](https://user-images.githubusercontent.com/51614345/228421355-59c624b3-34e6-4f51-8e8f-15cbca6c8a77.png)
The runner is
```py
def runQConv(circuit, inputs, weights):
    # check if inputs and weights are lists of lists else convert list to list of lists
    if not isinstance(inputs[0], list):
        inputs = [inputs]
    if not isinstance(weights[0], list):
        weights = [weights]

    params_list = []
    for i in inputs:
        for w in weights:
            i = [[j] for j in i]
            w = [[j] for j in w]
            params_list.append({
                **dict(zip(input_names, i)),
                **dict(zip(weight_names, w))
            })

    print(f"We expect {len(params_list)} runs")
    return backend.run(
        circuit if len(params_list)==1 else [circuit for _ in range(len(params_list))]
        ,parameter_binds=params_list).result()
```
And the run is
```
result2 = runQConv(
  demo,
  [[0.1,0.2,0.3,0.4], [1.1,1.2,1.3,1.4]],
  [
    [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.10,0.11,0.12,0.13,0.14,0.15],
    [1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,1.10,1.11,1.12,1.13,1.14,1.15]
  ]
)
print(result2)
```

This returns an error `AttributeError: 'AerJob' object has no attribute 'name'` at `AerJobSet._get_worker_result`

### Other variations
When I don't use `i = [[j] for j in i]` the error is `TypeError: object of type 'float' has no len()` at `AerBackend._convert_circuit_binds` which is also different from what other functions like `qiskit.execute` take in. Related to [#1551]

When I convert the params into a dict of lists (i.e {rx: [1,2,3]}) rather than a list of dicts (i.e [{rx: 1}, {rx: 2}, {rx: 3}]) the error is `AttributeError: 'list' object has no attribute 'values'` at `AerBackend._convert_circuit_binds`

### What is the expected behavior?
The simulation should run ideally and `.result().get_counts()` should return the counts for each run

I may be using this wrong in which case I apologize for the confusion

### Suggested solutions
Hey sorry i really don't know how to fix this, very new to Qiskit

**Comment by ikkoham** [comment]
Thanks for reporting the issue. 
I think this is the specification of Aer and the difference from others. (Base class does not restrict the type of `parameter_binds`)

Please check the documentation: Additional Information: in `AerSimulator.run`
 https://qiskit.org/documentation/aer/stubs/qiskit_aer.AerSimulator.run.html

**Comment by plutoniumm** [comment]
Hey thanks yeah I did try the AerSim variant also for some reason I just can't get it to run. I tried List of Dicts with each value singular array and also [dict of lists], its just debugging hell both ways and I end up reaching a point where its some internal issue

Could you help me with some examples of where Aer is used to execute multiple parameter values for a (or multiple) circuit(s) in a single call. Additionally if there's somewhere where batching has been shown

Thanks a lot for the prompt response 🙏🏻

**Comment by plutoniumm** [comment]
Hey, Why was this closed? If a new PR was merged in can you please link it? Or maybe let me know if I can help with additional information

If this is purely a debugging issue I would really appreciate it if I could pick someone's brain on it
