### ISSUE TITLE
Duplicate parameter_binds

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-aer#1771]
### Informations

- **Qiskit Aer version**: 0.12.0
- **Python version**:
- **Operating system**:

### What is the current behavior?

Qobj is being deprecated so it's probably not worth fixing. But if I `assemble()` a circuit with an Aer backend, then call its `backend.run()`, the job would fail with 

```
_run_qobj() got multiple values for argument 'parameter_binds'
```

because `assemble` inserts `parameter_binds` into `circuits.config`.

### Steps to reproduce the problem

```
from qiskit import transpile, assemble
from qiskit.test.reference_circuits import ReferenceCircuits
from qiskit_aer import Aer

sim = Aer.get_backend("aer_simulator")
bell = ReferenceCircuits.bell()
qobj = assemble(transpile(bell, sim), backend=sim)
sim.run(qobj)
```

### What is the expected behavior?

I can still run a qobj with Aer.

**Comment by bronze7** [comment]
I'm having the same issue. T

**Comment by bronze7** [comment]
Run the transpiled circuit directly instead of using QObj. It worked for me.
