### ISSUE TITLE
`tensor_network` method powered by cuQuantum is not available

### ISSUE THREAD

**Issue by HaoTy** [Qiskit/qiskit-aer#1790]
### Informations

- **Qiskit Aer version**: 0.12.0
- **Qiskit Aer GPU version**: 0.11.2
- **Python version**: 3.9.16
- **Operating system**: Ubuntu 20.04.5 LTS

### What is the current behavior?
Specifying `method="tensor_network"` ( #1637 ) with `device="GPU"` produces AerError: "Invalid simulation method tensor_network" for the latest release.

### Steps to reproduce the problem
```
pip install qiskit
pip install cuquantum-python-cu11 cupy-cuda11x
pip install qiskit-aer-gpu
```
This should install qiskit-aer 0.12.0, qiskit-aer-gpu 0.11.2, and cuQuantum with cuTensorNet support. Then
```python
from qiskit_aer import AerSimulator

backend = AerSimulator(method="tensor_network", device="GPU")
```

### What is the expected behavior?
`tensor_network` should be available for `AerSimulator` when cuTensorNet is functional.

### Suggested solutions
Not sure if it's related, but the latest version of qiskit-aer-gpu (available on PyPI) is 0.11.2.

**Comment by hhorii** [comment]
0.12.0 is not available through PyPI (though we will fix this issue soon). Could you compile and try Aer from codes?

**Comment by mtreinish** [comment]
Actually the qiskit-aer-gpu package does not include the cuQuantum support. If you'd like to use cuQuantum you will need to compile aer from source. There instructions on how to do this here: https://github.com/Qiskit/qiskit-aer/blob/main/CONTRIBUTING.md#building-with-gpu-support including the options needed to build the cuQuantum support.

**Comment by HaoTy** [comment]
Thanks for the clarification. I was aware that `cuStateVec_enable` needs Aer to be built from source with appropriate flags, but somehow forgot that this would likely be the case for `tensor_network` as well :/
