### ISSUE TITLE
Use same BLAS implimentation as NumPy

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#18]
### What is the expected enhancement?
Currently, a BLAS implementation is needed Aer to build.  However NumPy, which is a requirement, is already linked to a BLAS library.  Under Anaconda, for example, this is the Intel MKL.  It is possible to use this BLAS for Aer as well, a la Cython and the old `qasm_simulator` that used it.

**Comment by nonhermitian** [comment]
My point is that NumPy is a requirement that already is built against a specific blas implimentation. The aer installer should automatically link against that. This gives me, for example, the intel mkl for free. This allows one to test against different blas and time them quite easily by simply changing numpy, for example using the —nomkl flag in conda.

**Comment by atilag** [comment]
I see that there are versions of Numpy that are linked against OpenBLAS, depending on where Numpy comes from: Pypi -> OpenBlas , Conda -> mkl.
I guess that mkl version is faster for x86 architectures, but we still need to support Power architectures.
Anyway, letting the user choose their desired implementation sounds like a good things to me.
I'm labeling this issue as an `enhancement` for now.

**Comment by atilag** [comment]
With #543 merged, now we can chose which BAS implementation we want to build with.

**Comment by mdepasca** [comment]
It is not clear to me wether qiskit_aer depends completely on numpy (or a set of external packages) or not. 
The rationale for the question is:
- if it does, to use Intel MKL libraries on x86, for me is enough to install an numpy version depending on those libs;
- if it does not completely depends on numpy (or a set of external packages), then to use Intel MKL I would need to build from scratch.
