### ISSUE TITLE
cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by intelligi123** [Qiskit/qiskit-aer#1800]
### Informations

qiskit version: 0.11.2
python version: 3.10.9
Operating System: Ubuntu 18.04.6 LTS

### What is the current behavior?
I have installed qiskit-aer-gpu on my system having GPU: NVIDIA GeForce GTX 980 Ti. This gpu has CC of 5.2 and Cuda version installed is 12.1. My driver version is 530.30.02.

The output of nvidia-smi is:

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 980 Ti       On | 00000000:03:00.0 Off |                  N/A |
| 22%   34C    P8               13W / 250W|     10MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1241      G   /usr/lib/xorg/Xorg                            3MiB |
|    0   N/A  N/A      2366      G   /usr/lib/xorg/Xorg                            3MiB |
+---------------------------------------------------------------------------------------+

I think I have all the prerequisites for executing qiskit on my GPU (drivers and cuda >= 10.1), but once it run, it generates above error. Not sure is it compatibility issue or any other installation which needs to be done. The code I am running is working fine with qiskit-aer but when I chose GPU my device things got wrong. Program I am running is:

from qiskit import *
from qiskit.circuit.library import *
from qiskit.providers.aer import *

sim = AerSimulator(method='statevector', device='GPU')
#sim = AerSimulator(method='statevector')
shots = 100
depth=10
qubits = 25
circuit = transpile(QuantumVolume(qubits, depth, seed=0),
backend=sim,
optimization_level=0)
circuit.measure_all()
result = execute(circuit,sim,shots=shots,seed_simulator=12345).result()
print(result)

### Steps to reproduce the problem

With cuda and qiskit-aer-gpu installation on my GPU having CC 5.2 and Cuda version 12.1, I am not able to execute while selecting device=GPU

### What is the expected behavior?
As mentioned in github page, I have installed all requirements and was expecting above code to run.

### Suggested solutions
Please answer if there is any other requirement which needs to be met and also update it here as well.

**Comment by hhorii** [comment]
Could you leave more information (ex: error messages)? Also, if possible, please try the latest code.

**Comment by intelligi123** [comment]
This is the complete error I am getting on execution of above code using jupyter notebook:
Simulation failed and returned the following error message:
ERROR:  [Experiment 0] for_each: failed to synchronize: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

**Comment by hhorii** [comment]
Please confirm that your cuda can work with cuquantum that you downloaded, if you have not tried it. Here is an example code that uses custatevec.

test.cu:
```
#include <cuda_runtime_api.h> // cudaMalloc, cudaMemcpy, etc.
#include <cuComplex.h>        // cuDoubleComplex
#include <custatevec.h>       // custatevecApplyMatrix
#include <stdio.h>            // printf
#include <stdlib.h>           // EXIT_FAILURE

int main(void) {

   const int nIndexBits = 3;
   const int nSvSize    = (1 << nIndexBits);
   const int nTargets   = 1;
   const int nControls  = 2;
   const int adjoint    = 0;

   int targets[]  = {2};
   int controls[] = {0, 1};

   cuDoubleComplex h_sv[]        = {{ 0.0, 0.0}, { 0.0, 0.1}, { 0.1, 0.1},
                                    { 0.1, 0.2}, { 0.2, 0.2}, { 0.3, 0.3},
                                    { 0.3, 0.4}, { 0.4, 0.5}};
   cuDoubleComplex h_sv_result[] = {{ 0.0, 0.0}, { 0.0, 0.1}, { 0.1, 0.1},
                                    { 0.4, 0.5}, { 0.2, 0.2}, { 0.3, 0.3},
                                    { 0.3, 0.4}, { 0.1, 0.2}};
   cuDoubleComplex matrix[] = {{0.0, 0.0}, {1.0, 0.0},
                               {1.0, 0.0}, {0.0, 0.0}};


   cuDoubleComplex *d_sv;
   cudaMalloc((void**)&d_sv, nSvSize * sizeof(cuDoubleComplex));

   cudaMemcpy(d_sv, h_sv, nSvSize * sizeof(cuDoubleComplex),
              cudaMemcpyHostToDevice);

   //--------------------------------------------------------------------------

   // custatevec handle initialization
   custatevecHandle_t handle;

   custatevecCreate(&handle);

   void* extraWorkspace = nullptr;
   size_t extraWorkspaceSizeInBytes = 0;

   // check the size of external workspace
   custatevecApplyMatrixGetWorkspaceSize(
       handle, CUDA_C_64F, nIndexBits, matrix, CUDA_C_64F,
       CUSTATEVEC_MATRIX_LAYOUT_ROW, adjoint, nTargets, nControls,
       CUSTATEVEC_COMPUTE_64F, &extraWorkspaceSizeInBytes);

   // allocate external workspace if necessary
   if (extraWorkspaceSizeInBytes > 0)
       cudaMalloc(&extraWorkspace, extraWorkspaceSizeInBytes);

   // apply gate
   custatevecApplyMatrix(
       handle, d_sv, CUDA_C_64F, nIndexBits, matrix, CUDA_C_64F,
       CUSTATEVEC_MATRIX_LAYOUT_ROW, adjoint, targets, nTargets, controls,
       nullptr, nControls, CUSTATEVEC_COMPUTE_64F,
       extraWorkspace, extraWorkspaceSizeInBytes);

   // destroy handle
   custatevecDestroy(handle);

   //--------------------------------------------------------------------------

   cudaMemcpy(h_sv, d_sv, nSvSize * sizeof(cuDoubleComplex),
              cudaMemcpyDeviceToHost);

   bool correct = true;
   for (int i = 0; i < nSvSize; i++) {
       if ((h_sv[i].x != h_sv_result[i].x) ||
           (h_sv[i].y != h_sv_result[i].y)) {
           correct = false;
           break;
       }
   }

   if (correct)
       printf("example PASSED\n");
   else
       printf("example FAILED: wrong result\n");

   cudaFree(d_sv);
   if (extraWorkspaceSizeInBytes)
       cudaFree(extraWorkspace);

   return EXIT_SUCCESS;
}
```

Assuming `CUQUANTUM_ROOT` is the path to your cuquantum lib and `11` is the version of your cuda, this can be compiled and run with

```
nvcc test.cu -I${CUQUANTUM_ROOT}/include -L${CUQUANTUM_ROOT}/lib/11/ -lcustatevec -o test
./test
# example PASSED
```

**Comment by hhorii** [comment]
Please check my gist that runs on Colab: 

static_link: https://gist.github.com/hhorii/548c3d0afb50b7b06a3136152524d274
dynamic_link: https://gist.github.com/hhorii/44f3c36722ba0c33ff900fdd1f5a118c
