### ISSUE TITLE
Remove `PulseSimulator`

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-aer#1805]
`PulseSimulator` was deprecated in 0.12.0 on. Mar. 10, 2023. We will release 0.13.0 at least after Jun. 10 and remove `PulseSimulator` in the release.

**Comment by adilnaut** [comment]
@hhorii may I try this task? And does it mean to remove class implementation itself and all integration and tests?

**Comment by alt-shreya** [comment]
@hhorii is this issue still up for grabs? I noticed a linked PR that could potentially close it but hasn't been merged yet

**Comment by hhorii** [comment]
I will merge #1805 after releasing 0.12.1. > @alt-shreya

**Comment by hhorii** [comment]
Maybe because of configuration of this repository or organization, I cannot assign [Angelo Danducci](https://github.com/AngeloDanducci) to this issue. I will merge #1809 to main soon.

**Comment by 1ucian0** [comment]
Hi @AngeloDanducci
Do you mind comment on this issue so it can be assigned?

**Comment by AngeloDanducci** [comment]
Commenting!

**Comment by natestemen** [comment]
@AngeloDanducci I've been informed by Luciano that you'd like to donate $100 of this bounty (total value $180) back to Unitary Fund. Just want to confirm if that's the case and clear up any possible confusion in future payment.

**Comment by AngeloDanducci** [comment]
@natestemen Please donate the entire value ($180) back to the unitary fund - thanks!
