### ISSUE TITLE
Renew example codes in README

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-aer#1806]
Current example codes in README prints deprecation warnings and does not work.

- `qiskit.providers.ibmq` is deprecated
- `ibmq_athens` is not available

We need to update the code.

**Comment by Mostafa-Atallah2020** [comment]
Hi @hhorii ,i would like to work on this assign me please

**Comment by alt-shreya** [comment]
@hhorii Can I work on this task as well?

**Comment by andre-a-alves** [comment]
Will any available backend do? My PR uses `ibmq_manila` since it's the only 5-qubit free system that's a Falcon r5.11L.

**Comment by davidlearn** [comment]
My PR 1831 fixed the problem first, 5 hours earlier than another PR 1832.

**Comment by andre-a-alves** [comment]
Sorry, @davidlearn I hadn't seen your PR since the issue wasn't linked. I was not trying to ruffle any feathers - I just thought it was still an unsolved issue.

**Comment by davidlearn** [comment]
That is my first PR to fix an issue. What is the normal way to link PR to an issue?

**Comment by davidlearn** [comment]
@andre-a-alves It is OK. Hope that we closed the issue. There must be a better way to update all examples when a new release affect certain functions.

**Comment by andre-a-alves** [comment]
> That is my first PR to fix an issue. What is the normal way to link a PR to an issue?

You just need to include the issue number after a hashtag in the PR description or a comment. I think the clearest way is to say "closes," "fixes," or "addresses" as well. So, for example, in my PR for this issue, I included "Closes #1806". That links the PR to the issue and lets the reviewer know what the PR is for.

**Comment by davidlearn** [comment]
PR #1831  fixed #1806 using FakeManilaV2 fake backend.

**Comment by natestemen** [comment]
@hhorii please ensure this issue (and all other unitaryHACK issues) are assigned to the hacker who should receive the bounty upon closing. Looks to be @davidlearn in this case.

**Comment by davidlearn** [comment]
Please assign this issue to me as required by unitaryHack organization to keep track of who won the bounty. unitaryHack also has a leading board for all hackers who closes issues. Thank you.
