### ISSUE TITLE
Remove Python 3.7 from Github actions

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-aer#1807]
### What is the expected behavior?

Python 3.7 is no longer supported in qiskit-terra and Aer does not need to support the version. We do not need to run tests and to create packages in the version for 0.13.

**Comment by tungbq** [comment]
Hi @hhorii do you need any help? May I pick up this task?

**Comment by devilkiller-ag** [comment]
@hhorii Can I work on this?

**Comment by natestemen** [comment]
@devilkiller-ag bounties are open until the associated issue is closed, so yes you can still work on this! It does seem like #1819 might resolve the issue, but it hasn't seen much attention. @hhorii or @1ucian0 can you comment on the status of the linked PR?

**Comment by devilkiller-ag** [comment]
Thanks @natestemen

**Comment by hhorii** [comment]
maybe due to configuration of this repository or organization, I cannot assign contributors to this issue. I would like to assign @tungbq. I will merge #1819 in near future (I recently worked for release of 0.12.1).

**Comment by robotAstray** [comment]
was this issue completed succesfully? @hhorii
