### ISSUE TITLE
How to do non diagonal measurement using Primitives.Estimator?

### ISSUE THREAD

**Issue by eul94458** [Qiskit/qiskit-aer#1848]
### Informations

- **Qiskit AER version**: 0.12.1

How can I perform non diagonal measurement using the current scheme of Primitives.Estimator?

Say there are 2 states A and B that are distinct, constructed by qiskit.QuantumCircuit.

How can I carry out the following operation?

    < A | H | B >

**Comment by ikkoham** [comment]
It's not an expectation value, so we cannot support it.

I think you could run the circuit `U_A - P_a - U_B^dagger` and sum over `a`, where `H = \sum_a P_a` and `U_X`s are the quantum circuits which prepare the state A and B.
