### ISSUE TITLE
Update Qiskit-aer-gpu to 0.12

### ISSUE THREAD

**Issue by golanor** [Qiskit/qiskit-aer#1852]
### Informations

- **Qiskit Aer version**: 0.11.2 gpu
- **Python version**: 3.10.6
- **Operating system**: linux ubuntu 22.10

### What is the current behavior?
When trying to run the VQE tutorial, it works on qiskit aer cpu, 0.12.0. It fails on qiskit-aer-gpu 0.11.2
There is no version 0.12 for gpu on pypi.

### Steps to reproduce the problem
run the vqe tutorial with qiskit aer gpu.

### What is the expected behavior?
that the versions will match

### Suggested solutions

update qiskit-aer-gpu.

**Comment by hhorii** [comment]
We have now trouble to release qiskit-aer-gpu. CUDA 12 makes sizes of wheels exceed cap of PyPI and CUDA 11 is too old in a docker for Github actions. Please build from sources until we can provide alternative.

**Comment by contepablod** [comment]
Hi! which version of qiskit do you recommend to use with the current aer-gpu? I updated qiskit and it crashes aer-gpu.

**Comment by hhorii** [comment]
https://github.com/Qiskit/qiskit-aer/pull/1854 will add support of cuda 12.

**Comment by hhorii** [comment]
@contepablod 
qiskit-aer with GPU needs to run with the latest release of qiskit. Could you create a new issue if you encountered an error?

**Comment by contepablod** [comment]
@hhorii Thanks! I'll try it out.

**Comment by hhorii** [comment]
qiskit-aer-gpu is now in PyPI: https://github.com/Qiskit/qiskit-aer/releases/tag/0.12.2, and it will help running your VQE applications.
