### ISSUE TITLE
snapshot instruction not recognized by AER

### ISSUE THREAD

**Issue by ManuelGuatto** [Qiskit/qiskit-aer#1853]
### Informations

- **Qiskit Aer version**: 0.12.0
- **Python version**: 3.10.9
- **Operating system**: Windows 11 Pro

### What is the current behavior?

Using the snapshot instruction on the statevector simulator causes an error.

The error is the following:

`AerError: 'unknown instruction: snapshot'`

### Steps to reproduce the problem

```
from qiskit import *

qc = QuantumCircuit(2)
qc.h(0)
qc.snapshot('1')             # add a snapshot with the key '1'
qc.h(0)                      # add more gates after the snapshot

backend = Aer.get_backend('statevector_simulator')
result = execute(qc, backend).result()
snapshots = `result.data()['snapshots']['statevector']
```

### What is the expected behavior?

The function should return a snapshot of the qubit state

**Comment by vikragha** [comment]
I am facing the same issue here. I can provide my error output if requested. However, the steps to reproduce the problem is the simplest way that @ManuelGuatto shared.

**Comment by ikkoham** [comment]
That was deprecated since version 0.9.0. However, I am not sure if it is as intended that it is no longer available at this time.

**Comment by hhorii** [comment]
snapshot instructions were removed after over 3 months of deprecation warnings. please use save instructions instead.
