### ISSUE TITLE
Aer unitary simulator fails with C5X gate

### ISSUE THREAD

**Issue by cqc-alec** [Qiskit/qiskit-aer#1855]
### Informations

- **Qiskit Aer version**: 0.12.0
- **Python version**: 3.10
- **Operating system**: Ubuntu 22.04

### What is the current behavior?

Attempt to compute unitary of circuit containing C5X gate fails with the following message:

```
Simulation failed and returned the following error message:
ERROR:  [Experiment 0] Circuit test contains invalid instructions {"gates": {mcx_gray}} for "unitary" method.
```

### Steps to reproduce the problem

```python
from qiskit import QuantumCircuit, QuantumRegister
from qiskit_aer import Aer

qkc = QuantumCircuit(name="test")
r = QuantumRegister(6, "q") # no problem with 5
qkc.add_register(r)
qkc.mcx(r[:-1], r[-1])

qkc.save_unitary()
qkb = Aer.get_backend("aer_simulator_unitary")

h = qkb.run(qkc)
```

### What is the expected behavior?

The `run()` command should succeed.

**Comment by hhorii** [comment]
In terra,  `QuantumCircuit.mcx` with less than five control-qubits generates `CXGate`, `CCXGate`, `C3XGate`, and `C4XGate` and with more control-qubits generates `MCXGrayGate`. 

https://github.com/Qiskit/qiskit-terra/blob/cd770b59f81dbe07e2bd2cc314460c186067b6bd/qiskit/circuit/library/standard_gates/x.py#L1035-L1041

`UnitarySimulator` does not support `mcx_gray`. So you need to call `transpile` before `run`.

```
from qiskit import QuantumCircuit, QuantumRegister, transpile
from qiskit_aer import Aer

qkc = QuantumCircuit(name="test")
r = QuantumRegister(6, "q") # no problem with 5
qkc.add_register(r)
qkc.mcx(r[:-1], r[-1])

qkc.save_unitary()
qkb = Aer.get_backend("aer_simulator_unitary")

h = qkb.run(transpile(qkc, qkb))
```

**Comment by cqc-alec** [comment]
OK, thanks!
