### ISSUE TITLE
Type Error: AerBackend._run_qobj() got multiple values for argument 'parameter_binds' 

### ISSUE THREAD

**Issue by sonikarajesh** [Qiskit/qiskit-aer#1856]
### Informations

- Qiskit Aer version: 0.12.0
- Python version: 
- Operating system: 

### What is the current behavior?
Not able to execute the code taken from the Qiskit tutorials. 

`<ipython-input-3-7b667a2e8e7c>:24: DeprecationWarning: Using a qobj for run() is deprecated as of qiskit-aer 0.9.0 and will be removed no sooner than 3 months from that release date. Transpiled circuits should now be passed directly using backend.run(circuits, **run_options).
 job = self.backend.run(q_obj, **{'parameter_binds': None})`

`TypeError: AerBackend._run_qobj() got multiple values for argument 'parameter_binds'`

How should I modify the code inorder to execute ?

**Comment by hhorii** [comment]
Could you try 0.12.1? I think this issue was already resolved.

**Comment by hhorii** [comment]
Please reopen this issue if you still encounter the same problem with the latest qiskit-aer.
