### ISSUE TITLE
Add 2-qubit Clifford gate ECR in the stabilizer simulator (Clifford simulator)

### ISSUE THREAD

**Issue by ashsaki** [Qiskit/qiskit-aer#1883]
### What is the expected behavior?

Add 2-qubit ECR gate, which is a Clifford gate, to the stabilizer simulator (Clifford simulator). Newer IBM devices have ECR as the 2-qubit basis gate. Thus, it is better to have the gate in the stabilizer simulator as well.

**Comment by MarcMaussner** [comment]
Hello, could I bei assigned to the topic?

**Comment by doichanj** [comment]
I'm now fixing issue #1888 and I would like to implement this one after that

**Comment by MarcMaussner** [comment]
So I could take my chance to see if I can do the implementation before you start? Would be my first issue to implement ;-)

**Comment by MarcMaussner** [comment]
PR prepared. Review and Check needed.

**Comment by doichanj** [comment]
Thank you, we need test case for new feature, so could you please add test case for ECR gate?

**Comment by MarcMaussner** [comment]
Thanks for the info! Will do. Should be done by end of this week.

**Comment by MarcMaussner** [comment]
@doichanj: Coding style adapted and testcase written. Unfortunately I cannot execute "stestr run" also unit test executable cannot be found. Any hints for me?

**Comment by doichanj** [comment]
Try testing with `python -m unittest`

**Comment by MarcMaussner** [comment]
Getting Module not found: controller_wrappers :-(

**Comment by doichanj** [comment]
please try `mv qiskit_aer qiskit_aer_` before running tests. (do not forget to recover before building Qiskit Aer)

**Comment by MarcMaussner** [comment]
Thanks that helped.
