### ISSUE TITLE
Backend configuration should create type of QasmBackendConfiguration

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-aer#189]
### What is the expected behaviour?
Rather than instantiate `BackendConfiguration` the field of the configuration returned from the device should check for the flag `open_pulse` and either instantiate a `QasmBackendConfiguration` or `PulseBackendConfiguration`. See https://github.com/Qiskit/qiskit-terra/pull/2216 for more information.

**Comment by chriseclectic** [comment]
Closed by #295
