### ISSUE TITLE
Add `from_dict` to `QuantumError`

### ISSUE THREAD

**Issue by epelaaez** [Qiskit/qiskit-aer#1894]
### What is the expected behavior?

Currently, the class `QuantumError` has a [`to_dict`](https://github.com/Qiskit/qiskit-aer/blob/9999dfbe3a6e39a222fa3477888f0c02f7a178b5/qiskit_aer/noise/errors/quantum_error.py#L327) method. However, it does not have a `from_dict` method to convert back.

**Comment by MarcMaussner** [comment]
Hello, can I be assigned to this?
