### ISSUE TITLE
Estimator should not measure Paulis that are `I`

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-aer#1952]
### What is the expected behavior?

Aer already has an optimization to not simulate idle qubits. That means even a 100 qubit circuit can be simulated if only a small subset of qubits actually contain gates. See: https://github.com/Qiskit/qiskit-aer/issues/1299

However this stops working in the Estimator, when an observable with lots of `I`s is specified. Instead, the optimization should be extended to not simulate/measure such qubits. 

This is important due to the Qiskit transpiler often enlarging circuits/observables when it targets a large device. But the true non-trivial part of the circuit is still small, and should remain simulable.

**Comment by ikkoham** [comment]
Aer's estimator does not measure the Identity Pauli. `qargs` contains only non-identity qubits. https://github.com/Qiskit/qiskit-aer/blob/main/qiskit_aer/primitives/estimator.py#L291

```python
from qiskit_aer.primitives import Estimator
from qiskit.quantum_info import SparsePauliOp

qc = QuantumCircuit(100)
observable = SparsePauliOp("I"*99 + "Z")

estimator = Estimator()
result = estimator.run(qc, observable).result()
```
should work.

**Comment by ikkoham** [comment]
Close, but if you have some issue please reopen
