### ISSUE TITLE
`qiskit.test` is going to be removed in `qiskit 1.0`

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-aer#1957]
Qiskit exposes test utilities as part of its deliverable package. This is not consider good practice and [its removal is a long overdue issue](https://github.com/Qiskit/qiskit/issues/6862). Qiskit teams's intention is [to clean that up for `qiskit 1.0`](https://github.com/Qiskit/qiskit/pull/10998) (planned to be released on Jan 31st, 2024).  The module will be available in the `0.*` versions (EoL, mid 2024) and [raise a deprecation warning](https://github.com/Qiskit/qiskit/pull/11001).

Aer uses `qiskit.test` in, at least, the following file:
https://github.com/Qiskit/qiskit-aer/blob/64a969656e841e9bbd5b76c7e19ae9a475762cd9/test/terra/common.py#L33

Consider stop importing it from qiskit and move the relevant testing-supporting code to Aer codebase.

**Comment by 1ucian0** [comment]
Is this issue solved by https://github.com/Qiskit/qiskit-aer/pull/1971 ?

**Comment by doichanj** [comment]
yes, Aer is now independent from qiskit.test

**Comment by 1ucian0** [comment]
Awesome. Closing via https://github.com/Qiskit/qiskit-aer/pull/1971 in that case.
