### ISSUE TITLE
Migrate to PyPI Trusted publishers before Oct 19

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-aer#1959]
The Qiskit's PyPI will enable 2FA on Oct 19. As a consequence, deploying this repo won longer be able to use password authentication for publishing this package to PyPI. The best mechanism PyPI offers for publishing now is trusted publishers:

https://docs.pypi.org/trusted-publishers/using-a-publisher/

which authorizes a GitHub Action workflow to push to PyPI and bypasses the need for any user credentials. 
So, this repo needs such a workflow. Take a look to other project as examples:
 * `.github/workflows/wheels.yml` in https://github.com/Qiskit/qiskit/pull/10999/files
 * `.github/workflows/deploy-code.yml` in https://github.com/qiskit-community/qiskit-machine-learning/pull/698/files

Once done, [a manual linking process needs to be done in the web UI](https://docs.pypi.org/trusted-publishers/adding-a-publisher/) by @mtreinish  .

Related: https://github.com/Qiskit/qiskit-aer/pull/1947#discussion_r1352644797

**Comment by doichanj** [comment]
I modified deploy.yml in Release 0.13 PR #1953
