### ISSUE TITLE
`AerSimulator` from `NoiseModel` does not work with dynamic circuits

### ISSUE THREAD

**Issue by anedumla** [Qiskit/qiskit-aer#1997]
### Informations

- **Qiskit Aer version**: 0.13.0
- **Python version**: 3.10.8
- **Operating system**:

### What is the current behavior?

The custom noise is not applied when the circuit contains dynamic instructions. The output of the following example is `{'0 0': 1024}`, i.e. the result without noise. 

```python
from qiskit import QuantumCircuit

from qiskit_aer.noise import NoiseModel, pauli_error
from qiskit_aer import AerSimulator

# Create the noise model
p_error = 0.3

readout_error = pauli_error([('X', p_error), ('I', 1 - p_error)])
noise_bit_flip = NoiseModel()
noise_bit_flip.add_all_qubit_quantum_error(readout_error, ['id'])

backend = AerSimulator(noise_model=noise_bit_flip)

test = QuantumCircuit(1,1)
test.id(0)
test.measure(0,0)
with test.if_test((0, 1)):
        test.x(0)
test.measure_all()
backend.run(test).result().get_counts()
```

However, when commenting out the lines containing dynamic instructions:
```python
with test.if_test((0, 1)):
        test.x(0)
```

the output is `{'0 0': 730, '1 1': 294}`, as expected.

**Comment by doichanj** [comment]
I think this script always returns 0 at mid-measure and always skips x gate.

Following circuit works well.
```
test = QuantumCircuit(1,1)
test.h(0)
test.measure(0,0)
with test.if_test((0, 1)):
        test.x(0)
test.measure_all()
```

**Comment by anedumla** [comment]
In my original script, since the only noise is attached to the `id` gate, and from the results of the example without the dynamic instruction, the expected result would be `{'0 0': 730, '0 1': 294}`. I.e., because the `id` gate is noisy and flips the qubit with prob 0.3 to 1, you would expect that with probability 0.3, the dynamic X gate acts and the final result is with prob. 0.3 `0 1`, because measurements are noiseless in this example.

**Comment by doichanj** [comment]
I found id gate is removed by `qiskit.compiler.transpile` called from here https://github.com/Qiskit/qiskit-aer/blob/880df288af2c6a4730ab4f7f403a72befa661422/qiskit_aer/backends/aer_compiler.py#L101-L103
I think we can avoid by adding `optimization_level=0`, I will make PR for this fix
