### ISSUE TITLE
Building Aer on OSX should not require XCode

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#20]
### What is the expected enhancement?
Building Aer on OSX requires having XCode installed.  This is 6Gb of docs and other things that are not needed.  It should be possible to build Aer using only the Apple command line tools, homebrew llvm, or homebrew gcc.

**Comment by atilag** [comment]
You can use Apple command line tools. IIRC, I think that you are referring to the fact that when the target platform is not set, scikit defaults to 10.6, so it tries to build with an older compiler with libstdc++ support, but as we need C++11 the compiler fails to build and the message claiming XCode needs to be installed is shown, this is a misleading message from scikit I guess.

**Comment by nonhermitian** [comment]
Yes, this is resolved.
