### ISSUE TITLE
404 Page not found: /ecosystem/aer/

### ISSUE THREAD

**Issue by MoritzWillmann** [Qiskit/qiskit-aer#2010]
The documentation of qiskit-aer seems to be unreachable. Also I get the following error for intersphinx
```
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://qiskit.org/ecosystem/aer/objects.inv' not fetchable due to
<class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found https://qiskit.org/ecosystem/
aer/objects.inv for url: https://qiskit.org/ecosystem/aer/objects.inv
```

Can you point me to the new url (especially for the objects.inv)

**Comment by Eric-Arellano** [comment]
Thank you for the report @MoritzWillmann and pardon the issue! This was a temporary problem from rolling out the redirects for qiskit.org to https://docs.quantum.ibm.com.
