### ISSUE TITLE
Cannot transpile circuits with reset gate when noise modell is not None for simulator 

### ISSUE THREAD

**Issue by zuper1998** [Qiskit/qiskit-aer#2015]
### Informations

- **Qiskit Aer version**: 0.13.0
- **Python version**: Python 3.10.7
- **Operating system**: windows 11

### What is the current behavior?

When trying to transpile a circuit containing reset gate I get the following error:

HighLevelSynthesis was unable to synthesize Instruction(name='reset', num_qubits=1, num_clbits=0, params=[]).

### Steps to reproduce the problem

Using the following circuit I found to be able to produce the error.

```
qr= QuantumRegister(2)
qc = QuantumCircuit(qr)
qc.reset(qr)
noise_model = NoiseModel()
sim = AerSimulator(method='matrix_product_state', noise_model=noise_model)
transpiled_qc = transpile(qc, sim, optimization_level=0)
res = sim.run(transpiled_qc, shots=10).result()
```

### What is the expected behavior?

It should transpile successfully. Current workaround I found is removing the noise modell from the simulation.

**Comment by zuper1998** [comment]
Nvm updating to 13.1 fixed the issue

**Comment by derenliu** [comment]
Hi, I still have this issue.

HighLevelSynthesis was unable to synthesize Instruction(name='reset', num_qubits=1, num_clbits=0, params=[]). -- Verify the input circuits and the traspilation options. -- https://ibm.biz/error_codes#1516"

seems that the reset is causing the circuit unable to transpile. How did you fix the problem?

**Comment by HandyKurniawan** [comment]
Hi, 

I have updated to qiskit-aer 0.13.3, but I still have the issue. I am using the fake_backend here.
Do you know the solution?
