### ISSUE TITLE
[qiskit-aer-gpu] Cannot execute parallel processes with mpirun

### ISSUE THREAD

**Issue by intelligi123** [Qiskit/qiskit-aer#2025]
### Informations

- **Qiskit Aer version**: 0.12.2
- **Python version**:  3.11.6
- **Operating system**:  Ubuntu 23.10

### What is the current behavior?
I have installed qiskit-aer-gpu and MPI4PY using pip3 in order to run qiskit code on multiple nodes. My code is currently running on two nodes but independently. Below is the code I am running:

```
from qiskit import *
from qiskit.circuit.library import *
from qiskit.providers.aer import *
sim = AerSimulator(method='statevector', device='GPU', cuStateVec_enable=True, blocking_enable=True, blocking_qubits=10)
shots = 100
depth=10
qubits =  25
circuit = transpile(QuantumVolume(qubits, depth, seed=0),
backend=sim,
optimization_level=0)
circuit.measure_all()
result = execute(circuit,sim,shots=shots,seed_simulator=12345, blocking_enable=True, blocking_qubits=10).result()
dict=result.to_dict()
meta = dict['metadata']
myrank = meta['mpi_rank']
data = dict['results'][0]['data']['counts']
#print (myrank)
if (myrank==0):
   print(meta)
```

And the command is:
`mpirun -np 3 -machinefile machinefile.txt python3  demo.py `

I am getting following output as result:
```

{'time_taken_execute': 22.230309361, 'mpi_rank': 0, 'num_mpi_processes': 1, 'max_gpu_memory_mb': 5933, 'max_memory_mb': 15903, 'parallel_experiments': 1, 'num_processes_per_experiments': 1, 'omp_enabled': True}
{'time_taken_execute': 180.515637528, 'mpi_rank': 0, 'num_mpi_processes': 1, 'max_gpu_memory_mb': 5933, 'max_memory_mb': 15903, 'parallel_experiments': 1, 'num_processes_per_experiments': 1, 'omp_enabled': True}
{'time_taken_execute': 180.538947709, 'mpi_rank': 0, 'num_mpi_processes': 1, 'max_gpu_memory_mb': 5933, 'max_memory_mb': 15903, 'parallel_experiments': 1, 'num_processes_per_experiments': 1, 'omp_enabled': True}
```
All processes have rank=0 and num_mpi_processes=1. My goal is to share GPU resources of two nodes in order to run computation.

### Steps to reproduce the problem

Installation of MPI4PY and qiskit-aer-gpu

### What is the expected behavior?

My expectation is that output should show num_mpi_processes=3 (for this particular command) and mpi_rank should be assigned according to process number and computation share the resources (CPU+GPU) of both nodes.

### Suggested solutions

I cannot suggest any solution but I am concerned about installation of qiskit-aer-gpu? Is it come with support for MPI and GPU itself when installed it with pip3 or I have to build it separately with particular flags as mentioned in CONTIBUTING.md [installation instructions](https://github.com/Qiskit/qiskit-aer/blob/main/CONTRIBUTING.md#building-with-mpi-support)

**Comment by doichanj** [comment]
`pip install qiskit-aer-gpu` does not support MPI parallelization, but Aer should be built from source to add support for MPI parallel execution.

**Comment by intelligi123** [comment]
Thank you, Is there any link to guide for its build with all per-requisites?

**Comment by doichanj** [comment]
Please refer to https://github.com/Qiskit/qiskit-aer/blob/main/CONTRIBUTING.md#building-with-mpi-support

**Comment by intelligi123** [comment]
Thank you, I started that but I am getting Error at the very last step while building 
Command I am running:
`python3 ./setup.py bdist_wheel -- -DAER_THRUST_BACKEND=CUDA -DAER_MPI=True`

Error is:

```
-- Conan: checking conan executable
CMake Error at cmake/conan.cmake:531 (message):
  Conan executable not found!
Call Stack (most recent call first):
  cmake/conan.cmake:356 (conan_check)
  cmake/conan.cmake:497 (conan_cmake_install)
  cmake/conan_utils.cmake:71 (conan_cmake_run)
  cmake/dependency_utils.cmake:20 (setup_conan)
  CMakeLists.txt:144 (setup_dependencies)


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/home/dell/.local/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 666, in setup
    env = cmkr.configure(
          ^^^^^^^^^^^^^^^
  File "/home/dell/.local/lib/python3.11/site-packages/skbuild/cmaker.py", line 357, in configure
    raise SKBuildError(msg)
```

I have installed canon and added it to PATH as well, but still getting this error.

**Comment by doichanj** [comment]
Yes pybind11 is required to be installed on the system
