### ISSUE TITLE
Parsing options to Estimator and resilience level

### ISSUE THREAD

**Issue by ziechys** [Qiskit/qiskit-aer#2032]
### Informations

- **Qiskit AER version**: 0.13.1
- **Python version**: 3.10.12
- **Operating system**: Ubuntu 22.04.3

### What is the current behavior?
I want to use qiskit_aer's Estimator as substitution for a current script that uses qiskit_ibm_runtime's Estimator. Both will use QuasmSimulator Class.
These two Estimators seem to be quite different in initialization and features. 
I want to specificy: number of shots, optimization level, and resilience level. 
In the documentation of qiskit_aer's Estimator I cannot find a lot of information on the options that I can parse to the Estimator.
Moreover, it seems that the `run_options` of Estimator takes whatever dictionary you give it without error/warnings or any reaction to it. 

### Steps to reproduce the problem
In qiskit_ibm_runtime's Estimator number of shots, optimization level, and resilience level are defined like this:
```
from qiskit_ibm_runtime import QiskitRuntimeService, Estimator, Options
from qiskit_ibm_runtime.options import  ExecutionOptions
service = QiskitRuntimeService(name=redacted)

backend = 'ibmq_qasm_simulator'
options = Options(optimization_level=3,resilience_level=1, execution=ExecutionOptions(shots=10000, init_qubits=True))
estimator = Estimator(backend=backend, options=options) 
```
For qiskit_aer's Estimator I figured out with some try and error that this gives me the number of shots and optimization level. But I have not yet found resilience level
```
from qiskit_aer import QasmSimulator
from qiskit_aer.primitives import Estimator

estimator = Estimator(run_options={'shots':100000}, transpile_options={'optimization_level':3})
```
Moreover, as mentioned above, there seems to be no check or feedback on what you give the run_options as dictionary. To put it to extreme, you could, for example, run this with no problem:
```
estimator = Estimator(run_options={'shots':100000,'optimization_level': 'Hello World', 'resilience_level': 1.4+1j*0.5, 'favourite drink': 'coffee'})
```

### What is the expected behavior?
I would expect for qiskit_aer to have the same options available as qiskit_ibm_runtime, but I cannot find anything in the documentation. 
Being able to give run_options any arbitrary dictionary is also rather unexpected. 

### Suggested solutions
More info on options in documentation. 
Check of dictionary passed to run_options.

**Comment by ikkoham** [comment]
We will unify the options classes: https://github.com/Qiskit/RFCs/blob/master/0018-primitive-options-type.md
But it's pending in Qiskit now.

This issue is duplicated with https://github.com/Qiskit/qiskit-aer/issues/1850
