### ISSUE TITLE
CZ not compatible with If_test and NoiseModel

### ISSUE THREAD

**Issue by maheshwaripranav** [Qiskit/qiskit-aer#2036]
### Informations

- **Qiskit Aer version**: 0.13.0
- **Python version**: 3.11.4
- **Operating system**: Linux

### What is the current behavior?
Noise Model doesn't work well if the circuit has a CZ gate along with if_test operators.

### Steps to reproduce the problem
**Noise Model**
```
nm = NoiseModel()
qerror = pauli_error([('X', 1.0)])
nm.add_all_qubit_quantum_error(qerror, ['x'])
```

**Circuit**
```
qc = QuantumCircuit(2,1)
qc.cz(0,1)
qc.x([0,1])
qc.measure(0,0)
with qc.if_test((0,1)):
    qc.id(0)
qc.measure_all()
```

**Obtaining Counts**
```
backend = AerSimulator(noise_model=nm)
results = execute(qc, backend).result()
results.get_counts()
```
The output is `{'10 0': 1024}`

### What is the expected behavior?
For given quantum error, the expected outcome must be `{'00 0': 1024}`

### Suggested solutions
It works fine, if I remove the CZ or the if_test block.
I tried same with CX and CY gates, which do not pose any such problems. I also transpiled the circuit with basis including 'cz' but still doesn't improve.

**Comment by hhorii** [comment]
I was not able to reproduce this issue.

Code:
```
from qiskit import QuantumCircuit
from qiskit_aer.noise import NoiseModel
from qiskit_aer.noise.errors.standard_errors import pauli_error

nm = NoiseModel()
qerror = pauli_error([('X', 1.0)])
nm.add_all_qubit_quantum_error(qerror, ['x'])

qc = QuantumCircuit(2,1)
qc.cz(0,1)
qc.x([0,1])
qc.measure(0,0)
with qc.if_test((0,1)):
    qc.id(0)
qc.measure_all()

from qiskit_aer import AerSimulator

simulator = AerSimulator()
results = simulator.run(qc, noise_model=nm).result()
results.get_counts()
```

Output:
```
{'00 0': 1024}
```

**Comment by maheshwaripranav** [comment]
I used the execute function, which still gives the wrong results.
Is it wrong to use the `execute` function or does it have some limitations?

**Comment by doichanj** [comment]
`qiskit.execute` will be deprecated on Qiskit 1.0, so please use `backend.run` instead
