### ISSUE TITLE
Set up GitHub Pages

### ISSUE THREAD

**Issue by arnaucasau** [Qiskit/qiskit-aer#2051]
### Instructions 
The project now has the documentation deployed in a branch called [gh-pages](https://github.com/Qiskit/qiskit-aer/tree/gh-pages), but we need to set up the repo to use GitHub Pages by following the next 5 steps:

1. Navigate to your site's repository
2. Click `Settings`
3. Go to `Pages`
4. Select `Deploy from a branch`, under the `Source` section on `Build and deployment`
5. Select the `gh-pages` branch and the `/ (root)` folder in the `Branch` section on `Build and deployment`

![GitHubPages-example](https://github.com/Qiskit/ecosystem/assets/47946624/520f4f0c-905a-4a4f-b918-a580a953e80d)

The default URL where you can find your site is https://qiskit.github.io/qiskit-aer

For further information, you can see the [GitHub Pages Quickstart](https://docs.github.com/en/pages/quickstart#creating-your-website) and https://github.com/Qiskit/ecosystem/issues/578.

**Comment by doichanj** [comment]
I set up `gh-pages`, thank you

**Comment by arnaucasau** [comment]
Great! Thank you @doichanj! Could you update as well the link in the About section of the repo, please? I forgot to add it to the issue

**New link:** https://qiskit.github.io/qiskit-aer

**Comment by doichanj** [comment]
I fixed it, thank you
