### ISSUE TITLE
Not able to load IBMQ

### ISSUE THREAD

**Issue by DevG97** [Qiskit/qiskit-aer#2071]
from qiskit import IBMQ
IBMQ.save_account(open("apikey.txt","r").read())
Traceback (most recent call last):
  Cell In[25], line 1
    from qiskit import IBMQ
ImportError: cannot import name 'IBMQ' from 'qiskit' (/opt/conda/lib/python3.10/site-packages/qiskit/__init__.py)

Can someone help me with this

**Comment by MonitSharma** [comment]
`IBMQ` is now obsolete, make use of `qiskit-ibm-runtime`. This is how you can do it:

1. Install `qiskit-ibm-runtime`
```python
pip install qiskit-ibm-runtime
```
or if you are using a jupyter notebook

```python
%pip install qiskit-ibm-runtime
```


2. Authenticate to the service by calling QiskitRuntimeService with your IBM Cloud API key

```python
# do pip install qiskit-ibm-runtime first
from qiskit_ibm_runtime import QiskitRuntimeService
 
service = QiskitRuntimeService(channel="ibm_quantum", token="<MY_IBM_QUANTUM_TOKEN>")
```

3. Optionally use the `save_account()` method to save your credentials for easy access later on, before initializing the service.

```python
from qiskit_ibm_runtime import QiskitRuntimeService
 
# Save an IBM Quantum account and set it as your default account.
QiskitRuntimeService.save_account(channel="ibm_quantum", token="<MY_IBM_QUANTUM_TOKEN>", set_as_default=True)
 
# Load saved credentials
service = QiskitRuntimeService()
```

4. Test it:

```python
service.backends()
```

this will tell you the backends you have access to. 

or maybe run a code:

```python
 from qiskit import QuantumCircuit
 from qiskit_ibm_runtime import QiskitRuntimeService, Sampler
 
 # Create empty circuit
 example_circuit = QuantumCircuit(2)
 example_circuit.measure_all()
 
 # You'll need to specify the credentials when initializing QiskitRuntimeService, if they were not previously saved.
 service = QiskitRuntimeService()
 backend = service.backend("ibmq_qasm_simulator")
 job = Sampler(backend).run(example_circuit)
 print(f"job id: {job.job_id()}")
 result = job.result()
 print(result)
```

**Comment by 1ucian0** [comment]
Thanks @MonitSharma  for your great explanation.

@DevG97 please reopen if you think a problem still exists.
