### ISSUE TITLE
No module found qiskit.providers.aes 

### ISSUE THREAD

**Issue by tring27** [Qiskit/qiskit-aer#2082]
### Informations
I tried installing qiskit and qiskit-aer but this is not resolved
- **Qiskit Aer version**:
- **Python version**:
- **Operating system**:

### Steps to reproduce the problem
import qiskit.providers.aes

**Comment by jakelishman** [comment]
You can replace `import qiskit.providers.aer` with `import qiskit_aer` - the former has been deprecated for quite some time, and was entirely removed in Qiskit 1.0.
