### ISSUE TITLE
Aer sampler does not truncate to active number of qubits

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#2084]
### Informations

- **Qiskit Aer version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?

For many years now, the Aer simulator has truncated a circuit to only the active qubits, allowing for simulating transpiled circuits against device noise models; even when the full device number of qubits is larger than Aer supports (but the circuits active width is small enough for Aer to handle).  However, the Aer `Sampler` does not perform the same truncation.  E.g. using 5 qubits, and transpiling to an Eagle, the old Aer simulator will still truncate and run the circuit.

```python

sim = AerSimulator()
job1 = sim.run(trans_qc, shots=int(1e4), dynamic=True)
```

works fine.  But doing the same thing via the Aer sampler raises:

```python
from qiskit_aer.primitives import Sampler as AerSampler
sampler = AerSampler()
job1 = sampler.run(trans_qc, shots=int(1e4), dynamic=True)
```

CircuitTooWideForTarget: 'Number of qubits (127) in circuit-8195 is greater than maximum (30) in the coupling_map'

### Steps to reproduce the problem

Run a transpiled circuit that is smaller than 30Q in active qubits, but transpiled against a 127Q system

### What is the expected behavior?
The sampler should truncate to active qubits only, just like the simulator does.

**Comment by zlatko-minev** [comment]
+1

**Comment by doichanj** [comment]
Could you provide full script to reproduce the problem?

**Comment by nonhermitian** [comment]
```python

from qiskit import *
from qiskit_aer.primitives import Sampler
sampler = Sampler()

qc = QuantumCircuit(100, 2)
qc.h(98)
qc.cx(98, 99)
qc.measure([98, 99], [0, 1])
sampler.run(qc).result()
```

**Comment by doichanj** [comment]
This issue is fixed by release 0.14.1

**Comment by nonhermitian** [comment]
It is not fixed in Aer 0.14.1:

![image](https://github.com/Qiskit/qiskit-aer/assets/1249193/372cc5e9-fc27-43b1-9c7e-1bad780d4d48)

**Comment by doichanj** [comment]
I'm sorry but I had implemented wrongly this one:
https://github.com/Qiskit/qiskit-aer/blob/7b9371914da62cddb71daa0cf88bc6c9b7767ec7/qiskit_aer/backends/aerbackend.py#L355
I fixed this

**Comment by haimeng-zhang** [comment]
The issue does not seem to be fixed when one of the following simulation methods is specified:
`statevector`, `density_matrix`, `extended_stabilizer`, `matrix_product_state`, `unitary`, `superop`. 
For example, when using the method `matrix_product_state`, I got the following error 
<img width="1176" alt="image" src="https://github.com/Qiskit/qiskit-aer/assets/33587226/9f6788c9-f2a0-470e-b031-15d2f5fc256f">

The script to reproduce this error is the following:
```
from qiskit import *
from qiskit_aer.primitives import Sampler
options = {'shots':shots, 'method':'matrix_product_state'}
sampler = Sampler(backend_options=options)

qc = QuantumCircuit(100, 2)
qc.h(98)
qc.cx(98, 99)
qc.measure([98, 99], [0, 1])
sampler.run(qc).result()
```

I am using Aer version `'0.14.2'`.

**Comment by hhorii** [comment]
I confirmed that 0.15 can run

```
from qiskit import *
from qiskit_aer.primitives import Sampler
sampler = Sampler()

qc = QuantumCircuit(100, 2)
qc.h(98)
qc.cx(98, 99)
qc.measure([98, 99], [0, 1])
sampler.run(qc).result()
```
and
```
from qiskit import *
from qiskit_aer.primitives import Sampler
shots = 5000
options = {'shots':shots, 'method':'matrix_product_state'}
sampler = Sampler(backend_options=options)

qc = QuantumCircuit(100, 2)
qc.h(98)
qc.cx(98, 99)
qc.measure([98, 99], [0, 1])
sampler.run(qc).result()
```
, which were reported in this issue.
