### ISSUE TITLE
setup.py requirements for qiskit are outdated

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-aer#2096]
### What is the current behavior?

https://github.com/Qiskit/qiskit-aer/blob/main/setup.py#L24-L28

As V2 primitives are now included this should be made dependent on Qiskit 1.0 or above I believe.

I imagine latest Aer being installed with an older Qiskit is the cause of the failure reported here https://qiskit.slack.com/archives/C7SS31917/p1712246299460849

**Comment by jakelishman** [comment]
If all that Aer 0.14 needs from Qiskit 1.0 is the V2 primitives, it would be good to only conditionally expose the V2 primitives if Qiskit is 1.0+, and leave Aer 0.14 compatible with Qiskit pre-1.0, since we still officially support that.

**Comment by doichanj** [comment]
I put conditional import of Primitives V2 in PR #2094
