### ISSUE TITLE
Kernel dies when ECR in basis gate set for MPS

### ISSUE THREAD

**Issue by zlatko-minev** [Qiskit/qiskit-aer#2118]
### Informations

- **Qiskit Aer version**: 0.14.1
- **Python version**: 3.11.8
- **Operating system**: MacOS

### What is the current behavior?

Kernel dies when using ECR basis gate in MPS simulator. 

### Steps to reproduce the problem

```python
from qiskit import QuantumCircuit, transpile
from qiskit_aer import AerSimulator

qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0, 1)
qc.rz(0.5, 0)
qc.measure_all()

# Works with CX
simulator = AerSimulator(method="matrix_product_state", basis_gates=["cx", "id", "rz", "sx"])
qct = transpile(qc, simulator)
display(qct.draw(output='mpl'))
job = simulator.run(qct)

# Kernel dies with ECR
simulator = AerSimulator(method="matrix_product_state", basis_gates=["ecr", "id", "rz", "sx"])
qct = transpile(qc, simulator)
display(qct.draw(output='mpl'))
job = simulator.run(qct)
```

Last line causes Kernel to die every time. 

### What is the expected behavior?
 Kernel should not die, simulation should be able to use CX or ECR basis gate, esp. as new devices all use ECR. 

### Suggested solutions
Unsure

**Comment by doichanj** [comment]
I'm fixing this issue by 2 steps:

1. Raise error if unsupported gate is passed as basis_gates
2. Add native support for ecr gate in MPS method

**Comment by zlatko-minev** [comment]
Wonderful, thank you, that sounds good.

We will want to test the ECR to make sure it's implemented faithfully.
