### ISSUE TITLE
How to create a noise model

### ISSUE THREAD

**Issue by mvcerezo** [Qiskit/qiskit-aer#213]
Hello hive mind!

I need to build a noise model but I'm fairly new to python and qiskit and so far I haven't been able to do it. I was given the following code which was used in a previous version of qiskit but doesn't seem to work any more.

Please help!

    # error model
    p_reset = 0.0

    readouterrorprob = 0.02
    p_m0 = readouterrorprob
    p_m1 = readouterrorprob

    # relaxation rate
    r = 1.0/200

    # thermal populations
    p1 = 10**(-7)
    p0 = 1-p1

    p_depol1 = 0.1*10**(-2)
    p_pauli1 = 0.1*10**(-2)

    p_depol2 = 0.5*10**(-2)
    p_pauli2 = 0.5*10**(-2)

    # one-qubit gate noise
    p_x90 = p_depol1

    pX_x90 = p_pauli1
    pY_x90 = p_pauli1
    pZ_x90 = p_pauli1

    gatetime = 1
    t_meas = gatetime
    t_res = gatetime
    t_id = gatetime
    t_u = gatetime
    t_cx = 5 * gatetime
    t_X90 = gatetime

    # two-qubit gate noise
    p_cx = p_depol2

    pIX_cx = p_pauli2
    pIY_cx = p_pauli2
    pIZ_cx = p_pauli2
    pXI_cx = p_pauli2
    pXX_cx = p_pauli2
    pXY_cx = p_pauli2
    pXZ_cx = p_pauli2
    pYI_cx = p_pauli2
    pYX_cx = p_pauli2
    pYY_cx = p_pauli2
    pYZ_cx = p_pauli2
    pZI_cx = p_pauli2
    pZX_cx = p_pauli2
    pZY_cx = p_pauli2
    pZZ_cx = p_pauli2

    # error model
    config = {
               "shots": 50000,
               "data": [
                        "classical_state",
                        "quantum_state_ket",
                        "density_matrix",
                        "probabilities",
                        "probabilities_ket",
                        "target_states_inner_product"
                        "target_states_overlaps"
                        ],
                "initial_state": Psi,
                "chop": 1e-10,
                "noise_params": {
                                 "reset_error": p_reset,
                                 "readout_error": [p_m0, p_m1],
                                 "relaxation_rate": r,
                                 "thermal_populations": [p0, p1],
                                "X90": {
                                        "p_depol": p_x90,
                                        "p_pauli": [pX_x90, pY_x90, pZ_x90],
                                        "gate_time": t_X90,
                                        #"U_error": matrix_x90
                                        },
                                "CX": {
                                       "p_depol": p_cx,
                                       "p_pauli": [pIX_cx, pIY_cx, pIZ_cx,
                                                   pXI_cx, pXX_cx, pXY_cx, pXZ_cx,
                                                   pYI_cx, pYX_cx, pYY_cx, pYZ_cx,
                                                   pZI_cx, pZX_cx, pZY_cx, pZZ_cx],
                                        "gate_time": t_cx,
                               #         #"U_error": matrix_cx
                                        }
                               }
            }

    backend = "local_qasm_simulator"

    job = execute(qc, backend, config=config)

**Comment by yaelbh** [comment]
Please follow https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/aer/building_noise_models.ipynb

**Comment by chriseclectic** [comment]
Closing this issue since it is covered in the tutorials @yaelbh  linked to.
