### ISSUE TITLE
Number of qubits (15) in circuit-164 is greater than maximum (14) in the coupling_map

### ISSUE THREAD

**Issue by LukeTheWalker** [Qiskit/qiskit-aer#2133]
### Informations

- **Qiskit Aer version**: 0.14.1
- **Python version**: 3.12.3
- **Operating system**: Arch Linux

### What is the current behavior?
I am unable to run density matrix simulation on 15+ qubits

### Steps to reproduce the problem
```
import itertools
import cupy as cp
import numpy as np
import qiskit
from qiskit.circuit.random import random_circuit
from qiskit_aer import AerSimulator
from cuquantum import contract
from cuquantum import CircuitToEinsum
import os
import time
import sys

simulator = AerSimulator(method='density_matrix', device='GPU', cuStateVec_enable=True)
# or even on CPU
# simulator = AerSimulator(method='density_matrix', device='CPU')

qubit_count = 15
depth = 120

circuit = random_circuit(qubit_count, depth)

start_time = time.time()
circ = qiskit.transpile(circuit, simulator)
result = simulator.run(circ).result()
circ.save_density_matrix()
computation_time = time.time() - start_time


```

### What is the expected behavior?
Running the computation

**Comment by jakelishman** [comment]
A 15q density matrix requires 16GB of RAM to store, plus any other storage for other parts of the computation (which in the worst case could involve a further 16GB matrix).  Even if your system technically has more RAM than that (Aer detects the memory available to it), it's quite possible that there's insufficient _contiguous_ memory to store that matrix or to do the simulation.

**Comment by LukeTheWalker** [comment]
I see, thanks I will close the issue then.

Is there any way to check the computation requirements for each simulation mode?

**Comment by jakelishman** [comment]
Largely you have to know what type of simulation you're driving underneath.  A dense statevector requires $2^{\text{num\textunderscore qubits}}$ entries to store, a density matrix is the square of the statevector and a super-operator is the square of the density matrix.  All of those are then multiplied by the size of the scalar type, which is 16 bytes for a complex double-precision value.  Aer calculates it in its private method `AerSimulator._set_method_config`, and I think it becomes available as `simulator.configuration().n_qubits` if `simulator = AerSimulator(...)`.
