### ISSUE TITLE
Can't set method for EstimatorV2

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-aer#2140]
### Informations

- **Qiskit Aer version**: 0.14.1
- **Python version**: 3.11.9
- **Operating system**: Fedora 40

### Steps to reproduce the problem

```python
from qiskit_aer.primitives import EstimatorV2

estimator = EstimatorV2(options=dict(backend_options=dict(method="stabilizer")))
```

```
Traceback (most recent call last):
  File "/home/kevinsung/projects/documentation/scratch/repro.py", line 3, in <module>
    estimator = EstimatorV2(options=dict(backend_options=dict(method="stabilizer")))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevinsung/.pyenv/versions/documentation/lib/python3.11/site-packages/qiskit_aer/primitives/estimator_v2.py", line 74, in __init__
    self._backend = AerSimulator(method=method, **self.options.backend_options)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: qiskit_aer.backends.aer_simulator.AerSimulator() got multiple values for keyword argument 'method'
```

### What is the expected behavior?

Should work.

### Suggested solutions

Looks like [this line](https://github.com/Qiskit/qiskit-aer/blob/18987e012905253d39343f8ade4a2c54045744b9/qiskit_aer/primitives/estimator_v2.py#L74) should not be setting the method for the user.

**Comment by zlatko-minev** [comment]
Yeah I think this is the same bug I reported here https://github.com/Qiskit/qiskit-aer/issues/2117 #2117

**Comment by kevinsung** [comment]
ah, thanks, didn't see that. closing as duplicate
