### ISSUE TITLE
Transpile with multiple circuits fails after qiskit 1.1

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit-aer#2141]
### Informations

- **Qiskit Aer version**: *
- **Python version**: *
- **Operating system**: *

### What is the current behavior?

Transpile with multiple circuits fails in MacOS and Windows. Details are in https://github.com/Qiskit/qiskit/issues/12425

### Suggested solutions

In qiskit 1.1 there is a behavior change in the transpile. In many cases (especially in MacOS and Windows) the transpiler disables multiprocessing feature because of performance reason. In the parallel transpile backend Target information is deep copied via dill, but now all pass manager run shares the internal state. So Target should not be mutated.

**Comment by mtreinish** [comment]
I think the simplest fix is probably to just delete the custom translation stage plugin and the associated pass. It was added as a workaround for a previous bug in the 1q gate peephole optimization pass in qiskit with noiseless backends, which should have been fixed quite some time ago, I don't think that the pass is serving a purpose anymore.
