### ISSUE TITLE
stabilizer method fails with SamplerV2

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-aer#2164]
### Informations

- **Qiskit Aer version**: 0.14.2
- **Python version**: 3.12.3
- **Operating system**: Arch Linux

### What is the current behavior?

stabilizer method fails with SamplerV2 even though it works with V1 Sampler.

### Steps to reproduce the problem

```python
import numpy as np
from qiskit.circuit.library import EfficientSU2
from qiskit_aer.primitives import Sampler, SamplerV2

n_qubits = 8
circuit = EfficientSU2(n_qubits)
circuit.measure_all()
rng = np.random.default_rng(1234)
params = rng.choice(
    [0, np.pi / 2, np.pi, 3 * np.pi / 2],
    size=circuit.num_parameters,
)

# works
sampler = Sampler(backend_options=dict(method="stabilizer"))
job = sampler.run(circuit.decompose(), params, shots=10)
quasis = job.result().quasi_dists[0]

# throws error
samplerv2 = SamplerV2(options=dict(backend_options=dict(method="stabilizer")))
pub = (circuit.decompose(), params, 10)
job = samplerv2.run([pub])
result = job.result()
```
```

QiskitError: 'ERROR:  [Experiment 0] Circuit EfficientSU2 contains invalid instructions {"gates": {ry}} for "stabilizer" method.Circuit EfficientSU2 contains invalid parameters  for "stabilizer" method. ,  ERROR: Circuit EfficientSU2 contains invalid instructions {"gates": {ry}} for "stabilizer" method.Circuit EfficientSU2 contains invalid parameters  for "stabilizer" method.'
```

### What is the expected behavior?

Should work

**Comment by doichanj** [comment]
I think V2 primitives only accepts ISA circuits, so the circuits should be transpiled before passing to `run()` function
(V1 primitive runs because it calls transpiler inside)

**Comment by kevinsung** [comment]
How do I obtain the appropriate transpiler target from the SamplerV2 instance?

**Comment by doichanj** [comment]
`circuit = transpile(circuit, AerSimulator(method='stabilizer'))`
Do you think it is acceptable for users, or not?

**Comment by kevinsung** [comment]
It's less than ideal that the user has to initialize the AerSimulator object separately from the SamplerV2. This is not easy to discover.

**Comment by doichanj** [comment]
I do not know how to use `qiskit.primitives` with transpiler but I think we have to provide the similar way to use `qiskit_aer.primitives`

**Comment by kevinsung** [comment]
With `qiskit.primitives`, it seems that no transpilation is required. It can even handle the `EfficientSU2` gate directly (for `qiskit_aer.primitives` I had to do `circuit.decompose()` to decompose that gate.

For example, this works:
```python
import numpy as np
from qiskit.circuit.library import EfficientSU2
from qiskit.primitives import StatevectorSampler

n_qubits = 8
circuit = EfficientSU2(n_qubits)
circuit.measure_all()
rng = np.random.default_rng(1234)
params = rng.choice(
    [0, np.pi / 2, np.pi, 3 * np.pi / 2],
    size=circuit.num_parameters,
)

samplerv2 = StatevectorSampler()
pub = (circuit, params, 10)
job = samplerv2.run([pub])
result = job.result()
```

**Comment by kevinsung** [comment]
To match this behavior, the primitives in Qiskit Aer should not require any transpilation. It should handle any gate that can be simulated.

**Comment by kevinsung** [comment]
Closing in favor of #2165
