### ISSUE TITLE
qiskit-aer not getting imported

### ISSUE THREAD

**Issue by AbhayBhandarkar** [Qiskit/qiskit-aer#2193]
### Informations

- **Qiskit Aer version**: NA since not imported
- **Python version**: 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
- **Operating system**: Windows 11 (also tried using colab which uses Linux)

### What is the current behavior?
Aer in qiskit isn't getting imported

### What is the expected behavior?
Aer should be imported

**Comment by doichanj** [comment]
Aer is not in Qiskit anymore. Please import Aer from Aer

**Comment by Cerbetron** [comment]
use:  from qiskit_aer import AerSimulator
Aer is not available on qiskit directly anymore. Use qiskit_aer to import Aer
