### ISSUE TITLE
Qiskit is deprecating `qiskit.providers.models`, which it is used by Aer

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-aer#2197]
The object `QasmBackendConfiguration` is going to be deprecated in Qiskit. An instance of that object is created in:

https://github.com/Qiskit/qiskit-aer/blob/5efea5735433ac4914e63b0ff866c6e10e881585/qiskit_aer/backends/aer_simulator.py#L731

**Comment by t-imamichi** [comment]
Is this fix planned for the next release?

**Comment by doichanj** [comment]
I'm fixing for Aer 0.15
