### ISSUE TITLE
Support distributed environment for shot-level parallelization

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-aer#220]
### What is the expected behavior?
Simulation with noise is an embarrassingly parallel workload if one-shot simulation needs time. Multiple servers can reduce simulation time.

We think two cases of distributed environment.

1. Personal workstations: qiskit application on a laptop runs simulation on personal workstations 
2. HPC cluster or kubernetes cluster:  qiskit application on a laptop submits job to a scheduler and receives its result

In this issue, we focus on the first case. I list discussion points in following.

#### API
We need to keep simplicity in APIs to use distributed environment. Following code is an example to use `server1` and `server2` (urls): 
```
from qiskit import execute, Aer 
bkend = Aer.get_backend("qasm_simulator", hosts=['server1', 'server2'])
```

#### Installation
We also need to keep simplicity in installation. `pip qiskit-aer` should install the all.

#### RPC
We are thinking two ways to start simulation:

1. REST
2. shell (ssh, mpirun, and etc)

In 1, a daemon process handles a http request and return results by calling local standalone-simulator. This approach is similar to a way to call simulators in IBM QX Experience.
In 2, a client (qiskit application) calls shell commands to start simulation on remote (or local) servers.

**Comment by atilag** [comment]
>... Multiple servers can reduce simulation time.

So for the first case: Personal workstations. How can multiple servers can be faster than spwaning tasks in parallel using the CPU cores? ... I may have not understood the problem correctly.
We already have parallel shot-level simulation in palce right?

**Comment by hitomitak** [comment]
Current parallel shot-level simulation (OpenMP parallelization) is effective for only the local node. 
We do not mention OpenMP parallelization but the distributed environment with multiple nodes.
For example, when the simulation is 10 shots with noise and workers are 2 nodes, we can send 5 shots' simulations to 2 workers and collect the results from them such as map/reduce function. The execution time becomes half compared with only one node.

**Comment by atilag** [comment]
So the workers are executed in different computers, right?

**Comment by hitomitak** [comment]
Yes. That's right.

**Comment by atilag** [comment]
So I guess that servers need to be launched manually on each of the nodes, before the `master` (or client) distribute the jobs among them. And this server code will just execute the standalone simulator, or will run the Terra addon.

**Comment by atilag** [comment]
Ok, I just saw it on your PR.

**Comment by atilag** [comment]
MPI simulator will handle this functionality, and it's already in progress, so I'm closing this issue.
