### ISSUE TITLE
Simulator can run indefinately when running circuits with conditionals

### ISSUE THREAD

**Issue by IlanIwumbwe** [Qiskit/qiskit-aer#2230]
[Benny](https://github.com/Bennybenassius) and I found this bug.

### Informations

- **Qiskit Aer version**: 0.15.0
- **Python version**: 3.11.6
- **Operating system**: Ubuntu 23.01 LTS

### What is the current behavior?
Runs indefinately

### Steps to reproduce the problem
Run this code:
``` py
from qiskit import QuantumCircuit, ClassicalRegister
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation

subcirc1 = QuantumCircuit(0)
# subcirc1.x(0)

main_circ = QuantumCircuit(1)
# Adding creg resources 
creg_0 = ClassicalRegister(1)
main_circ.add_register(creg_0)


main_circ.measure(0, creg_0[0])
main_circ.x(0)
with main_circ.if_test((creg_0[0],0)) as else_1:
    main_circ.append(subcirc1)
with else_1:
    main_circ.append(subcirc1)

main_circ.measure_active()
print(main_circ)
run_on_simulator(main_circ, 1)
```

Making the subroutine non-empty makes it work
``` py
from qiskit import QuantumCircuit, ClassicalRegister
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation

subcirc1 = QuantumCircuit(1)
subcirc1.x(0)

main_circ = QuantumCircuit(1)
# Adding creg resources 
creg_0 = ClassicalRegister(1)
main_circ.add_register(creg_0)


main_circ.measure(0, creg_0[0])
main_circ.x(0)
with main_circ.if_test((creg_0[0],0)) as else_1:
    main_circ.append(subcirc1, [0])
with else_1:
    main_circ.append(subcirc1, [0])

main_circ.measure_active()
print(main_circ)
run_on_simulator(main_circ, 1)
```

Moving the `x` gate before the measure makes it work
``` py
from qiskit import QuantumCircuit, ClassicalRegister
from helpers.qiskit_helpers import compare_statevectors, run_on_simulator, run_routing_simulation

subcirc1 = QuantumCircuit(0)

main_circ = QuantumCircuit(1)
# Adding creg resources 
creg_0 = ClassicalRegister(1)
main_circ.add_register(creg_0)

main_circ.x(0)
main_circ.measure(0, creg_0[0])

with main_circ.if_test((creg_0[0],0)) as else_1:
    main_circ.append(subcirc1)
with else_1:
    main_circ.append(subcirc1)

main_circ.measure_active()
print(main_circ)
run_on_simulator(main_circ, 1)
```

### What is the expected behavior?
Should return results, in the case of empty subroutine, should always treat it as identity

**Comment by gadial** [comment]
I was unable to run your code (I'm missing your qiskit helpers and getting `qiskit_aer.aererror.AerError: 'unknown instruction: circuit-166'` when trying to replicate on my own) but I did manage to reproduce the infinite loop with

```
from qiskit import ClassicalRegister
backend = self.backend(method="statevector", device="CPU")
backend.set_options(max_parallel_experiments=0)
main_circ = QuantumCircuit(1)
creg_0 = ClassicalRegister(1)
main_circ.add_register(creg_0)
main_circ.measure(0, creg_0[0])
main_circ.x(0)
with main_circ.if_test((creg_0[0],0)) as else_1:
    pass
with else_1:
    pass

main_circ.measure_active()
result = backend.run(main_circ, shots=1).result()
print(result)
```

It seems to me that it's not an `Aer` problem but a transpiler problem. `Aer` attempts to run the transpiler, and it messes up the circuit, moving jump instructions to the beginning. This results from the conversion to DAG and back, not anything `Aer`-specific. I've forwarded the issue to the `Qiskit` crew.

**Comment by jakelishman** [comment]
Gadi: the "jump" instructions are inserted by Aer itself as part of how it makes the tree-like structure of control-flow into a sequence of instructions.  If the jumps and marks are getting set wrong, that'll be happening within Aer.

**Comment by gadial** [comment]
Thanks Jake. It's now clearer to me what's going on: `Aer` generates the `jump` command without assigning it to any qubit (which does not happen in the case of non-empty branches). This leads to the reordering of the instructions when converting back from DAG to circuit. So it's indeed a problem with the way Aer uses the transpiler.

**Comment by IlanIwumbwe** [comment]
> I was unable to run your code

Sorry about that, that was my mistake. I forgot to add the helper functions we were using into the issue.
