### ISSUE TITLE
Noise approximation for 2-qubit errors

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#224]
### What is the expected behavior?

Extend the noise approximation functions to work for 2-qubit errors. 

Initially this should include options for 2-qubit Pauli channels, two-qubit reset channels ( which consists of single qubit resets to 0 or 1, or correlated 2-qubit resets to |ij> for i,j=0,1), or a custom defined set of unitaries.

**Comment by gadial** [comment]
This is done; see #236 .
