### ISSUE TITLE
0.15.1 doesn't install bin/qasm_simulator like 0.10.4 did

### ISSUE THREAD

**Issue by yurivict** [Qiskit/qiskit-aer#2254]
### Informations

- **Qiskit Aer version**: 0.15.1
- **Python version**: 3.11
- **Operating system**: FreeBSD 14.1

### What is the current behavior?
bin/qasm_simulator isn't installed any more by cmake, but qasm_simulator.py is present in the source tree.
Did you forget to install it?

**Comment by doichanj** [comment]
Standalone simulators are removed since 0.15
