### ISSUE TITLE
getting noise model from device fails when gates are better than coherence limit

### ISSUE THREAD

**Issue by sarah-sheldon** [Qiskit/qiskit-aer#226]
### Informations

- **Qiskit Aer version**: 0.2.0
- **Python version**: 3.7
- **Operating system**: macOS

### What is the current behavior?
Getting the noise model from a real device fails when the reported error rate is less than the error predicted by T1/T2.  

Using device properties to generate the noise model:
`noise.device.basic_device_noise_model(properties)`

If the gate error rate is lower than the coherence limit, `basic_device_gate_errors` calculates a negative depolarizing error and throws an error:

`NoiseError: 'Depolarizing probability must be in between 0 and 1.' `

### Suggested solutions
Have a check for this condition and instead of throwing an error.  Then the easiest option is for the noise model to use only the T1/T2 error.

**Comment by chriseclectic** [comment]
@sarah-sheldon did #243 fix this issue?
