### ISSUE TITLE
warning: '_WIN64' is not defined, evaluates to 0 [-Wundef]

### ISSUE THREAD

**Issue by yurivict** [Qiskit/qiskit-aer#232]
On FreeBSD I'm getting these warnings:
```
In file included from /usr/ports/science/py-qiskit-aer/work/qiskit-aer-0.2.1/src/simulators/qasm/qasm_controller.hpp:18:
/usr/ports/science/py-qiskit-aer/work/qiskit-aer-0.2.1/src/base/controller.hpp:29:7: warning: '_WIN64' is not defined, evaluates to 0 [-Wundef]
#elif _WIN64
      ^
/usr/ports/science/py-qiskit-aer/work/qiskit-aer-0.2.1/src/base/controller.hpp:376:7: warning: '_WIN64' is not defined, evaluates to 0 [-Wundef]
#elif _WIN64
      ^
2 warnings generated.
```

Are you by any chance developing the project on Windows?

**Comment by atilag** [comment]
Hey @yurivict, this warning is fine. We do support various OS: Linux 64 bits, MacOS and Windows 64 bits. So it all depends on the compiler you are using. FreeBSD should work as well if you use a version of clang or gcc that supports C++14, but we don't officially support it. I haven't even tried to build on it but I'd be glad to help if you wanted to add this support :)

**Comment by yurivict** [comment]
I think this should be:
```
#elif defined(_WIN64_)
```

**Comment by atilag** [comment]
Oh, yes. You are right.
Could you fix it in a PR? :)
I can mentor you If not used to Github collaboration workflow

**Comment by yurivict** [comment]
Why don't you just commit the fix?

**Comment by atilag** [comment]
hehehe sure I will
