### ISSUE TITLE
No install target defined in cmake scripts

### ISSUE THREAD

**Issue by yurivict** [Qiskit/qiskit-aer#233]
It does build the executable ```qasm_simulator```.
It should also be installed. Does something else need to be installed too?

**Comment by atilag** [comment]
Yep, depending on the OS we have to install BLAS and/or OpenMP libraries.
As this is not our main use-case (standalone executable), we haven't implemented the install target yet. But I'll put it in the backlog.
I can mentor too, if someone wants to jump in and implement it :)

**Comment by leskunberg** [comment]
I can implement it, but since this my first run at things I would appreciate some mentorship @atilag

**Comment by yurivict** [comment]
You can just look at some other cmake project to see how installing files in done. FOr example, qTox: https://github.com/qTox/qTox

**Comment by leskunberg** [comment]
That gives me enough to run with. Thanks @yurivict

**Comment by atilag** [comment]
It's been a while, but maybe @leskunberg wants to resume this and try to add an install target for the standalone version? Otherwise, it's ok to close the issue?
