### ISSUE TITLE
double check equations for obtaining basic_device_noise_model

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-aer#241]
Currently when getting a basic device noise model, any cx_error above 0.75 causes error, and when considering thermal relaxation, any cx_error above 0.5 causes error.

Is this correct?

Motivation:

There is currently an error with modeling noise from some devices, as they report non-calibrated gates as 100% error. We need to find out what should be reported, but first check to make sure we do the correct math for getting the depolarizing error probability etc.

To reproduce the current error:

```python
from qiskit import IBMQ
from qiskit.providers.aer.noise.device import basic_device_noise_model

IBMQ.load_accounts()
device = IBMQ.get_backend('ibmq_poughkeepsie')
properties = device.properties()
noise_model = basic_device_noise_model(properties, thermal_relaxation=False)
```

**Comment by chriseclectic** [comment]
After double checking this is mostly correct, but still points out a bug in the device model.

For a n-qubit depolarizing error channel then minimum average gate fidelity for a depolarizing channel (the completely depolarizing channel) is 1 / 2^n for n qubits. So this means the largest gate error (infidelity 1-F) that can be fit to a depolarizing error channel is 1 - 1 / 2^n, which is 0.5 for single qubit depolarizing channel.

In the case of thermal relaxation its minimum minimum F is also 1 / 2^n, so having the composition of two errors in that case gives you a minimum single qubit F of 0.5^2 = 0.25, so thats why maximum error allowed rate for that model is 0.75.

The bit thats a bug is that the single-qubit probability calculations are being used for the 2-qubit gate errors.
