### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found. 

### ISSUE THREAD

**Issue by phraretein** [Qiskit/qiskit-aer#242]
### Informations

- **Qiskit Aer version**:
{'qiskit': '0.10.4',
 'qiskit-terra': '0.8.2',
 'qiskit-ignis': '0.1.1',
 'qiskit-aer': '0.2.1',
 'qiskit-ibmq-provider': '0.2.2',
 'qiskit-aqua': '0.5.1'}
- **Python version**:
3.7.3
- **Operating system**:
Windows

### What is the current behavior?
I tried to run `from qiskit import Aer`.  The result shows  `ImportError: cannot import name 'Aer' from 'qiskit'`

Diggin in, with the command `from qiskit.providers.aer import Aer`, the result shows 
```
c:\users\phrarephrare\appdata\local\programs\python\python37\lib\site-packages\qiskit\providers\aer\backends\qasm_simulator.py in <module>
     20 from qiskit.providers.models import BackendConfiguration
     21 from .aerbackend import AerBackend
---> 22 from .qasm_controller_wrapper import qasm_controller_execute
     23 from ..aererror import AerError
     24 from ..version import __version__

ImportError: DLL load failed: The specified module could not be found.
```

**Comment by atilag** [comment]
I guess you installed qiskti-aer via `pip` , right?
How did you install Pyhton in your Windows? Is it from Anaconda 3? Miniconda 3?

**Comment by phraretein** [comment]
@atilag , Yes, I've installed qiskit-aer via `pip`.  I've install python on my windows directly from `https://www.python.org/downloads/`.  Does this leads to the problem?

Thanks,

**Comment by atilag** [comment]
Probably,  I'm going to try to reproduce the error, but in the meantime if you can install Anaconda3 (or Miniconda3) and create a virtual env for installing Qiskit, you won't have any problems.

**Comment by tkeen94** [comment]
Hello, I am having a similar issue. I am trying to use a noisy simulator, but when I do 
from qiskit.providers.aer import noise
I get an error. I am using a conda environment with python 3.6.7 in VSCode and my qiskit versions are 
qiskit: 0.11.1
qiskit-aer: 0.2.3

Here is the error I get:
Traceback (most recent call last):
  File "c:\Users\Trevor\Documents\Research\Greens_Calcs_IBM_NoisySim_SC.py", line 8, in <module>
    from qiskit.providers.aer import noise
  File "C:\Users\Trevor\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\providers\aer\__init__.py", line 25, in <module>
    from .aerprovider import AerProvider
  File "C:\Users\Trevor\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\providers\aer\aerprovider.py", line 20, in <module>
    from .backends.qasm_simulator import QasmSimulator
  File "C:\Users\Trevor\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\providers\aer\backends\__init__.py", line 15, in <module>
    from .qasm_simulator import QasmSimulator
  File "C:\Users\Trevor\AppData\Local\Programs\Python\Python36\lib\site-packages\qiskit\providers\aer\backends\qasm_simulator.py", line 23, in <module>
    from .qasm_controller_wrapper import qasm_controller_execute
ImportError: DLL load failed: The specified module could not be found.

**Comment by chriseclectic** [comment]
@atilag is this resolved?
