### ISSUE TITLE
'basic_device_noise_model' error with real device properties

### ISSUE THREAD

**Issue by revilooliver** [Qiskit/qiskit-aer#245]
### Informations

- **Qiskit Aer version**:' '0.2.1',
- **Python version**: 3.7
- **Operating system**: Windows 64bit

### What is the current behavior?

Hi, I tried to use the noise_model = noise.device.basic_device_noise_model(device.properties()) to simulate noise on real device. However, it returns the following error message:
**"NoiseError: 'Depolarizing probability must be in between 0 and 1.'"**
I am using properties from backend 'ibmq_20_tokyo'

**Comment by ajavadia** [comment]
This will be fixed by #243

**Comment by chriseclectic** [comment]
Closing this since there is already an issue to track this bug in #241
