### ISSUE TITLE
Cannot import Aer in Jupyter Notebook

### ISSUE THREAD

**Issue by BoschSamuel** [Qiskit/qiskit-aer#256]
### Informations

- **Packages versions**:
_Note: all packages were installed from source as explained on the [qiskit website](https://qiskit.org/documentation/contributing_to_qiskit.html#install-install-from-source-label)_
`pip list`
asn1crypto            0.24.0    
certifi               2019.6.16 
cffi                  1.12.3    
chardet               3.0.4     
cryptography          2.7       
cvxopt                1.2.3     
decorator             4.4.0     
dlx                   1.0.4     
docloud               1.0.375   
docplex               2.9.141   
fastdtw               0.3.2     
h5py                  2.9.0     
idna                  2.8       
inflection            0.3.1     
joblib                0.13.2    
jsonschema            2.6.0     
marshmallow           2.19.5    
marshmallow-polyfield 3.2       
more-itertools        5.0.0     
mpmath                1.1.0     
ndg-httpsclient       0.5.1     
nest-asyncio          1.0.0     
networkx              2.3       
ntlm-auth             1.3.0     
numpy                 1.16.4    
pandas                0.24.2    
pip                   19.1.1    
ply                   3.11      
psutil                5.6.3     
pyasn1                0.4.5     
pycparser             2.19      
pyeda                 0.28.0    
pyOpenSSL             19.0.0    
pyscf                 1.6.2     
python-dateutil       2.8.0     
pytz                  2019.1    
**qiskit-aer            0.3.0     /Users/samuelbosch/OneDrive/Dokumenti/Studium/Singapore/Qiskit/qiskit-aer**          
qiskit-aqua           0.5.2     /Users/samuelbosch/OneDrive/Dokumenti/Studium/Singapore/Qiskit/qiskit-aqua         
qiskit-chemistry      0.5.1     /Users/samuelbosch/OneDrive/Dokumenti/Studium/Singapore/Qiskit/qiskit-chemistry    
qiskit-ibmq-provider  0.2.3rc2  /Users/samuelbosch/OneDrive/Dokumenti/Studium/Singapore/Qiskit/qiskit-ibmq-provider
qiskit-ignis          0.2.0     /Users/samuelbosch/OneDrive/Dokumenti/Studium/Singapore/Qiskit/qiskit-ignis        
**qiskit-terra          0.9.0     /Users/samuelbosch/OneDrive/Dokumenti/Studium/Singapore/Qiskit/qiskit-terra**        
Quandl                3.4.8     
requests              2.22.0    
requests-ntlm         1.1.0     
scikit-learn          0.21.2    
scipy                 1.3.0     
setuptools            41.0.1    
six                   1.12.0    
sympy                 1.4       
urllib3               1.25.3    
websockets            7.0       
wheel                 0.33.4    

- **Python version**:
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
- **Operating system**:
macOS Mojave: 10.14.5 (18F132)
### What is the current behavior?
I created a Conda environment for running qiskit. When I activate this environment and just type `python` in the terminal and then `from qiskit import Aer` in Python, this works without further issues. 

But when I open Jupyter Notebook (from the Conda environment ), by typing `jupyter notebook` in the terminal, and then run `from qiskit import Aer` in Jupyter Notebook, I get the following error:
`---------------------------------------------------------------------------`
`ImportError                               Traceback (most recent call last)`
`<ipython-input-3-5cf2fb0b7167> in <module>`
`----> 1 from qiskit import Aer`
`ImportError: cannot import name 'Aer'`

### Steps to reproduce the problem
I tried changing the Kernel in Jupyter Notebooks, but didn't have any options besides "Python 3"

### What is the expected behavior?
Jupyter Notebook should work exactly the same as the Python instance in the terminal. 

### Suggested solutions
There should be a way of telling Jupyter Notebook to run Python code through this environment, from which it was opened in the terminal.

**Comment by chriseclectic** [comment]
Hello @BoschSamuel. You probably need to setup a Jupyter kernel for the conda environment that you installed qiskit into. One way to do that is follow the [instructions here](https://ipython.readthedocs.io/en/stable/install/kernel_install.html)

I'm closing this issue since it isn't really an Aer issue.
