### ISSUE TITLE
Need way of optionally installing OP components 

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#265]
### What is the expected behavior?

OP requires knowing where local numpy headers are and runtme codegen, so the users need  to install from source. This means OP should be optional in the build process.

**Comment by atilag** [comment]
OP has been integrated into the build system few weeks ago (see `openpulse-sim` branch), and progress is being made to remove the dynamically generated cyhton files, so  I think it's fine to close this issue.
