### ISSUE TITLE
Add tests for controlled-swap (Fredkin) gate

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#274]
### What is the expected behavior?

Add tests for controlled-swap gate for qasm simulator (statevector), statevector simulator, unitary simulator.

Like other tests in the qasm simulator these should test for execution in the standard basis gates (which will soon include `cswap` directly), the waltz basis gates (u1, u2, u3, cx), and the minimal basis gate set (cx, u3).

**Comment by BryceFuller** [comment]
Looking into this.
