### ISSUE TITLE
Add tests for controlled-u3 gate

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#275]
### What is the expected behavior?

Add tests for controlled-u3 gate for qasm simulator (statevector), statevector simulator, unitary simulator.

*NOTE: that there is an issue with how `cu3` is currently defined in Terra (see Terra [Issue 2703](https://github.com/Qiskit/qiskit-terra/issues/2703) / [PR 2754](https://github.com/Qiskit/qiskit-terra/pull/2755)), so that should be fixed before these tests are added.*

Like other tests in the qasm simulator these should test for execution in the standard basis gates (which will include `cu3` directly once the definition issue is resolved), the waltz basis gates (u1, u2, u3, cx), and the minimal basis gate set (cx, u3).

**Comment by newsma** [comment]
@chriseclectic Could you give me more information about what it means to add tests for a gate? Do you just need to run qasm simulations with the backends mentioned for some controlled unitary and test how it works for the different set of basis gates?

**Comment by chriseclectic** [comment]
Ideally the tests should run on all of the Aer simulation methods that support the gate and check it returns correct output.

For the cu3 gate at the moment this is the statevector method of the qasm simulator, the statevector simualtor, and the unitary simulator. For the last two you can check the actual unitary or output vector, but for the first one you will need ot use counts.

You can add it to the non_clifford reference library like for ccx gates here: https://github.com/Qiskit/qiskit-aer/blob/master/test/terra/reference/ref_non_clifford.py

**Comment by SatyaKuppam** [comment]
I can look into this.
