### ISSUE TITLE
Reset operation not working

### ISSUE THREAD

**Issue by quantumjim** [Qiskit/qiskit-aer#279]
### Informations

- **Qiskit Aer version**: master
- **Python version**: 3.7.0
- **Operating system**: Mojave

### What is the current behavior?

Reset operation is not working in
```
         ┌───┐┌─┐     ┌─┐     
q0_0: |0>┤ X ├┤M├─|0>─┤M├─|0>─
         └───┘└╥┘     └╥┘     
 c0_0: 0 ══════╩═══════╬══════
                       ║      
 c1_0: 0 ══════════════╩══════
```                            

### Steps to reproduce the problem

```
from qiskit import *
q = QuantumRegister(1)
b0 = ClassicalRegister(1)
b1 = ClassicalRegister(1)
qc = QuantumCircuit(q,b0,b1)

qc.x(q[0])

qc.measure(q[0],b0[0])
qc.reset(q[0])

qc.measure(q[0],b1[0])
qc.reset(q[0])

print(qc)

execute(qc,Aer.get_backend('qasm_simulator')).result().get_counts()
```

### What is the expected behavior?

Result should be `{'0 1': 1024}`, with the second (leftmost) result reset to `0`. But instead it is `{'1 1': 1024}`.

**Comment by chriseclectic** [comment]
It looks like this was introduced in PR #270, I will put in a fix
