### ISSUE TITLE
circuit.initialize does not work for general normalised state vectors with complex coefficients in state vector simulation

### ISSUE THREAD

**Issue by Croydon-Brixton** [Qiskit/qiskit-aer#298]
### Informations

- **Qiskit Aer version**: qiskit-aer 0.2.1 (pippy)
- **Python version**: Python 3.7
- **Operating system**: MacOS Mojave (10.14.5)

### What is the current behavior?
When I try to simulate the circuit qiskit Aer throws a type error (via qiskit/validation/fields/custom.py from sympy/core/expr.py)
TypeError: can't convert complex to float

Here the screenshot of a code that reproduces the issue:

![Screen Shot 2019-07-29 at 14 16 12](https://user-images.githubusercontent.com/19754061/62047703-6deace80-b20b-11e9-9a4f-23931c2f374c.png)

### Steps to reproduce the problem
```
import numpy as np
from qiskit import QuantumCircuit, QuantumRegister, Aer, execute
from random import gauss

def make_rand_vector(dims, complex=True):
    vec = [gauss(0, 1)+ 1j*gauss(0, 1) for i in range(dims)]
    mag = sum(abs(x)**2 for x in vec) ** .5
    return np.array([x/mag for x in vec])

register = QuantumRegister(3)
state = make_rand_vector(8)

circ = QuantumCircuit(register)
circ.initialize(state, register)
execute(circ, Aer.get_backend('statevector_simulator'))
```

### What is the expected behavior?
Simply initialise the state vector to the given numpy array

### Suggested solutions
I don't know where the problem lies.

**Comment by Croydon-Brixton** [comment]
Interestingly it works if I use 
'BasicAer' instead of 'Aer':

`import numpy as np
from qiskit import QuantumCircuit, QuantumRegister, BasicAer, execute
from random import gauss

def make_rand_vector(dims, complex=True):
    vec = [gauss(0, 1)+ 1j*gauss(0, 1) for i in range(dims)]
    mag = sum(abs(x)**2 for x in vec) ** .5
    return np.array([x/mag for x in vec])

register = QuantumRegister(3)
state = make_rand_vector(8)

circ = QuantumCircuit(register)
circ.initialize(state, register)
execute(circ, BasicAer.get_backend('statevector_simulator'))`

**Comment by chriseclectic** [comment]
@Croydon-Brixton I can reproduce this error is present on Aer 0.2.3  / Terra 0.8.2, but when running your example code on master it seems to already have been fixed.

The reason it was working on BasicAer before was that `initialize` isn't a basis instruction for that simulator, so it was being unrolled to a state preparation circuit of u1,u2,u3,cx gates.
