### ISSUE TITLE
Feature Request: Stabilizer / Clifford Simulator Backend

### ISSUE THREAD

**Issue by adamisntdead** [Qiskit/qiskit-aer#3]
It could be helpful to add a backend based on something like the simulator described in '[Fast simulation of stabilizer circuits using a graph state representation](https://arxiv.org/abs/quant-ph/0504117)' (to my knowledge, that is the best known algorithm)'

I saw that there was previously a stabilizer simulator based on the tableau in Terra.

**Comment by chriseclectic** [comment]
This is WIP in PR #13

**Comment by atilag** [comment]
Merged here: https://github.com/Qiskit/qiskit-aer/commit/dac153d6730e4de9d7787b0de8540855a26b81e6
