### ISSUE TITLE
Unitary simulator not working for self-defined unitary

### ISSUE THREAD

**Issue by NnktYoshioka** [Qiskit/qiskit-aer#308]
### Informations

- **Qiskit AER version**:
- **Operating system**:macOS 10.14.5

### What is the current behavior?
Simulating the unitary circuit with locally-defined unitary matrix is not allowed.
Concretely, we get the following error:
> AerError: 'ERROR: Failed to load qobj: "unitary" params must be a single matrix.'

### Steps to reproduce the problem
```python
from qiskit import QuantumCircuit, QuantumRegister
from qiskit import Aer, execute
Y_half = QuantumCircuit(1, name = "unitary")
Y_half.rx(pi/2, 0)
Y_half.rz(pi/2, 0)
Y_half.rx(pi/2, 0)
q = QuantumRegister(1)
qc = QuantumCircuit(q)
qc.append(Y_half.to_instruction(), [q[0]])
simulator = Aer.get_backend("unitary_simulator")
result = execute(qc, simulator).result()
unitary = result.get_unitary(qc)
```

### What is the expected behavior?
Returning unitary matrix corresponding to the quantum circuit

### Suggested solutions
Do you have any idea why the error points out that > Failed to load qobj ?

**Comment by chriseclectic** [comment]
@NnktYoshioka This is due to you naming the circuit with the same name as a basis gate for the simulator. The name `"unitary"` is reserved for unitary circuit instructions, so the assembler isn't unrolling it into the component gates. If you change to `Y_half = QuantumCircuit(1)` it should work.

**Comment by NnktYoshioka** [comment]
Thank you for your quick reply. I see, we did not have to name it `"unitary"`.
Actually I also want to visualize the circuit with many self-defined unitary gates (e.g. control Ry) using `qc.draw(outtput="mpl")` .
It would be nice if gates could be discriminated by giving names individually, but I found this is not possible.
Is there any other option?

**Comment by NnktYoshioka** [comment]
Found out that you can get around this problem, enabling both simulation and drawing, by
```python
unitary_gate = QuantumCircuit(1)
unitary_gate.name = "gate_name"
...
```
instead of `unitary_gate = QuantumCircuit(1, name = "gate_name")`.
Maybe there is some bug in the constructor of the circuit.

**Comment by maddy-tod** [comment]
When I run `unitary_gate = QuantumCircuit(1, name = "gate_name")` I am able to run the circuit and get the output 
![image](https://user-images.githubusercontent.com/40489777/62528890-83787d80-b835-11e9-877c-9597c292a18a.png)
What version of qiskit terra are you using?

**Comment by chriseclectic** [comment]
@NnktYoshioka You could open an issue about circuit drawer labels in Qiskit Terra if you like and the people that know that part of the code can help you.

You could also consider using the terra `Operator` class for constructing custom unitary gates to add to circuits, [see here](https://github.com/Qiskit/qiskit-tutorials/blob/master/qiskit/terra/operators_overview.ipynb).

@maddy-tod I think the simulator raises an exception if the circuit is empty.
