### ISSUE TITLE
Terra-integrated tests not running (fix compilation step in instructions and fix "...import state_fidelity")

### ISSUE THREAD

**Issue by jlatone** [Qiskit/qiskit-aer#32]
### Informations

- **Qiskit AER version**: 0.1.0
- **Operating system**: macOS Mojave 10.14.2 (18C54)

### What is the current behavior?
Aer's Terra-integrated tests not running, i.e.:
python -m unittest discover -s test -v

### Steps to reproduce the problem
python -m unittest discover -s test -v

### What is the expected behavior?
Tests run.

### Suggested solutions
Fix the offending line of code in test/terra/utils/common.py

**Comment by atilag** [comment]
PR #33  [Merged](https://github.com/jlatone/qiskit-aer/commit/80b1b262dc2adf1ef4a8f8f0d149720efcc6de80)

**Comment by atilag** [comment]
Thanks for the contribution Joe!! :)
