### ISSUE TITLE
aer_provider notebook is not working

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#321]
### Informations

- **Qiskit Aer version**: master
- **Python version**: 3.6.5
- **Operating system**: Linux

### What is the current behavior?
![image](https://user-images.githubusercontent.com/22316088/62468194-24b3f500-b79e-11e9-86db-acc66a6b7fb7.png)

**Comment by chriseclectic** [comment]
I've found the bug here, I'll put in a fix
