### ISSUE TITLE
Build Aer fails on CentOS 7 Power9

### ISSUE THREAD

**Issue by jwoehr** [Qiskit/qiskit-aer#324]
### Informations

- **Qiskit Aer version**: master
- **Python version**: 3.6.8
- **Operating system**: CentOS Linux 7 (AltArch) `Linux 4.14.0-115.8.1.el7a.ppc64le #1 SMP Wed Jun 5 15:02:21 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux`

### What is the current behavior?
Building Qiskit from master branch on specified platform succeeds in the order

1. terra
2. ibmq-provider
3. ignis

and then fails on qiskit-aer.

### Steps to reproduce the problem

From basic installation:
```
sudo yum install python36
mkdir work
mkdir work/Qiskit
mkdir work/Qiskit/DEV
sudo yum install git
cd DEV
git clone https://github.com/jwoehr/qiskit
git clone https://github.com/jwoehr/qiskit-terra
git clone https://github.com/jwoehr/qiskit-ibmq-provider
sudo yum install python36-pip
sudo yum install openblas openblas-devel
sudo yum install gcc-gfortran
cd ..
python3 -m venv `pwd`/qdev_env --system-site-packages
. qdev_env/bin/activate
pip install wheel
pip install cython
sudo yum update
export CFLAGS="--std=c11" # https://github.com/numpy/numpy/issues/14147
cd DEV/qiskit-terra/
pip install -e .
sudo yum install libffi-devel
sudo yum install openssl-devel
cd ../qiskit-ibmq-provider
pip -install -e .
cd ..
git clone https://github.com/jwoehr/qiskit-ignis
cd qiskit-ignis
pip install -e .
cd ..
git clone https://github.com/jwoehr/qiskit-aer
sudo yum install cmake3
pushd /usr/bin
sudo ln -s cmake3 cmake
popd
cd qiskit-aer
pip install -e .
# fails with CentOS 7 installed gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
# ./../../src/third-party/headers/nlohmann_json.hpp:127:10: error: #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
             #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
# build gcc 4.9.2
export PATH=/usr/local/gcc-4.9.2/bin:$PATH
cd qiskit-aer
pip install -e .
```
This fails as shown in the attached file [install_aer.txt](https://github.com/Qiskit/qiskit-aer/files/3479887/install_aer.txt)

### What is the expected behavior?

Aer builds.

### Suggested solutions

Wrestle with the C/C++ code.

**Comment by atilag** [comment]
Yep, we need at least a compiler which supports C++14.

**Comment by jwoehr** [comment]
> Yep, we need at least a compiler which supports C++14.

Thanks, @atilag ... do you happen to know what level of gcc would that be? I was able to build 4.9.2 but not 4.9.4.

**Comment by jwoehr** [comment]
Building gcc 6.30 now on the P9 Centos platform ... I will see if that works out ...

**Comment by jwoehr** [comment]
Thank you, @atilag qiskit-aer builds fine on the specified CentOS 7 platform with gcc-6.3.0.

**Comment by chnzhangrui** [comment]
Hi @jwoehr, do you build it from source code? I am also trying to install Aer on Power9. The installation doesn't give me any error, but I can't a folder called `aer` under `.conda_venv/lib/python3.6/site-packages/qiskit/providers/` where it supposes to live. I tried to install from [wheel](https://pypi.org/project/qiskit-aer/#modal-close) but none of these wheel files are built for power9. I wonder if I can find some wheel for power9 somewhere.

**Comment by jwoehr** [comment]
@chnzhangrui I did not use Anaconda. I used `python -m venv`

I build from the `master` branch of all the source components.

I had to build gcc 6.3.0 to get everything to work.

**Comment by chnzhangrui** [comment]
Hi @jwoehr, thanks for the quick reply. After you installed everything, are you able to `import qiskit.providers.aer`? This line gives me 
`ModuleNotFoundError: No module named 'qiskit.providers.aer'`
which points me to the fact that `aer` is not properly installed although no error during the installation.
So how you eventually use `aer`?

**Comment by jwoehr** [comment]
Yes, everything is installed correctly in my environment. Perhaps you are executing from outside the virtual environment you installed qiskit into.

**Comment by chnzhangrui** [comment]
OK, thanks for the feedback!
