### ISSUE TITLE
Initial thermal state

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-aer#326]
Add the ability to start in an initial thermal states (i.e. a mixed state with e^{-hw/kT} excited)

**Comment by chriseclectic** [comment]
This could be done using a noise model or the quantum error instructions directly.
eg.

```python
excited_pop = 0.3
init = thermal_relaxation_error(1, 1, np.inf, excited_pop)
```

Then to initialize directly 
```python
nq = 5
circ = QuantumCircuit(nq, nq)
for j in range(nq):
    circ.append(init, [j])
```
Or to use an errror model
```python
nm = NoiseModel()
nm.add_all_qubit_quantum_error(init, 'reset')

nq = 5
circ = QuantumCircuit(nq, nq)
for j in range(nq):
     circ.reset(j)
```

In the latter case you would have to make sure that the compiler doesn't remove the initial reset instructions.

**Comment by chriseclectic** [comment]
@dcmckayibm closing this issue unless you have nay further questions?
