### ISSUE TITLE
Documentation "Not Found"

### ISSUE THREAD

**Issue by kharazity** [Qiskit/qiskit-aer#331]
I can access the generic documentation pages, but several documentation pages are simply a blank page with small text saying "Not Found". Here's an example URL that's failing: https://qiskit.org/documentation/autodoc/qiskit.providers.aer.backends.qasm_simulator.html

Essentially all of the links on [this](https://qiskit.org/documentation/the_elements.html#aer) page return "Not Found" when clicked. Has the documentation been moved to somewhere else?

**Comment by nonhermitian** [comment]
Please refresh your qiskit.org.  The api docs have recently been moved:

https://qiskit.org/documentation/api/qiskit.providers.aer.QasmSimulator.html#qiskit.providers.aer.QasmSimulator

**Comment by kharazity** [comment]
I have refreshed qiskit.org. If I go to qiskit.org >> API Documentation >> Qiskit Aer >> Qasm Simulator I get the same error as above. Is the above link provided not hooked into qiskit.org yet?
