### ISSUE TITLE
incorrect measurements

### ISSUE THREAD

**Issue by JunChiehWang** [Qiskit/qiskit-aer#332]
### Informations

- **Qiskit Aer version**:0.8.2
- **Python version**: 3.6.4
- **Operating system**:Linux ip-172-31-30-115 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### What is the current behavior?
print out wrong measurements:
{'01': 55, '00': 45}

### Steps to reproduce the problem
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import execute
from qiskit import BasicAer as Aer
from qiskit.tools.visualization import plot_histogram
backend = Aer.get_backend('qasm_simulator')
c = ClassicalRegister(2)
q = QuantumRegister(1)
circuit = QuantumCircuit(q, c)
circuit.h(q[0])
circuit.measure(q[0], c[0])
circuit.measure(q[0], c[1])
job = execute(circuit, backend, shots=100)
job.result().get_counts(circuit)

### What is the expected behavior?
there shouldn't be a 01 measurements.
After the first measurement, the wave-function collapse.
After the second measurement on the same qubit, 
<img width="933" alt="Screen Shot 2019-08-27 at 22 04 58" src="https://user-images.githubusercontent.com/29104344/63830487-19796280-c921-11e9-83f8-206fe79d9b9f.png">
we should get measurement of '00' or '11' state,
instead of '01' and '00'

**Comment by hhorii** [comment]
@JunChiehWang In my environment (Ubuntu 18.04.2 LTS, Python 3.7.3), results look as you expected (`BasicAer` and `Aer`). The latest version of qiskit-aer is 0.3 as of Sept. 1, 2019. What version are you using?
```
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit import execute
from qiskit import BasicAer
from qiskit import Aer

backend = Aer.get_backend('qasm_simulator')
c = ClassicalRegister(2)
q = QuantumRegister(1)
circuit = QuantumCircuit(q, c)
circuit.h(q[0])
circuit.measure(q[0], c[0])
circuit.measure(q[0], c[1])
job = execute(circuit, backend, shots=100)
print("Aer: " + str(job.result().get_counts(circuit)))
backend = BasicAer.get_backend('qasm_simulator')
job = execute(circuit, backend, shots=100)
print("BasicAer: " + str(job.result().get_counts(circuit)))
```
```
Aer: {'00': 51, '11': 49} 
BasicAer: {'00': 45, '11': 55}
```

**Comment by atilag** [comment]
This seems to be working correctly, please reopen the issue if you are still having issues with latest versions.
