### ISSUE TITLE
`gate_time_values` fails to get correct gate times

### ISSUE THREAD

**Issue by georgesbarron** [Qiskit/qiskit-aer#336]
### Informations

- **Qiskit Aer version**: qiskit-aer 0.3.0
- **Python version**: 3.7.3
- **Operating system**: macOS Mojave 10.14.5

### What is the current behavior?

Constructing gate times from properties does not return correct results.

It's possible I could just be using this function incorrectly, though I believe I'm understanding the function `gate_time_values` correctly based on the docstring. https://github.com/Qiskit/qiskit-aer/blob/master/qiskit/providers/aer/noise/device/parameters.py#L81

### Steps to reproduce the problem

```
from qiskit import IBMQ
from qiskit.providers.aer.noise.device.parameters import gate_time_values
IBMQ.load_accounts()
pk = IBMQ.get_backend('ibmq_poughkeepsie')
props = pk.properties()
gate_times_out = gate_time_values(props)

# Compare gate time for U3 gate on qubit 0
res_1 = props.gates[3].parameters[1]
res_2 = gate_times_out[3]
```

I find that...
```
res_1 = Nduv(date=datetime.datetime(2019, 9, 2, 8, 39, 14, 753630, tzinfo=tzutc()), name='gate_length', unit='ns', value=206.2222222222222)
res_2 = ('u3', [0], None)
```

### What is the expected behavior?

`res_2` should be `('u3', [0], 206.2222222222222)`

### Suggested solutions

Not sure, I haven't tried debugging it yet.

Also if it's relevant, here are other versions...
```
adapt-vqe-qiskit-algorithm   0.1.0
qiskit                       0.10.5
qiskit-aer                   0.3.0
qiskit-aqua                  0.5.3
qiskit-chemistry             0.5.1
qiskit-ibmq-provider         0.3rc1
qiskit-ignis                 0.2.0
qiskit-terra                 0.9.0
```

**Comment by maddy-tod** [comment]
It looks like what is being returned from the backend contains the parameter `'gate_length'` but the code is checking for `'gate_time'`. Assuming these variables are meant to refer to the same thing it should be a simple case of switching over the naming of one of them.

**Comment by georgesbarron** [comment]
Oh great, I didn't catch that. I'll try this and make a PR if that fixes it. Thanks!

**Comment by chriseclectic** [comment]
@maddy-tod yep it looks like we need to update the code to use the "gate_length" field o the backend properties, @georgesbarron were you still planning on putting in a PR?

It also looks like gate length is still not being returned by properties for devices ibmqx2, ibmqx4 or ibmq_16_melbourne.

**Comment by georgesbarron** [comment]
@chriseclectic I was originally planning on making a PR for this, but Aer is the only package I haven't installed from source and I haven't had time to sort it out yet.
