### ISSUE TITLE
qasm simulator may return a partial result

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-aer#346]
### What is the expected behavior?
qasm simulator may return a result that has `'status': COMPLETED` and an error in `results` as follows: 

```
 {'backend_name': 'ibmq_qasm_simulator',
 ...
 'results': [{'status': 'ERROR: Circuit contains invalid instructions ( '
                        'invalid gate instructions: {test_name})',
              'success': False},
             {'data': {'counts': {'0x0': 122, '0x3': 134}},
              'header': {...},
              'shots': 256,
              'status': 'DONE',
              'success': True],
 'status': 'COMPLETED',
 'success': False,
 'time_taken': 0.003798207}
```

According to [Issue 49 in qiskit-ibmq-provider](https://github.com/Qiskit/qiskit-ibmq-provider/issues/49), the result schema does not allow this format. Some alternatives are being proposed.

1. manipulate the data to make it schema compliant or
2. ask the simulator teams to return schema compliant results for failed experiments or 
3. loosen the schema to not require data and shots.

**Comment by jyu00** [comment]
The issue here is that `ibmq-provider` converts the job result into a `qiskit.Result` object. The `qiskit.Result` object expects each item in the `results` list to have `data` and `shots`, as specified by the [schema](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/schemas/result_schema.json).

**Comment by jyu00** [comment]
Test with partial result (a slight modification of [this test](https://github.com/Qiskit/qiskit-ibmq-provider/blob/master/test/ibmq/test_ibmq_job.py#L375))

```
provider = IBMQ.enable_account(qe_token)
backend = provider.get_backend('ibmq_qasm_simulator')
qc = QuantumCircuit(2, 2)
qc.cx(0, 1)
qc_new = transpile(qc, backend)
qobj = assemble([qc_new, qc_new], shots=1000)
qobj.experiments[0].instructions[0].name = 'test_name'
job_sim = backend.run(qobj)
job_sim.result()
```

Note that the `.result()` call today would just raise a `JobError`. But if I comment out the code that raises the error and print the result, I get a mixture of successful and failed results (as seen above). The end goal here is to be able to present to the user both the successful experiments and error messages for the failed ones when they invoke `job.result()`.

**Comment by chriseclectic** [comment]
I've added schema-valid support for partial results in #365, but to properly implement without hacks this would require modifying the `Result` object itself to handle validating success of individual experiments, and removing this validation from the `AerBackend` class.

The main problem is that the `Result` object checks that `"success": True` at the top result-schema level when you call a method like `result.data` or `result.get_counts` etc, and if success is `False` it raises an exception showing  the `status` string message from the top level.

If any individual experiment fails, this top level success should remain `False`, so we would need to change it to check for the success value at the `ExperimentResult` schema level when you say `get_counts(j)`, and raise an exception if experiment `j` was unsuccessful.

**Comment by chriseclectic** [comment]
Related Terra PR https://github.com/Qiskit/qiskit-terra/pull/3217

**Comment by jyu00** [comment]
I was under the impression qasm simulator would always return results of individual experiment, successful or not. In other words, the `results` list would contain an entry for each experiment, along with its `success` and `status`. 

The test job with partial success (see above) failed today with an empty `results` list:
```
{'success': False, 'status': 'job failed', 'results': [], 'job_id': '5d9f32a5a633c60019f73e2c', 'backend_name': 'ibmq_qasm_simulator', 'backend_version': '0.3.0', 'date': '2019-10-10T13:31:21.051005'}
```

I'm not sure why the behavior changed, as it got partial results just few days ago. For cases where `results` is empty, can we get an error message/code? This is related to the effort to make `job.error_message()` more informative. I can open a separate issue but wanted to verify the behavior first.
