### ISSUE TITLE
Reading the quantum state by keeping global phase in qiskit 0.12.0

### ISSUE THREAD

**Issue by qabu** [Qiskit/qiskit-aer#353]
### What is the expected behavior?

Being able to read the quantum state by keeping global phase. 

If the quantum state is -|0>, then it should not be read as |0>. 

We have an educational material used for 3-day long workshops, and the recent change in qiskit 0.12.0 (ignoring global phase) affects certain parts of our materials.

**Comment by perlinm** [comment]
I am also having this issue with qiskit 0.12.0.

Global phase is not important for individual simulations in isolation, but *can* be important when post-processing results from multiple simulations.

**Comment by chriseclectic** [comment]
The simulator does not ignore global phase. This is an issue with the transpiler optimizing single qubit gates which does not preserve global phase, which you can prevent by using `optimization_level=0`.

See this issue in terra: https://github.com/Qiskit/qiskit-terra/issues/3083

**Comment by qabu** [comment]
Thank you. 

As I have observed, in Qiskit 0.13.0 the default option is "optimization_level=0".
