### ISSUE TITLE
unitary_simulator -- gates seem to act on incorrect qubits

### ISSUE THREAD

**Issue by JansenZZ** [Qiskit/qiskit-aer#358]
### Informations

- **Qiskit Aer version**: 'qiskit-aer': '0.3.0'
- **Python version**:
- **Operating system**:

### What is the current behaviour?

When implementing a quantum circuit corresponding to the unitary X \otimes I, the unitary_simulator seems to produce 
[[0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]]

rather than 

[[0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]]

as expected in conventional notation in quantum information.

### Steps to reproduce the problem

qc = QuantumCircuit(2)
qc.x([0])

simulator = Aer.get_backend('unitary_simulator')

result = execute(qc, simulator).result()
unitary = result.get_unitary(qc)
print("Circuit unitary:\n", unitary)

### What is the expected behaviour?

The unitary corresponding to this circuit ought to be

X \otimes I =

[[0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]]

### Suggested solutions

I am not sure whether this is merely an alternative convention of Qiskit or there is actually a bug when dealing with tensor product of unitary gates that result in operation acting on the wrong subspaces.

**Comment by brandhsn** [comment]
Qiskit labels the qubits from right to left (see: https://community.qiskit.org/textbook/ch-prerequisites/qiskit.html ).
So, |01> is (0,1,0,0)^T and applying X \otimes I (which is then effectively qc.x([1]) yields |11>.

**Comment by JansenZZ** [comment]
Thank you brandhsn.

**Comment by brandhsn** [comment]
You are welcome! :-)
