### ISSUE TITLE
Reset instruction can cause seg-fault for MPS method

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#372]
### Informations

- **Qiskit Aer version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

Certain circuits with reset instructions in them cause a segmentation fault when using the MPS simulator.

I'm not sure if the MPS is supposed to support reset instructions or not,

### Steps to reproduce the problem

This circuit causes seg-fault for me:

```python
circ = QuantumCircuit(2, 2)
circ.x(0)
circ.x(1)
circ.reset(0)
circ.measure(0, 0)
opts = {'method': 'matrix_product_state'}
job = execute(circ, sim, backend_options=opts)
job.result().get_counts(0)
```

### What is the expected behavior?

Circuit executes correctly

### Suggested solutions

Not sure what is causing this, but if the x gate isn't present on the qubit not being reset it seems to execute without crashing.

**Comment by merav-aharoni** [comment]
Added support for the reset function. See PR #393.
