### ISSUE TITLE
FrameChange stops OpenPulse simulation

### ISSUE THREAD

**Issue by NnktYoshioka** [Qiskit/qiskit-aer#395]
### Informations

- **Qiskit Aer version**: 0.3.0
- **Python version**: 3.7.3
- **Operating system**: macOS 10.14.6

### What is the current behavior?
Simulation by OpenPulse is very unstable when the frame change is included.
For example,  X/Y measurements for a single-qubit Rabi oscillation.

### Steps to reproduce the problem
After calibrating the pi pulse following the currently available notebook, you define 
```python
pi_2_pulse_y = pulse_lib.gaussian(duration=drive_samples,
                                amp=1j*pi_amp, 
                                sigma=drive_sigma)
fc_pi_2 = pulse.FrameChange(phase = np.pi/2)
```
Then you can define another Schedule such as
```python
schedules = []
for drive_amp in drive_amps:
    # drive pulse
    rabi_pulse = pulse_lib.gaussian(duration=drive_samples, \
                                             amp=drive_amp, sigma=drive_sigma)
    
    # add commands to schedule
    schedule = pulse.Schedule()
    schedule |= rabi_pulse(system.qubits[0].drive)
    
    # Y-measurement
    #HS^dag = Y^(1/2) Z^(1/2)
    schedule |= fc_pi_2(system.drives[0]) << schedule.duration
    schedule |= pi_2_pulse_y(system.qubits[0].drive) << schedule.duration
    schedule |= measure_and_acquire << schedule.duration

    schedules.append(schedule)
```
and run the schedule as
```python
qobj = assemble(schedules, backend_real, 
                     meas_level=1, meas_return='avg', 
                     memory_slots=2, qubit_lo_freq = [evals0[1]/2/np.pi,\
                                                     evals0[3]/2/np.pi],
                     shots=shots, sim_config = back_config)
sim_result = backend_sim.run(qobj).result()
```
In the activity monitor of macOS I see that a process named "ReportCrash" would run for a few seconds.
### Suggested solutions
I am not sure whether there is a bug in `pulse.FrameChange` or simply a technical difficulty in calculation, but expect that the latter case is unlikely (since it simply shifts the phases).

Also, running the code directly as `xxx.py` would tell you there is some problem in convergence of ODE solver. Although increasing the `nstep` in the ODE option didn't improve the situation so much, it would be helpful for users to display the error.

**Comment by chriseclectic** [comment]
I think this was fixed by #451
