### ISSUE TITLE
Add Qiskit AER homepage URL to the setup.py

### ISSUE THREAD

**Issue by cbjuan** [Qiskit/qiskit-aer#40]
### What is the expected enhancement?

As we do in other Qiskit-related packages, like Terra (see below), we should provide the URL of the Qiskit AER homepage in the `setup.py`. That URL is shown as part of the installation info and in other dependencies-related tools. In this sense, we are using the GitHub repo URL as the homepage for all the Qiskit packages. 

This is what `pip show qiskit-terra` looks like:
<img width="1108" alt="screen shot 2019-01-29 at 13 39 46" src="https://user-images.githubusercontent.com/2938045/51931779-ab40e180-23cb-11e9-9b9b-a3b004a5972d.png">

And this is what `pip show qiskit-aer` looks like:
<img width="1103" alt="screen shot 2019-01-29 at 13 39 52" src="https://user-images.githubusercontent.com/2938045/51931812-beec4800-23cb-11e9-96f7-02a26eb61d66.png">

**Comment by atilag** [comment]
Thanks for fixinf this!
Landed!
