### ISSUE TITLE
PV command does nothing in pulse simulator

### ISSUE THREAD

**Issue by zachschoenfeld33** [Qiskit/qiskit-aer#403]
### Informations

- Qiskit AER Version: `0.3.0` 
- Python Version: `3.7.4`
- Operating System: Mac OS X 10.14.6 (Mojave)

### What is the current behavior?

In the pulse simulator, PersistantValue command does nothing when followed by a drive pulse with `0` amplitude. 

### Steps to reproduce the problem

Create a schedule as follows:
``` 
pv_pulse = PersistentValue(value=omega1_pv, name='pv')

# 0 amp drive pulse
drive_pulse = SamplePulse(np.zeros(self.drive_samples), name='drive_pulse_0amp')

# add commands to schedule
schedule = pulse.Schedule(name='pv_schedule')
schedule |= pv_pulse(self.system.qubits[self.qubit_0].drive)
# make pv_pulse last exactly self.drive_samples
schedule += drive_pulse(self.system.qubits[self.qubit_0].drive) << self.drive_samples
schedule |= self.acq_0 << self.drive_samples
```

Now run a single qubit `qobj` with this schedule on `meas_level=2` and check the counts. You should see `{'0': number of shots}`. 

### What is the expected behavior?

Unless the PV command leads to a `2 pi` pulse, there should be some change in the counts. A good example to try is setting the PV amplitude to pi/number of samples which should lead to a pi pulse. This should make all the counts `1`.

**Comment by DanPuzzuoli** [comment]
As we've added PV pulses to the 'unsupported' list, and they will also be removed from pulse, I think we can close this issue @chriseclectic
