### ISSUE TITLE
QiskitError when running Pulse Simulator Pulse Schedules tutorial notebook

### ISSUE THREAD

**Issue by DaniloZZZ** [Qiskit/qiskit-aer#419]
### Informations

- **Qiskit Aer version**: 0.3.0 (built from sources branch `openpulse-sim` commit `6c2dd4`)
- **Python version**:  3.7.3
- **Operating system**: Linux 5.0.10-arch1-1-ARCH x86_64

### What is the current behavior?

When I run code from Pulse Schedules tutor [notebook](https://github.com/Qiskit/qiskit-iqx-tutorials/blob/master/qiskit/advanced/terra/5_pulse_schedules.ipynb)
a QiskitError: 'qubit_lo_freq must be supplied' is raised

<details><summary>Traceback</summary>
<pre>
---------------------------------------------------------------------------
QiskitError                               Traceback (most recent call last)
<ipython-input-38-53ed8b085d24> in <module>
----> 1 job = execute(sched, backend=backend_sim, meas_level=1, meas_return='avg')
      2 result = job.result()

/usr/lib/python3.7/site-packages/qiskit/execute.py in execute(experiments, backend, basis_gates, coupling_map, backend_properties, initial_layout, seed_transpiler, optimization_level, pass_manager, qobj_id, qobj_header, shots, memory, max_credits, seed_simulator, default_qubit_los, default_meas_los, schedule_los, meas_level, meas_return, memory_slots, memory_slot_size, rep_time, parameter_binds, **run_config)
    216                     parameter_binds=parameter_binds,
    217                     backend=backend,
--> 218                     **run_config
    219                     )
    220 

/usr/lib/python3.7/site-packages/qiskit/compiler/assemble.py in assemble(experiments, backend, qobj_id, qobj_header, shots, memory, max_credits, seed_simulator, qubit_lo_freq, meas_lo_freq, qubit_lo_range, meas_lo_range, schedule_los, meas_level, meas_return, meas_map, memory_slot_size, rep_time, parameter_binds, **run_config)
    157 
    158         return assemble_schedules(schedules=experiments, qobj_id=qobj_id,
--> 159                                   qobj_header=qobj_header, run_config=run_config)
    160 
    161     else:

/usr/lib/python3.7/site-packages/qiskit/assembler/assemble_schedules.py in assemble_schedules(schedules, qobj_id, qobj_header, run_config)
     45     qubit_lo_freq = qobj_config.get('qubit_lo_freq', None)
     46     if qubit_lo_freq is None:
---> 47         raise QiskitError('qubit_lo_freq must be supplied.')
     48 
     49     meas_lo_freq = qobj_config.get('meas_lo_freq', None)
</pre>
</details>

### Steps to reproduce the problem

build and install qiskit-aer from branch `openpulse-sim`
add following lines to the notebook

```python
from qiskit import *
backend_sim = Aer.get_backend('pulse_simulator')
job = execute(sched, backend=backend_sim, meas_level=1, meas_return='avg')
result = job.result()
```
### What is the expected 

Successfull simulation

### Suggested solutions

Somehow specify `meas_lo_freq`

**Comment by chriseclectic** [comment]
The simulator is still very much in alpha so you cant use it quite that seamlessly yet. 

You need to get a real device `backend.configuration()` as shown in the  [example notebook](https://github.com/Qiskit/qiskit-aer/blob/openpulse-sim/example/pulse_sim.ipynb), which contains missing fields.

**Comment by DaniloZZZ** [comment]
Ok, the notebook works.
Can you please reference some info about Hamiltonian format in it?
I mean these lines
```python
hamiltonian['h_str'].append('np.pi*(2*v0-alpha0)*O0')
hamiltonian['h_str'].append('np.pi*alpha0*O0*O0')
hamiltonian['h_str'].append('2*np.pi*r*X0||D0')
```

**Comment by chriseclectic** [comment]
We are still working on the functions to automatically generate hamiltonian strings, when the simulator is released a typical user shouldn't deal with these directly. There is some limited wip documentation [here](https://github.com/Qiskit/qiskit-aer/blob/openpulse-sim/qiskit/providers/aer/openpulse/readme.md]).

Closing this issue for now.
