### ISSUE TITLE
Simulating Hadamard gate using AER backend leads to non-even distribution of counts even after explicitly excluding NoiseModel model option

### ISSUE THREAD

**Issue by marekyggdrasil** [Qiskit/qiskit-aer#437]
### Informations

- **Qiskit Aer version**: 0.3.2
- **Python version**: 3.5.3
- **Operating system**: macOS Mojave 10.14.5

### What is the current behavior?

A Hadamard gate applied to |0> would create even superposition of |0> and |1>. It can be visualised as following circuit.

![quantum circuit](https://gist.githubusercontent.com/marekyggdrasil/bfcf9a9f3eac0f23c38142fec84156a6/raw/e349a70bc34c75b9f201942911e2f0f3d2c98a3a/res_circuit.png)

If I simulate this circuit using `aer` backend for `1024` shots I find measurements of `0` and `1` are not evenly distributed.

![non-even distribution](https://gist.githubusercontent.com/marekyggdrasil/bfcf9a9f3eac0f23c38142fec84156a6/raw/e349a70bc34c75b9f201942911e2f0f3d2c98a3a/res_counts.png)

### Steps to reproduce the problem

Briefly,

```python
# setup simplest circuit that reproduces the issue

N = 1
shots = 1024
q = QuantumRegister(N)
c = ClassicalRegister(N)
qc = QuantumCircuit(q, c)
qc.h(q[0])
qc.measure(q, c)
diagram = qc.draw(output="mpl")
diagram.savefig("res_circuit.png", format="png")

# set the noise model to be None

nm = None

# setup the backend

job = qiskit.execute(qc, backend_aer, shots=shots, noise_model=nm)
result = job.result()
counts = result.get_counts()
title = "Noise model set to None"
figure = plot_histogram(counts, title=title)
figure.savefig("res_counts.png", format="png")
```

Please consult [this public gist repository](https://gist.github.com/marekyggdrasil/bfcf9a9f3eac0f23c38142fec84156a6) for a complete example that reproduces the issue.

### What is the expected behavior?

As no noise or decoherence has been simulated, the expected behaviour would be to have exactly the same number of counts for both possible outcomes.

![even distribution](https://gist.githubusercontent.com/marekyggdrasil/bfcf9a9f3eac0f23c38142fec84156a6/raw/e349a70bc34c75b9f201942911e2f0f3d2c98a3a/res_qutip_counts.png)

### Suggested solutions

If you go through the code in the linked above [public gist repository](https://gist.github.com/marekyggdrasil/bfcf9a9f3eac0f23c38142fec84156a6) you will see I tried several things to ensure no noise is simulated, I set the `NoiseModel` option to `None`, I also tried to build my own `NoiseModel` such that it ensures no readout errors are simulated (which I tested with built-in method `is_ideal()`).

I cannot suggest a solution until I understand this behaviour. Here are some of my thoughts:

1. Is noise being simulated when I set `NoiseModel` to `None`?
2. If answer to (1) is `yes` then it is a bug because such behaviour is counter-intuitive.
3. If answer to (1) is `no`, then it is a bug anyway because without simulated noise the distribution should be even, just like in the `QuTip` example I provided.

Thanks a lot in advance for taking your time to help me understand it better. Cheers!

**Comment by nonhermitian** [comment]
Measurements are random samples of the probability distribution that is 50/50.  You should not expect to get exactly 50/50, just like you should not expect that when flipping a coin a finite number of times.  

QuTiP is doing a statevector simulation and computing expectation values.  Expectation values are what you would get having performed the experiment infinity many times.

**Comment by marekyggdrasil** [comment]
@nonhermitian now it makes sense! Thank you for such quick response immediately after I opened the issue!
