### ISSUE TITLE
Simulator should recognize repeated pulse patterns

### ISSUE THREAD

**Issue by dcmckayibm** [Qiskit/qiskit-aer#440]
The open pulse simulator should go through the pulse sequence and look for repeated patterns and then only simulate those patterns once.

**Comment by nonhermitian** [comment]
This requires computing the unitary from the underlying time dependent evolution. This involves computing the dynamics of all the basis vectors.

**Comment by dcmckayibm** [comment]
I agree this would only be a good idea in certain situations.

**Comment by DanPuzzuoli** [comment]
Closing as not being actively developed.
