### ISSUE TITLE
T1 example from pulse_sim example crashes

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#452]
### Informations

- **Qiskit Aer version**: openpulse-sim branch with #451 fix
- **Python version**: 3.7 Anaconda
- **Operating system**: OSX 10.15.1

### What is the current behavior?
Running the T1 example from pulse sim breaks with the error:
```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
```
I was able to get it to run successfully with `python setup.py install --with-openpulse` but I am unclear if this actually resolves the issue as it is difficult to bypass all the skbuild framework.

Note that this example was the only one I had when building the simulator, so I can guarantee that this used to work as expected.

**Comment by nonhermitian** [comment]
Looks to be related to this: https://github.com/gammapy/gammapy/issues/2453

**Comment by nonhermitian** [comment]
I can confirm that, with the removal of all mpl calls, that it is related to this: https://github.com/matplotlib/matplotlib/issues/15410

**Comment by chriseclectic** [comment]
Can we close this issue if it's not specifically related to pulse simulator?

**Comment by nonhermitian** [comment]
Yeah, sure.  It is a generic bug that will affect anyone on OSX till march
