### ISSUE TITLE
typo in pulse_simulator.py

### ISSUE THREAD

**Issue by smolinIBM** [Qiskit/qiskit-aer#455]
qiskit/providers/aer/backends/pulse_simulator.py  has a typo

### Informations

- **Qiskit Aer version**:
on branch openpulse-sim, just pulled today
- **Python version**:
3.7
- **Operating system**:
CentOS 7
### Steps to reproduce the problem

line 110 in the file spells "items" as "itmes"

### Suggested solutions

fix the spelling of items

**Comment by chriseclectic** [comment]
Fixed in #459
