### ISSUE TITLE
Unsupported features of pulse simulator for initial merge discussion

### ISSUE THREAD

**Issue by DanPuzzuoli** [Qiskit/qiskit-aer#462]
### Description

As per the discussion this morning in the OpenPulse meeting, some of the less well-tested/developed pieces of the pulse simulator will be designated as 'unsupported' for the initial merge to the master branch.

The current list of features, as well as proposed approaches for handling unsupported features are below. Please comment, and we can update this list as necessary.

### Current list of features to be designated as 'unsupported':
- Noise (i.e. Lindblad operators, as per issues with T1 simulation #452)
- Persistent value pulses (as per issue #403)
- Oscillator system types

### Proposed solution

A few options were suggested:
- Add warnings in `digest.py`, notifying the user that the feature is unsupported (and therefore may be buggy)
- Raise errors in `digest.py`, preventing the user from attempting to run simulations with the specified options
- Remove the relevant segments of code pertaining to the options before merging.

The first option seemed to be preferred in the meeting.

**Comment by chriseclectic** [comment]
I believe this has been addressed, with the exception of the oscillator system case.
