### ISSUE TITLE
Connect class Snapshots with function allowed_snapshots

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#463]
### What is the expected behavior?

Currently the developer needs to remember to update allowed snapshots in both the class `Snapshots` and the function `alloewed_snapshots`. Change this, such that there is only one location to update.

**Comment by yaelbh** [comment]
Same goes also for `snapshotset_`

**Comment by yaelbh** [comment]
In addition `apply_snapshot` independently throws an error for non-allowed snapshots, where it has its own list of allowed snapshots...

**Comment by yaelbh** [comment]
Note that the tests pass even when `allowed_snapshots` and `snapshotset_` are not updated; this is although not updating them can cause failure to the user.

**Comment by yaelbh** [comment]
I'll try to do it soon

**Comment by yaelbh** [comment]
Actually, better do it after the refactoring of snapshots.

**Comment by chriseclectic** [comment]
Closing since this method will be deprecated with snapshots, new save instructions are treated like regular circuit instructions which avoids this issue.
