### ISSUE TITLE
Replace usage of `==` for floating point compare by `Linalg::almost_equal` in svd.cpp

### ISSUE THREAD

**Issue by merav-aharoni** [Qiskit/qiskit-aer#468]
### Informations

- **Operating system**: all

### What is the current behavior?
In the file svd.cpp there are several floating point comparisons using `==` and `!=`.
Replace them by `Linalg::almost_equal`.
This issue was raised by Chris in reviewing PR #344.

### What is the expected behavior?
This usage is more correct and will eliminate several warning from compilation.

**Comment by atilag** [comment]
Flagging this issue as `bug` too, because although things are working fine at the moment, that could not be the case with some future change. Floating-point comparison using the canonical  operators it's dangerous (and erroneous depending on the needed precision).
