### ISSUE TITLE
Clifford+T Simulator Qasm Simulator method

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#47]
### What is the expected enhancement?

Adding a simulation method for the `QasmSimulator` based on the techinques in [Bravyi & Gosset (2016)](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.116.250501) for simulating Clifford + T circuits with low T gate depth.

**Note** This issue is to track the work already underway by @padraic-padraic

**Comment by atilag** [comment]
For the record: @padraic-padraic has already started a PR to address this issue.

**Comment by chriseclectic** [comment]
@atilag I can't seem to assign @padriac-padriac to the issue, his username doesn't show up

**Comment by atilag** [comment]
Yeah, Github limitation, we can only add Qiskit organization members, that's why I put a comment instead.
