### ISSUE TITLE
Pulse simulator uses numpy matrix and warning is raised

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-aer#470]
*BUG TEMPLATE* 

### Informations

- **Qiskit AER version**:
- **Operating system**:

### What is the current behavior?
When calling
`evals, estates = backend_sim.get_dressed_energies(rabi_qobj)`

I am seeing a warning raised:

```
PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  return matrix(data, dtype=dtype, copy=False)
```
It seems the pulse simulator is using the numpy matrix class which is deprecated.

### Suggested solutions

---

*FEATURE REQUEST TEMPLATE*  

### What is the expected behavior?

---

*ENHANCEMENT REQUEST TEMPLATE*

**Comment by DanPuzzuoli** [comment]
@taalexander which version of `scipy` do you have? I *think* it's coming somewhere from `scipy.sparse`: there are some threads about this warning appearing in `scipy.sparse`, and as far as I can tell the matrix class is never being directly used anywhere in the pulse simulator. 

I've just tried a few versions of `scipy`, and I get the warning in `1.2.0` and `1.2.1`, but I don't get the warning in `1.3.0` and `1.3.1`

**Comment by taalexander** [comment]
I'm was on `1.1.0`, upgrading to `1.3.0` seems to have done the trick.
