### ISSUE TITLE
Suggestion for making expectation value run faster in statevector simulator

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#471]
### What is the expected behavior?

If all the operator matrices together act on m qubits, and m is much smaller than the total number of qubits, which we denote by n. Then we can extract the density matrix of the m qubits, this costs if I remember correctly one pass on the 2^n amplitudes. Then all the remaining calculations do not depend on n.

This is similar, actually maybe identical, to something that we once did (and is still doable) for Kraus operators, but somehow did not make it into Aer.

**Comment by yaelbh** [comment]
Do we want to do anything with it?  If not then we can close.

**Comment by chriseclectic** [comment]
Closing since I think this isn't as necessary anymore with the optimized Pauli based expectation values.
