### ISSUE TITLE
cvxpy needed by noise transformations but not installed

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#490]
### Informations

- **Qiskit Aer version**: 0.3.4
- **Python version**: 3.7
- **Operating system**: Win

### What is the current behavior?
`cvxpy` is needed for noise transformations but is not installed when installing Aer with the Qiskit meta-package.  It is in the requirements-dev, but not in the setup.

**Comment by chriseclectic** [comment]
Is it not installed by qiskit-ignis either?

**Comment by nonhermitian** [comment]
Nope.  See https://github.com/Qiskit/qiskit-ignis/issues/312, https://github.com/Qiskit/qiskit-ignis/issues/313

**Comment by atilag** [comment]
Is it probably a transitive dependency? I've never needed to install it.
Anyway, yes, we have to add it to the setup.py.

**Comment by chriseclectic** [comment]
It was always intended as an optional dependency, which is why the import is handled only when that function is called. It's only used by one not frequently used function.

I'm not sure what the best way to handle these are.

**Comment by atilag** [comment]
Fixed in #520
