### ISSUE TITLE
Change name of `qubit_list` in `PulseSystemModel` and `HamiltonianModel` to something more general

### ISSUE THREAD

**Issue by DanPuzzuoli** [Qiskit/qiskit-aer#500]
As suggested by @chriseclectic , `qubit_list` should be renamed to something more general/abstract, such as `subsystemlist` or `qargs`, the latter of whcih is used in `QuantumCircuit` and `Operator` classes for specifying subsystems.  

This requires some thought though in terms of what the right way to do this right now with what is currently supported.

**Comment by DanPuzzuoli** [comment]
After thinking about it more I think it might make sense to just leave this as is for now. My thinking is that we are only really supporting simulation of transmon-type systems at the moment, and `qubit_list` feels consistent with this (as opposed to the more general `subsystemlist`, for example).

**Comment by DanPuzzuoli** [comment]
This is minor but will affect several existing PRs now, so I will leave this until those are resolved.

**Comment by chriseclectic** [comment]
Is this issue resolve @DanPuzzuoli ?

**Comment by DanPuzzuoli** [comment]
Ah I had forgotten about this. I'll do this now.
