### ISSUE TITLE
Simulation method based on measurement-based quantum computing (MBQC)

### ISSUE THREAD

**Issue by merav-aharoni** [Qiskit/qiskit-aer#508]
### What is the expected behavior?
Build a simulation method that implements the ideas presented in *Measurement-based quantum computation on cluster states* by Robert Raussendorf, Daniel E. Browne, and Hans J. Briegel, 
arXiv:quant-ph/0301052.
Milestones include support for the following:
- [ ] cluster states
- [ ] single gates: 
- [ ] H gate, pi/2 phase gate
- [ ] general rotation gates
- [ ]  CNOT
- [ ] Conversion of a quantum circuit to MBQC
- [ ] Allow snapshots into internal states

--

**Comment by merav-aharoni** [comment]
It appears there is no interest in developing this simulation method, so I am closing the issues.

**Comment by karthiknair253** [comment]
> It appears there is no interest in developing this simulation method, so I am closing the issue.

Hello Merav, I am pursuing a project revolving around using MBQC as a tool for Blind Quantum Computation Protocol and this simulation method will be very helpful for my research, I would love to help in develop a MBQC based simulator, Is there any way in which we could reopen the issue and start active development?

**Comment by merav-aharoni** [comment]
Hi @karthiknair253 , on a personal level, I find this subject very interesting, but unfortunately I won't have the bandwidth to work on it this year. Of course, if you or one of your colleagues would like to do the development and contribute the code, it would be great. I would be happy to help if possible. All the best with your research! @chriseclectic, do you know if there are any plans for such development?

**Comment by fangkunfred** [comment]
Hi guys, 

Just want to point out that we have developed a MBQC toolkit in Paddle Quantum. All of your desired requirements are met. You can even do quantum machine learning with it! Please find the source code [here](https://github.com/PaddlePaddle/Quantum/tree/master/paddle_quantum) and the tutorials/API documentations [here](https://qml.baidu.com/tutorials/measurement-based-quantum-computation/measurement-based-quantum-computation-module.html). 

We have also applied the MBQC toolkit to the universal blind quantum computation. You can find the tutorial [here](https://quantum-hub.baidu.com/bqc/tutorial-bqc) if interested. Basically, we have a module that automatically translates user's quantum circuit to a MBQC algorithm with brickwork pattern. Then the computation follows the [UBQC protocol](https://ieeexplore.ieee.org/abstract/document/5438603/) and interacts in real-time between your laptop and our cloud server :)
