### ISSUE TITLE
Two test files for MPS can be probably merged

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#510]
### What is the expected enhancement?

Consider merging `test_qasm_martix_product_state.py` and `test_qasm_mps_simulator.py `, both in `test/terra/backends`.

**Comment by chriseclectic** [comment]
Thanks @yaelbh, yes there should just be one file for the tests, probably `test_qasm_matrix_product_state_simulator.py` (but `test_qasm_mps_simulator.py` for short if the other file name is too long).
