### ISSUE TITLE
OpenMP is not enabled

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-aer#524]
### Informations
Since 0e184e0 was merged, OpenMP is not enabled.
- **Qiskit Aer version**:
- **Python version**: 3.*
- **Operating system**: Mac

### What is the current behavior?
`_OPENMP` is not defined in compilation, then qiskit-aer uses only one thread.

### Steps to reproduce the problem
Run qft and watch the CPU utilization does not exceed 100%.
```
import math
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from qiskit.compiler import assemble, transpile
from qiskit.providers.aer import QasmSimulator
def qft(qreg, circuit):
    n = len(qreg)
    for i in range(n):
        circuit.h(qreg[i])
    for i in range(n):
        for j in range(i):
            l = math.pi / float(2 ** (i - j))
            circuit.u1(l / 2, qreg[i])
            circuit.cx(qreg[i], qreg[j])
            circuit.u1(-l / 2, qreg[j])
            circuit.cx(qreg[i], qreg[j])
            circuit.u1(l / 2, qreg[j])
        circuit.h(qreg[i])
    return circuit
qubit = 25
q = QuantumRegister(qubit, "q")
c = ClassicalRegister(qubit, "c")
circ = qft(q, QuantumCircuit(q, c, name="qft"))
circ.barrier()
circ.measure(q, c)
qobj = assemble(circ)
QasmSimulator().run(qobj).result()
```

### What is the expected behavior?
`_OPENMP` is enabled in compilation.

**Comment by hhorii** [comment]
I confirmed that Linux can use multiple threads.

**Comment by chriseclectic** [comment]
@atilag @hhorii The current travis logs of master show that OpenMP is disabled on Linux builds. You can see this in the build logs as they say `ignoring unrecognised pragma #pragma omp parallel ...`. I confirmed this on my Ubuntu desktop as well.

OpenMP does appear to be working on master on my Macbook (and in travis) now though.

An easy way to test without looking at the build logs is to look at the result metadata:

```python
from qiskit import *

backend = Aer.get_backend('qasm_simulator')
result = execute(QuantumCircuit(1), backend).result()
omp = result.metadata.get('omp_enabled')
if omp:
    print('OpenMP is ENABLED!')
else:
    print('OpenMP is DISABLED!')
```

**Comment by hhorii** [comment]
I confirmed that this bug was fixed in recent master.

**Comment by hhorii** [comment]
I found OpenMP is not enabled in Linux env.

**Comment by atilag** [comment]
#550 has landed on `master` so everything should be working now.
