### ISSUE TITLE
HamiltonianModel parsing fails with constants in Hamiltonian

### ISSUE THREAD

**Issue by haggaila** [Qiskit/qiskit-aer#527]
### Informations

- **Qiskit Aer version**: PulseSimulator 
- **Python version**: 3.7
- **Operating system**: Windows

### What is the current behavior?
Calling `HamiltonianModel.from_dict(hamiltonian)` with the dictionary in `hamiltonian['h_str']` a simple numeric string like "0" causes an exception in file oppparse.py, `HamiltonianParser._compute_drift_data()` in the line `ham_full = np.zeros(np.shape(self._system[0][0].full()), dtype=complex)`.

Using as a Hamiltonian "0*Z0" causes an exception in `ham_full += ham_part[0].full() * eval(ham_part[1])`

**Comment by DanPuzzuoli** [comment]
Closed by #752 - forgot to list this one in the list of closed issues for that PR.
