### ISSUE TITLE
UnboundLocalError occurs when thermal_relaxation is False in basic_device_noise_model

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-aer#53]
### Informations

- **Qiskit AER version**: 0.1.1
- **Operating system**: Windows 10

### What is the current behavior?

When I call `qiskit.providers.aer.noise.device.basic_device_noise_model` with `thermal_relaxation=False`, `UnboundLocalError` occurs.
It is because `relax_params` is defined only when `thermal_relaxation=True`.
See https://github.com/Qiskit/qiskit-aer/blob/master/qiskit/providers/aer/noise/device/models.py#L158

### Steps to reproduce the problem

Run the following code.
```
from qiskit import IBMQ
from qiskit.providers.aer.noise.device.models import basic_device_noise_model

IBMQ.load_accounts()
properties = IBMQ.get_backend('ibmq_16_melbourne').properties()
basic_device_noise_model(properties, thermal_relaxation=False)
```

Get the following output.
```
C:\home\ima\envs\vqe2\lib\site-packages\marshmallow\schema.py:364: ChangedInMarshmallow3Warning: strict=False is not recommended. In marshmallow 3.0, schemas will always be strict. See https://marshmallow.readthedocs.io/en/latest/upgrading.html#schemas-are-always-strict
  ChangedInMarshmallow3Warning
Traceback (most recent call last):
  File "a.py", line 6, in <module>
    basic_device_noise_model(properties, thermal_relaxation=False)
  File "C:\home\ima\envs\vqe2\lib\site-packages\qiskit\providers\aer\noise\device\models.py", line 104, in basic_device_noise_model
    standard_gates=standard_gates)
  File "C:\home\ima\envs\vqe2\lib\site-packages\qiskit\providers\aer\noise\device\models.py", line 185, in basic_device_gate_errors
    relax_params,
UnboundLocalError: local variable 'relax_params' referenced before assignment
```

### What is the expected behavior?

No error occurs.

### Suggested solutions

Initialize `relax_params`.
See https://github.com/Qiskit/qiskit-aer/pull/52

**Comment by atilag** [comment]
[Merged](https://github.com/Qiskit/qiskit-aer/commit/942e47111a0c0362574aa173b6f41765041d442c)
