### ISSUE TITLE
Pulse simulator fails when no channels are being used

### ISSUE THREAD

**Issue by haggaila** [Qiskit/qiskit-aer#530]
### Informations

- **Qiskit Aer version**: PulseSimulator 
- **Python version**: 3.7
- **Operating system**: Windows

### What is the current behavior?
Running the pulse solver raises an exception in file data_config.py function `op_data_config()` executing `final_freq = freq_list[-1]` when no channels have been defined in the Hamiltonian Model string (using the syntax, e.g., "0.5 \* omegaa \* X0||D0"), since `OPSystem.freqs` remains empty.

### Suggested solutions
Verify emptiness of `OPSystem.freqs`.

**Comment by haggaila** [comment]
I tried to fix this by verifying that `freq_list` and `chan_list` are nonempty so these lines do not raise an exception, but this caused the process to crash with access violation [`Process finished with exit code -1073741819 (0xC0000005)`] at some unknown later point.

**Comment by chriseclectic** [comment]
I think if no channels are defined the HamiltonianModel class should raise an exception when loading from a string since these types of hamiltonians arent currently supported by the simulator
