### ISSUE TITLE
Unable to generate a near-identity evolution

### ISSUE THREAD

**Issue by haggaila** [Qiskit/qiskit-aer#532]
### Informations

- **Qiskit Aer version**: PulseSimulator 
- **Python version**: 3.7
- **Operating system**: Windows

### What is the current behavior?
Adding the following function to class `TestPulseSimulator` and running it, I expect it generates a near-zero Hamiltonian and evolve it using the simulator for one unit of time, to get a near-identity transformation applied to the initial state |000>. Instead, the state is ~ |+00> for any (tiny) value of `omega2`, while it remains the expected |000> when setting `omega2` to 0 exactly.

### Steps to reproduce the problem
```
    @run_cython_and_cpp_solvers
    def test_near_identity_3Q_propagator(self):
        """Tests the evolution with a near-identity three-qubit Hamiltonian."""
        time = 1
        # make Hamiltonian
        hamiltonian = {}
        hamiltonian['h_str'] = ['0.5*omega1*X0||D0', '0.5*omega2*X0*I1*I2']
        hamiltonian['vars'] = {'omega1': 0., 'omega2' : 0.01}
        hamiltonian['qub'] = {'0': 2, '1': 2, '2': 2}

        ham_model = HamiltonianModel.from_dict(hamiltonian)
        system_model = PulseSystemModel(hamiltonian = ham_model, u_channel_lo = [], qubit_list = [0, 1, 2], dt = 1)
        schedule = pulse.Schedule(name = '3Q_constant')
        acq_cmd = pulse.Acquire(duration = time)
        schedule |= acq_cmd([AcquireChannel(0), AcquireChannel(1), AcquireChannel(2)],
                            [MemorySlot(0), MemorySlot(1), MemorySlot(2)]) << time

        qobj = assemble([schedule], backend = self.backend_sim, meas_level = 2, meas_return = 'single', meas_map = [[0, 1, 2]],
                        qubit_lo_freq = [0,0,0.], memory_slots = 3, shots = 1000)
        backend_options = {'seed': 9000}
        backend_options['use_cpp_ode_func'] = True if USE_CPP_ODE_FUNC else False
        result = self.backend_sim.run(qobj, system_model, backend_options).result()
        statevector = result.get_statevector()

        # Check fidelity of statevectors
        psi0 = np.zeros((8,))
        psi0[0] = 1
        self.assertGreaterEqual(state_fidelity(statevector, psi0), 0.99)
```

### What is the expected behavior?
The fidelity of the resulting state with |000> is expected to be 1 - O(0.01^2).

**Comment by DanPuzzuoli** [comment]
@haggaila I think what's going on is that the drift Hamiltonian has `X0` on qubit 0, and the simulator defaults the initial state to be the ground state of the Hamiltonian. The state vector output is 

`array([0.70709794-0.00353552j, 0.70709794-0.00353552j,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        +0.j        ])`

which I believe is correct: this is the ground state of X*I*I multiplied by a phase. Need to be careful with the tensor product convention: using the tensor product convention in `np.kron`, the order of the subsystems in the simulator is actually reversed, i.e. this is `kron(|0>, kron(|0>, |x1>))`, where `|x1>` is the ground state of `X`.

**Comment by haggaila** [comment]
Thanks Dan, I'll fix the tests, and I will test to check what is the initial state in the case of a Hamiltonian with a degenerate ground state..
So perhaps it could be useful for users to issue a warning if the drift Hamiltonian is not Z in all qubits, or does not commute with \sum_i Z_i, etc.

**Comment by haggaila** [comment]
I'm closing this issue, it's not a bug, the discussion is summarized in the new (feature) issue #539.
