### ISSUE TITLE
Update to new standard gate names

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-aer#533]
### Summary

Qiskit/qiskit-terra#3695 (not yet merged!) changes the names of some standard gates to adhere to a more consistent naming scheme. Aer should update the gate names accordingly.

### Details

Several class names are updated and some gate names and `QuantumCircuit` methods too. The complete list of all changes is available [here](https://github.com/Qiskit/qiskit-terra/pull/3695#issuecomment-572442337).

Note, that
- the PR is **not yet merged**, but we should keep track of this!
- all previous qasm definitions are still valid (e.g. both `id` and `i` are defined)
- all previous `QuantumCircuit` methods are still supported (some are deprecated)

Aer is probably mostly affected by the changed gate names (i.e. `Gate.name`), which are
- `id` to `i`
- `tdg` to `tinv`
- `sdg` to `sinv`

Fore more details check out Qiskit/qiskit-terra#3695.

**Comment by chriseclectic** [comment]
Are these name changes confirmed for Terra? I can add dual support for these three case ("i" and "id", "sdg" and "sinv" etc) in the next release.

**Comment by Cryoris** [comment]
I think they are, but maybe it's still better to wait for the PR to be merged. 

What do you think @ajavadia @ewinston @kdk?

**Comment by chriseclectic** [comment]
@Cryoris Am I correct that this can be closed now since no changes are needed on the simulator because because the qasm/qobj names were left unchanged in the end?

**Comment by Cryoris** [comment]
Correct!
