### ISSUE TITLE
Allow to set initial state and require its setting or default it to a unique state

### ISSUE THREAD

**Issue by haggaila** [Qiskit/qiskit-aer#539]
Currently the initial state is chosen as the ground state of the drift Hamiltonian. In addition to not allowing the user to control this (which could be essential for some applications and uses), it seems that in some cases the choice is somewhat arbitrary:
When the ground state is degenerate, it is not clear how the initial state is chosen from the degenerate subspace, e.g. in the case of "-0.5 * omega0 * (X0 * X1)", where any linear combination of |++> and |--> is degenerate.

### What is the expected behavior?

Add a setting allowing the user to set the initial state.
Making the initial state a required argument for the solver would avoid any ambiguity. Otherwise, it should probably be uniquely defined if not set by the user, but I'm not sure that there is a canonical choice for degenerate ground states.

**Comment by DanPuzzuoli** [comment]
Closed by #811
