### ISSUE TITLE
Excessive build warnings for pulse simulator cython files

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-aer#548]
### Informations

- **Qiskit Aer version**: Master
- **Python version**: All
- **Operating system**: Linux and MacOS on Travis

### What is the current behavior?

CI build scripts have become excessively long due to hundreds of warnings being emitted from building the pulse simulator cython files. In some cases this can cause the build to fail due to the log file becoming too large.

### What is the expected behavior?

These warnings should be suppressed from the build logs.

### Suggested solutions

Disable the offending warnings in the CMake build script for `openpulse/cy` and `openpulse/qutip_lite/cy` directories.

**Comment by chriseclectic** [comment]
Close by #553

**Comment by atilag** [comment]
PR #553 has been merged, so this should be fixed by now.
