### ISSUE TITLE
Build break in POWER env

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-aer#555]
### Informations
`libmuparserx.a` is for x86 file and not for POWER.

- **Qiskit Aer version**: 
- **Python version**:
- **Operating system**:

### What is the current behavior?
Aer can not be compiled in ppc64le because x86 binary is included in the repository.

### Steps to reproduce the problem
Just build on ppc64le

### What is the expected behavior?
Remove binary or prepare binary for ppc64le and supported architecture.

**Comment by atilag** [comment]
Yep, we need to build a version of `libmuparserx.a` for PowePc. Should be easy. I got this.

**Comment by chriseclectic** [comment]
I've added a ppc64le case to the compile and test Travis stages in PR #554

**Comment by chriseclectic** [comment]
Looking at the log in #554, the build script for Power is failing to install Terra (because of scipy dependency). Scipy is also a dependence in Aer now due to the pulse simulator so this will be another issue.
