### ISSUE TITLE
[OpenPulse] PyDataMem_NEW_ZEROED is not declared

### ISSUE THREAD

**Issue by doichanj** [Qiskit/qiskit-aer#578]
### Informations

- **Qiskit Aer version**: 0.4
- **Python version**: 3.7
- **Operating system**: Red Hat Enterprise Linux Server release 7.6 (ppc64)

### What is the current behavior?
Compilation failure occurs on (only?) Power + RedHat environment because of Numpy's function "PyDataMem_NEW_ZEROED", maybe it is not implemented on this environment.
The error message is as follow (same 7 errors occur while compiling OpenPulse)

`/gpfs/wscgpfs01/doichan/Q/test/qiskit-aer/_skbuild/linux-ppc64le-3.7/cmake-build/qiskit/providers/aer/pulse/qutip_lite/cy/spmath.cxx:3677:52: error: ‘PyDataMem_NEW_ZEROED’ was not declared in this scope
     __pyx_v_mat->data = ((__pyx_t_double_complex *)PyDataMem_NEW_ZEROED(__pyx_v_nnz, (sizeof(__pyx_t_double_complex))));
                                                    ^~~~~~~~~~~~~~~~~~~~
/gpfs/wscgpfs01/doichan/Q/test/qiskit-aer/_skbuild/linux-ppc64le-3.7/cmake-build/qiskit/providers/aer/pulse/qutip_lite/cy/spmath.cxx:3677:52: note: suggested alternative: ‘PyDataMem_NEW’
     __pyx_v_mat->data = ((__pyx_t_double_complex *)PyDataMem_NEW_ZEROED(__pyx_v_nnz, (sizeof(__pyx_t_double_complex))));
                                                    ^~~~~~~~~~~~~~~~~~~~
                                                    PyDataMem_NEW
`

### Suggested solutions
Could you please replace PyDataMem_NEW_ZEROED to PyDataMem_NEW that maybe supported on the Power + RedHat environment. 
I googled PyDataMem_NEW_ZEROED, but it seems very few people uses this function, so I think using PyDataMem_NEW is a common way.

**Comment by nonhermitian** [comment]
One has to be a bit careful as some routines might be expecting a zeroed memory.
