### ISSUE TITLE
Statevector_simulator gives different results for transpiled and untranspiled circuits 

### ISSUE THREAD

**Issue by rsln-s** [Qiskit/qiskit-aer#581]
### Information

- **Qiskit Aer version**:
```
{'qiskit-terra': '0.11.1',
 'qiskit-aer': '0.3.4',
 'qiskit-ignis': '0.2.0',
 'qiskit-ibmq-provider': '0.4.5',
 'qiskit-aqua': '0.6.2',
 'qiskit': '0.14.1'}
```
- **Python version**:
Python 3.6.9 |Intel Corporation|
- **Operating system**:
CentOS Linux 7 (Core)

### What is the current behavior?

The results of running statevector simulator on transpiled and untranspiled circuit are different. Not clear if a simulator or transpiler issue, so reporting here.

### Steps to reproduce the problem

```python
import numpy as np
from qiskit import execute, Aer, QuantumCircuit
from qiskit.compiler import transpile

qc = QuantumCircuit(2,2)
qc.h(0)
qc.h(1)
qc.cx(0,1)
qc.rz(5.408457395985537, 1)
qc.cx(0,1)
qc.h(0)
qc.rz(1.8145842528337557, 0)
qc.h(0)
qc.h(1)
qc.rz(1.8145842528337557, 1)
qc.h(1)

backend = Aer.get_backend('statevector_simulator')

sv1 = execute(qc, backend).result().get_statevector()

print(sv1)

qc_t = transpile(qc, optimization_level=0,basis_gates=['u1', 'u2', 'u3', 'cx']) 

sv2 = execute(qc_t, backend).result().get_statevector()

print(sv2)

assert(np.allclose(sv1, sv2))
```

When running, I get:
```
[0.42093065-0.40335186j 0.39967219+0.01966733j 0.39967219+0.01966733j
 0.42093065-0.40335186j]
[-0.49302935-0.31112281j -0.0773872 -0.39260143j -0.0773872 -0.39260143j
 -0.49302935-0.31112281j]
Traceback (most recent call last):
  File "qiskit_qaoa_bug.py", line 30, in <module>
    assert(np.allclose(sv1, sv2))
AssertionError
```

### What is the expected behavior?

Assert should pass.

### Suggested solutions

I think the transpiled circuit output is correct (i.e. sv2), so looks like the issue is with simulating circuits with gates other than `['u1', 'u2', 'u3', 'cx']`

**Comment by rsln-s** [comment]
Actually, the two states are the same up to a global phase:
```
>> a = np.array([0.42093065-0.40335186j, 0.39967219+0.01966733j, 0.39967219+0.01966733j,
 0.42093065-0.40335186j])
>> b = np.array([-0.49302935-0.31112281j, -0.0773872 -0.39260143j, -0.0773872 -0.39260143j,
 -0.49302935-0.31112281j])
>> a/b
array([-0.24138027+0.9704306j , -0.24138027+0.97043061j,
       -0.24138027+0.97043061j, -0.24138027+0.9704306j ])
```

Still, not sure if this is desirable behavior.

**Comment by chriseclectic** [comment]
This is a transpiler issue: certain transpiler passes not respecting global phase (for example the unroller when for certain gates such as rz to u1). There is not really anything that can be done about it in the simulator at the moment.

There are several issues related to global phase in Terra you can follow for updates.
