### ISSUE TITLE
MPS expectation value is incorrect when qubits are not in ascending order

### ISSUE THREAD

**Issue by merav-aharoni** [Qiskit/qiskit-aer#582]
### Informations

- **Qiskit Aer version**: 0.4
- **Python version**:
- **Operating system**: all

### What is the current behavior?
Computation of expectation value value in MPS assumes qubits are ordered in ascending order. Otherwise the result may be incorrect. This requires two separate fixes - one for Pauli expectation value and one for matrix expectation value.

### Steps to reproduce the problem
There are two suitable tests that are currently in test_qasm_simulator_statevector.py: QasmSnapshotExpValPauliTests and QasmSnapshotExpValPauliTests. 
These should be added also to test_qasm_simulator_matrix_product_state.py

**Comment by chriseclectic** [comment]
Closed by #603
