### ISSUE TITLE
The seed_simulator doesn't work for list of circuits

### ISSUE THREAD

**Issue by AzizNgoueya** [Qiskit/qiskit-aer#585]
### Informations

- **Qiskit Aer version**: 0.3.4 and 0.4.0 on master
- **Python version**: 3.7.6
- **Operating system**: Windows

### What is the current behavior?
Run a list of the same circuit with a `seed_simulator` fixed gives different results.
The problem is not reproducible with BasicAer

### Steps to reproduce the problem
```Python
from qiskit import QuantumCircuit, Aer,BasicAer
from qiskit.compiler import transpile, assemble

circuit = QuantumCircuit(1,1)
circuit.h(0)
circuit.measure(0, 0)

simulator=Aer.get_backend('qasm_simulator')
for i in range(1):
    trans_circ=transpile(circuit,simulator,seed_transpiler=1,optimization_level=0)
    print('circuit',i, trans_circ.count_ops())
    qobj=assemble(10*[trans_circ],simulator,seed_simulator=1)
    for i in range(10):
        print(i, ':', simulator.run(qobj).result().get_counts(i))
```
When checking the `job.result().to_dict()`, it looks like the seed_simulator is taken into account for the first circuit.

### What is the expected behavior?
Obtain the same results for all circuits in the set

**Comment by nonhermitian** [comment]
I do not think this is the desired behavior here. When seeded, the simulator should return the same results given the same input. This is different than all inputs being identical due to using the same seed. That is to say that the seed should seed the rng used for the ensemble of circuits.

**Comment by chriseclectic** [comment]
As @nonhermitian said what you are expecting is not the correct seed behavior. 

If you set a seed it is for the entire qobj, not a single circuit. So each circuit in qobj will return the same results each time you execute the qobj. Individually each circuit uses a different, but deterministic seed, derived from the `seed_simulator` value.

**Comment by AzizNgoueya** [comment]
Sorry for the confusion, that exactly what i said, for a specific `seed_simulator` fixed, i obtain different results for the same circuits in the qobj on Aer simulator. This is not expected right?

```Python
from qiskit import QuantumCircuit, Aer,BasicAer
from qiskit.compiler import transpile, assemble

circuit = QuantumCircuit(1,1)
circuit.h(0)
circuit.measure(range(1), range(1))

simulator=Aer.get_backend('qasm_simulator')
trans_circ=transpile(circuit,simulator,seed_transpiler=1,optimization_level=0)
print('circuit', trans_circ.count_ops())
qobj=assemble(10*[trans_circ],simulator,seed_simulator=1)
for i in range(10):
        print(i, ':', simulator.run(qobj).result().get_counts(i))
```
```
circuit OrderedDict([('h', 1), ('measure', 1)])
0 : {'0': 529, '1': 495}
1 : {'0': 502, '1': 522}
2 : {'0': 523, '1': 501}
3 : {'0': 516, '1': 508}
4 : {'0': 518, '1': 506}
5 : {'0': 502, '1': 522}
6 : {'0': 508, '1': 516}
7 : {'0': 516, '1': 508}
8 : {'0': 500, '1': 524}
9 : {'0': 504, '1': 520}
```

**Comment by nonhermitian** [comment]
This is the expected result.  If you run the same batch of circuits again, you get the same output as you have posted.

**Comment by AzizNgoueya** [comment]
Ok, i see @nonhermitian thanks, just out of curiosity, why you don't use the same seed for all circuit, not just for the qobj or the batch, because it seems more plausible to me? Also, on BasicAer simulator, i got the same results for each circuit in the batch.

**Comment by nonhermitian** [comment]
Because you want each circuit to perform independent random sampling based on the amplitudes of the statevector.  If the seed is the same for all, then this is not independent random sampling.  The `basicaer` issue you show above is a bug, and should be reported.

**Comment by chriseclectic** [comment]
The only requirement of the seed is that the ENTIRE output is deterministic for a fixed qobj and fixed seed. You could do it the way you say, but to what purpose? If you set the same seed for every circuit then there is literally no reason to execute 10 identical circuits because they all would have the same outcomes and just take 10 times the simulation time. For more realistic use cases there would also be a problem with biasing error for noise models and measure sampling which would be an issue for noisy simulations (in randomized benchmarking or tomography for example)

**Comment by AzizNgoueya** [comment]
Oh, i understand better now thanks for your explanations @nonhermitian and @chriseclectic
