### ISSUE TITLE
hone 'install from source' instructions in CONTRIBUTING file

### ISSUE THREAD

**Issue by derivation** [Qiskit/qiskit-aer#59]
Related to https://github.com/Qiskit/qiskit/issues/84

### Summary

Make sure Aer's [CONTRIBUTING](https://github.com/Qiskit/qiskit-aer/blob/master/.github/CONTRIBUTING.rst) file stands on its own, so [Aer's install doc](https://qiskit.org/documentation/aer/installing_aer.html) can be removed.

### Details

We want to synthesize install instructions for all Qiskit packages into a global [Install Qiskit](https://qiskit.org/documentation/install.html) doc section, where the global install doc refers Qiskit contributors to each package's CONTRIBUTING file for details on how to install from source. 

Currently, Aer's doc includes 'Install from Source' instructions [here](https://qiskit.org/documentation/aer/installing_aer.html). This was an initial (incomplete) attempt to hone the current instructions in Aer's [CONTRIBUTING](https://github.com/Qiskit/qiskit-aer/blob/master/.github/CONTRIBUTING.rst) file.

Aer's [CONTRIBUTING](https://github.com/Qiskit/qiskit-aer/blob/master/.github/CONTRIBUTING.rst) file should be updated to stand on its own.

After Aer's [CONTRIBUTING](https://github.com/Qiskit/qiskit-aer/blob/master/.github/CONTRIBUTING.rst)  file is updated, the [Installing Aer](https://qiskit.org/documentation/aer/installing_aer.html) section of the doc will be removed.

**Comment by chriseclectic** [comment]
I think this is fixed in #119
