### ISSUE TITLE
installation of 0.1.1 from source code

### ISSUE THREAD

**Issue by alex-choquette** [Qiskit/qiskit-aer#60]
*BUG TEMPLATE* 

### Informations

- **Qiskit AER version**: 0.1.1
- **Operating system**:  CentOS 7.5.1804

### What is the current behavior?

it crashed during the configuration when I try to build  (python ./setup.py build) under my virtualenv

### Steps to reproduce the problem
1) install qiskit from source
wget https://github.com/Qiskit/qiskit/archive/0.7.2.tar.gz
tar xzvf 0.7.2.tar.gz
pip ...
2) uninstall qiskit-terra qiskit-aer

3) pip install qiskit-terra/0.8.0 from source

4) python ./setup.py build
from source of aer

5) the error message:
CMake Error at CMakeLists.txt:13 (project):
  Running

   '/tmp/pip-build-env-w2x28op_/bin/ninja' '--version'

  failed with:

   No such file or directory

### What is the expected behavior?

it installs correctly the package

### Suggested solutions

---

*FEATURE REQUEST TEMPLATE*  

### What is the expected behavior?

---

*ENHANCEMENT REQUEST TEMPLATE*

**Comment by atilag** [comment]
Hi @alex-choquette the [CONTRIBUTING](https://github.com/Qiskit/qiskit-aer/blob/master/.github/CONTRIBUTING.rst#pre-requisites) guide has exhaustive steps about how to build from source code. Take a look and let me know if something is not working for you.

**Comment by atilag** [comment]
It's been a while since there was activity in this issue, so I'm guessing that the CONTRIBUTING guide has helped.
Please, reopen the issue if you feel you need to!
