### ISSUE TITLE
ERROR: Stabilizer::State::invalid instruction 'fusion'.

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#604]
### Informations

- **Qiskit Aer version**: master
- **Python version**: 3.6
- **Operating system**: Linux

### What is the current behavior?

`ERROR: Stabilizer::State::invalid instruction 'fusion'.` for a simple innocent circuit.

### Steps to reproduce the problem

```
import qiskit
from qiskit.providers.aer.extensions.snapshot_expectation_value import *
import numpy as np

n = 25
circ = qiskit.QuantumCircuit(n, n)
circ.h(0)
for i in range(n-1):
    circ.cx(0, i+1)
circ.snapshot_expectation_value('hi', [[1, 'Z']], [0])

sim = qiskit.Aer.get_backend('qasm_simulator')
res = qiskit.execute(circ, sim, shots=100).result()

print(res)
```

This works fine for `n<=19` (expectation value is 0). Starting from `n=20`, execution fails with the error that's in the issue's title.

### What is the expected behavior?

Work always

**Comment by yaelbh** [comment]
Related to the line:
```
fusion_threshold (int): Threshold that number of qubits must be greater than or equal to enable fusion optimization [Default: 20]
```

**Comment by yaelbh** [comment]
I guess that for now disabling fusion optimization will do the job

**Comment by yaelbh** [comment]
Note that problems occur also for the MPS simulator starting from 20 qubits. For the MPS simulator, there is no error (for n>=20), only strange behavior and incorrect results.

**Comment by chriseclectic** [comment]
It looks like there are a couple of bugs tucked in here: The first is this "fusion" op should actually be a "unitary" op. The need for a separate fusion operation was removed a while ago and for all purposes this instruction is an arbitrary "unitary" gate.

The second one is that PR #579 enabled fusion automatically when number of qubits was >20, but fusion should only be happening if the output gates are in the supported gate-set so this looks like a bug in the case of the stabilizer simulation which doesn't support arbitrary unitary instructions. As you say you can get around it by explicitly disabling fusion.

The third is a bug in the MPS simulator. The MPS simulator says it supports unitary instructions, but after looking at the code it only supports one and 2 qubit unitaries and just ignores the instruction if its larger than that which would be why you are seeing incorrect results.

**Comment by yaelbh** [comment]
There is an additional aspect with regard to the MPS simulator. It is much slower for arbitrary unitaries. If the fusion optimization replaces standard gates by unitary matrices, then this is not a good heuristic for the MPS simulator, even if it fully and correctly support these matrices.

**Comment by atilag** [comment]
> but fusion should only be happening if the output gates are in the supported gate-set so this looks like a bug in the case of the stabilizer simulation which doesn't support arbitrary unitary instructions

This seems to be a good candidate for a test.

**Comment by ajavadia** [comment]
This is also a problem for extended stabilizer simulator. The tutorial on that one does not run currently. There should be tests to catch these kinds of regressions.
