### ISSUE TITLE
wrong job status

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-aer#622]
A job that does not succeed still reports `job.status() == JobStatus.DONE`.

```python
from qiskit import *
from qiskit.providers.aer import QasmSimulator

circ = QuantumCircuit(40, 40)
circ.h(range(40))
circ.measure(range(40), range(40))
qobj = assemble(circ, backend=QasmSimulator(), shots=1)
job = QasmSimulator().run(qobj, backend_options={
    'method': 'statevector'
})
result = job.result()
```

job.status() says DONE, however the result actually shows there was error:
```
Result(backend_name='qasm_simulator', backend_version='0.4.0', date=datetime.datetime(2020, 2, 20, 16, 54, 52, 984208), header=Obj(backend_name='qasm_simulator', backend_version='0.4.0'), job_id='5527f67a-f872-439d-b5da-56f113e9a25c', metadata={'max_memory_mb': 16081, 'omp_enabled': True, 'parallel_experiments': 1, 'time_taken': 0.00044281}, qobj_id='fafa2c1f-fa6d-4641-8f29-00113712b954', results=[ExperimentResult(data=ExperimentResultData(), meas_level=<MeasLevel.CLASSIFIED: 2>, seed_simulator=139764221439088, shots=139764221439936, status='ERROR: AER::Base::Controller: State statevector has insufficient memory to run the circuit circuit0', success=False, time_taken=0.0)], status='PARTIAL COMPLETED', success=False, time_taken=0.05461716651916504)
```

**Comment by chriseclectic** [comment]
Currently the job object only checks that the returned `Result` object is schema valid (and doesn't check if the result itself was a success or not), in that sense the job is "done". 

The error messages are then contained in the result object. We used to have it aggressively raise a logger error if any experiment failed, but to match the IBMQ provider API we changed it that those error messages are now only obtained if you call `result.data` or `get_counts` etc. for an experiment that failed. In that case an exception is raised containing the error message for that experiment.

There is a bug with the Result object that `result.status` returns `PARTIAL COMPLETED` when in fact all the circuits failed, it should only do that if at least 1 experiment is successful, and at least one is failed.
