### ISSUE TITLE
GPU support fails on google colab

### ISSUE THREAD

**Issue by kareem1925** [Qiskit/qiskit-aer#624]
### Informations

- **Qiskit Aer version**: 0.4.0
- **Python version**: 3.6.9
- **Operating system**: Linux- google colab

### What is the current behavior?
simulation of a basic circuit like applying a Hadamard fails when I choose "statevector_gpu"

### Steps to reproduce the problem
in this colab notebook, you will find the required steps. less than 10 cells
https://colab.research.google.com/drive/10OOzdV9GKeehrbr2wRaEqfa1rBFE7PkZ

### What is the expected behavior?

I expect the counts of an entangled state with no errors raised

### Suggested solutions

I think there is something in colab's environment or maybe I should git clone the repo itself. I don't know :/

**Comment by chriseclectic** [comment]
@kareem1925 it looks like you didn't install the `qiskit-aer-gpu` package

**Comment by kareem1925** [comment]
So how should i install the packages in order?

**Comment by chriseclectic** [comment]
You need to pip install `qiskit-aer-gpu` after `pip install qiskit` since it will override the (non-gpu) qiskit-aer included in the metapackage.

**Comment by kareem1925** [comment]
hello sir, I've done exactly what you said but the same error occurs 
here's the updated [colab notebook](https://colab.research.google.com/drive/10OOzdV9GKeehrbr2wRaEqfa1rBFE7PkZ)

**Comment by chriseclectic** [comment]
Running GPU on colab is not something we have tested or attempted to support. I am not familiar with what sort of system setup colab runs on with regards to GPUs, but that error message looks like it has wrong version of CUDA.

**Comment by atilag** [comment]
Seems like the GPU driver installed by default in Colab underlying system is not compatible with our CUDA version (10.2). This is the only tested version we support but it doesn't mean that other older versions won't work it is just that we haven't tested there. 
Unfortunately there's nothing we can do at the moment.
Thanks for reporting @kareem1925

**Comment by shreychowdhary** [comment]
I was able to update google collab's CUDA version to 10.2, but I'm still getting the same error as @kareem1925. [Notebook](https://colab.research.google.com/drive/1yjjYCs95PvXK1ZMfTZtIHRTsYW0qGkZE).

**Comment by Danimhn** [comment]
Has anyone found a fix or a workaround for this? Having the same issue
