### ISSUE TITLE
VQE produces an error sometimes with the MPS simulator

### ISSUE THREAD

**Issue by AzizNgoueya** [Qiskit/qiskit-aer#663]
### Informations

- **Qiskit Aer version**: 0.4.1
- **Python version**: 3.8.1
- **Operating system**: Windows

### What is the current behavior?
 On a windows system, i use VQE algorithm to resolve the tsp problem(25 qubits)  and it appears that i get sometimes this error: `qiskit.exceptions.QiskitError: 'Data for experiment "circuit3" could not be found.'` when an optimal parameter or the maximum number of iterations is reached. It's not occurs on a Linux machine.

### Steps to reproduce the problem
`quantum_instance = QuantumInstance(backend=Aer.get_backend('qasm_simulator'), shots=1,
                                   backend_options={'method': 'matrix_product_state', 'fusion_enable': False})`

I can share the full code if needed.

### Suggested solutions
I investigated into the code and it looks like the execution of the varational form for optimal parameters found fails with the fusion_enable:False . The job has the `status='ERROR: error: wrong SVD calc: A != USV*.`

According to @yaelbh and @merav-aharoni, Windows does not support 128 bit FP, which is needed for the SVD, and this may cause the problem.

**Comment by nonhermitian** [comment]
Why do we need extended precision fp numbers here?

**Comment by merav-aharoni** [comment]
During the SVD algorithm, we sometimes reach a result of 0 when subtracting two numbers that are very close in value in double precision. This should not occur. If this happens, I convert the calculation to extended precision, and then the computation can continue.
Since Windows does not support extended precision, we need to find some workaround for larger precision computation on Windows.

**Comment by nonhermitian** [comment]
Is this a custom svd?  Typically this means the algorithm in question needs to be tweaked to avoid this.

**Comment by merav-aharoni** [comment]
We developed it here. It is based on an implementation by P. A. Businger and G. H. Golub. At first it only used double precision, but we sometimes had segmentation faults because of this problem, and this was the solution we reached.

**Comment by woodsp-ibm** [comment]
Are you using Aqua from stable for this? Under some conditions we saw recently Aer providing back a partial completion. Before Aqua expected success or fail period. Partial completion looked like success and so it went to get circuit results and would fail like you show i.e. `qiskit.exceptions.QiskitError: 'Data for experiment "circuit3" could not be found.` The partial completion status is now recognized and a error is raised with information from the failure i the partial completion. This change is just in the master branch. So while it would not change the overall outcome, as Aqua algorithms do not work with partial completion, the exception may have been more meaningful dependent on what information Aer put in the failed cct(s).

**Comment by yaelbh** [comment]
In the master branch, I expect the exception would say "ERROR: error: wrong SVD calc: A != USV*", which is the result of @AzizNgoueya's investigation of the error.

**Comment by merav-aharoni** [comment]
@AzizNgouey , can you please provide the full test-case? I am currently working on this bug and it will help if I can test on something.
