### ISSUE TITLE
Qasm simulator gives wrong result on measure when given a permutation

### ISSUE THREAD

**Issue by merav-aharoni** [Qiskit/qiskit-aer#664]
### Informations

- **Qiskit Aer version**: master
- **Python version**:
- **Operating system**: Linux

### What is the current behavior?
measure(q, c) always gives the same result, regardless of the order of q and c.

### Steps to reproduce the problem
```
from qiskit import *
from qiskit.providers.aer import *
n = 3
q = QuantumRegister(n)
c = ClassicalRegister(n)
qc = QuantumCircuit(q, c, name="circuit")
qc.x(0)
qc.measure([1, 0, 2], [1, 0, 2])
BACKEND_OPTS_SV = {"method": "statevector"}
res_SV = execute([qc], QasmSimulator(), backend_options=BACKEND_OPTS_SV, shots=1).result()
print("counts = " + str(res_SV.get_counts()))
```
Result is:
```
counts = {'001': 1}
```

### What is the expected behavior?
I would expect the result to be:
```
counts = {'010': 1}
```
I get the same result when I change the measure line to:
```
qc.measure([0, 1, 2], [0, 1, 2])
```
or any other permutation.
I have the same problem with the MPS simulation method. I didn't check the other methods.

**Comment by kdk** [comment]
I think the issue is in the arguments to the `measure` command. The first arg is a list of qubit indicies, and the second argument is a list of clbit indicies, that will be zipped together to generate the individual measure commands. e.g.

```
>>> qc = qk.QuantumCircuit(3,3)
>>> qc.x(0)
>>> qc.barrier()
>>> qc.measure([0,1,2],[0,1,2])
>>> print(qc)
        ┌───┐ ░ ┌─┐
q_0: |0>┤ X ├─░─┤M├──────
        └───┘ ░ └╥┘┌─┐
q_1: |0>──────░──╫─┤M├───
              ░  ║ └╥┘┌─┐
q_2: |0>──────░──╫──╫─┤M├
              ░  ║  ║ └╥┘
 c_0: 0 ═════════╩══╬══╬═
                    ║  ║
 c_1: 0 ════════════╩══╬═
                       ║
 c_2: 0 ═══════════════╩═
```
In your example, the order of the generated `measure`s will be different, but the qubit->clbit mapping for each will be the same ( still `q_0->c_0`, ...).
```
>>> qc = qk.QuantumCircuit(3,3)
>>> qc.x(0)
>>> qc.barrier()
>>> qc.measure([1,0,2],[1,0,2])
>>> print(qc)
        ┌───┐ ░    ┌─┐
q_0: |0>┤ X ├─░────┤M├───
        └───┘ ░ ┌─┐└╥┘
q_1: |0>──────░─┤M├─╫────
              ░ └╥┘ ║ ┌─┐
q_2: |0>──────░──╫──╫─┤M├
              ░  ║  ║ └╥┘
 c_0: 0 ═════════╬══╩══╬═
                 ║     ║
 c_1: 0 ═════════╩═════╬═
                       ║
 c_2: 0 ═══════════════╩═
```
To generate a permutation in the measure, you'd want something like:
```
>>> qc = qk.QuantumCircuit(3,3)
>>> qc.x(0)
>>> qc.barrier()
>>> qc.measure([1,0,2],[0,1,2])
>>> print(qc)
        ┌───┐ ░    ┌─┐
q_0: |0>┤ X ├─░────┤M├───
        └───┘ ░ ┌─┐└╥┘
q_1: |0>──────░─┤M├─╫────
              ░ └╥┘ ║ ┌─┐
q_2: |0>──────░──╫──╫─┤M├
              ░  ║  ║ └╥┘
 c_0: 0 ═════════╩══╬══╬═
                    ║  ║
 c_1: 0 ════════════╩══╬═
                       ║
 c_2: 0 ═══════════════╩═
```

**Comment by merav-aharoni** [comment]
I see. So I understand that this is the specification of what the behavior should be.

**Comment by chriseclectic** [comment]
Thanks for explaining @kdk
