### ISSUE TITLE
Wrong result when using QasmSimulator with matrix_product_state method

### ISSUE THREAD

**Issue by EgrettaThula** [Qiskit/qiskit-aer#681]
### Informations

- **Qiskit Aer version**: 0.4.0
- **Python version**: 3.7.5
- **Operating system**: Windows

### What is the current behavior?
When running the sample code in [Advanced Tutorials](https://qiskit.org/documentation/tutorials/advanced/aer/7_matrix_product_state_method.html)
The result has to be
{'00000000000000000000000000000000000000000000000000': 496,
 '11111111111111111111111111111111111111111111111111': 528}

However, I got
{'00000000000000000000000000000000000000000000000000': 513,
 '00000000000000000000000000000000000000000000000011': 511}

### Steps to reproduce the problem
Just use the sample code as it is.

**Comment by yaelbh** [comment]
Hi, can you please check that the lines
```
num_qubits = 50
qr = QuantumRegister(num_qubits)
cr = ClassicalRegister(num_qubits)
```
at the beginning of [6] were copied correctly?

**Comment by EgrettaThula** [comment]
Checked!

I just noted that the issue start happening when num_qubits >= 20
When num_qubits < 20, the circuit works as expected.

**Comment by merav-aharoni** [comment]
I suspect this has to do with a bug related to the "fusion" optimization that does not work well with MPS. Please try the following:
```
backend_options={'method': 'matrix_product_state', 'fusion_enable':False}
```

**Comment by EgrettaThula** [comment]
@merav-aharoni 

Indeed, disabling fusion optimization fixes the issue.

Thank you.

**Comment by chriseclectic** [comment]
@merav-aharoni Should we patch the controller to disable fusion when using the MPS simulator?
