### ISSUE TITLE
missing gate in stablizer backend

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-aer#700]
### What is the current behavior?
'PARTIAL COMPLETED ,  ERROR: Circuit contains invalid instructions ( invalid gate instructions: {cy} for stabilizer method)'

### Steps to reproduce the problem
run a circuit with cy

### What is the expected behavior?
work 

### Suggested solutions
add to stablizer backend

**Comment by chriseclectic** [comment]
Closed by #701
