### ISSUE TITLE
QASM simulation of circuit with noise model takes very long time to run.

### ISSUE THREAD

**Issue by a-rawlinson** [Qiskit/qiskit-aer#710]
### Informations

- **Qiskit Aer version**: 0.5.0
- **Python version**: 3.6.5
- **Operating system**: Darwin

### What is the current behavior?
The code block below takes ~100 seconds to run using qiskit 0.18.0 and uses an excessive amount of CPU time (~600% on MacBook Pro). Running same code on qiskit 0.17.0 only took about ~0.1 seconds. 

### Steps to reproduce the problem
The following code produces the issue. The problem seems to arise when the noise_model and initial_layout options are used in the execute command.

```
from qiskit import Aer, IBMQ, execute
from qiskit.providers.aer.noise import NoiseModel
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.quantum_info.operators import Operator
import numpy as np
import time

# Choose ibmq_almaden
IBMQ.load_account()
device_name='ibmq_almaden'
providerDeployed=IBMQ.get_provider(group='deployed')

# Get device properties, coupling map, noise model and basis gates.
device=providerDeployed.get_backend(device_name)
properties = device.properties()
coupling_map = device.configuration().coupling_map
noise_model = NoiseModel.from_backend(device)
basis_gates = noise_model.basis_gates

# Use a simulator.
simulator = Aer.get_backend('qasm_simulator')

# ibmq_almaden has 20 qubits. Let's choose the first(0) and 
# last(19) qubits in the device.
qubitA=0
qubitB=19

# A matrix operator acts on the 2 qubits
theOperator=np.array([
    [0.82533561, 0., 0., 0.56464247j],
    [0., 0.82533561, 0.56464247j, 0.],
    [0., 0.56464247j,0.82533561, 0.],
    [0.56464247j, 0.,0., 0.82533561]])

q = QuantumRegister(2,'qr')
c = ClassicalRegister(2,'cr')
ckt = QuantumCircuit(q,c)
ckt.append(Operator(theOperator), [q[0], q[1]])
ckt.measure(q, c)

start_time = time.time()
expResults = execute(ckt, simulator,
                  coupling_map=coupling_map,
                  noise_model=noise_model,
                  basis_gates=basis_gates,
                  initial_layout = {q[0]:qubitA, q[1]:qubitB}).result().get_counts()

print('Time taken = ',time.time() - start_time,'  Result = ',expResults)
```

### What is the expected behavior?
Time taken for the code to run would be similar to that using qiskit 0.17.0.

### Suggested solutions
Not clear to me at the moment.

**Comment by vvilpas** [comment]
Hi @a-rawlinson! This bug is already solved (see https://github.com/Qiskit/qiskit-aer/pull/693) in AER release 0.5.1 (https://github.com/Qiskit/qiskit-aer/releases/tag/0.5.1) , which is already available. Please, update your AER version:
```
pip install -U qiskit-aer
```
Thanks for letting us know!

**Comment by a-rawlinson** [comment]
Thanks @vvilpas. The update to qiskit 0.18.3 resolved the issue.
