### ISSUE TITLE
Optimize statevector Pauli expectation value and sequences of Pauli gates

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#715]
In `State<statevec_t>::snapshot_pauli_expval`, denote by `k` if the number of qubits in `pauli` whose Pauli is different from `I`. Then there are `k` passes on the `2^n` basis states. This can be reduced to only two passes:
- One pass for all the `X`'s, switching amplitudes between pairs of basis gates.
- One pass for all the `Z`'s, flipping the sign of amplitudes of basis states with odd parity in the corresponding qubits.

This can help chemistry VQE simulation, where there are thousands of Pauli terms, and some of the terms have many qubits (i.e., large `k`).

**Comment by yaelbh** [comment]
Can probably be done in a single apply matrix loop, based on an algorithm to construct the Pauli matrix from a string in Terra's `PauliTable` class.

**Comment by yaelbh** [comment]
It is possible to first write a multi-qubit Pauli gate, and use it in the Pauli expectation value.

**Comment by yaelbh** [comment]
Denote: n - the number of qubits, m - the total number of all qubits participating in at least one Pauli term, k - number of Pauli terms. Once we evaluate the complexity of #471, we will be able to identify cases where #471 is more efficient than the solution suggested here, which takes k apply matrix loops, each costs 2^n.

**Comment by chriseclectic** [comment]
I implemented an optimized method for all-qubit expectation values is in #737 (this is the method based on the sympletic representation in the Pauli table class)

**Comment by yaelbh** [comment]
Expectation value is fine since #737. However instead of closing the issue I'm renaming it to apply to all cases where a circuit contains a sequence of Pauli gates.

**Comment by yaelbh** [comment]
There will be a new instruction of a set of Paulis (rather than an automatic detection in the circuit). As long as Terra doesn't support it, we will create our own instruction and add it to the set of basis gates when transpiling.

**Comment by yaelbh** [comment]
Done in #919 and #1012
