### ISSUE TITLE
Add simulator support for new Pulse instructions

### ISSUE THREAD

**Issue by DanPuzzuoli** [Qiskit/qiskit-aer#736]
### What is the expected behavior?

Add support for new Pulse instructions: 

`Delay`, `SetPhase`, `ShiftPhase`, `SetFrequency`, `ShiftFrequency`

### Implementation

My initial thought is that `Delay`, `SetPhase`, and `ShiftPhase` will all naturally fit into the current interpretation scheme that the simulator uses for pulses in the `PulseQObj`. E.g. the deprecated `FrameChange` instruction was already supported in the PulseQobj interpretations, so updating that portion may be all that is necessary for the phase instructions.

`SetFrequency` and `ShiftFrequency` on the other hand will require a change in the way frequencies are dealt with; currently frequency is a static property of the "differential equation model", and there is currently no mechanism/process for updating this model mid-simulation. Some options:
1. I think the simplest option in terms of immediate implementation is the promotion of channel frequency from a constant to a time-dependent function, which can be constructed similarly to how the signals over channels are done now. The DE RHS function can then be updated to call the frequency function.
2. Add the ability to update/modify the "model" mid-simulation. This will amount to having types of instructions that induce an update of the `PulseSimDescription` object, in which case the ODE solver will also need to be updated with the new information.

Option 2 is more involved but more in-line with future plans - a solver's behaviour can make use of the carrier frequency (entering/exiting frames automatically, making RWA, etc) - but if the frequency is also treated as an arbitrary time-dependent function this won't be possible. Also, the ability to do such updates is necessary for future extensions involving more complicated simulation flows (e.g. handling control flow, performing measurements mid-experiment, etc).

**Comment by DanPuzzuoli** [comment]
As a first step we can:
1. Add interpretation/support for `Delay`, `SetPhase`, and `ShiftPhase`.
    - Remove/replace internal `FrameChange` interpretation.
2. Add warnings for `SetFrequency` and `ShiftFrequency` commands.

**Comment by eggerdj** [comment]
Perhaps we can easily implement `SetFrequency` and `ShiftFrequency` by multiplying the pulse envelope with a modulation.

**Comment by DanPuzzuoli** [comment]
Not being actively developed.

**Comment by amirebrahimi** [comment]
I'm getting an error when trying to make use of SetFrequency or ShiftFrequency on a DriveChannel of FakeArmonk:
```
~/miniconda3/envs/qiskit/lib/python3.9/site-packages/qiskit/providers/aer/pulse/controllers/digest_pulse_qobj.py in experiment_to_structs(experiment, ham_chans, pulse_inds, pulse_to_int, dt, qubit_list)
    356             else:
    357                 start = inst['t0'] * dt
--> 358                 pulse_int = pulse_to_int[inst['name']]
    359                 pulse_width = (pulse_inds[pulse_int + 1] - pulse_inds[pulse_int]) * dt
    360                 stop = start + pulse_width
KeyError: 'shiftf'
```
Debugging it seems to uncover that the instruction doesn't end up in the pulse_library of the qobj.to_dict()['config'].

It seems related to the above. @DanPuzzuoli - when you say this is no longer being actively being developed do you mean the PulseSimulator in general? This feature only?  Should I view FakeBackends / PulseSimulator as being deprecated? I'm a little confused because I see that `SetPhase` and `ShiftPhase` were implemented. Additionally, setting `schedule_los` on assemble works for PulseSimulator, so wondering how that is being done.
