### ISSUE TITLE
Aer doesn't parallelise over shots unless there are gates after measurement on qubits

### ISSUE THREAD

**Issue by abhishekagarwal2301** [Qiskit/qiskit-aer#739]
### Informations

- **Qiskit Aer version**: 0.5.0
- **Python version**: 3.7.6
- **Operating system**: Linux

### What is the current behavior?
If the circuit doesn't have rotation gates on a qubit after it has been measured, then the qiskit **does not** parallelise over shots even when the appropriate backend options are set. However, if we add a rotation gate after a qubit has been measured, then qiskit **does** parallelise over shots.

### Steps to reproduce the problem

```import timeit

from qiskit import execute, Aer, QuantumCircuit

qc = QuantumCircuit(2, 1)
qc.rx(-0.3, 0)
qc.rz(1, 1)
qc.measure(0, 0)

reps = 16
shots = 1000000
backend = Aer.get_backend('qasm_simulator')

parallel_shots_options = {'max_parallel_threads': 0, 'max_parallel_experiments': 1, 'max_parallel_shots': 0}
parallel_experiments_options = {'max_parallel_threads': 0, 'max_parallel_experiments': 0, 'max_parallel_shots': 1}
serial_options = {'max_parallel_threads': 1, 'max_parallel_experiments': 1, 'max_parallel_shots': 1}

st = timeit.default_timer()
execute([qc] * reps, backend, shots=shots, backend_options=parallel_shots_options).result()
print(f'Parallel shots with no operation after measurement: {timeit.default_timer() - st}', flush=True)

st = timeit.default_timer()
execute([qc] * reps, backend, shots=shots, backend_options=parallel_experiments_options).result()
print(f'Parallel experiments with no operation after measurement: {timeit.default_timer() - st}', flush=True)

st = timeit.default_timer()
execute([qc] * reps, backend, shots=shots, backend_options=serial_options).result()
print(f'Non-parallel with no operation after measurement: {timeit.default_timer() - st}', flush=True)

# Add operation after measurement
qc.rx(0.1, 0)

st = timeit.default_timer()
execute([qc] * reps, backend, shots=shots, backend_options=parallel_shots_options).result()
print(f'Parallel shots with rx operation after measurement: {timeit.default_timer() - st}', flush=True)

st = timeit.default_timer()
execute([qc] * reps, backend, shots=shots, backend_options=parallel_experiments_options).result()
print(f'Parallel experiments with rx operation after measurement: {timeit.default_timer() - st}', flush=True)

st = timeit.default_timer()
execute([qc] * reps, backend, shots=shots, backend_options=serial_options).result()
print(f'Non-parallel with rx operation after measurement: {timeit.default_timer() - st}', flush=True)

""" Result when run on a 16-core linux machine:
Parallel shots with no operation after measurement: 24.355489145964384
Parallel experiments with no operation after measurement: 4.188818443566561
Non-parallel with no operation after measurement: 24.38543907739222
Parallel shots with rx operation after measurement: 11.380083112046123
Parallel experiments with rx operation after measurement: 11.414414478465915
Non-parallel with rx operation after measurement: 86.62012434750795"""

```

### What is the expected behavior?
Adding a rotation after measurement shouldn't affect whether parallelisation is used.

**Comment by yaelbh** [comment]
This is not a bug. Aer has an optimization to save run time: when possible (measurements at the end of the circuit, no noise) it runs only a single shot. In this shot, it calculates the state vector right before the measurements begin. Then it creates the counts according to the induced probability distribution and the number of shots.

**Comment by abhishekagarwal2301** [comment]
Ah, I see! Thanks for clarifying that.

**Comment by bjader** [comment]
Hi @yaelbh would this optimisation be reconsidered then? Our results show that forcing the parallel behaviour is faster than the default behaviour you described of using the statevector. 
```
Parallel shots with no operation after measurement: 24.355489145964384
Parallel shots with rx operation after measurement: 11.380083112046123
```

The first run is a smaller circuit which falls back to the optimisation you described. The second circuit is larger, yet runs in less time when we force the parallelisation.

**Comment by yaelbh** [comment]
@chriseclectic do you have an idea what can cause these results? Can we reproduce the same results?

**Comment by chriseclectic** [comment]
This seems to make sense. This is a very small example in terms of qubit numbers and the parallel shots is roughly 8x faster. Sampling of such small circuits is done single threaded, so if you forced shot parallelization of sampling it should see a similar speed up. eg:

```python
qc = QuantumCircuit(1, 1)
qc.u3(0.5, 0.2, 0.3, 0)
qc.measure([0], [0])

qobj = assemble(qc, shots=100000)
sim = Aer.get_backend('qasm_simulator')

# Single threaded
%timeit sim.run(qobj).result()
92.6 ms ± 1.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

# Forcing parallel shots
%timeit sim.run(qobj, backend_options={'_parallel_shots': 4}).result()
35.4 ms ± 1.02 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

From a practical point of view this is an edge case that I don't think is particularly worth optimizing. If you are doing enough shots of an ideal circuit for this to be an issue you should probably just compute the exact measurement probabilities using `qiskit.quantum_info.Statevector.from_instruction(circuit).probabilities_dict()`

**Comment by bjader** [comment]
@chriseclectic, the key point of this ticket is to say that we are not able to reproduce the behaviour you are demonstrating. We find that unless there are operations after the measurement, we have no control of the multithreading behaviour. This is best demonstrated by the results

```
Parallel shots with no operation after measurement: 24.355489145964384
Parallel shots with rx operation after measurement: 11.380083112046123
```

despite the fact that we have set `'max_parallel_shots': 0` for **both** of those runs. As such, I am surprised that your example shows an improvement in runtime. One notable difference between our examples is your use of `_parallel_shots` instead of `max_parallel_shots`, which we use with guidance from the qasm simulator docstring.

Could that be responsible?

**Comment by bjader** [comment]
I can confirm that replacing `_parallel_shots` with `max_parallel_shots` in your code @chriseclectic leads to no speedup:

```python
qc = QuantumCircuit(1, 1)
qc.u3(0.5, 0.2, 0.3, 0)
qc.measure([0], [0])

qobj = assemble(qc, shots=100000)
sim = Aer.get_backend('qasm_simulator')

# Single threaded
%timeit sim.run(qobj).result()
151 ms ± 1.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

# Forcing parallel shots
%timeit sim.run(qobj, backend_options={'max_parallel_shots': 4}).result()
151 ms ± 1.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by bjader** [comment]
What confuses me is how the `max_parallel_shots` flag does nothing by default - **but** if you do an operation after the measurement then it is used?

**Comment by chriseclectic** [comment]
@bjader "max_parallel_shots" is used to set a maximum allowed value, but that doesn't mean that many threads will be used. Several conditions are checked when choosing how to assign threads for parallelization with the default behavior is chosen to optimize performance for typical usage.  The `"_parallel_shots"` is a debug method for forcing the number of threads to a specific value.

As @yaelbh mentioned above the automatic default of any noiseless circuit where all measurements can be pushed to the end of the circuit is to only simulate a single shot, and sample all measurement outcomes from the final state vector. Hence in this case there will never be any parallel shots unless you manually override that behavior as I did in my code example. If you add an instruction after measurement this optimization is not possible so it simulates the full shot every shot independently. In this case the max_parallel_shots value is taken into account. Parallel shots are intended for noisy simulation where you need to simulate the full circuit for every shot to average over realizations of the noise.
