### ISSUE TITLE
Add option to build without conan and document it

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-aer#757]
Conan doesn't support every build platform out there. I encountered this trying to get aer to build with emscripten to get aer webassembly (I was able to build wasm binaries in the past by setting the llvm target but was missing the glue code that emscripten provides so it wasn't useful) I imagine there are other use cases or platforms that it doesn't work on. Also the requirement for an external internet connection could be a deal break for some use cases. It would be good if we had an option available to be able to build aer without needing conan. We don't and shouldn't vendor dependencies in that case it'll be on the user to ensure they have all the libraries and headers needed if they're not using conan.

**Comment by atilag** [comment]
We already have a way to skip Conan for OpenBLAS dependency, we could go this way in order to skip other dependencies so the user can choose others.
