### ISSUE TITLE
Redesign how backend configuration is loaded

### ISSUE THREAD

**Issue by atilag** [Qiskit/qiskit-aer#77]
### What is the expected behavior?
Since we have to pass an important configuration parameter (runtime path) to the MacOS simulator, I have noticed that we have to explicitly call the `controller::set_config( qobj["config"] )` function before calling `execute`. The thing is that `execute` already takes the `qobj` (so the `qobj["config"]`) as a parameter, so there's no virtual need for calling  `controller::set_config()` explicitly.
We need to redesign how configuration is loaded in the simulators, having simplicity for the user in mind (he should not call any function if it's not strictly necessary).

**Comment by chriseclectic** [comment]
Closing since I think this was fixed in #287
