### ISSUE TITLE
pip installation fail with compilation

### ISSUE THREAD

**Issue by hhorii** [Qiskit/qiskit-aer#79]
### Informations

- **Qiskit Aer version**: 0.1.0
- **Python version**: 3.6
- **Operating system**: Ubuntu 16.04

### What is the current behavior?
`pip install qiskit-aer --no-binary :all:` does not install qiskit-aer.

### Steps to reproduce the problem
1. Install Python 3.6 and pip3
```
$ apt-get install software-properties-common -y
$ apt-get install python3.6 python3.6-dev wget -y
$ wget https://bootstrap.pypa.io/get-pip.py
$ python3.6 get-pip.py
```
2. Install the latest cmake.
```
wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4.tar.gz
cd cmake-3.13.4
./configure
make
make install
```
3. Install scikit-build, cmake, and cython modules.
```
pip3 install scikit-build -y
pip3 install cmake cython -y
```
4. Install qiskit
```
pip3 install qiskit
```
5. Re-install qiskit-aer without wheel files
```
pip3 uninstall qiskit-aer
pip3 install qiskit-aer --no-binary :all:
```
### What is the expected behavior?
qiskit-aer is installed correctly.

**Comment by hhorii** [comment]
I believe that this bug is critical for POWER users.

**Comment by atilag** [comment]
Ok, so with latest version of scikit-build (== 0.9) and not the latest version of pip ( <= 18 ), this should just work.
I have noticed though, there's a problem with scikit-build and pip 19, so I have filed a new issue accordingly:  https://github.com/scikit-build/scikit-build/issues/390. 
@hhorii try to build using these versions, and show me the output of this command if it doesn't build:
```
$ pip install pip==18
$ pip install --upgrade scikit-build
$ pip install -v qiskit-aer --no-binary :all: 2>&1 | tee install.log
```

**Comment by atilag** [comment]
Ok, this is  a bug of pip: https://github.com/pypa/pip/issues/6222
I'm will keep this issue open until a fix is released.
@hhorii in the meantime, I have to add something to the MANIFEST file so you can build on Power9.
PR is comming...
