### ISSUE TITLE
Get the state vector as a dictionary

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#790]
### What is the expected behavior?

We have a use case where we query the statevector, which in our case is a basis state. If we use `get_snapshot` or the statevector snapshot, we obtain a vector of length 2^n. We would like to have the option to represent the statevector as a dictionary that maps basis states to amplitudes, where zero amplitudes do not have to be present.

**Comment by yaelbh** [comment]
Create a new snapshot, which will probably call `vec2ket` of `utils.hpp`.

**Comment by chriseclectic** [comment]
This will be handled by the new `SaveStatevectorDict` instruction
