### ISSUE TITLE
Python wheels from PyPi don't work with Miniconda 3 and Python 3.7 on Windows.

### ISSUE THREAD

**Issue by atilag** [Qiskit/qiskit-aer#80]
### Informations

- **Qiskit Aer version**: pypi packages
- **Python version**: 3.7
- **Operating system**: Windows

### What is the current behavior?
Seems like the packages we are distributing via PyPi don't work as expected on Minicionda3 AND Python 3.7
Everything seems to be working with Python 3.5 and 3.6

### Steps to reproduce the problem
1. pip install qiskit
2. launch python interpreter in version 3.7
3. from qiskit.proivders.aer import Aer
- That should error complaining about not loading a DLL.

**Comment by nonhermitian** [comment]
This is quite important as the default conda Python version is 3.7.  It is also important given that we have tutorials coming up in countries that use Windows almost exclusively.

**Comment by atilag** [comment]
Ok, I have found the problem. As the Windows version we provide via Pypi is not statically linked, it requires some libraries to be previously installed in the system, and seems like Miniconda3 with Python 3.6 doesn't come with these libraries installed by default :(
In order to make it work, install `mkl` libraries:
```
conda install mkl
```
I'm closing this issue and creating a new one to address this issue in a proper way

**Comment by nonhermitian** [comment]
How does installing the mkl libs correct things when we are using openblas?

**Comment by atilag** [comment]
We are not using OpenBLAS with Windows builds on Aer 0.1.1. But we will on 0.2.0, and it won't require any other external BLAS .dll installed, as I'm linking it statically.

**Comment by nonhermitian** [comment]
Then why is `openblas.dll` in the wheel for Aer 0.1.1?

**Comment by atilag** [comment]
woops, seems like Python 3.5/3.6 builds are linked with openblas.dll but the Python 3.7 wheel is using `mkl`. That's definetely not intended.
For next release, all versions will be statically linked with openblas.
