### ISSUE TITLE
Use system-installed libs if they are present, don't download and rebuild them using conan

### ISSUE THREAD

**Issue by KOLANICH** [Qiskit/qiskit-aer#802]
# What is the expected behavior?

Libs installed via APT are not redownloaded and are not rebuilt. Also we need a mode when it never uses libs from conan, just instructs the user which system package manager packages he needs.

**Comment by vvilpas** [comment]
@KOLANICH Thanks for bringing up this issue. The default build system uses `conan` to ensure the use of the right version of the dependencies. It is not in our plans to mix this dependency management with user provided dependencies except maybe for some specific libraries. However, we're thinking on how to implement in the build system an option where `conan` is not used and the user is responsible of providing the necessary dependencies.
I'm closing this issue as there was a similar one already (#757)
