### ISSUE TITLE
Adding muparserx lib for armv6l (RPi 0/1)

### ISSUE THREAD

**Issue by JanLahmann** [Qiskit/qiskit-aer#815]
### Informations
- **Operating system**: Raspberry OS ("Buster")

### What is the current behavior?
Qiskit-aer compiles on ARM7 based Raspberry, but not on ARM6 based models (i.e. Pi Zero, Pi 1).
For ARM7, a specific version of libmuparserx has been added to aer with pull request #660 by @atilag .

### What is the expected behavior?
qiskit-aer should also install on ARM6 based Raspberry models.
Instructions how to install Qiskit on Raspberry are at http://ibm.biz/Qiskit-Raspberry-Medium (chapter 12).

### Suggested solutions
Provide an ARM6 version of libmuparserx similar to pull request #660 .

**Comment by vvilpas** [comment]
Hi @JanLahmann. Thanks for reporting this.
Right now, our dependencies are managed through the [Conan](https://docs.conan.io/en/latest/) package manager and we no longer distribute any dependency (no more libmuparserx distributed with aer).
So, to begin with, have you been able to build AER master on Raspberry ARM7 model, but not ARM6 one? Can you provide the error(s) you get when trying to compile aer?  
(It seems I need an account to check the instructions on medium, can I access it at any other place?)

**Comment by JanLahmann** [comment]
OK, I understand that there will be a significant change in the package and dependency management in the next release.
I think it's not necessary to fix ARM6 in the previous versions of Aer.
(In the above medium article, we'll provide a workaround for installing Qiskit on a Raspberry Pi Zero.)
