### ISSUE TITLE
Inconsistency detected by ld.so: dl-version.c after installing qiskit-aer-gpu

### ISSUE THREAD

**Issue by oneTimePad** [Qiskit/qiskit-aer#837]
### Informations
- **Qiskit AER version**:
qiskit-aer-gpu: 0.5.2
- **Operating system**:
Ubuntu 18.0.4.4 LTS 
- **GPU**:
Nvidia GTX 1080Ti
- **CUDA**:
11.0
- **GLIBC version**:
2.27
- **GCC version**: 
7.5.0

### What is the current behavior?
result of importing qiskit after install of qiskit aer gpu:
Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!

### Steps to reproduce the problem
python3 - m pip install qiskit-aer-gpu
python3 -c 'import qiskit'

### Suggested solutions
This goes away after uninstalling qiskit-aer-gpu and reinstalling qiskit-aer, but obviously reappears upon re-installation of the gpu version

**Result of running with LD_DEBUG=ALL** (please let me know if more logs are needed)
      9858:	file=libgomp-f7e03b3e.so.1.0.0 [0];  needed by /home/lie/.local/lib/python3.6/site-packages/qiskit/providers/aer/backends/controller_wrappers.cpython-36m-x86_64-linux-gnu.so [0]
      9858:	find library=libgomp-f7e03b3e.so.1.0.0 [0]; searching
      9858:	 search path=/home/lie/.local/lib/python3.6/site-packages/qiskit/providers/aer/backends/../../../.libs		(RPATH from file /home/lie/.local/lib/python3.6/site-packages/qiskit/providers/aer/backends/controller_wrappers.cpython-36m-x86_64-linux-gnu.so)
      9858:	  trying file=/home/lie/.local/lib/python3.6/site-packages/qiskit/providers/aer/backends/../../../.libs/libgomp-f7e03b3e.so.1.0.0
      9858:	
      9858:	file=libgomp-f7e03b3e.so.1.0.0 [0];  generating link map
      9858:	  dynamic: 0x00007f4b495bb060  base: 0x00007f4b493a7000   size: 0x0000000000216310
      9858:	    entry: 0x00007f4b493ab190  phdr: 0x00007f4b495bc000  phnum:                  8
      9858:	
      9858:	
      9858:	file=libgfortran-139be63a.so.3.0.0 [0];  needed by /home/lie/.local/lib/python3.6/site-packages/qiskit/providers/aer/backends/../../../.libs/libopenblas-r0-da994f36.3.3.so [0]
      9858:	find library=libgfortran-139be63a.so.3.0.0 [0]; searching
      9858:	 search path=/home/lie/.local/lib/python3.6/site-packages/qiskit/providers/aer/backends/../../../.libs		(RPATH from file /home/lie/.local/lib/python3.6/site-packages/qiskit/providers/aer/backends/controller_wrappers.cpython-36m-x86_64-linux-gnu.so)
      9858:	  trying file=/home/lie/.local/lib/python3.6/site-packages/qiskit/providers/aer/backends/../../../.libs/libgfortran-139be63a.so.3.0.0
      9858:	
      9858:	file=libgfortran-139be63a.so.3.0.0 [0];  generating link map
      9858:	  dynamic: 0x00007f4b4939db78  base: 0x00007f4b490ae000   size: 0x00000000002f8518
      9858:	    entry: 0x00007f4b490c1e30  phdr: 0x00007f4b493a0000  phnum:                  7
      9858:	
      9858:	checking for version `GLIBC_2.3' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /home/lie/.local/lib/python3.6/site-packages/qiskit/providers/aer/backends/controller_wrappers.cpython-36m-x86_64-linux-gnu.so [0]
      9858:	checking for version `GCC_3.0' in file /lib/x86_64-linux-gnu/libgcc_s.so.1 [0] required by file /home/lie/.local/lib/python3.6/site-packages/qiskit/providers/aer/backends/controller_wrappers.cpython-36m-x86_64-linux-gnu.so [0]
      9858:	checking for version `GCC_3.4' in file /lib/x86_64-linux-gnu/libgcc_s.so.1 [0] required by file /home/lie/.local/lib/python3.6/site-packages/qiskit/providers/aer/backends/controller_wrappers.cpython-36m-x86_64-linux-gnu.so [0]
**Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!**

**I did a lot of research and couldn't find anything to resolve this issue. Please let me know if it is better suited for "StackExchange".**

**Comment by alfa871212** [comment]
Same issue without better solution

**Comment by hhorii** [comment]
Sorry that we have not handle this issue timely. I hope the latest version (0.10.4) does not produce this issue. Please reopen this if a problem still remains.
