### ISSUE TITLE
Better docstring for how to use snapshot_* methods

### ISSUE THREAD

**Issue by refraction-ray** [Qiskit/qiskit-aer#839]
Currently the API reference/docstring for ``QuantumCircuit.snapshot_*`` methods look like this: https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.snapshot_expectation_value.html, which is the docstring from https://github.com/Qiskit/qiskit-aer/blob/98c6142c22418ed0ad4a86267215cadf4c74c8d1/qiskit/providers/aer/extensions/snapshot_expectation_value.py#L123-L137, the docstring is now under terra API reference in the documentation.

However these snapshot methods are not native to QuantumCircuit object in terra, instead they are registered on QuantumCircuit class at runtime when ``from qiskit.providers.aer.extensions.snapshot_expectation_value import *
``, this behavior is due to the runtime registration https://github.com/Qiskit/qiskit-aer/blob/98c6142c22418ed0ad4a86267215cadf4c74c8d1/qiskit/providers/aer/extensions/snapshot_expectation_value.py#L148

It may be confusing when the users try the following with AttributeError:

```python
from qiskit import QuantumCircuit
c = QuantumCircuit(2)
c.snapshot_expectation_value()
# AttributeError: 'QuantumCircuit' object has no attribute 'snapshot_expectation_value'
```

So my suggestion is adding one line to the relevant snapshot_* docstrings, which tells the user that to use this method, one should first  run ``from qiskit.providers.aer.extensions.snapshot_expectation_value import *`` to register the corresponding method on QuantumCircuit class.

**Comment by chriseclectic** [comment]
Closing since snapshots are being deprecated for new save instructions, and the new instructions include the suggestions from this issue.
