### ISSUE TITLE
README command does not work: "pip install qiskit-aer-gpu"

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-aer#841]
The README file suggests running:
```
pip install qiskit-aer-gpu
```
However, errors:
```
ERROR: Could not find a version that satisfies the requirement qiskit-aer-gpu (from versions: none)
ERROR: No matching distribution found for qiskit-aer-gpu
```

Maybe the README file is outdated?

**Comment by mtreinish** [comment]
Are you on linux? There are only builds available for linux: https://pypi.org/project/qiskit-aer-gpu/#files. If you're on linux then you can run pip verbose mode and it will tell you why it doesn't use the binaries, for example your pip version is too old and doesn't recognize manylinux2010, your distro is too old and isn't compatible with manylinux2010, non-x86_64 machine, etc.

**Comment by 1ucian0** [comment]
I was on a MacOS and I did not read the README carefully enough. Probably the issue should be renamed to "Emphasis that qiskit-aer-gpu is only available on x86_64 linux."
