### ISSUE TITLE
Modify the error message for wrong shot value in stimulator

### ISSUE THREAD

**Issue by anto-pv** [Qiskit/qiskit-aer#842]
### What is the expected behavior?
Can we make the error message for wrong shot value in simulator more user interactive.
since many of them unexpectedly input ...........
execute(citcuit_name,Aer.get_simulator(qasm_simulator),shots="1024")
................................................................................................
error message is like something not understandable for beginners
so if it is like.......................
shots shounld contain a int type ...........etc
it would be nice...

**Comment by siddharthdangwal** [comment]
I guess this is an issue relevant to qiskit-terra and not aer. This exception first occurs in qiskit.compiler.assemble which is part of terra.

**Comment by chriseclectic** [comment]
Closing since this is a terra issue
