### ISSUE TITLE
Migrate current deprecated CUDA build system to native language support in CMake

### ISSUE THREAD

**Issue by atilag** [Qiskit/qiskit-aer#843]
With the inclusion of SIMD in our codebase, we build parts of the code with SIMD support, and other parts without it.
There seems to be a bug in `FindCUDA.cmake` that doesn't allow us to build files with specific compiler flags, so we cannot set the SIMD flags for the parts of the code that supports it, we have to set these flags "globally" for the cmake target and this will conflict with systems running Aer with no SIMD support.

### What is the expected behavior?
The new way to build CUDA files in CMake allow us to set different flags to different source code files, so we should migrate our current CUDA build implementation to this new one.

**Comment by vvilpas** [comment]
Implemented in #859
