### ISSUE TITLE
Modify CONTRIBUTING.md (for Linux) to indicate that g++ must be installed before installing from requirements-dev.txt

### ISSUE THREAD

**Issue by aditya-giri** [Qiskit/qiskit-aer#845]
**requirements-dev.txt** includes the **cvxpy** package, which requires a C++ compiler. I was building Aer on WSL2 on my windows system and the `pip install -r requirements-dev.txt` failed to install cvxpy, because I was missing g++. 

I assume running `sudo apt install build-essential` will install g++ and mitigate this error, so maybe we could switch the order of commands and document that build-essential needs to be installed before installing the python packages?

**Comment by atilag** [comment]
Unfortunately, we cannot include all our dependencies requirements as our own requirements. 
IRCC `build-essentials` package on Ubuntu comes with a g++ version (depending on your distro it could be an older version or not).
Try installing it directly: `sudo apt-get install g++`
Anyway, `Aer` doesn't build `cvxpy` by iteself, I guess you are trying to install with `pip install .` , right?
I'd go to `cvxpy` documentation to see what other dependencies requires, and try install them.

**Comment by aditya-giri** [comment]
I see what you mean. But I believe asking Linux developers to install `build-essentials` first _before_ running `pip install -r requirements-dev.txt` will fix this issue. Sorry if I phrased it a little poorly in the issue description - I'm not saying we should include all the dependencies' requirements as our own, just that we could avoid this error by asking developers to install build-essentials before doing anything else.

**Comment by atilag** [comment]
Oh, ok, I see. We mention it but after `pip install -r requirements-dev.txt` instructions.
Makes sense.
I guess it's a matter of rearrange the texts.
