### ISSUE TITLE
Capture global phase

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-aer#847]
### What is the expected behavior?

Qiskit/qiskit-terra#4565 introduced global phase to the circuit. The quantum info operators already capture the phase, Aer (and BasicAer) currently do not. The Aer unitary and statevector simulators should ideally also include the global phase. After the Terra meeting the consensus was to add the phase information to the Qobj header to be able to do this.

Currently this leads to the quantum info operator producing different outputs as the simulators:
```python
>>> qc = QuantumCircuit(1)
>>> qc.rz(0.2, 0)
>>> Operator(qc)
Operator([[0.99500417-0.09983342j, 0.        +0.j        ],
          [0.        +0.j        , 0.99500417+0.09983342j]],
         input_dims=(2,), output_dims=(2,))
>>> execute(qc, Aer.get_backend('unitary_simulator')).result().get_unitary()
array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.98006658+0.19866933j]])
>>> execute(qc, BasicAer.get_backend('unitary_simulator')).result().get_unitary()
array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.98006658+0.19866933j]])
```
See also Qiskit/qiskit-terra#4805.

**Comment by mtreinish** [comment]
Since Qiskit/qiskit-terra#4822 merged terra is now sending the global phase in the qobj to backends. The global phase for the circuit has been added as a field in the experiment header for qasm qobj.
