### ISSUE TITLE
Aer backends do not have a coupling_map

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#87]
### Informations

- **Qiskit Aer version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
According to the spec "Qiskit Backend Specifications for OpenQASM and OpenPulse Experiments", all backends are required to have a `coupling_map` in their `backend.configuration()`.  The `Aer` backends do not.

**Comment by chriseclectic** [comment]
How do you specify an all-to-all coupling map for arbitrary number of qubits as per spec?

**Comment by nonhermitian** [comment]
Well, I believe that we upper bound the number of qubits based on the local memory.  So given that we call this number `n_qubits` it would be `[[i,j] for i in range(n_qubits) for j in range(n_qubits)]`
