### ISSUE TITLE
Farm embarrassingly-parallel simulation tasks to a cluster

### ISSUE THREAD

**Issue by levbishop** [Qiskit/qiskit-aer#874]
Many large simulation jobs have embarrassing parallelism (over shots and/or circuit instances) and could pick up a big speedup on an HPC cluster. We need some way to:

1. Break the task up into managable chunks (not too many that the job setup/teardown overhead becomes dominating)
2. Deal with cluster configuration issues: queuing system LSF vs SLURM vs PBS etc. Shared NSF home directory vs other work-distribution methods, etc. Authentication, resource allocation and quotas.
3. Wait for the jobs to complete while providing progress feedback and depending on the reliability of the underlying queuing system maybe providing a reliability layer
4. Reassemble the partial results as though it were executed as one task
5. Handle RNG seeding to ensure the same level of reproducability as the underlying simulation method.

It seems to me that most self-contained way to implement this is as a new aer provider.

For point 2, I think that [dask-distributed](https://docs.dask.org/en/latest/setup/single-distributed.html) is potentially a great option, since it contains [dask-jobqueue](https://jobqueue.dask.org/) who wraps up all the big cluster queueing systems: LSF, PBS, Slurm, HTCondor, Moab, SGE, OAR giving jupyter widgets to monitor and with some well-thought-out example configurations and workflows. In addition there are components that provide the same interface via mpirun, an informal cluster of ssh-able machines, DRMAA-compliant resource managers, kubernetes-based cloud clusters, YARN/Hadoop cloud providers etc. You get a nice API that extends `concurrent.futures`. It can implement the same API locally (ie without a cluster) for testing, CI, etc. They've put some effort into serialize/deserialize that goes beyond pickle. It can do some forms of load scaling and such. And it's part of the [dask project](https://docs.dask.org/en/latest/) which is large, modern and very active. I guess we point users to the dask documentation for them to set up a `dask.Cluster()` instance which they can pass to our new provider.

**Comment by chriseclectic** [comment]
Dask looks like a really nice option for doing this

**Comment by woodsp-ibm** [comment]
Has there been any progress on this with regards to having such a capability in Aer?

**Comment by levbishop** [comment]
@woodsp-ibm see #1084 which is intended for next release

**Comment by chriseclectic** [comment]
Dask executor support added in 0.9.0
