### ISSUE TITLE
Poetry cannot resolve dependency from Aer 0.6.0

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit-aer#880]
### Informations

- **Qiskit Aer version**:
0.6.0 and 0.6.1
- **Python version**:
3.8.5
- **Operating system**:
macOS 10.15.6

### Steps to reproduce the problem

1. Install `poetry` (https://github.com/python-poetry/poetry)
2. Initialize poetry
3. `poetry add qiskit-aer==0.6.x`

### What is the expected behavior?

Poetry should install required libraries (e.g. numpy, scipy, pybind11, qiskit-terra, cython...
But only qiskit-aer is installed.

### Suggested solutions

Qiskit Aer 0.5.2 can resolve the dependency. (`poetry add qiskit-aer==0.5.2` installs required libraries.)
`pipenv` can also resolve the dependency for Qiskit Aer 0.6.x.
This may be poetry's or pypi's issue.

**Comment by mtreinish** [comment]
Hmm, well the install requirements are set in 0.6.1 the same as in previous releases: https://github.com/Qiskit/qiskit-aer/blob/0.6.1/setup.py#L101 we did change how that list `requirements` is built to be slightly different than in 0.5.x but it shouldn't result in any change like this https://github.com/Qiskit/qiskit-aer/blob/0.6.1/setup.py#L35-L53

I also checked the package metadata by downloading the wheel and looking at the https://files.pythonhosted.org/packages/bc/80/8bc3aa424ba813a54e667cb5b01bda6c6f0e30378ab1c9a6b3bce4185dc8/qiskit_aer-0.6.1-cp38-cp38-macosx_10_9_x86_64.whl unzipping it and looking at `qiskit_aer-0.6.1.dist-info/METADATA` lists the install requirements correctly as:

```
Requires-Dist: cython (>=0.27.1)
Requires-Dist: pybind11 (>=2.4)
Requires-Dist: qiskit-terra (>=0.12.0)
Requires-Dist: numpy (<1.19.0,>=1.16.3) ; python_version < "3.6"
Requires-Dist: scipy (<1.5.0,>=1.0) ; python_version < "3.6"
Requires-Dist: numpy (>=1.16.3) ; python_version > "3.5"
Requires-Dist: scipy (>=1.0) ; python_version > "3.5"
```
(https://www.python.org/dev/peps/pep-0491/#the-dist-info-directory and
https://www.python.org/dev/peps/pep-0345/#requires-dist-multiple-use are the specs around this)

If this isn't working how does poetry parse the dependencies for a package?

**Comment by ikkoham** [comment]
I think this is closable because the PR is merged in Poetry.
If needed, please reopen.
