### ISSUE TITLE
Possible Typos In the Section of Simulators

### ISSUE THREAD

**Issue by cyx617** [Qiskit/qiskit-aer#883]
**Describe the issue**

In the subsection **setting a custom initial unitary** of  [this tutorial page ](https://qiskit.org/documentation/tutorials/simulators/1_aer_provider.html), there seems to be two typos regarding with matrix multiplication, as shown in the snapshot below
![image](https://user-images.githubusercontent.com/69285126/90104370-bfaeba00-dd76-11ea-8223-495096d2eb3d.png)
I think it would be better to replace the notation '.' with the centered dot.

**Describe what you expect to see**

![image](https://user-images.githubusercontent.com/69285126/90105692-e968e080-dd78-11ea-95f4-807d11f0b1ba.png)

**Comment by TanveshT** [comment]
@cyx617 This piece of content is under the qiskit-tutorials package so I have left an Open PR over there.

**Comment by cyx617** [comment]
@TanveshT Thanks for opening a PR for this issue. I actually opened a [PR](https://github.com/Qiskit/qiskit-tutorials/pull/1029) regarding this issue a few days ago under the branch of qiskit-tutorials but there is some problem with it and I am about to open a new one. (Sorry for forgetting to close this issue) It seems like I don't need to open a duplicate PR now as yours look perfect  :blush:

**Comment by TanveshT** [comment]
Hey, @cyx617 Can you please keep the issue open until the PR is merged. Otherwise, it looks like the issue has been addressed. I am soon going to request someone with write permissions to repo to merge the PR.

**Comment by TanveshT** [comment]
@cyx617 Can you close this issue? I forgot to remind you that the PR got merged.

**Comment by cyx617** [comment]
@TanveshT Sure. Thanks!
