### ISSUE TITLE
Suspect of performance degradation in Qiskit 0.20.0

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#884]
- **Qiskit Aer version**: 0.20.0
- **Python version**: 3.6.8
- **Operating system**: Linux

I'm running the following code (with varied values to `shots` and `backend_options`):
```
import numpy as np
from qiskit import Aer
from qiskit.aqua import QuantumInstance
from qiskit.optimization.applications.ising import max_cut
from qiskit.aqua.components.optimizers import COBYLA
from qiskit.aqua.algorithms import VQE
from qiskit.circuit.library import RealAmplitudes

def random_graph(n, p):
    graph = np.zeros([n, n])
    for i in range(n):
        for j in range(i+1, n):
            if np.random.choice(2, 1, p=[1-p, p]):
                graph[i, j] = 1
                graph[j, i] = 1

    op, _ = max_cut.get_operator(graph)
    return op

nqubits = 20
reps = 1
entanglement = 'linear'

qasm_sim = Aer.get_backend('qasm_simulator') 
cobyla = COBYLA(maxiter=1)
var_form = RealAmplitudes(nqubits, reps=reps, entanglement=entanglement)
op = random_graph(nqubits, 0.8)
print(op.num_qubits)
print(var_form.num_qubits)
vqe = VQE(op, var_form, cobyla)
quantum_instance = QuantumInstance(qasm_sim, shots=1,
                                   backend_options={'method': 'matrix_product_state'}
                                   )
vqe.run(quantum_instance, include_custom=True)
```

This code runs a circuit which terminates in a Pauli expectation values, and, because of a bug in Aqua (https://github.com/Qiskit/qiskit-aqua/issues/1015), also appends measurement gates to all qubits at the end.

Here are run times (in seconds) on my machine with Qiskit 0.19.3:
shots | statevector | MPS
------ | ------------ | -----
1 | 8 | 5
1024 | 8 | 10

With Qiskit 0.20.0:
shots | statevector | MPS
------ | ------------ | -----
1 | 5 | 5
1024 | 22 | 23

I didn't verify that the circuit (before and after transpilation) remains the same in the two versions of Qiskit. So in theory this could be an issue in Aqua or Terra. I suspect Aer because we recently modified the sample measure mechanism.

**Comment by yaelbh** [comment]
I see now that the circuits are somewhat different between executions (because of the randomization). Nevertheless I argue that this does not explain the run time results.

**Comment by chriseclectic** [comment]
My guess is something changed (either in Aer or Aqua) to prevent measurement sampling getting applied in 0.20

**Comment by chriseclectic** [comment]
I double checked and measure sampling should still apply with snapshots in the circuit. However if Aqua changed to append unused measurements in 0.20.0 the difference could just be the overhead of the measure sampling itself.

```python
from qiskit import *
from qiskit.providers.aer.extensions import *
from qiskit.providers.aer import QasmSimulator

# Snapshot circuit
qc1 = QuantumCircuit(2)
qc1.h(0)
qc1.cx(0,1)
qc1.snapshot_expectation_value('XX', qi.Pauli(label='XX'), [0, 1])

# Snapshot circuit with final measure
qc2 = qc1.copy()
qc2.measure_all()

# Execute
circs = [qc1, qc2]
sim = QasmSimulator(method='statevector')
result = execute(circs, sim, shots=10000).result()

# Simulation times
for i in range(len(circs)):
    t = result.results[i].time_taken
    print('i = {}, t = {:.5f}'.format(i, t))
```
```
i = 0, t = 0.00020
i = 1, t = 0.01791
```

**Comment by yaelbh** [comment]
Aqua added the unused measurements already before 0.20.0

**Comment by yaelbh** [comment]
If the findings described here are still correct, then we need to fix it (a fix in either Aer or Aqua). I'm adding this to my list of tasks.

**Comment by yaelbh** [comment]
I created a simple circuit with measurements, and checked the run time of the statevector simulator for different numbers of shots. I don't see a significant difference between Version 0.19.3 and the current version. So I vote for closing this issue.
