### ISSUE TITLE
Hamiltonian Conversion to Hz from GHz

### ISSUE THREAD

**Issue by taalexander** [Qiskit/qiskit-aer#891]
### What is the expected behavior?
Starting with the merger of https://github.com/Qiskit/qiskit-terra/pull/4932, the Hamiltonian will begin returning with units of Hz. An adjustment in the simulator conversion code will have to be made to compensate for this.

**Comment by modmatic** [comment]
I can look into this 🚀

**Comment by menehune23** [comment]
I can look into this 🚀

**Comment by patdenim** [comment]
A client got this error during Pulse simulation of a FakeValencia() model :  The symtoms is an error with RabiFitter  : "ValueError: array must not contain infs or NaNs" I had to factor by 1e9 each wq0 to wq5 but also each omegad0 to omegad5 to make it working. FOr now that's the workaround i proposed to the client

**Comment by DanPuzzuoli** [comment]
The only unit conversion the pulse simulator does is: when digesting the pulse `qobj`, it multiplies the `qubit_lo_freq` provided in the pulse `qobj` by `1e9`, as - as far as I recall - the `qobj` output by `assemble` reports `qubit_lo_freq` multiplied by a factor of `1e-9` (whether this was a supplied as a `kwarg` to `assemble` or it was retrieved from the backend defaults). Aside from this no conversions are ever done.

So, _I believe_ things should work as is so long as all parameters in the backend config and defaults, and any user supplied parameters (like `qubit_lo_freq` passed as a `kwarg` to `assemble`) are provided in consistent units. I may however be missing something or accessing parameters incorrectly - e.g. I know that there is a factor of `1e9` difference between accessing `dt` in the `qobj.config` as an attribute, or accessing it in dictionary form from `qobj.to_dict()['config']` (we do the former in the pulse simulator).

**Comment by taalexander** [comment]
Sounds good, thank you.
