### ISSUE TITLE
Parallel thread tests fail on CPU with >64 cores

### ISSUE THREAD

**Issue by drewrisinger** [Qiskit/qiskit-aer#892]
### Informations

- **Qiskit Aer version**: 0.5.2
- **Python version**: 3.8.5
- **Operating system**: Linux (NixOS)

Cross-post from https://github.com/NixOS/nixpkgs/issues/95527

### What is the current behavior?

Parallel tests fail on AMD Threadripper 3990X system with 128 cores, e.g.:
https://github.com/Qiskit/qiskit-aer/blob/25de39f0916290d914251c1f755fba0332deee1c/test/terra/backends/qasm_simulator/qasm_thread_management.py#L99-L102

All failing tests:
```
FAILED test/terra/backends/test_qasm_simulator.py::TestQasmSimulator::test_parallel_experiment_thread_assignment
FAILED test/terra/backends/test_qasm_simulator.py::TestQasmSimulator::test_parallel_shot_thread_assignment
FAILED test/terra/backends/test_qasm_simulator.py::TestQasmSimulator::test_parallel_thread_assignment_priority
FAILED test/terra/backends/test_qasm_simulator.py::TestQasmSimulator::test_parallel_thread_defaults
FAILED test/terra/backends/test_qasm_simulator_statevector.py::TestQasmSimulatorStatevector::test_parallel_experiment_thread_assignment
FAILED test/terra/backends/test_qasm_simulator_statevector.py::TestQasmSimulatorStatevector::test_parallel_shot_thread_assignment
FAILED test/terra/backends/test_qasm_simulator_statevector.py::TestQasmSimulatorStatevector::test_parallel_thread_assignment_priority
FAILED test/terra/backends/test_qasm_simulator_statevector.py::TestQasmSimulatorStatevector::test_parallel_thread_defaults
```

Full build log can be found at: https://gist.githubusercontent.com/jonringer/a86a889f2684ee64bb95732f0b065126/raw/efb78b20ac536cbedbfa490f342374228b1f0b2d/qiskit-aer%2520failure

### Steps to reproduce the problem
On 128 core system: 
```bash
git clone https://github.com/nixos/nixpkgs
git checkout f1efdd2c0b2efb3af9e2822bd490ede184a2bf6f
# install Nix
curl -L https://nixos.org/nix/install | sh
# build qiskit-aer with Nix
nix-build -A python38Packages.qiskit-aer
```
Current build config: https://github.com/NixOS/nixpkgs/blob/08df77da32b8adb91f45cbf0dd978fb9d46feaa7/pkgs/development/python-modules/qiskit-aer/default.nix

### What is the expected behavior?

Tests don't fail.

### Suggested solutions

Not sure if this is due to an issue with OpenMP or qiskit-aer's dispatching algorithm.

**Comment by hhorii** [comment]
> @drewrisinger 
Could you tell me if your issue is resolved with #918?

**Comment by drewrisinger** [comment]
@hhorii I don't have access to the machine that raised this issue, pinging @jonringer. I know that he resolved the issue externally by limiting the number of cores used to build packages to ~4.

@jonringer, I know you're busy, but if you have time to test, this should be able to be tested with the existing ``qiskit-aer`` derivation & checking out ``master`` (https://github.com/Qiskit/qiskit-aer/commit/ef7fd430b2dd9bb53e300580fe6fe35dc47c67ee)

**Comment by jonringer** [comment]
```
[15:30:13] jon@nixos ~/projects/nixpkgs (master)
$ NIX_BUILD_CORES=128 nix-build -A python3Packages.qiskit-aer --check
....
========= 1070 passed, 940 skipped, 98 warnings in 1314.01s (0:21:54) ==========
/build/source
Finished executing pytestCheckPhase
pytestcachePhase
/nix/store/wbqs96d2qprrcxbnbcg1xk0s1ni88h4c-python3.8-qiskit-aer-0.6.1
```

LGTM

**Comment by jonringer** [comment]
although, it did take 22 mins to run the tests for nixpkgs, the rule of thumb is <5 mins. Maybe we could have a `--fast` version? or opt into a `--slow` version.

```
{ lib, buildPythonPackage
, withSlowTests ?  false
...
}:

buildPythonPackage rec {
  ...

  pytestFlagsArray = lib.optionals withSlowTests [ "--slow" ];

  passthru.tests = {
     slowTests = self.override { withSlowTests = true; };
  };
  ...
```
not sure if `self.override` will actually work, but you could make it into a "point" then override it:
```
let
  package = buildPythonPackage rec {
  ...
  }
in package // ({ passthru.tests.slowTests = package.override { withSlowTests = true; })

**Comment by drewrisinger** [comment]
Thanks @jonringer. Closing based on tests passing on ``master`` build.

**Comment by hhorii** [comment]
Thanks @drewrisinger and @jonringer !!
