### ISSUE TITLE
Distutils warning when running setup.py install

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-aer#899]
*BUG TEMPLATE* 

### Informations

- **Qiskit AER version**: master
- **Operating system**: OSX

### What is the current behavior?
```
(base) paul@macbook-pro qiskit-aer % python setup.py install
/opt/miniconda3/lib/python3.7/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
```

### Suggested solutions

---

*FEATURE REQUEST TEMPLATE*  

### What is the expected behavior?

---

*ENHANCEMENT REQUEST TEMPLATE*

**Comment by mtreinish** [comment]
Hmm, I'm not sure where this would be coming from. The setup.py in aer doesn't import distutils directly at all, just setuptools: https://github.com/Qiskit/qiskit-aer/blob/master/setup.py#L30 My only thought is that one of the dependencies in the setup.py like conan, or scikit-build is pulling in distutils. I wasn't able to reproduce this warning locally (or get a build working which I'll open another issue about) when using `python setup.py install` My only suggestion is to try moving the setuptools import at L30 in the setup.py to be first before everything else and see if the warning is still emitted. Something like: 

```diff
diff --git a/setup.py b/setup.py
index fd71e9f..d59372f 100644
--- a/setup.py
+++ b/setup.py
@@ -11,6 +11,8 @@ import inspect
 
 PACKAGE_NAME = os.getenv('QISKIT_AER_PACKAGE_NAME', 'qiskit-aer')
 
+import setuptools
+
 try:
     from conans import client
 except ImportError:
@@ -27,8 +29,6 @@ try:
 except ImportError:
     subprocess.call([sys.executable, '-m', 'pip', 'install', 'pybind11>=2.4'])
 
-import setuptools
-
 # These are requirements that are both runtime/install dependencies and
 # also build time/setup requirements and will be added to both lists
 # of requirements
```

**Comment by vvilpas** [comment]
I haven't been able to reproduce this. We don't import `setuptools` directly anymore, not sure if that caused this issue. @nonhermitian are you still experiencing this?

**Comment by nonhermitian** [comment]
I haven't tried in some time. Can probably close as stale. Can reopen if needed.

**Comment by vvilpas** [comment]
ok, closing then. thanks.
