### ISSUE TITLE
Remove parameter variance from snapshots

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-aer#903]
### What is the expected behavior?

Computing the variance does not require much resources. In essence this is an accumulation of the squares of the values (see `add_data` and `normalize` in `src/framework/results/data/average_data.hpp`). Therefore it makes sense to just always compute and return the variance.

**Comment by chriseclectic** [comment]
I think we should remove variance entirely from snapshots since it is actually the variance only from sampling over noise (and hence is always zero for ideal simulations). This seems to confuse people who are expecting it to be variance from measurement statistics.

**Comment by yaelbh** [comment]
Ok, makes sense. By the way, the variance can be non-zero also for ideal simulations, if the circuit contains different measurement gates that write to the same classical qubit.

**Comment by yaelbh** [comment]
Done in #974
