### ISSUE TITLE
Unable to use snapshot in the qasm simulator while executing a circuit in the presence of noise models.

### ISSUE THREAD

**Issue by Pingal-Pratyush-Nath** [Qiskit/qiskit-aer#908]
### Informations

- **Qiskit Aer version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

It either shows the result without noise or a state vector with all zeros. If I execute the circuit without noise models then the snapshot works properly.

### Steps to reproduce the problem
While executing a random circuit using the qasm simulator if we use the snapshot option it gives a proper state vector. But if we execute the circuit in the presence of some noise models the snapshot option doesn't work. It either gives the state vector without errors(file uploaded) or makes all the elements of the state vector 0.(The error models work fine without the snapshot command)

### What is the expected behavior?
I wanted to extract the output state vector/density matrix of a noisy simulation using the qasm simulator and the snapshot option doesn't work. And we can't use any noise models in the state vector simulator or the unitary simulator.

**Comment by chriseclectic** [comment]
Can you provide a short code example?

**Comment by Pingal-Pratyush-Nath** [comment]
Try this out. In this case, the snapshot shows different results from the
probability distribution. In my main code the snapshot collapses all the
counts to 0.

**Comment by chriseclectic** [comment]
Here is nothing attached, please post code snippet in the github comment.

I can't reproduce this issue. For example this code runs fine for me:

```python
from pprint import pprint
from qiskit import QuantumCircuit, execute, transpile
from qiskit.providers.aer import QasmSimulator
from qiskit.providers.aer.noise import NoiseModel, amplitude_damping_error
from qiskit.providers.aer.extensions import *

qc = QuantumCircuit(1)
qc.x(0)

qc1 = qc.copy()
qc1.snapshot_statevector('final')

qc2 = qc.copy()
qc2.snapshot('final', snapshot_type='statevector')


qc3 = qc.copy()
qc3.snapshot_density_matrix('final')


noise_model = NoiseModel()
noise_model.add_all_qubit_quantum_error(amplitude_damping_error(0.25), 'x')
basis_gates = noise_model.basis_gates
circs = transpile([qc1, qc2, qc3], basis_gates=basis_gates)

result = execute(circs,
                 QasmSimulator(),
                 shots=10,
                 seed_simulator=100,
                 noise_model=noise_model,
                 basis_gates=basis_gates).result()

pprint(result.data(0)['snapshots'])

pprint(result.data(1)['snapshots'])

pprint(result.data(2)['snapshots'])
```
results
```python
{'statevector': {'final': [array([-0.+0.j, -1.+0.j]),
                           array([-0.+0.j, -1.+0.j]),
                           array([1.+0.j, 0.+0.j]),
                           array([-0.+0.j, -1.+0.j]),
                           array([-0.+0.j, -1.+0.j]),
                           array([-0.+0.j, -1.+0.j]),
                           array([1.+0.j, 0.+0.j]),
                           array([-0.+0.j, -1.+0.j]),
                           array([-0.+0.j, -1.+0.j]),
                           array([1.+0.j, 0.+0.j])]}}
{'statevector': {'final': [array([-0.+0.j, -1.+0.j]),
                           array([-0.+0.j, -1.+0.j]),
                           array([1.+0.j, 0.+0.j]),
                           array([-0.+0.j, -1.+0.j]),
                           array([-0.+0.j, -1.+0.j]),
                           array([-0.+0.j, -1.+0.j]),
                           array([-0.+0.j, -1.+0.j]),
                           array([-0.+0.j, -1.+0.j]),
                           array([-0.+0.j, -1.+0.j]),
                           array([-0.+0.j, -1.+0.j])]}}
{'density_matrix': {'final': [{'value': array([[0.25+0.j, 0.  +0.j],
       [0.  +0.j, 0.75+0.j]])}]}}
```

**Comment by Pingal-Pratyush-Nath** [comment]
[Noise_1_git.html.pdf](https://github.com/Qiskit/qiskit-aer/files/5136870/Noise_1_git.html.pdf)

**Comment by chriseclectic** [comment]
I don't see any issue here. The fact counts are showing noise means noise was correctly applied to this simulation.

For statevector simulation noise is sampled from errors for each shot and inserted into the circuit, each snapshot will be one instance of a sampled noise circuit. For depolarizing error this means a Pauli (eg I, X, Y, Z for one qubit) is inserted as an error term. For low error probability the majority of the time it should be an identity so the snapshot would be the ideal state.

If you look at the distribution of the state snapshots over all shots you should see different statevectors corresponding to the different instances of noise sampling, which you can see in the example I posted above where there are two different snapshot states, one corresponding to each Kraus operator of the single noise op. Taking the mean of the outer product of all these vectors should approach the expected density matrix (for large enough shots).

**Comment by Pingal-Pratyush-Nath** [comment]
All right. I got it. Thank you for the clarification!
