### ISSUE TITLE
How can I config json to simulate noise circuit use matrix product state in C++?

### ISSUE THREAD

**Issue by NicolasYL** [Qiskit/qiskit-aer#912]
*BUG TEMPLATE* 

### Informations

- **Qiskit AER version**: latest
- **Operating system**: win10

### What is the current behavior?
I want to simulate noise circuit in Qisikit Aer use MPS，here is my json
`{

    "qobj_id": "19213d25-279b-48d4-86dd-1f959c48e8ed",
    "schema_version": "1.0.0",
    "type": "QASM",
    "config": {
        "max_parallel_shots": 2,
        "method" : "matrix_product_state",
        "noise_model": {
            "errors": [
                {
                    "type": "qerror",
                    "operations": ["cx"],
                    "probabilities": [1.0],
                    "instructions": [
                        [{"name": "kraus", "qubits": [0,1], "params":
                          [
                            [[[-1, 0], [0, 0],[0,0],[0,0]], 
                            [[0, 0], [-0.9487, 0],[0,0],[0,0]],
                            [[0,0],[0,0],[-0.9487,0],[0,0]],
                            [[0,0],[0,0],[0,0],[-0.9,0]]],

                            [[[0, 0], [0, 0]], [[-0.3162, 0], [0, 0]],
                             [[0, 0], [0, 0]], [[0, 0], [-0.3, 0]],
                             [[0, 0], [0, 0]], [[0, 0], [0, 0]],
                             [[0, 0], [0, 0]], [[0, 0], [0, 0]]],

                            [[[0, 0], [-0.3162, 0]], [[0, 0], [0, 0]],
                            [[0, 0], [0, 0]], [[0, 0], [0, 0]],
                            [[0, 0], [0, 0]], [[0, 0], [-0.3, 0]],
                            [[0, 0], [0, 0]], [[0, 0], [0, 0]]],
                            
                            [[[0, 0], [0, 0]], [[0, 0], [0.1, 0]],
                             [[0, 0], [0, 0]], [[0, 0], [0, 0]],
                             [[0, 0], [0, 0]], [[0, 0], [0, 0]],
                             [[0, 0], [0, 0]], [[0, 0], [0, 0]]]													   
                        ]
                         }
                        ]
                    ]
                },

              {
                "type": "qerror",
                "operations": [ "h" ],
                "probabilities": [ 1.0 ],
                "instructions": [
                  [
                    {
                      "name": "kraus",
                      "qubits": [ 0 ],
                      "params": [
                        [
                          [
                            [ -1, 0 ],
                            [ 0, 0 ]
                          ],
                          [
                            [ 0, 0 ],
                            [ -0.9486833, 0 ]
                          ]
                        ],
                        [
                          [
                            [ 0, 0 ],
                            [ 0.31622777, 0 ]
                          ],
                          [
                            [ 0, 0 ],
                            [ 0, 0 ]
                          ]
                        ]
                      ]
                    }
                  ]
                ]
              }
             ]
        }
        
    },
    "experiments": [
        {
            "config": {
                "shots": 1024,
                "memory_slots": 3,
                "n_qubits": 3,
                "max_parallel_shots": 2,
                "method" : "matrix_product_state"
            },

          "instructions": [
            {
              "name": "h",
              "qubits": [ 0 ]
            },
            {
              "name": "cx",
              "qubits": [ 0, 1 ]
            },
            {
              "name": "cx",
              "qubits": [ 0, 2 ]
            },
            {
              "name": "measure",
              "qubits": [ 0 ],
              "memory": [ 0 ]
            },
            {
              "name": "measure",
              "qubits": [ 1 ],
              "memory": [ 1 ]
            },
            {
              "name": "measure",
              "qubits": [ 2 ],
              "memory": [ 2 ]
            }
          ]
        }
    ]
}

`

and here is my main function

![image](https://user-images.githubusercontent.com/47812418/91633355-30fa9800-ea1a-11ea-888d-24c9d12a362b.png)

unfortunately，It runs fail.Can someone tell me how to config this json file?

### Steps to reproduce the problem
none

---

*FEATURE REQUEST TEMPLATE*  

### What is the expected behavior?

use MPS method to simulate noise 

---

*ENHANCEMENT REQUEST TEMPLATE*

**Comment by merav-aharoni** [comment]
The MPS method currently does not support Kraus noise. This is currently under development. We will update you when it is working. For now, you can use the default "simulation_method": "statevector."

**Comment by NicolasYL** [comment]
thanks a lot!
