### ISSUE TITLE
Unable to build/install on win32.

### ISSUE THREAD

**Issue by HaraldBlab** [Qiskit/qiskit-aer#947]
### Informations

- **Qiskit Aer version**: 0.6.1
- **Python version**: 3.8.3
- **Operating system**: WIndows 10 Home

### What is the current behavior?
"pip install qiskit" stops with error when it tries to install qiskit-aer.
I get an error message in the command window

``` starts here
  -- The CXX compiler identification is GNU 9.2.0
  -- The C compiler identification is GNU 9.2.0
... some more
  -- Conan executing: D:/Users/Harald/Programs/Python/Python38-32/Scripts/conan.exe install . -s build_type=Release -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libstdc++11 -e=CONAN_CMAKE_PROGRAM=C:/Users/PRIVAT/AppData/Local/Temp/pip-install-gswqcevt/qiskit-aer/.eggs/cmake-3.18.2.post1-py3.8-win32.egg/cmake/data/bin/cmake.exe -g=cmake --build=missing
  Configuration:
  [settings]
  arch=x86_64
  arch_build=x86_64
  build_type=Release
  compiler=gcc
  compiler.libcxx=libstdc++11
  compiler.version=9
  os=Windows
  os_build=Windows
  [options]
  [build_requires]
  [env]
  CONAN_CMAKE_PROGRAM=C:/Users/PRIVAT/AppData/Local/Temp/pip-install-gswqcevt/qiskit-aer/.eggs/cmake-3.18.2.post1-py3.8-win32.egg/cmake/data/bin/cmake.exe
  ERROR: muparserx/4.0.8: option 'fPIC' doesn't exist
  Possible options are ['shared']
  CMake Error at cmake/conan.cmake:402 (message):
    Conan install failed='1'
``` more

### Steps to reproduce the problem
pip install qiskit
Error happens very time I start installation

### What is the expected behavior?
Installation is successful.


### Suggested solutions
Can't provide any help here. Sorry.

**Comment by mtreinish** [comment]
The issue you're facing is that you are not running a 64bit version of python. There are no Aer binaries published on pypi for win32, only amd64: https://pypi.org/project/qiskit-aer/#files There are issues trying to get aer to build on win32, there is an open PR for adding support here: #925 but until that is merged and included in a release you will have issues trying to run with a 32bit version of Python.

In the meantime you can workaround this by just installing a 64bit version of python and using that.

**Comment by HaraldBlab** [comment]
Installed conda and python x64. Works like a charm here.
I think this one can be closed.

**Comment by mtreinish** [comment]
Lets leave it open until #925 and #950 merge which will add support for win32 and then start publish win32 binaries. This is actually fairly common issue that people hit, so it'll be good to both document the current win32 issues and track when they're fixed.
