### ISSUE TITLE
Qiskit ReadoutError doc is inconsistent

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit-aer#962]
It seems inconsistent that in the first equation (i.e. the equation defining how to use ReadoutError), the LHS depends only on `j` while the RHS depends only on `m`.

Based on the accompanying text and example, it seems likely that the LHS should change to `probabilities[m]`. It may be worth verifying this is the correct definition in the source code before updating the docs given the past confusion: #422 .

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/60495383/94497042-da17e800-01aa-11eb-9f54-4e70e85f2259.png">

**Comment by chriseclectic** [comment]
Yes it should be `probabilities[m] = [P(0|m), ...]`
