### ISSUE TITLE
Segmentation fault during randomized benchmarking using statevector_simulator

### ISSUE THREAD

**Issue by yuanyao56** [Qiskit/qiskit-aer#968]
### Informations

- **Qiskit Aer version**: 
{'qiskit-terra': '0.15.1', 'qiskit-aer': '0.6.1', 'qiskit-ignis': '0.4.0', 'qiskit-ibmq-provider': '0.8.0', 'qiskit-aqua': '0.7.5', 'qiskit': '0.20.0'}
- **Python version**: 3.6.6 
- **Operating system**:  CentOS Linux 7

### What is the current behavior?
Benchmarking using circuit gengerated by qiskit.ignis.verification.randomized_benchmarking on 36 qubits and simulate on statevector_simulator with reparations. segmentation fault (core dumped). Scirpt works until 34 qubits

Debuged with gdb and get 

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff0f7e6700 (LWP 313147)]
0x00007fff23237fd0 in AER::QV::QubitVector<double, AER::QV::QubitVectorAvx2<double> >::zero() [clone ._omp_fn.158] ()
```

### Steps to reproduce the problem
test script
```
import qiskit.ignis.verification.randomized_benchmarking as rb
import qiskit
import random
from qiskit import  Aer, execute
import re
import os

nQ = 36
rb_opts = {}
rb_opts['length_vector'] = [100]
rb_opts['nseeds'] = 1
id = [i for i in range(nQ)]
random.shuffle(id)
pattern = [[id[i],id[i+int(nQ/2)]] for i in range(int(nQ/2))]
rb_opts['rb_pattern'] = pattern

rb_circs, xdata = rb.randomized_benchmarking_seq(**rb_opts)
circuit = rb_circs[0][0]
backend = Aer.get_backend('statevector_simulator')
results = execute(circuit, backend, shots=2048).result()
```

### What is the expected behavior?
Scirpt finish without error

### Suggested solutions
no idea

**Comment by chriseclectic** [comment]
A 36-qubit circuit requires over 1TB of memory to store the statevector, which is likely why you are getting a segment fault. 34-qubits would require ~275 GB.

It looks like a bug where the memory checking which raises an exception when a circuit requires more memory than is available that is done on the QasmSimulator wasn't done on the Statevector or Unitary simulator. This is fixed in #969 so that if you run the above example it will return:

```
print(result.success)
print(result.status)
```
```
False
ERROR:  [Experiment 0] Insufficient memory to run circuit "rb_length_0_seed_0" using the statevector simulator.
```
