### ISSUE TITLE
0.6.1: How to use locally installed packages during build?

### ISSUE THREAD

**Issue by yurivict** [Qiskit/qiskit-aer#970]
0.6.1 fails:
```
[env]
CONAN_CMAKE_PROGRAM=/usr/local/bin/cmake
nlohmann_json/3.1.1: Not found in local cache, looking in remotes...
nlohmann_json/3.1.1: Trying with 'conan-center'...
ERROR: Not able to automatically detect '/usr/bin/cc' version
ERROR: Unable to find a working compiler
WARN: Remotes registry file missing, creating default one in /wrkdirs/usr/ports/science/qiskit-aer/work/.conan/remotes.json
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/ping (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x803e44710>: Failed to establish a new connection: [Errno 8] Name does not resolve'))
```

Package build is performed without internet connection for security reasons. All dependencies should be pre-installed.

I do have ```nlohmann-json``` installed, so it isn't clear why does it try to download it.

How to only use local packages for dependendcies?

0.5.2 was building fine.

**Comment by vvilpas** [comment]
Hi @yurivict 
Right now we use Conan as a dependency manager to deliver (some) needed libraries. The possibility of disabling Conan and use installed dependencies is being implemented In the ongoing PR #877.
In the meantime, to try to find a solution, can you give us more information about your system? Regular pip installation of qiskit-aer for win64, mac and linux shouldn't need conan.

**Comment by yurivict** [comment]
I am trying to update the FreeBSD port. It uses cmake for build.

**Comment by vvilpas** [comment]
I see, the aforementioned #877 PR was also opened to be able to do packaging on Linux. In the meantime, maybe you can follow the suggestion in this issue: https://github.com/conan-io/conan/issues/2197 to try to make an offline installation of the conan packages needed.

**Comment by yurivict** [comment]
> In the meantime, maybe you can follow the suggestion in this issue: conan-io/conan#2197 to try to make an offline installation of the conan packages needed.

I'll just wait until you'll bring back a regular dependency management.

Thank you,
Yuri

**Comment by vvilpas** [comment]
OK. Thanks anyway for raising this! I'm closing this one as we already have the issue #757 opened to track the non-Conan build.
