### ISSUE TITLE
statevector_simulator produces wrong phase, state for 2pi-rotations

### ISSUE THREAD

**Issue by johannesgreiner** [Qiskit/qiskit-aer#977]
### Information

- **Qiskit Aer version**: 0.6.1
- **Python version**: 3.8.2
- **Operating system**: Win 10

### What is the current behavior?

`statevector_simulator` produces wrong phase for 2*pi rotations. 
Code example produces phase: 0, statevector: [1 0]. 

### Steps to reproduce the problem
```python
from qiskit import *
from numpy import pi

#statevector wrong phase minimal example
qreg = QuantumRegister(1, 'qubit')
circuit = QuantumCircuit(qreg)

circuit.rz(2*pi, qreg[0])
job = execute(circuit, Aer.get_backend('statevector_simulator'))

qubit_state = job.result().get_statevector(circuit)
print(qubit_state)
visualization.plot_state_qsphere(qubit_state)
```
Jupyter Notebook Screenshot:
![qiskit wrong result statevector jupyter notebook](https://user-images.githubusercontent.com/70909228/95307216-a4e55700-0888-11eb-8e34-e2bfea3149e0.png)

### What is the expected behavior?
Correct result from example would be: phase: pi, statevector: [-1 0]
IQX Screenshot from application of single Rz(2*pi) gate:
![qiskit 2pi statevector correct result from IQX](https://user-images.githubusercontent.com/70909228/95307395-dcec9a00-0888-11eb-9922-c16f3f48adf0.png)

**Comment by chriseclectic** [comment]
If you use the master branches of terra and aer it will work as you expect.

Global phase was not supported in qiskit-terra 0.15, but is being added in the next release.

**Comment by jdserna** [comment]
Hi. I'm using qiskit-terra 0.19.1 and still get the same phase error. Is there any workaround for this issue?
