### ISSUE TITLE
Request: Ability to add list of noise errors through add_all_qubit_quantum_error(...): 

### ISSUE THREAD

**Issue by noamsgl** [Qiskit/qiskit-aer#985]
### What is the expected behavior?

Allow a user to add a list of quantum noise errors (depolarizing, thermal...) to all qubits with one function call.

### Proposed solution:

In noise_modely.py:
[https://github.com/Qiskit/qiskit-aer/blob/master/qiskit/providers/aer/noise/noise_model.py](https://github.com/Qiskit/qiskit-aer/blob/master/qiskit/providers/aer/noise/noise_model.py
)

define a new method (notice **errors** instead of **error**):
`add_all_qubit_quantum_errors(self, *errors, instructions, warnings=True)`

which accepts an (iterable) of quantum errors and applies all of them to all the qubits

**Comment by hhorii** [comment]
```
add_all_qubit_quantum_errors(self, *errors, instructions, warnings=True)
```
can be written as follows with the current API:
```
for error in errors:
    add_all_qubit_quantum_errors(self, error, instructions, warnings=True)
```
I think the bottom is still simple and should not introduce complexity to API for such small improvement. Please reopen this issue with some examples if you have more significant usability issue with the current `add_all_qubit_quantum_errors`.
